### ISSUE TITLE
WoRMS Octocorallia (id 1131): test report 

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#100]
WoRMS Octocorallia, id 1131 on prod
https://data.catalogueoflife.org/dataset/1131/meta

- [x] _Sector:_ subclass Octocorallia established (were orders Alcyonacea, Helioporacea, Pennatulacea in ac19)
- [ ] _Metadata:_ as available for 2021-04-01. **Country is missing in organisation**: Universidade Federal de Pernambuco, Recife, **Brazil**
- [x] _Imported:_  3715 spp vs 3647 in ac19

**Comment by yroskov** [comment]
**ISSUES** 2021-04-21

-[x] **Partially Parsable Name**, 3 - blocked in CoL
https://data.catalogueoflife.org/catalogue/3/dataset/1131/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=parsed%20name%20differs&limit=100&offset=0
Calyptrophora japonica f. a Versluys, 1906	
Calyptrophora japonica f. b Versluys, 1906	
Calyptrophora japonica f. c Versluys, 1906

- [ ] **Unusual Name Characters**, 19. Diacritical symbols appear in accepted names. @bart-v, It may have interest for WoRMS authors. No actions in CoL.
https://data.catalogueoflife.org/catalogue/3/dataset/1131/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=unusual%20name%20characters&limit=100&offset=0

**Comment by yroskov** [comment]
**TASKS** 2021-04-21

![image](https://user-images.githubusercontent.com/28574252/115568722-3004c800-a282-11eb-88ff-6a398415c3d6.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/115569224-a275a800-a282-11eb-96a2-88f3ec9bd964.png)

**Comment by yroskov** [comment]
Synced 2021-04-21

**Comment by bart-v** [comment]
We do allow diacritics in synonyms, whenever it was originally published like this.
So yes, there are 5 cases that we can fix, indeed.

**Comment by yroskov** [comment]
Yes, CoL has the same policy: allow diacritics in synonyms, but follows ICZN with valid names (where it possible of course)

**Comment by yroskov** [comment]
TASKS 2021-07-08

![image](https://user-images.githubusercontent.com/28574252/124976299-afd63f00-dff4-11eb-92be-97b74337e2a8.png)

- [x] Brocken decisions: 2; re-matched: 1. Deleted.

Resolved:

![image](https://user-images.githubusercontent.com/28574252/124976591-1b201100-dff5-11eb-8749-2c0c67bd1494.png)

**Comment by yroskov** [comment]
**ver 2021-11-01**

TASKS - there are changes
![image](https://user-images.githubusercontent.com/28574252/140392001-bb4c5efe-c59c-4b33-b958-a83e15da3aff.png)

- [x] Broken decisions, 0
- [x] Identical family, genus, subgenus: all cases are flagged as acc - prov acc by the dataprovider; no decisions needed.

Resolved 2021-11-04
![image](https://user-images.githubusercontent.com/28574252/140392563-2fafa528-b251-43ac-b210-526e1c3db3e3.png)

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/182903072-87ac1a19-c354-4722-9dd5-97754c98f3c9.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/182903438-86f33636-93fa-4198-9526-14990dbc10af.png)

Re-synced 2022-08-04

**Comment by yroskov** [comment]
**ver 2023-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/5fa93902-6b31-45ea-b6be-e932e34e6bb4)

- Broken decisions, 22: all deleted

Resolved 2023-05-10

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/5add7876-9fac-406c-a6c8-dadd0f4782a1)

**Re-synced 2023-05-10**

**Comment by yroskov** [comment]
**ver 2024-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/d12195c2-d041-4777-99f6-3902e1765930)

Resolved 2024-04-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/4f4b1106-dfb4-480f-81d0-a57c8e90c30f)

**Re-synced 2024-04-07**

**Comment by yroskov** [comment]
**ver 2025-01-01**

Continue with **Either the opening or closing bracket is missing in the authorship**...
https://www.checklistbank.org/dataset/307413/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&issue=unmatched%20name%20brackets&limit=50&offset=0

@bart-v, missing bracket in Sclerophytum mesophoticum (Benayahu, McFadden, Shoham & van Ofwegen, 2017 https://www.marinespecies.org/aphia.php?p=taxdetails&id=1608905

**Comment by bart-v** [comment]
Fixed

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 3 names with portion _incertae sedis_ = 3 prov acc IGNORED

ISSUES assessed 2025-05-21

![Image](https://github.com/user-attachments/assets/507638c7-843f-4995-a365-30f69a6aba4e)

TASKS

![Image](https://github.com/user-attachments/assets/bf2bc0bc-8686-4400-a002-deb998682fac)

- Broken decisions, 101 = deleted

Resolved 2025-05-21:

![Image](https://github.com/user-attachments/assets/b19af965-a6e4-4de0-89fc-ffebed6a9b5a)

**Synced 2025-05-21**

**Comment by yroskov** [comment]
- [ ] rank of the sector was changed from **subclass** Octocorallia to **class** Octocorallia in WoRMS. 
As a result in CoL:

![Image](https://github.com/user-attachments/assets/898d0107-7cc8-4430-a2df-16a17b7689b1)
