### ISSUE TITLE
WoRMS Oligochaeta (id 1099): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#101]
WoRMS Oligochaeta, id1099 on prod
https://data.catalogueoflife.org/dataset/1099/classification

- [x] _Sector:_ subclass Oligochaeta established
- [x] _Metadata:_ as available for 2021-04-01
- [ ] _Imported:_  2715 spp vs 1992 in ac19

**Comment by yroskov** [comment]
**TASKS** 2021-04-21

![image](https://user-images.githubusercontent.com/28574252/115572838-e322f080-a285-11eb-9ef4-e41f432eb9ab.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/115573120-1ebdba80-a286-11eb-88d6-1437064d2abd.png)

**Comment by yroskov** [comment]
Synced 2021-04-21

**Comment by yroskov** [comment]
TASKS 2021-07-09

![image](https://user-images.githubusercontent.com/28574252/125086442-435d4d80-e091-11eb-9ee8-c91f27d295cf.png)

Resolved: 

![image](https://user-images.githubusercontent.com/28574252/125086717-828b9e80-e091-11eb-9c34-13c3d0de5b4f.png)

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/182904086-39266729-b918-4e7c-8940-4f2f6192e306.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/182904365-d6378379-08a6-455e-bae4-853240f5bb7e.png)

Re-synced 2022-08-04

**Comment by yroskov** [comment]
**ver 2023-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/c4a447b5-19b9-4d69-9596-afb1372f6eff)

- Broken decisions, 8: all deleted

Resolved 2023-05-10

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/fe484748-1fa3-42ea-b8f4-767362270481)

**Re-synced 2023-05-10**

**Comment by yroskov** [comment]
**ver 2023-06-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/22b6cc01-a7e9-4182-996d-2ec5ed443633)

- Broken decisions, 4: all deleted

Resolved 2023-06-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/8127e332-b729-4129-98cc-15677faac115)

**Re-synced 2023-06-07**

**Comment by yroskov** [comment]
**ver 2024-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/1ddaff4c-e90a-40f0-8517-ad2d97415e22)

Resolved 2024-05-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/c9ac192c-3edc-4b16-a576-9a1fb150d6b2)

**Re-synced 2024-05-07**

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 2 names with portion _incertae sedis_ = 2 prov acc IGNORED

@bart-v, 
- Unparsable Authorship, [38](https://www.checklistbank.org/dataset/1099/names?issue=unparsable%20authorship) - _perhaps "Hernández-García & . al." need a little correction in all names in the list; and "Popč enko"_

ISSUES assessed 2025-05-20

![Image](https://github.com/user-attachments/assets/d0702a02-712c-4f93-b5df-463ab9c2e30f)

TASKS

![Image](https://github.com/user-attachments/assets/5a9fb4af-470f-40f5-a298-28a38f2b6742)

- Broken decisions, 48 = deleted

Resolved 2025-05-20:

![Image](https://github.com/user-attachments/assets/44dd4905-465c-4678-9695-1b63d9a84ad4)

**Synced 2025-05-20**

**Comment by bart-v** [comment]
Probably COL should stop doing replacements of `& et. al.` to `& . al.`, this does not help...
Will need to discuss with the editor whether they are willing to adapt their behavior of abusing the authority field for the status of a taxon/name. Have tried before without success...

**Comment by yroskov** [comment]
For @mdoering attention: >Probably COL should stop doing replacements of & et. al. to & . al., this does not help...

**Comment by mdoering** [comment]
Do we have a problematic case I can look at? Authorship should not be changed really, but this is a minefield area.
As far as I remember the state since some years is to stick with the supplied name and authorship and only reassemble them if atomised names are provided, which then take precendence.

**Comment by bart-v** [comment]
Problematic case example:
https://www.checklistbank.org/dataset/1099/taxon/urn%3Alsid%3Amarinespecies.org%3Ataxname%3A1781421
vs.
https://www.marinespecies.org/aphia.php?p=taxdetails&id=1781421

**Comment by mdoering** [comment]
I guess it is the dot following the et that makes it bad
