### ISSUE TITLE
WoRMS Orthonectida (id 1149): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#102]
WoRMS Orthonectida, id 1149 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1149/meta

- [x] _Sector:_ phylum Orthonectida (was not broken)
- [x] _Metadata:_ as available for 2021-04-01. **Country is missing**.
- [x] _Imported:_  25 spp vs 25 in ac19

**ISSUES** (selected only) 2021-04-21
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-04-21

No issues.

![image](https://user-images.githubusercontent.com/28574252/115585796-904f3600-a291-11eb-83b5-5af9dbaceab9.png)

**Comment by yroskov** [comment]
Synced 2021-04-21
