### ISSUE TITLE
WoRMS Ostracoda (id 1175): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#103]
WoRMS Ostracoda, id 1175 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1175/meta

- [x] _Sector:_ class Ostracoda re-established. Was present as subphyllum Crustacea.
- [ ] _Metadata:_ as available for 2021-04-01. Incomplete Orgainsation; as present with missing City & Country: University of Hamburg & Universidade Federal do Rio Grande do Norte
Expected: University of Hamburg, **Hamburg, Germany**
Universidade Federal do Rio Grande do Norte, **Natal [?], Rio Grande do Norte [state], Brazil**
- [x] _Imported:_ 10371 spp vs 6308 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-04-21
- [x] assessed 

- [ ] **Unusual Name Characters**, 9. There are few accepted names with diacritics. May have an interest for WoRMS authors (@bart-v)
https://data.catalogueoflife.org/catalogue/3/dataset/1175/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=unusual%20name%20characters&limit=100&offset=0

- [ ] **Unparsable Authorship**, 276. Some names with non-standard authorstrings

- [ ] **Name Id Invalid**, 3537. Big number of names with invalid IDs.

**Comment by yroskov** [comment]
**TASKS** 2021-04-21

![image](https://user-images.githubusercontent.com/28574252/115590833-07d39400-a297-11eb-9ad4-ad8a0c58a971.png)

Resolved:

![image](https://user-images.githubusercontent.com/28574252/115591740-0d7da980-a298-11eb-8d5c-2879265850a1.png)

**Comment by yroskov** [comment]
Synced 2021-04-21

**Comment by yroskov** [comment]
2021-07-01 **Broken hierarchy**, see https://github.com/CatalogueOfLife/testing/issues/141#issuecomment-871721022

Experiment with normalized classification tables was unsuccessful:
![image](https://user-images.githubusercontent.com/28574252/124185858-20bfa900-da81-11eb-86c6-3b6586afb801.png)

Data imported in original format again.

**Comment by yroskov** [comment]
TASKS 2021-07-09

![image](https://user-images.githubusercontent.com/28574252/125088332-ecf10e80-e092-11eb-8f08-84e605399170.png)

- [x] Broken decisions: 6; re-matched all: 17. Deleted all.

Resolved:

![image](https://user-images.githubusercontent.com/28574252/125088957-89b3ac00-e093-11eb-9757-43cb1e2599f5.png)

**Comment by yroskov** [comment]
**ver 2021-11-01**

TASKS - there are changes
![image](https://user-images.githubusercontent.com/28574252/140394051-0c87e5ed-c46e-45fa-86a4-8413f60509b6.png)


- [x] Broken decisions, 5; deleted all
- [x] Identical superfamily, family, genus, subgenus: all cases are flagged as acc - prov acc by the dataprovider; no decisions needed.

Resolved 2021-11-04

**Comment by yroskov** [comment]
Absolutely identical species records appear in Ostracoda checklist of 2021-11-01 (full list):

![image](https://user-images.githubusercontent.com/28574252/140394829-8215a40b-2c92-4947-9542-eefa73a133bc.png)

**Comment by bart-v** [comment]
Bionominal duplicates now removed.
For the uninominals or epithets, please provided an LSID or AphiaID

**Comment by yroskov** [comment]
TASKS as 2022-07-26
![image](https://user-images.githubusercontent.com/28574252/181037681-a7f23b93-c0af-4338-9f57-be2b01844d7f.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/181038037-22155d2e-4b37-4548-9e33-992a5dc0bfe1.png)

Synced 2022-07-26

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/182921581-b3ddeba8-da02-48ff-bbd5-0cc06d4800af.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/182921994-a426e5b4-8eeb-4f07-a10d-610cfd2ed879.png)

Re-synced 2022-08-04

**Comment by yroskov** [comment]
- [ ] @bart-v, there are two entries for _Propontocypris dromas_ Aiello, Barra & Bonaduce, 2000 †  in WoRMS Ostacoda:

https://www.marinespecies.org/aphia.php?p=taxdetails&id=1584252
and 
https://www.marinespecies.org/aphia.php?p=taxdetails&id=1587985

A difference between them is in Taxonomic edit history, as I can see.

**Comment by bart-v** [comment]
Thanks.
Fixed in WoRMS, available in next export 2023-06-01

**Comment by yroskov** [comment]
**ver 2023-06-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/f69e8b00-66f3-4c00-963a-ab809afd85bf)

- Broken decisions, 44: all deleted

Resolved 2023-06-06:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/103c42bb-f8d2-4212-a5ef-87e01562006d)

**Re-synced 2023-06-06**

**Comment by yroskov** [comment]
- [x] There is a set of internal duplicates in WoRMS Foraminifera spottedin the whole CoL report for duplicated accepted species with different authorstrings: 

It is caused by triple duplicates like this
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/1cbbbe98-0860-4793-8b67-1b2035efa80b)

Only one name flagged if button _Most Recent Name_ used. Button **_All Except Oldest_** should be used.

= FIXED 2023-06-09

**Re-synced 2023-06-09**

**Comment by yroskov** [comment]
**ver 2024-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/9462b0f7-a8a5-4a14-87a7-1a2bc631fc78)

Resolved 2024-05-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/f305406a-8ea3-4e2d-a6fd-a38c61b2f7f0)

**Re-synced 2024-05-07**

**Comment by yroskov** [comment]
@bart-v, duplicated subgenera:

**Pataviella (Pataviella)**: 
https://www.marinespecies.org/ostracoda/aphia.php?p=taxdetails&id=771610 = no species 
https://www.marinespecies.org/ostracoda/aphia.php?p=taxdetails&id=771848  

**Tricornina (Ovornina)**

**Urocythere (Urocythere)**

**Cushmanidea (Chartocythere)**

**Urocythereis (Drobetiella)**

**Comment by bart-v** [comment]
Fixed in WoRMS

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 13 names with portion _incertae sedis_ = 1 acc & 9 prov acc IGNORED

@bart-v, FYI:
- Infraclass Leperditicopa beneath suborder https://www.marinespecies.org/ostracoda/aphia.php?p=taxdetails&id=877106 
- †Paracytheridea shoa'lriverensis Puri, 1954 _- misspelled epithet. Here is a spelling in the protologue by Puri_:
![Image](https://github.com/user-attachments/assets/5f5a774c-7d7b-4c94-bfe1-d205b630bf5d)
- misspelled year Kozlowskiella (Illativella) Zanina, 1 960
- two entries for Macroasteropteroninae (first without spp): 
https://www.marinespecies.org/ostracoda/aphia.php?p=taxdetails&id=1443636
https://www.marinespecies.org/ostracoda/aphia.php?p=taxdetails&id=730875

ISSUES assessed 2025-05-21

![Image](https://github.com/user-attachments/assets/7239f414-ee0e-4184-8a0c-de5b58c189c8)

TASKS

![Image](https://github.com/user-attachments/assets/7db7e729-11e1-4816-b91c-98936607b0f2)

- Broken decisions, 158 = deleted
- Outdated decisions, 4 = no action

Resolved 2025-05-21:

![Image](https://github.com/user-attachments/assets/e757969e-de5e-44c2-9e87-29e94086be8c)

**Synced 2025-05-21**

**Comment by bart-v** [comment]
Issues fixed, except Leperditicopa

**Comment by yroskov** [comment]
**ver. 2025-09-01**

TASKS

<img width="1347" height="940" alt="Image" src="https://github.com/user-attachments/assets/d3637154-0eef-4fff-8388-ce473e22c93f" />

Resolved 2025-09-11:

<img width="1354" height="964" alt="Image" src="https://github.com/user-attachments/assets/392cdfa1-2073-435e-9a46-111c86bb4f25" />

**Re-synced 2025-09-11**

**Comment by yroskov** [comment]
**ver. 2025-11-01**

TASKS

<img width="1936" height="1256" alt="Image" src="https://github.com/user-attachments/assets/6201ea14-407c-4c1a-bc46-eeca547bfd06" />

- Broken decisions, 2 = deleted
- Outdated decisions, 1 = deleted

Resolved 2025-11-11:

<img width="1987" height="1293" alt="Image" src="https://github.com/user-attachments/assets/ebf3094c-6a98-41f2-9d6d-7cb92d9fd52d" />

**Re-synced 2025-11-11**

**Comment by yroskov** [comment]
**ver. 2025-12-01**

TASKS

<img width="1617" height="1063" alt="Image" src="https://github.com/user-attachments/assets/f6bc2660-4010-4515-8bc4-720d257fe8bf" />

- Broken decisions, 22 = deleted

Resolved 2025-12-12:

<img width="1617" height="1047" alt="Image" src="https://github.com/user-attachments/assets/929debcd-69e1-49e9-bec3-f2b88d9f52e3" />

**Re-synced 2025-12-12**

**Comment by gdower** [comment]
@yroskov, sync failed for April 2026 edition on class Ostracoda.

**Comment by yroskov** [comment]
- [x] Sector Ostracoda is broken: missing subject = REPAIRED 2026-04-10. **Synced 2026-04-10**

**Comment by yroskov** [comment]
- [x] Sector Ostracoda is broken: missing subject = REPAIRED 2026-05-04. **Synced 2026-05-04**

**Comment by yroskov** [comment]
- [x] Sector Ostracoda is broken: missing subject = REPAIRED 2026-06-05. **Synced 2026-05-05**

**Comment by yroskov** [comment]
- [x] Sector Ostracoda is broken: missing subject = REPAIRED 2026-07-06.

TASKS 

<img width="1850" height="1273" alt="Image" src="https://github.com/user-attachments/assets/09716872-5399-4ca7-8bc0-8cb3041b7319" />

Resolved 2026-07-06:

<img width="1835" height="1293" alt="Image" src="https://github.com/user-attachments/assets/e8b2ca59-f793-4d9d-94a3-7520b0db867b" />

**Synced 2026-07-06**
