### ISSUE TITLE
WoRMS Placozoa (id 1123): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#104]
WoRMS Placozoa, id 1123 on prod
https://data.catalogueoflife.org/dataset/1123/meta

- [x] _Sector:_ phylum Placozoa
- [ ] _Metadata:_ as available for 2021-04-01. Organisation data need improvement. As records appear now (2 or 3?):
    School of veterinary medicine Hannover
    Institute of Animal Ecology and Cell Biology, Germany
    University of Hong Kong, The Swire Institute of Marine Science, Hong Kong
- [x] _Imported:_  3 spp vs 2 in ac19

**ISSUES** (selected only) 2021-04-21
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-04-21

No issues.

![image](https://user-images.githubusercontent.com/28574252/115601444-728acc80-a2a3-11eb-95a0-047ddffeefbc.png)

**Comment by yroskov** [comment]
Synced 2021-04-21
