### ISSUE TITLE
WoRMS Polychaeta (id 1090): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#105]
WoRMS Polychaeta, id 1090 on prod
https://data.catalogueoflife.org/dataset/1090/meta

- [x] _Sector:_ class Polychaeta (was not broken)
- [x] _Metadata:_ as available for 2021-04-01. "Read, G.  Fauchald, K. (Ed.)" placed in Authors field.
- [x] _Imported:_  12664 spp vs 12270 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-04-21

- [ ] **Unparsable Year**, 40 - @mdoering, what might be wrong with years in these names? They look fine for me.
https://data.catalogueoflife.org/catalogue/3/dataset/1090/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=unparsable%20year&limit=100&offset=0

**Comment by yroskov** [comment]
**TASKS** 2021-04-21

![image](https://user-images.githubusercontent.com/28574252/115603236-86cfc900-a2a5-11eb-9971-c217013286d6.png)

Resolved:

![image](https://user-images.githubusercontent.com/28574252/115604058-8a178480-a2a6-11eb-8a35-d343767bf1b1.png)

**Comment by yroskov** [comment]
Synced 2021-04-21

**Comment by mdoering** [comment]
The verbatim browser can also filter by issues, but there is no UI filter for that yet.
If you add it manually to the URL you can see the verbatim records with that problem:

https://data.catalogueoflife.org/catalogue/3/dataset/1090/verbatim?issue=unparsable%20year

![Screenshot 2021-04-21 at 23 39 32](https://user-images.githubusercontent.com/327505/115624393-dbe9fa00-a2fa-11eb-8593-c0f9c8a37c23.png)

You can see immediately that the publishedInYear field is the problem.
There are original dates in there which is fine, but the parser seems to have problems deriving a year from that. What do the rectangular brackets mean again?

There also seems to be another semantics/mapping problem here. _Nereimyra mutilata_ is a recombination with the authorship (Treadwell, 1901). The publication year and reference should never reflect the basionym but the publication that created that specific combination. If that is unknown referenceID and all publishedIn fields should stay empty. 

[ColDP specifies](https://github.com/CatalogueOfLife/coldp/blob/master/README.md#referenceid):

> a Reference indicating the original publication of the name in its given combination, not the basionym.

**Comment by bart-v** [comment]
ICZN art. 22A.2.3.
> if wishing to cite both the actual and the imprint dates, should first cite the actual date (cited as above), followed by the imprint date for information and enclosed in parentheses or other brackets and quotation marks; (...)

https://code.iczn.org/date-of-publication/article-22-citation-of-date/?frame=1

**Comment by bart-v** [comment]
Correct about _Nereimyra mutilata_ and publishedIn
This is now fixed for the next export

**Comment by yroskov** [comment]
>What do the rectangular brackets mean again?

It means, that taxonomic expert has doubts about the year in the authorstring or in the reference; a year should be confirmed in further research.

**Comment by yroskov** [comment]
>The publication year and reference should never reflect the basionym but the publication that created that specific combination.

It is true for botanical names, but incorrect for zoological.

**Comment by bart-v** [comment]
> It is true for botanical names, but incorrect for zoological.
Good point.

Then then the question is do we keep the current definition of _PublisheIn_  or not?
> a Reference indicating the original publication of the name in its given combination, not the basionym.

This is quite clear...

**Comment by yroskov** [comment]
I meant in my sentence, that zoological names do keep an author and year of **original** combination only. A year of the publication, where consecvent combination was published, usually, are not present in the authorstring of that combination.

**Comment by mdoering** [comment]
When the referenceID (or publishedInYear if the entire reference is not known) is correct for combinations you can e.g. organise them chronologically like Plazi does: 

<img width="342" alt="basionym timeline" src="https://user-images.githubusercontent.com/327505/115737957-e3f27a00-a38c-11eb-9327-9765f86103b9.png">

**Comment by mdoering** [comment]
Note also that [ColDP says about _publishedInYear_](https://github.com/CatalogueOfLife/coldp#publishedinyear):

> The effective year the name was published, given as a 4 digit integer. It is the year that is nomenclaturally relevant for the given combination. In most cases this will be the same as the publication year given in the linked reference record via referenceID. But in some cases this might be different.

So ideally imprint years and uncertainty markers should not be found in the field. They can exist in the authorship, but this field is in particular meant for understanding the effective year of publication. 

I will make sure the [interpreter understands also imprint years and uncertainties](https://github.com/CatalogueOfLife/backend/issues/1005), but in a perfect world these should not exist here.

**Comment by yroskov** [comment]
**ver 2021-11-01**

TASKS - there are changes
![image](https://user-images.githubusercontent.com/28574252/140397061-3e222110-d0b3-4e3c-88d6-9a6ff21d554b.png)

- [x] Broken decisions, 5
- [x] Identical genus, subgenus: all cases are flagged as acc - prov acc by the dataprovider; no decisions needed.

Resolved 2021-11-04
![image](https://user-images.githubusercontent.com/28574252/140398576-fb6a5a11-a49e-41af-8a1e-f1c526dcc302.png)

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS

Resolved:
![image](https://user-images.githubusercontent.com/28574252/182935959-c76ae31c-a14c-460d-a37d-c74f332ee71f.png)

Re-synced 2022-08-04

**Comment by yroskov** [comment]
**ver 2023-05-01**

TASKS

![image](https://user-images.githubusercontent.com/28574252/236891567-789d9e3a-d148-4775-ba55-251f908729fa.png)

- Broken decisions, 10: all deleted

Resolved 2023-05-08

![image](https://user-images.githubusercontent.com/28574252/236892067-f61537f3-9ef1-474f-8f0c-c93958424674.png)

**Re-synced 2023-05-08**

**Comment by yroskov** [comment]
**ver 2023-06-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/3165069f-d2f0-4995-adec-002c744b00e7)

- Broken decisions, 13: all deleted

Resolved 2023-06-08:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/222b8cb9-618c-4be7-a33a-09e947470d6a)

**Re-synced 2023-06-08**

**Comment by yroskov** [comment]
**ver 2024-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/63ddf2d9-8591-4584-b79d-cd857c51a3ff)

Resolved 2024-05-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/5cc73732-9238-4223-8087-6d1ca584c724)

**Re-synced 2024-05-07**

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 8 names with portion _incertae sedis_ = 7 prov acc IGNORED

- Unparsable Authorship, [647](https://www.checklistbank.org/catalogue/3/dataset/1090/workbench?issue=unparsable%20authorship&limit=100) _- authorstrings contain various cases of comments, incl. patterns such as " [misspelling of 'Cycnoserpula`]"_ = unable to resolve in CoL

ISSUES assessed 2025-05-20

![Image](https://github.com/user-attachments/assets/d378e49d-2d90-4d60-b597-575a430beabe)

TASKS

![Image](https://github.com/user-attachments/assets/e7d2fc80-4e84-40d2-9922-b9d404ba8dc8)

- Broken decisions, 82 = deleted
- Outdated decisions, 4 = no action

Resolved 2025-05-20:

![Image](https://github.com/user-attachments/assets/db571296-c0ad-499a-bb87-2d02a0487afd)

**Synced 2025-05-20**

**Comment by bart-v** [comment]
Will need to discuss with the editor whether they are willing to adapt their behavior of abusing the authority field for the status of a taxon/name. Have tried before without success...

**Comment by mdoering** [comment]
> * Unparsable Authorship, [647](https://www.checklistbank.org/catalogue/3/dataset/1090/workbench?issue=unparsable%20authorship&limit=100) _- authorstrings contain various cases of comments, incl. patterns such as " [misspelling of 'Cycnoserpula`]"_ = unable to resolve in CoL

... we could provide an update decision to remove them from the authorship. Or even automatically remove all these square bracket comments from the authorship during syncs. We could add a new sector setting to control this behavior, so you can activate it only for a few sectors if needed.

**Comment by mdoering** [comment]
There are many names with just `[auct.]` as the authorship.
What does that actually mean without any following authority? E.g. `Glyphanostoma [auct.]` synonym of [Glyphanostomum Levinsen, 1884](https://www.checklistbank.org/dataset/1090/taxon/urn%3Alsid%3Amarinespecies.org%3Ataxname%3A152406)

Is it the same as **sensu auct.** (sensu auctoris) aka "_Glyphanostoma, taxonomically in the sense of the authors of the Polychaeta Database_" ?
If so that would be very superfluous and we should just remove these cases.

**Comment by bart-v** [comment]
`auct.` means "according to multiple authors of published papers"
So yes, the same as `sensu auct.`
And not related to authors of the Polychaeta Database.
It could indicates a misapplication or misspelling, etc...

We did not have the extended status field in WoRMS to reflect this.
So all these cases could be migrated, but we need agreement of editors..

**Comment by yroskov** [comment]
**ver. 2026-01-01**

TASKS

<img width="1671" height="1203" alt="Image" src="https://github.com/user-attachments/assets/212377cf-ba89-4d12-9ca6-c48e88e7ff11" />

- Broken decisions, 19 = deleted
- Outdated decisions, 3 = deleted

Resolved 2026-01-13:

<img width="1671" height="1184" alt="Image" src="https://github.com/user-attachments/assets/685b17dd-8fb1-4f0d-bbdc-84ee82772005" />

**Re-synced 2026-01-13**
