### ISSUE TITLE
WoRMS Polycystina (id 1109): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#106]
WoRMS Polycystina, id 1109 on prod
https://data.catalogueoflife.org/dataset/1109/meta

- [x] _Sector:_ class Polycystina Re-established (was phylum Radiozoa)
- [x] _Metadata:_ as available for 2021-04-01
- [x] _Imported:_  424 spp vs 417 in ac19

**Comment by yroskov** [comment]
**TASKS** 2021-04-21

No issues.

![image](https://user-images.githubusercontent.com/28574252/115615159-3744c980-a2b4-11eb-9580-4e2b940ebb96.png)

**Comment by yroskov** [comment]
Synced 2021-04-21
