### ISSUE TITLE
WoRMS Porifera (id 1044): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#107]
WoRMS Porifera, id 1044 on prod
https://data.catalogueoflife.org/dataset/1044/meta

- [x] _Sector:_ phylum Porifera (wasn't broken)
- [x] _Metadata:_ as available for 2021-04-01 (20 authors)
- [x] _Imported:_  9418 spp vs 9126 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-04-22

- [ ] **Unmatched Name Brackets**, 1: synonym Theonella prattii (Bowerbank, 1869
https://data.catalogueoflife.org/catalogue/3/dataset/1044/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=unmatched%20name%20brackets&limit=100&offset=0

- [x] **Unparsable Authorship**, 12. Modified in CoL: synonyms with authorstrings contained "sensu" have been flagged as CoL Misapplied Names.
https://data.catalogueoflife.org/catalogue/3/dataset/1044/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=unparsable%20authorship&limit=100&offset=0

- [ ] **Not Interpreted**, 12451 - high number of names reported as not interpreted. Why?

**Comment by yroskov** [comment]
**TASKS** 2021-04-22

![image](https://user-images.githubusercontent.com/28574252/115746021-9872a880-a359-11eb-82c8-5cd7e3356150.png)

Resolved:

![image](https://user-images.githubusercontent.com/28574252/115746745-32d2ec00-a35a-11eb-8a85-ff7bbe07a2bd.png)

**Comment by yroskov** [comment]
Synced 2021-04-22

**Comment by yroskov** [comment]
**ver 2021-11-01**

TASKS - there are changes
![image](https://user-images.githubusercontent.com/28574252/140416036-f4ed2df3-dda8-4629-ae24-e547dc93d13a.png)

- [x] Broken decisions, 2; RematchAll = 1 left; deleted.
- [x] Identical order, genus, subgenus: all cases are flagged as acc - prov acc by the dataprovider; no decisions needed.

Resolved 2021-11-04
![image](https://user-images.githubusercontent.com/28574252/140416431-878f8f4c-b454-4828-b42b-65e4c1b10493.png)

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/182936469-94a63134-c3cd-49f0-a650-de5a73e084e0.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/182936871-a242953b-3620-402e-a2f8-8e0589d2d4e7.png)

Re-synced 2022-08-04

**Comment by yroskov** [comment]
**ver 2023-06-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/946b93ef-fa84-49d4-9272-fc053c3d6186)

- Broken decisions, 22: all deleted

Resolved 2023-06-08:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/77082e2a-5af8-4394-b0c6-eccb27c2b9fe)

**Re-synced 2023-06-08**

**Comment by yroskov** [comment]
**ver 2024-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/fbc842e7-9662-4085-a522-c7f607518166)

Resolved 2024-05-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/909d2ea8-ec22-4719-a568-356106318472)

**Re-synced 2024-05-07**

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 11 names with portion _incertae sedis_ = 1 acc & 7 prov acc IGNORED; 1 syn BLOCKED

@bart-v, FYI:
- Unmatched Name Brackets, [1](https://www.checklistbank.org/catalogue/3/dataset/1044/workbench?issue=unmatched%20name%20brackets&limit=100)

ISSUES assessed 2025-05-21

![Image](https://github.com/user-attachments/assets/d61b5bb5-cb51-49d0-b73b-2b942fe4c2c1)

TASKS

![Image](https://github.com/user-attachments/assets/a47cef0a-a67c-4e9e-8fdd-13f61c12a4fd)

- Broken decisions, 75 = deleted

Resolved 2025-05-21:

![Image](https://github.com/user-attachments/assets/df8a35d2-82dd-4709-b15f-99499f4260ee)

**Synced 2025-05-21**

**Comment by bart-v** [comment]
Cannot fix, no access to `Unmatched Name Brackets` link

**Comment by yroskov** [comment]
Sorry.

https://www.checklistbank.org/dataset/1044/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=secondarySource&facet=group&issue=unmatched%20name%20brackets&limit=50&offset=0

**Comment by bart-v** [comment]
Fixed
