### ISSUE TITLE
WoRMS Priapulida (id 1124): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#108]
WoRMS Priapulida, id 1124 on prod
https://data.catalogueoflife.org/dataset/1124/meta

- [x] _Sector:_ phylum Priapulida established. (Was class Priapulida in phylum Cephalorhyncha). Phylum Cephalorhyncha deleted.
- [x] _Metadata:_ as available for 2021-04-01
- [ ] _Imported:_  22 spp vs 22 in ac19

**ISSUES** 2021-04-22
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-04-22

No issues.

![image](https://user-images.githubusercontent.com/28574252/115749025-4e3ef680-a35c-11eb-9c1a-b4c6d814885e.png)

**Comment by yroskov** [comment]
Synced 2021-04-22
