### ISSUE TITLE
WoRMS Pycnogonida (id 1183): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#109]
WoRMS Pycnogonida, id 1183 on prod
https://data.catalogueoflife.org/dataset/1124/meta

- [ ] _Sector:_ class Pycnogonida re-established (sector appeared as subphylum Chelicerata)

- [ ] _Metadata:_ as available for 2021-04-01. All are fine, except the title.
Short name + Full name in CoL looks now as "WoRMS Pycnogonida: Pycnobase: World Pycnogonida Database". 
@Geoff, @bart-v, Should record in Title field be corrected? It could be done on an export end or as a patch in the clearinghouse. (In ac19, combination was "WoRMS Pycnobase: World Pycnogonida Database").

Now:
![image](https://user-images.githubusercontent.com/28574252/115750283-9f031f00-a35d-11eb-9f0e-289523f783ef.png)

Was in ac19:
![image](https://user-images.githubusercontent.com/28574252/115751027-61eb5c80-a35e-11eb-83c1-ec5d0113bf35.png)

- [ ] _Imported:_  424 spp vs 1354 in ac19   -???

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-04-22

- [ ] **Unusual Name Characters**, 3. There is one accepted name with diacritics: accepted  Pallenopsis vanhöffeni Hodgson, 1914
https://data.catalogueoflife.org/catalogue/3/dataset/1183/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=unusual%20name%20characters&limit=100&offset=0

**Comment by yroskov** [comment]
**TASKS** 2021-04-22

![image](https://user-images.githubusercontent.com/28574252/115752888-294c8280-a360-11eb-9760-7643775bfe4e.png)

Resolved:

![image](https://user-images.githubusercontent.com/28574252/115753048-58fb8a80-a360-11eb-82d6-103f289d3ed0.png)

**Comment by yroskov** [comment]
Synced 2021-04-22

**Comment by yroskov** [comment]
**ver 2023-06-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/7752b6bf-c050-47a3-be79-1f7f53c5965a)

- Broken decisions, 21: all deleted

Resolved 2023-06-08:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/7000c793-e0ed-4f04-ae5b-8983875026fe)

**Re-synced 2023-06-08**

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 4 names with portion _incertae sedis_ = 1 acc & 2 prov acc IGNORED

ISSUES assessed 2025-05-21

![Image](https://github.com/user-attachments/assets/3e72ce80-ca0e-454c-8866-175c99dcb68f)

TASKS

![Image](https://github.com/user-attachments/assets/ec0e077e-cd30-400f-9421-95d8d12c9076)

- Broken decisions, 21 = deleted

Resolved 2025-05-21:

![Image](https://github.com/user-attachments/assets/03631f6b-542b-41d6-8c67-1698b869b9a4)

**Synced 2025-05-21**

**Comment by yroskov** [comment]
**ver. 2025-09-01**

TASKS

Resolved 2025-09-11:

<img width="1340" height="964" alt="Image" src="https://github.com/user-attachments/assets/a9271925-cba8-4430-a52b-6dd633ae2e6c" />

**Re-synced 2025-09-11**
