### ISSUE TITLE
WoRMS Rhombozoa (id 1150): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#111]
WoRMS Rhombozoa, id 1150 on prod

- [x] _Sector:_ class Rhombozoa re-established (was phylum Dicyemida)
- [ ] _Metadata:_ as available for 2021-04-01. 
Incomplete organisation data "University of Adelaide" (in ac19: School of Earth and Environmental Science, University of Adelaide, Adelaide SA, USA).
Misplaced editor:
![image](https://user-images.githubusercontent.com/28574252/115779281-65daa700-a37d-11eb-8c8f-1b55139b8839.png)
- fixed in clearionghouse (temporarily?)
- [x] _Imported:_  122 spp vs 122 in ac19

**ISSUES** 2021-04-22
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-04-22

No issues

![image](https://user-images.githubusercontent.com/28574252/115779977-3c6e4b00-a37e-11eb-8540-4c0dd1acb688.png)

**Comment by yroskov** [comment]
Synced 2021-04-22

**Comment by yroskov** [comment]
**ver 2023-06-01**

- [x] Imported: 122 spp (vs 122 in May)

- [x] Sector: broken (in a strange way)
During checks of AC23 draft pf 2023-06-07 spotted 1 spp vs 122 spp in May

Problem with sectors (only one genus turned to be a sector instead of class Rhombozoa, as expected:
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/8fc17368-249f-41e0-89c3-3ca81923f7be)

Sectors report:
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/c3320f7d-f0c0-4b25-8981-414d9f6c4d43)

FIXES: Assembly - sector deleted - class Rhombozoa re-established in the phylum Dicyemida.

TASKS (no actions)

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/25f12cd6-1284-49a0-a80a-87a23ad9ab35)

**Re-synced 2023-06-08**

**Comment by mdoering** [comment]
You seem to have deleted the old sector, so I cannot trace what went wrong.
Please, NEVER DELETE A BROKEN SECTOR! Instead manually select a new subject or target. This keeps the history. changes over time and allows to jump between releases.

**Comment by yroskov** [comment]
>NEVER DELETE A BROKEN SECTOR

Not in this case. Genus cannot be re-established as Class.
