### ISSUE TITLE
WoRMS Scleractinia (id 1196): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#112]
WoRMS Scleractinia, id 1196 on prod

- [x] _Sector:_ order  Scleractinia established
- [x] _Metadata:_ as available for 2021-04-01
- [ ] _Imported:_  3615 spp vs 1997 in ac19

**Comment by yroskov** [comment]
**TASKS** 2021-04-23

![image](https://user-images.githubusercontent.com/28574252/115881344-42f9d280-a411-11eb-84fb-229a6f4abe4f.png)

- [x] **ACC-ACC species (different authors)**. @bart-v, just in case: there are two identical(?) species with different spellings in authorstrings: Flabellum gallapagense Milne Edwards & Haime, 1848 & Flabellum gallapagense M. Edwards & Haime, 1848
https://data.catalogueoflife.org/catalogue/3/dataset/1196/duplicates?authorshipDifferent=true&category=binomial&limit=500&minSize=2&mode=STRICT&offset=0&status=accepted&withDecision=false

- [ ] **Identical genus**. @bart-v, just in case: there are two pairs of identical(?) genera in the report: 
Eugyra de Fromentel, 1857 & Eugyra Fromentel, 1857
Placohelia Počta, 1887 & Placohelia Počta, 1887

Resolved:

![image](https://user-images.githubusercontent.com/28574252/115883183-2068b900-a413-11eb-99c3-78817e7decc6.png)








Resolved:

**Comment by yroskov** [comment]
Synced 2021-04-23

**Comment by bart-v** [comment]
All 3 duplicates fixed in WoRMS

**Comment by yroskov** [comment]
TASKS 2021-07-09

![image](https://user-images.githubusercontent.com/28574252/125090125-a43a5500-e094-11eb-8427-4f35568588b0.png)

- [x] Broken decisions: 2; re-matched all: 3. Deleted all.

Resolved:

![image](https://user-images.githubusercontent.com/28574252/125090641-2dea2280-e095-11eb-95d1-fe8bdfcff73a.png)

**Comment by yroskov** [comment]
**ver 2021-11-01**

TASKS - there are changes
![image](https://user-images.githubusercontent.com/28574252/140416751-623b2e59-4f2e-4fdc-916a-6fcfbc7e60ca.png)

- [x] Broken decisions, 2; Rematched = 1 lefty; deleted
- [x] Manuscript names, 3; all synonyms. No actions. 
- [x] Identical family, genus, subgenus: all cases are flagged as acc - prov acc by the dataprovider; no decisions needed.

Resolved 2021-11-04
![image](https://user-images.githubusercontent.com/28574252/140417326-5cd1760d-1ca7-4231-a4e8-848d8b0cfe3b.png)

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/182937872-f7c7a13c-c558-4fc7-93e9-cb0b22b6f20f.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/182938227-77c923b8-224b-4190-a4a2-81454b316373.png)

Re-synced 2022-08-04

**Comment by yroskov** [comment]
**ver 2023-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/dcd39368-5f37-46c5-8df4-4fffda9c0b88)

- Broken decisions, 21: all deleted

Resolved 2023-05-10

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/01e48f81-e8fc-4164-9e05-f672cefe95a2)


**Re-synced 2023-05-10**

**Comment by yroskov** [comment]
**ver 2023-06-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/e3db2773-fb38-4e78-92f4-88cadbac1400)

- Broken decisions, 26: all deleted

Resolved 2023-06-08:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/c13a0885-108f-46c0-bdb4-f0cf7bab84ed)

**Re-synced 2023-06-08**

**Comment by yroskov** [comment]
- Metadata https://github.com/CatalogueOfLife/data/issues/454

**Comment by yroskov** [comment]
**ver 2024-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/3b40271e-6733-44ff-aa53-b98f2cd29784)

Resolved 2024-05-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/c5f21f22-357c-4d7e-934c-1ba1fec0c2e0)

**Re-synced 2024-05-07**

**Comment by yroskov** [comment]
@bart-v, just in case: CLB reported double entry for †Stephanophyllia celsa Počta, 1887: 

https://www.marinespecies.org/scleractinia/aphia.php?p=taxdetails&id=1509936
and
https://www.marinespecies.org/scleractinia/aphia.php?p=taxdetails&id=1697737

**Comment by bart-v** [comment]
Thx, fixed in WoRMS

**Comment by yroskov** [comment]
**ver 2025-05-01**

TASKS

![Image](https://github.com/user-attachments/assets/0263513f-2cd4-4fdd-990a-e828fb26f3fb)

- Manuscript names, 0 of 2 = n/a
- Broken decisions, 248 = deleted 

Resolved 2025-05-09:

![Image](https://github.com/user-attachments/assets/ffd41f70-0d1c-443e-9885-735b2aaef17b)

**Synced 2025-05-09**

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 1 names with portion _incertae sedis_ = 1 prov acc IGNORED

@bart-v, FYI:
- Unmatched Name Brackets, [3](https://www.checklistbank.org/catalogue/3/dataset/1196/workbench?issue=unmatched%20name%20brackets&limit=100) 

ISSUES assessed 2025-05-21

![Image](https://github.com/user-attachments/assets/949881ad-01d4-413b-af4b-ced652f48e19)

TASKS = no new issues

![Image](https://github.com/user-attachments/assets/ee287340-034f-44a1-b94c-51db5a527e71)

**Synced 2025-05-21**

**Comment by bart-v** [comment]
403 access denied, cannot fix brackets

**Comment by yroskov** [comment]
Sorry. 
Unmatched Name Brackets, 3:
https://www.checklistbank.org/dataset/1196/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=secondarySource&facet=group&issue=unmatched%20name%20brackets&limit=50&offset=0

**Comment by bart-v** [comment]
Thx, all 3 fixed

**Comment by yroskov** [comment]
**ver. 2025-09-01**

TASKS

<img width="1332" height="932" alt="Image" src="https://github.com/user-attachments/assets/2aa8724c-de6e-4de9-b99f-bb1397dc8971" />

Resolved 2025-09-11:

<img width="1354" height="964" alt="Image" src="https://github.com/user-attachments/assets/cb6ede93-304b-46c5-ab91-7a0eb6f24c52" />

**Re-synced 2025-09-11**

**Comment by yroskov** [comment]
**ver. 2025-11-01**

TASKS

<img width="1895" height="1235" alt="Image" src="https://github.com/user-attachments/assets/6114ec46-ad5c-46c6-917d-154172d443d0" />

- Manuscript names, 3 = no acc names
- Broken decisions, 5 = deleted
- Outdated decisions, 0

Resolved 2025-11-11:

<img width="1931" height="1293" alt="Image" src="https://github.com/user-attachments/assets/875b94d5-b75c-4c4c-b795-5cde59c9483a" />

**Re-synced 2025-11-11**

**Comment by yroskov** [comment]
**ver. 2025-12-01**

TASKS

<img width="1617" height="1063" alt="Image" src="https://github.com/user-attachments/assets/29c03b82-b556-49b8-889d-8198ef98a130" />

- Manuscript names, 0 of 3 = no action 9bare & syn)
- Broken decisions, 12 = deleted
- Outdated decisions, 1 = deleted

Resolved 2025-12-12:

<img width="1617" height="1047" alt="Image" src="https://github.com/user-attachments/assets/ed41a184-0200-4ab0-8f98-0cdc0624453f" />

**Re-synced 2025-12-12**

**Comment by yroskov** [comment]
**ver. 2026-03-01**

TASKS

<img width="1721" height="1203" alt="Image" src="https://github.com/user-attachments/assets/99f6b8a0-48e5-43aa-ba35-3fff7a004ef6" />

- Broken decisions, 27 = deleted
- Outdated decisions, 2 = deleted

Resolved 2026-03-10:

<img width="1721" height="1184" alt="Image" src="https://github.com/user-attachments/assets/52d5395f-9cf5-4823-85a2-5ff98acd03c7" />

**Re-synced 2026-03-10**
