### ISSUE TITLE
WoRMS Scyphozoa (id 1188): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#113]
WoRMS Scyphozoa, id 1188 on prod
https://data.catalogueoflife.org/dataset/1188/meta

- [x] _Sector:_ class Scyphozoa (wasn't broken)
- [ ] _Metadata:_ as available for 2021-04-01. "Smithsonian Institution" parsed incorrectly.
- [x] _Imported:_  224 spp vs 194 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-04-23

- [ ] **Unusual Name Characters**, 2. One accepted name with diacritics: Cyanea mjöbergi Stiasny, 1921
https://data.catalogueoflife.org/catalogue/3/dataset/1188/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=unusual%20name%20characters&limit=100&offset=0

**Comment by yroskov** [comment]
**TASKS** 2021-04-23

![image](https://user-images.githubusercontent.com/28574252/115884569-a9ccbb00-a414-11eb-935f-0fcc3d8468cf.png)

Resolved:

![image](https://user-images.githubusercontent.com/28574252/115884691-ccf76a80-a414-11eb-830f-69bf902ff943.png)

**Comment by yroskov** [comment]
Synced 2021-04-23
