### ISSUE TITLE
WoRMS Staurozoa (id 1184): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#114]
WoRMS Staurozoa, id 1184 on prod
https://data.catalogueoflife.org/dataset/1184/meta

- [x] _Sector:_ class Staurozoa (wasn't broken)
- [x] _Metadata:_ as available for 2021-04-01
- [x] _Imported:_ 49 spp vs 50 in ac19

**ISSUES** 2021-04-23
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-04-23

No issues

![image](https://user-images.githubusercontent.com/28574252/115912704-456e2380-a435-11eb-8a98-4b7457ec6af9.png)

**Comment by yroskov** [comment]
Synced 2021-04-23
