### ISSUE TITLE
WoRMS Tanaidacea (id 1110): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#115]
WoRMS Tanaidacea, id 1110 on prod
https://data.catalogueoflife.org/dataset/1110/meta

- [x] _Sector:_ order Tanaidacea established
- [x] _Metadata:_ as available for 2021-04-01
- [x] _Imported:_  1504 spp vs 1435 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-04-23

-[x] **Unparsable Authorship**, 31 
In CoL: synonyms with authorstrigs containing "not" are flagged as MisappliedNames (i.e. Apseudes minutus Brown, 1956 not Claus, 1888; Apseudes talpa (Lilljeborg, 1864) not (Montagu, 1808)

**Comment by yroskov** [comment]
**TASKS** 2021-04-23

![image](https://user-images.githubusercontent.com/28574252/115914262-54ee6c00-a437-11eb-9a85-d035fa3d16d9.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/115915085-6ab06100-a438-11eb-81c0-5d8a72dd10f5.png)



- [ ] **Two broken decisions**. Unresolved.
![image](https://user-images.githubusercontent.com/28574252/115914963-405ea380-a438-11eb-8b67-387ea51486c0.png)

these are two names flagged as Provisionally Accepted:
![image](https://user-images.githubusercontent.com/28574252/115914847-19a06d00-a438-11eb-994e-3e071e5838df.png)

**Comment by yroskov** [comment]
Synced 2021-04-23

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/183086920-4fa57976-56f3-4e8e-96b4-5c33c90b1f87.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/183089555-53d4d054-9337-4bc6-aa1e-16d265c2ee28.png)

Synced 2022-08-05

**Comment by yroskov** [comment]
**ver 2023-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/68d8a8c6-c7e6-4714-a662-15bffc95b96f)

- Broken decisions, 18: all deleted

Resolved 2023-05-10

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/48cd8c8a-83d5-4e59-8415-ec91c3cebb49)

**Re-synced 2023-05-10**

**Comment by yroskov** [comment]
**ver 2023-06-01**

TASKS

- Broken decisions, 18: all deleted

Resolved 2023-06-08:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/a9fa5190-5b38-482a-88e6-abb92cbaa36f)

**Re-synced 2023-06-08**

**Comment by yroskov** [comment]
**ver 2025-01-01**

Continue with **Either the opening or closing bracket is missing in the authorship**...
https://www.checklistbank.org/dataset/307413/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&issue=unmatched%20name%20brackets&limit=50&offset=0

@bart-v, missing bracket in Pseudolongiflagrum caeruleus (Boesch, 1973  https://www.marinespecies.org/aphia.php?p=taxdetails&id=1612936

**Comment by bart-v** [comment]
Fixed

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 3 names with portion _incertae sedis_ = 3 prov acc IGNORED

ISSUES assessed 2025-05-21

![Image](https://github.com/user-attachments/assets/a5840cce-8045-42c8-ab77-afa969434116)

TASKS

![Image](https://github.com/user-attachments/assets/2d35e093-5dd9-4842-8bd9-f6615daa1b1c)

- Broken decisions, 60 = deleted

Resolved 2025-05-21:

![Image](https://github.com/user-attachments/assets/03a10619-6f18-4d84-bb13-9560b7fe57d9)

**Synced 2025-05-21**
