### ISSUE TITLE
Towards the next Annual Checklist 2021

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#118]
_version of 2020-11-02_ for @olafbanki attention

**CONTENT, ESSENTIAL:** 

**1) Rebuild pipelines for automated updates, and update cluster checklists:**
- [x] ITIS via CoLDP, 66 sectors 
- [x] WoRMS via CoLDP, 60 checklists
- [ ] TaxonWorks via CoLDP, 17+1 Species Files, 2 3i checklists (in good progress)
- [ ] DBTNT-Paris, 7 checklists
_(these providers cover ~503K (27%) species in CoL)_

**CONTENT, DESIRABLE:**

**1) bring 2-3 more new checklists and achieve 1.9M species in total:**
- [x] New checklist(s) from TaxonWorks (WCO: World Catalogue of Opiliones)
- [x] New checklist(s) from WoRMS (Brachiopoda (replacement), Crinoidea, Euphausiacea (replacement), Nemys)
- [ ] ~~Acarorum Catalogus vol. 6-7 by Petar Beron~~
- [ ] ~~Zygentoma (silverfish) by Markus Koch~~

**2) update GSDs, at least**
- [ ] FishBase via CoLDP
- [ ] ~~WCSP~~ (at least, via DwC as it presents in the Clearinghouse - DwC of WCVP is a nude name list
- [x] Systema Dipterorum (in good progress)
- [x] WTaxa (in good progress)
- [x] The Reptile Database - NEED TO SYNC A NEW VER WITH SUBSP (block duplicated syns!)
- [ ] ~~TITAN via website crawler~~
- [ ] ~~ScaleNet~~
- [ ] ~~Briophytes~~ @ WFO

**3) update estimates**, incl. GSD sectors, where estimates should be equal to accounted species (ITIS, SF)

**LEGAL ISSUES, ESSENTIAL**
**IPR, credits & publication attributes**
- [x] clean up IPR issues (license) with each database custodian
- [ ] be sure that every custodian happy with credits in a new environment
- [x] set up DOIs for CoL editions and GSD components
- [ ] get a new ISSN for online editions (if required)

**SOFTWARE, ESSENTIAL**
**Software ready for production**
- [ ] complete production interface development, incl. issues mentioned here:
https://github.com/CatalogueOfLife/portal/issues/41 
https://github.com/CatalogueOfLife/portal/issues/40 
https://github.com/CatalogueOfLife/data/issues/199 
- [ ] discuss interface prototype with GSD providers and user panel
- [ ] get approval from GT for a final interface version
- [ ] be sure that name IDs are persistent through CoL editions
- [ ] be sure that deployment stages are reliable
