### ISSUE TITLE
CCW: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#120]
Data received 2021-05-07. Two files: **CCW species voor COL.xlsx** & **CCW complete voor COL.xlsx** ("complete" contains lines with Genus name + Authorstring + generic Synonyms .

Original format.  Fields: cat nr	kingdom	class	order	family	subfamily	genus	subgenus	species	subspecies	author and year	original genus	synonym(s), synonym of, doubtful taxon	distribution

**Comment by yroskov** [comment]
- [ ] 6 species are not assign in any family. Need to ask Pjotr, what to do with them?

![image](https://user-images.githubusercontent.com/28574252/117867323-d6c6fd80-b25d-11eb-9fe5-f921d412a858.png)

**Comment by yroskov** [comment]
Names to chec synonymy:
Acc
Phalacrocera replicata (Linnaeus, 1758)
Synonyms
    = Phalacrocera fusca (De Geer, 1773)
    = Phalacrocera brevirostris (Zetterstedt, 1838)
    = Phalacrocera diversa (Walker, 1856)
    = Phalacrocera neoxena Alexander, 1914
    = Phalacrocera nudicornis (Schummel, 1829)
    ≡ Tipula replicata Linnaeus, 1758

**Comment by yroskov** [comment]
@gdower imported data to the prod: https://data.catalogueoflife.org/dataset/1005/classification, 2021-05-11

**Comment by yroskov** [comment]
From: Pjotr Oosterbroek 
Sent: Friday, May 14, 2021 8:11
To: Roskov, Yury 
Cc: Ower, Geoffrey Donald 
Subject: Two remaining CCW items

Dear Yury and Geoff,

Many thanks again for your time an patience while updating the CCW to the COL.

1) This link to Gynoplistia reidi: https://data.catalogueoflife.org/dataset/1005/taxon/2167 
It has Molophilus reidi as a synonym. This is incorrect. My mistake again.
The species was described as a Gynoplistia and there are no synonyms. Molophilus reidi does not exist.

- [x] YR **blocked name Molophilus reidi**
![image](https://user-images.githubusercontent.com/28574252/118280039-6bfe0800-b491-11eb-961a-a690fc0ad64e.png)


2) Credits and metadata.
This now looks as follows.

Organisation = Naturalis Biodiversity Center, Darwinweg 2, 2333 CR Leiden, The Netherlands
Description = The Catalogue of the Craneflies of the World (CCW; ccw.naturalis.nl) covers all genera, subgenera, species, subspecies, and synonyms of the World Tipuloidea (Insecta – Diptera – Nematocera – families Pediciidae, Limoniidae, Cylindrotomidae, Tipulidae), in total XX.XXX taxa. It also includes up to date information on the distribution of the species and subspecies, specified by countries and, for the larger countries, states, provinces and islands. The website’s list of references has over 7.400 titles, about 4.300 of which available as easy downloadable pdf.

Please fill in the number as taxa as in the COL.

I hope this settles all. Let me know when it goes online.

Kind regards,

Pjotr Oosterbroek

**Comment by yroskov** [comment]
- [x] Sector superfamily Tipuloidea in order Diptera re-established 2021-05-14

**ISSUES**
- [x] Assessed
**Indetermined**, 3
accepted Maekistocera species Jeevan Jose, 2015
synonym Megistocera species Jeevan Jose, 2015

**Comment by yroskov** [comment]
**TASKS**

![image](https://user-images.githubusercontent.com/28574252/118282497-f21b4e00-b493-11eb-94b8-c60d7a649077.png)

Resolved 2021-05-14

![image](https://user-images.githubusercontent.com/28574252/118282714-34448f80-b494-11eb-91a6-abf908f09d72.png)

**Comment by yroskov** [comment]
**Synced 2021-05-14**

**Comment by yroskov** [comment]
Pjotr has checked PREVIEW of 2021-05-19 and reported (eml of 2021-05-22):

1) A search for the synomym “jaroslavi” give the proper result
**But a search for the synonym Tipula solstitialis gives no result.**

Indeed, the system marked **Tipula (Yamatotipula) solstitialis** Westhoff, 1879 as **bare name**. Why? - @mdoering, @gdower

**Comment by mdoering** [comment]
A bare name is a name record without a reference from either Synonym, Taxon or NameUsage "tables".
It seems they simply forgot such a record for [nameID= 17778](https://data.catalogueoflife.org/dataset/1005/verbatim?type=col%3ATaxon&type=col%3ASynonym&type=col%3AName&type=col%3ANameRel&type=col%3ANameReference&type=col%3ATypeMaterial&col:nameID=17778&col:nameID=17778&col:basionymID=17778&col:nameID=17778&col:relatedNameID=17778&col:nameID=17778&col:nameID=17778&termOp=OR)?

**Comment by mdoering** [comment]
@gdower the synonym.tsv file uses quotes which causes the problems:

> "11777"	"Tipuloidea-Limoniidae-Limoniinae-Ceratocheilus-tasmaniensis"	"synonym"

They are not present in the other files, please remove them from the TSV. `"11777"` is considered the value, not `11777`

**Comment by mdoering** [comment]
This is a weird mix of identifiers, resulting in a bad archive:

 - _Taxon.tsv_ uses the concatenated classification like `Tipuloidea-Cylindrotomidae-Stibadocerinae-Stibadocerodes`. 
 - _Synonm.tsv_ uses quoted integer numbers like `"11777"`
 - _Distribution.tsv_ refers to taxa with integers like those used in synonyms: `"22"`
 - _Name.tsv_ uses a mix of both integers and classification string, but does not quote any values incl integers.

I am surprised to not find more ID issues here:
https://data.catalogueoflife.org/dataset/1005/issues

**Comment by yroskov** [comment]
More comments from Pjotr  (eml to @yroskov of 2021-05-25): - for attaention of @gdower @mdoering 

Dear Yuri

About 
1.	Very strange situation: the software has marked Tipula (Yamatotipula) solstitialis Westhoff, 1879 as “bare name” and excluded it from CoL. I have reported this as a bug to the programmers.
 
There are many more synonyms that are not found. Of course I can not check them all, but by random checking I found:
Amphineurus flavoscutellatus
Ormosia sytlifer
Paradelphomyia abnormalis
Ctenophora hilgendorfi
Ctenophora nigrobasalis
Ptilogyna longipedalis
Tipula cinctocornis
Tipula casta
Tipula docilis

It is apparently not completely ad random, it seems that
- all 96 synonyms in the genus Nephrotoma are found.
- all 399 synonyms in the genus Tipula are not found

A very minor remark, while checking these synonyms I came across Tipula fasciculatus Fabricius, 1781, whereas the original description is as Tipula fasciculata

![image](https://user-images.githubusercontent.com/28574252/119500518-83f54780-bd2d-11eb-960f-6dd96475beeb.png)

**Comment by yroskov** [comment]
Pjotr:

The **synonyms are not the first interest of the users**.
I strongly suggest to **stick to the latest update** because it includes all new taxa and an enormous amount of new distributional information.
Meanwhile, try to fix the synonyms.

All the best,
Pjotr Oosterbroek

**Comment by yroskov** [comment]
**Improved data imported 2021-05-25**: https://data.catalogueoflife.org/catalogue/3/dataset/1005/classification

**TASKS**

![image](https://user-images.githubusercontent.com/28574252/119572991-3c94a880-bd79-11eb-9835-9a6dec6184ee.png)

Resolved 2021-05-25:

![image](https://user-images.githubusercontent.com/28574252/119573144-7b2a6300-bd79-11eb-9424-4dd4c135c2e1.png)

**Comment by yroskov** [comment]
**Synced 2021-05-25**

**Comment by yroskov** [comment]
See https://github.com/CatalogueOfLife/data/issues/927

**Comment by yroskov** [comment]
Request for a new version sent to Pjotr 2025-02-20

**Comment by yroskov** [comment]
Data received 2025-02-21. Excel file **CCW for Col 2025-02-21.xlsx**. Columns: nr	Status 1	Status 2	Status 3	subfamily	genus	subg	spec	subsp	auth	descr	orig. genus	distr	syns	unrecognize or doubtful

Pjotr:
_Presently there are 15.731 living species in the CCW. (As you call them, I doubt how much are still living.)
Attached is an Excell sheet for these 15.731 species, their genera, subgenera, subspecies, synonyms, distribution.
The three ’status’ columns is just for your information.
**Note that all more than 100 Eloeophila species group names are now in [CCW genus] Idioptera** (after Santos and Ribeiro, 2024, pdf in CCW).

My workfile is in Filemaker. Shall I send you this as well ?

We are working on a catalogue for fossil craneflies.
Does CoL include fossils.
Anyway, it is the best to wait until the catalogue is published.

Please let me know how the Excell file should be arranged otherwise to make it work for you._

**Comment by yroskov** [comment]
**CCW of Mar 2025 / 2025-03-15**
_Geoff received data as an Excel file and as a copy of Filemaker database)_

- [x] Imported: 15566 spp (vs 15452 spp in AC24)  
- [x] Metadata: OK (re-used)
- [x] Classification: OK. Superfamily (1) - Family (4) - Subfamily (11) - Genus (213) - Subgenus (329) - Species (15566) - Subspecies (495) 
- [x] Sectors: broken (missing subject) = FIXED. Families Cylindrotomidae, Limoniidae, Pediciidae & Tipulidae
- [ ] No extinct flag: paleotaxa not included yet (Pjotr: _Anyway, it is the best to wait until the catalogue is published_)
- [ ] Links to the website species pages: no

Metrics:

![Image](https://github.com/user-attachments/assets/74198341-161b-419f-b9af-0fa3e33b6cdf)

ISSUES assessed 2025-04-08

![Image](https://github.com/user-attachments/assets/9d955388-a772-4a2d-afda-6af922cd8bef)

TASKS

![Image](https://github.com/user-attachments/assets/bda074c4-7885-48b6-9538-4f75d474f62e)

- Broken decisions, 130 = deleted
- Outdated decisions, 26 = deleted

Resolved 2025-04-08:

![Image](https://github.com/user-attachments/assets/56e581c4-6092-4e2c-b8cf-f5b07e418184)

**Synced 2025-04-08**

**Comment by yroskov** [comment]
**CCW of Apr 2025 / 2025-04-10**; imported 2025-04-14
_Now with links to the source species pages_

- [x] Imported: 15566 spp (vs 15566 spp)  
- [x] Metadata: OK 
- [x] Classification: OK
- [x] Sectors: OK
- [ ] No extinct flag: paleotaxa not included yet (Pjotr: _Anyway, it is the best to wait until the catalogue is published_)
- [x] Links to the website species pages: OK

Metrics:

![Image](https://github.com/user-attachments/assets/8ae8b10d-44b1-4396-8ffc-9f506bb06f59)

ISSUES assessed 2025-04-17

![Image](https://github.com/user-attachments/assets/f1bace3c-8552-4cbd-a84e-927e0bc9c681)

- Unparsable Authorship,[1](https://www.checklistbank.org/catalogue/3/dataset/1005/workbench?issue=unparsable%20authorship&limit=100) = Pselliophora gloria Alexander, 192r -> 1924 = **change/decision does not appear** 

TASKS

![Image](https://github.com/user-attachments/assets/15f88edd-0ca7-4da0-aee1-f0acddc90e5e)

Resolved 2025-04-17:

![Image](https://github.com/user-attachments/assets/74e3b621-d6c2-4fe0-a70a-a30778b70b3e)

**Synced 2025-04-17**
