### ISSUE TITLE
Eumycetozoa.com (id 1053): test report 

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#122]
Update received: 2021-05-15

Imported: 2021-05-10
https://data.catalogueoflife.org/dataset/1053/classification

**Comment by yroskov** [comment]
- [x] Metadata checked & updated

- [x] Sector Ok

- [x] **Issues**: assessed
- **Indetermined**, 3    - 3 subgenera marked as bare names (not resolved):
Arcyria subg. Arcyrella Rostaf., 1875	bare name	species	
Arcyria subg. Clathroides Rostaf., 1875	bare name	species	
Arcyria subg. Lachnobolus Fr., 1829 bare name	species	

- **Multi Word Epithet**, 23 - quadrinomials (all syns) are blocked

**Comment by yroskov** [comment]
**TASKS**

![image](https://user-images.githubusercontent.com/28574252/118136360-a69c6d80-b3c9-11eb-84b9-e1edc0d33dd4.png)

  | x4M |   | accepted | Ceratiomyxaceae |   | family | Protozoa>Mycetozoa>Myxomycetes>Ceratiomyxales
-- | -- | -- | -- | -- | -- | -- | --
  | x4T |   | accepted | Ceratiomyxaceae |   | family | Protozoa>Mycetozoa>Protosteliomycetes>Ceratiomyxales

**Comment by yroskov** [comment]
2021-05-13: waiting for answer from Carlos on "split" family & genera.

**Comment by yroskov** [comment]
Experimental sync with unresolved "splits" 2021-05-13.

**Comment by yroskov** [comment]
Carlos, 2021-05-18: correct classification in bold:

Protozoa>Mycetozoa>Myxomycetes>Ceratiomyxales> Ceratiomyxaceae
**Protozoa>Mycetozoa>Protosteliomycetes>Ceratiomyxales> Ceratiomyxaceae** 
 
And 3 genera “split” in different places:
 
**Protozoa>Mycetozoa>Protosteliomycetes>Ceratiomyxales>Ceratiomyxaceae>Ceratiomyxa** 
Protozoa>Mycetozoa>Myxomycetes>Ceratiomyxales>Ceratiomyxaceae>Ceratiomyxa 
 
**Protozoa>Mycetozoa>Dictyosteliomycetes>Dictyosteliales>Dictyosteliaceae>Dictyostelium** 
Protozoa>Mycetozoa>Dictyosteliomycetes>Incertae sedis>Incertae sedis>Dictyostelium 
 
**Protozoa>Mycetozoa>Myxomycetes>Physarales>Didymiaceae>Didymium** 
Protozoa>Mycetozoa>Myxomycetes>Physarales>Physaraceae>Didymium

**Comment by yroskov** [comment]
Source file has been corrected. Imported 2021-05-18.

**TASKS**

![image](https://user-images.githubusercontent.com/28574252/118729023-c503ce00-b7fa-11eb-83f3-ddef9d0b9f39.png)

**Comment by yroskov** [comment]
**Final sync 2021-05-19**

**Comment by yroskov** [comment]
**Eumycetoza.com of May 2022** received 2022-05-25; imported 2022-05-25

- [x] Imported: 1224 spp 
- [x] Metadata: checked
- [x] Classification: OK
![image](https://user-images.githubusercontent.com/28574252/170530523-52b374aa-de8f-4ca7-970f-5772555fb22b.png)
- [x] Sector: Ok

**ISSUES** assessed 2022-05-26
![image](https://user-images.githubusercontent.com/28574252/170530794-063610eb-d033-4af2-9ace-7cc9c9de8de3.png)

- Multi Word Epithet, 23. 20 quadrinomial synonyms (e.g. Dictydium cancellatum subsp. anomalum var. purpureum (T.Macbr.) Meyl., 1937) blocked.

**Comment by yroskov** [comment]
- [ ] 2023-01-09, bug in synonymy reported via GBIF: https://github.com/CatalogueOfLife/data/issues/500

ac21: correct
https://www.checklistbank.org/dataset/2328/taxon/53QDL

export files (2022-05-20, zip 2022-05-25): correct

nomen.eumycetozoa.com @CLB: wrong
https://www.checklistbank.org/dataset/1053/taxon/1225

ac22: wrong
https://www.checklistbank.org/dataset/9837/taxon/53QDL

**Comment by yroskov** [comment]
PREVIEW started 2023-01-11 (server time 7:04 pm)
Finished as COL23.1, 2023-01-11, id 9858
Deployed to the PREVIEW site 2023-01-12

- [ ] nomen.eumycetozoa.com of 2022-05-25: synonymy
Synonyms are missing in the PREVIEW site (for example, for accepted species _Fuligo septica_ (L.) F.H.Wigg., 1780): 

**CLB: 53 synonyms** at https://www.checklistbank.org/dataset/9858/taxon/6JRVD
![image](https://user-images.githubusercontent.com/28574252/212098018-7e9b0999-d07e-41b4-bad6-b31051bf846a.png)

**PREVIEW: only 2 synonyms** at https://preview.catalogueoflife.org/data/taxon/6JRVD
Both these synonyms are not present in CLB(!)
![image](https://user-images.githubusercontent.com/28574252/212097905-7c39f271-8f1d-4953-9a4d-ceb73339b494.png)

**Comment by yroskov** [comment]
New version:
**Eumycetoza.com** of Jan 2023 received 2023-01-12; imported 2023-01-12



ISSUES

- Subspecies Assigned, 3: only 3 synonyms with portion "subg." in SpeciesEpithet field: Arcyria subg. Arcyrella Rostaf., 1875; Arcyria subg. Clathroides Rostaf., 1875; Arcyria subg. Lachnobolus Fr., 1829 = No problem, marked as _bare names_ by CLB

**Comment by yroskov** [comment]
**Eumycetoza.com of May 2024** received 2024-05-21; imported 2024-06-03

- [x] Imported: 1345 spp (vs 1297 spp)
- [x] Metadata: OK
- [x] Classification: OK 
- [x] Sector: OK, phylum: Mycetozoa

Metrics

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/d05eb83b-a9bd-4b10-bbcf-6f87defc034a)

ISSUES assessed 2024-06-04

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/570487fc-b177-4c6c-9a16-931caebb20ed)

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/442f1087-7668-450c-b72d-e12109e1f0f9)

- Broken decisions, 187 = all deleted 
- Outdated decisions, 4 = no actions (ref: the problem of decisions between GSDs)

Resolved 2024-06-04:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/d52253bf-ada8-4222-96ee-58514dd9761e)

**Synced 2024-06-04**
