### ISSUE TITLE
WoRMS Euphausiacea (id 2301): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#123]
WoRMS Euphausiacea (id 2301) - new dataset in replacement of frozen ETI WBD: World Biodiversity Database (Euphausiacea) with 86 spp

Dataset received 2021-05-01. Imported to prod 2021-05-06.
https://data.catalogueoflife.org/dataset/2301/about

- [x] Imported 86 spp (vs 86 spp in ac19)

- [x] Sector: order Euphausiacea; established in replacement of ETI checklist

- [ ] Metadata: short name with underscore; no organisation; eds in authors field

**Comment by yroskov** [comment]
**ISSUES**
- [x] Assessed

**TASKS**
No issues.

![image](https://user-images.githubusercontent.com/28574252/118144338-eff0bb00-b3d1-11eb-9d64-d2e4b4e86c4a.png)

**Comment by yroskov** [comment]
**Synced 2021-05-13**
