### ISSUE TITLE
WoRMS Brachiopoda (id 2209): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#124]
**WoRMS Brachiopoda**, id 2299 - new dataset as a replacement for frozen Brachiopoda Database by Emig C.C., Bitner M.A., Alvarez F. (2016) with 396 spp.

Dataset received 2021-05-01. Imported to prod 2021-05-06.
https://data.catalogueoflife.org/dataset/2299/about

- [x] Imported 435 spp (vs 396 spp in ac19)

- [x] Sector: phylum Brachiopoda; established in replacement of Brachiopoda Database

- [ ] Metadata: short name with underscore; organisation shown as "WoRMS"; authors shown as "WoRMS" (@bart-v, is that OK?); no English name of the taxon; no GeographicScope (Global?); no ChecklistConfidence (5 stars?), no Completeness (100%?)

**Comment by yroskov** [comment]
**ISSUES**
- [x] Assessed

**TASKS** 2021-05-13

![image](https://user-images.githubusercontent.com/28574252/118151209-00586400-b3d9-11eb-8863-8eb85efd188d.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/118151425-3a296a80-b3d9-11eb-8e6c-d46150a6aa7a.png)

**Comment by yroskov** [comment]
**Synced 2021-05-13**

**Comment by bart-v** [comment]
Yes, WoRMS is OK as there is no actual editor (yet).
The Data Management Team is maintaining it for the time being.

The metadata fix is now live. So the June 2021 export will have a proper metadata.yml for all GSDs

**Comment by yroskov** [comment]
**ver 2023-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/8ae7ec67-9198-4acf-ab89-6af2d1bbec19)

- Broken decisions, 1: all deleted

Resolved 2023-05-10

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/bb187357-eede-4787-b417-ccbf0f224ce7)

**Re-synced 2023-05-10**

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

ISSUES assessed 2025-05-20

![Image](https://github.com/user-attachments/assets/ad299766-78ab-41de-ac76-dec63f6e42cb)

TASKS

![Image](https://github.com/user-attachments/assets/9d7698ef-6665-44d8-8041-dc42a5f46a1a)

- Broken decisions, 4 = deleted
- Outdated decisions, 1 = no action

Resolved 2025-05-20:

![Image](https://github.com/user-attachments/assets/dd04868d-6e71-407c-8a44-4e5d026f9c52)

**Synced 2025-05-20**

**Comment by yroskov** [comment]
**ver. 2025-10-01**

TASKS

<img width="1591" height="1063" alt="Image" src="https://github.com/user-attachments/assets/9afd7dd1-6342-452d-b143-a22f26e00abd" />

Resolved 2025-10-06:

<img width="1591" height="1047" alt="Image" src="https://github.com/user-attachments/assets/130e98eb-1cfe-4d1e-8918-da2beae93aaf" />

**Re-synced 2025-10-06**
