### ISSUE TITLE
WoRMS Crinoidea (id 2300): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#125]
**WoRMS Crinoidea**, id 2300 - a new dataset since May 2021

Dataset received 2021-05-01. Imported to prod 2021-05-06.
https://data.catalogueoflife.org/dataset/2300/about

- [x] Imported 672 spp (vs ?? spp in ac19)

- [x] Sector: subphylum Crinozoa (in phylum Echinodermata); established 2021-05-13

- [ ] Metadata: short name with underscore; organisation incorrectly parsed; no English name of the taxon (Crinoids?); no GeographicScope (Global?); no ChecklistConfidence (5 stars?), no Completeness (100%?) (@bart-v)

**Comment by yroskov** [comment]
**ISSUES**
- [x] Assessed
**Unparsable Authorship**, 25 - few synonyms with comment "non"/"not of" are flagged as Misapplied Names in CoL
https://data.catalogueoflife.org/catalogue/3/dataset/2300/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=unparsable%20authorship&limit=100&offset=0

**Comment by yroskov** [comment]
**TASKS** 

![image](https://user-images.githubusercontent.com/28574252/118156718-4ca6a280-b3df-11eb-9308-be757a725681.png)

Resolved 2021-05-13

![image](https://user-images.githubusercontent.com/28574252/118156869-795aba00-b3df-11eb-8fc9-ef483cc49aba.png)

**Comment by bart-v** [comment]
Metadata OK as you suggest. June 2021 export will have the proper values.

**Comment by yroskov** [comment]
**ver 2023-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/eb1fb025-77b5-4b35-8306-fc2a31a3bc9a)

- Broken decisions, 5: all deleted

Resolved 2023-05-10

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/4f837142-b850-49c7-afc8-04b923fbbecb)

**Re-synced 2023-05-10**

**Comment by yroskov** [comment]
**ver 2023-06-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/d718cbf9-967d-4d05-af3e-403f12000dab)

- Broken decisions, 5: all deleted

Resolved 2023-06-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/e2ef7646-4556-4623-b0ce-d2fee5af5252)

**Re-synced 2023-06-07**

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 12 names with portion _incertae sedis_ = 7 acc & 4 prov acc IGNORED

@bart-v, FYI:
- There are two entries for Poecilocrinus porcatus
https://www.marinespecies.org/aphia.php?p=taxdetails&id=1702346 _- without authorstring_
https://www.marinespecies.org/aphia.php?p=taxdetails&id=1702347 

ISSUES assessed 2025-05-22

![Image](https://github.com/user-attachments/assets/5601257e-bfdb-4ecb-8e93-f9ab7fbd29b2)

TASKS

![Image](https://github.com/user-attachments/assets/b00e524d-09e5-4ee8-94ef-017d96609b15)

- Broken decisions, 11 = deleted

Resolved 2025-05-22:

![Image](https://github.com/user-attachments/assets/88f6c1e3-a62c-4704-aed4-082d6d1bf64f)

**Synced 2025-05-22**

**Comment by bart-v** [comment]
Duplicate removed
