### ISSUE TITLE
WoRMS Nematoda, Nemys (id 2302): test report, part 1 (2021-2025, finished)

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#126]
**WoRMS Nematoda, Nemys**, id 2302 - a new dataset since May 2021

Dataset received 2021-05-01. Imported to prod 2021-05-06.
https://data.catalogueoflife.org/dataset/2302/about

- [x]  Imported 12219 spp (vs 3455 spp in ac19, all regional)

- [x] Sector: phylum Nematoda; established 2021-05-13

- [x] Metadata: OK, but short name with underscore; English name of the taxon is needed; no GeographicScope (Global?); no ChecklistConfidence (5 stars?), no Completeness (100%?)

**Comment by yroskov** [comment]
**ISSUES**
- [x] Assessed
**Unmatched Name Brackets**, 2 - fixed in CoL

**Indetermined**, 6 - 3 names with "sp" blocked in CoL

**Unusual Name Characters**, 19 - There are few accepted species names with diacritics (@bart-v). No actions in CoL.
https://data.catalogueoflife.org/dataset/2302/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=unusual%20name%20characters&limit=50&offset=0

**Unparsable Authorship**, 116. There are 3 names with character encoding problems (@bart-v). Fixed in CoL.
Amplimerlinius longicauda Castillo, Siddiqi & G√≥mez-Barcina, 1990
Amplimerlinius magnistylus Castillo, G√≥mez-Barcina, Vovlas & Navas, 1991
should be **Gómez-Barcina**

Paratrophurus bhutanensis (Ganguly, Lal & Proctor, 2004) Andr√°ssy, 2007
should be **Andrássy**

**Comment by yroskov** [comment]
**TASKS**

![image](https://user-images.githubusercontent.com/28574252/118186873-d8cac100-b403-11eb-9fb8-fcf2721015c1.png)

Resolved 2021-05-13

![image](https://user-images.githubusercontent.com/28574252/118187476-9786e100-b404-11eb-80a2-07e931173730.png)

**Comment by yroskov** [comment]
**Synced 2021-05-13**

**Comment by bart-v** [comment]
Authority character encoding issues fixed in Nemys.

**Comment by yroskov** [comment]
**Metadata patch** created 2021-06-29

alias: WoRMS Nematoda
title:  Nemys, World Database of Nematodes

**Comment by yroskov** [comment]
**ver 2021-11-01**

TASKS - there are changes
![image](https://user-images.githubusercontent.com/28574252/140391082-1f3514c8-8ed4-45b5-8694-3e3ad7a962eb.png)

- [x] Broken decisions, 0
- [x] Identical superfamily, family, genus, subgenus: all cases flagged as acc - prov acc by the dataprovider

Resolved 2021-11-04
![image](https://user-images.githubusercontent.com/28574252/140391746-4c19a26c-ee50-4f9b-83fa-dd4c5e730123.png)

**Comment by yroskov** [comment]
TASKS as 2022-07-26
![image](https://user-images.githubusercontent.com/28574252/181038490-37c4b92f-e0cb-4f8b-a731-13dc3b34f9af.png)

Resolved
![image](https://user-images.githubusercontent.com/28574252/181039026-39d8e9e6-507d-4786-ac42-8980de8dae99.png)

Synced 2022-07-26

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/182902051-aea637b9-d054-4ff7-bc69-aac1233b2c1e.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/182902608-feaab0e9-f040-4e79-ad8b-fb002d5b195c.png)

Re-synced 2022-08-04

**Comment by yroskov** [comment]
**ver 2023-05-01**

TASKS

![image](https://user-images.githubusercontent.com/28574252/236894067-9b0a741e-ec25-4b45-af47-285f083df61e.png)

- Broken decisions, 48: all deleted

Resolved 2023-05-08

**Re-synced 2023-05-08**

**Comment by bart-v** [comment]
Fixed in WoRMS

**Comment by yroskov** [comment]
**ver 2024-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/1f7eeae1-f857-47ba-b895-6d84511a638e)

- Broken decisions, 82 = deleted
- Outdated decisions, 3 = deleted

Resolved 2024-05-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/44dd318a-1dc3-44a8-a5c1-cb0303c889bc)

**Re-synced 2024-05-07**

**Comment by yroskov** [comment]
**ver 2024-06-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/5d459cb4-2518-4ed2-bf67-09edeb0e4ed9)

- Broken decisions, 132 = all deleted 

Resolved 2024-06-03:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/aea8d68c-58a9-40cb-b03d-bab2877dba4a)

**Synced 2024-06-03**

**Comment by yroskov** [comment]
**ver 2025-01-01**

Continue with **Either the opening or closing bracket is missing in the authorship**...
https://www.checklistbank.org/dataset/307413/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&issue=unmatched%20name%20brackets&limit=50&offset=0

@bart-v, duplicated year in Porrocaecum crassum (Deslongchamps, 1824) 1824) Railliet & Henry, 1912 https://nemys.ugent.be/aphia.php?p=taxdetails&id=1696159

**Comment by bart-v** [comment]
Fixed

**Comment by yroskov** [comment]
@bart-v, just in case, for the attention of Nemys editors (Markus reported):

Unresolved homonymic families **Iotonchidae Goodey, 1935** vs **Iotonchidae Jairajpuri, 1969** (= prov acc in CoL, 2025-04-14), re-synced

**Comment by bart-v** [comment]
Thanks
Forwarded to Nemys editors

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 11 names with portion _incertae sedis_ = 2 acc + 7 prov acc IGNORED

@bart-v, few issues: 
- Unmatched Name Brackets, [5](https://www.checklistbank.org/dataset/2302/names?issue=unmatched%20name%20brackets)
- ACC-ACC species (different authors), [16](https://www.checklistbank.org/dataset/2302/duplicates?authorshipDifferent=true&category=binomial&limit=100&minSize=2&mode=STRICT&offset=0&status=accepted) - _check for misspelled authorstrings in duplicated pairs_ 
- Identical genus, [4](https://www.checklistbank.org/dataset/2302/duplicates?_colCheck=b4) - it might be an interest for the checklist editors

ISSUES assessed 2025-05-20

![Image](https://github.com/user-attachments/assets/e476ccb8-2996-4700-8a27-d84518c780bd)

TASKS

![Image](https://github.com/user-attachments/assets/e4923d70-0792-4876-9452-87330bbbea68)

- Broken decisions, 148 = deleted
- Outdated decisions, 6 = no action

Resolved 2025-05-20:

![Image](https://github.com/user-attachments/assets/4d3f5f98-a2cb-44f3-b8fd-45d6c7c389cd)

**Synced 2025-05-20**

**Comment by bart-v** [comment]
- `Unmatched Name Brackets` are fixed
- duplicates have been forwarded to Nemys editors

**Comment by bart-v** [comment]
Duplicates removed now

**Comment by yroskov** [comment]
**ver. 2025-10-01**

TASKS

<img width="1591" height="1063" alt="Image" src="https://github.com/user-attachments/assets/61fa17bf-c6ef-49cb-886c-a748bf9426ee" />

Resolved 2025-10-06:

<img width="1591" height="1047" alt="Image" src="https://github.com/user-attachments/assets/6f9c1a7b-7a0e-45c6-b952-67b2eb8cbd0f" />

**Re-synced 2025-10-06**

**Comment by yroskov** [comment]
**ver. 2025-12-01**

TASKS

<img width="1617" height="1063" alt="Image" src="https://github.com/user-attachments/assets/fa271efc-f1c3-4213-8863-c5f48b595327" />

- Broken decisions, 83 = deleted
- Outdated decisions, 2 = deleted

Resolved 2025-12-12:

<img width="1617" height="1047" alt="Image" src="https://github.com/user-attachments/assets/e9fcb808-f0a4-4599-9fc1-a6375131f890" />

**Re-synced 2025-12-12**

**Comment by yroskov** [comment]
.
