### ISSUE TITLE
ReptileDB: test report 

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#129]
@gdower used database dump 2020_12_v2 + classification from http://www.reptile-database.org/db-info/taxa.html

First version on DEV: https://data.dev.catalogueoflife.org/dataset/2144/classification

**Comment by yroskov** [comment]
**CLASSIFICATION**

- [ ] Empty subfamilies in ord Squamata - superfam Scincomorpha - fam Scincidae:
Acontinae
Ateuchosauridae
Ristellidae 

![image](https://user-images.githubusercontent.com/28574252/118852622-8de3fa00-b898-11eb-823f-8d2a873e8c82.png)

Children taxa from the website:

Acontinae: children Acontias, Typhlosaurus https://reptile-database.reptarium.cz/advanced_search?taxon=Acontinae&submit=Search   - **these 2 genera are in subfamily NotAssigned in DEV**

Ateuchosauridae: 1 child Ateuchosaurus (2 spp) https://reptile-database.reptarium.cz/advanced_search?taxon=Ateuchosauridae&submit=Search - **the genus & 2 spp are in family Scincinae in DEV**

Ristellidae: children Lankascincus, Ristella https://reptile-database.reptarium.cz/advanced_search?taxon=Ristellidae&submit=Search - **these 2 genera are in family Sphenomorphinae in DEV**

**Comment by yroskov** [comment]
- [ ] family NotAssigned in superfamily Gymnophthalmoidea. To yr: from where are all its genera?
On the website, the superfamily has only 3 families (no space for NotAssigned).

**Comment by gdower** [comment]
Fixed those issues--it was caused by atypical formatting in the classification field.

**Comment by yroskov** [comment]
- [ ] family Shinisauridae in superfam Platynota in DEV - it should be in superfamily Shinisauroidea:
DEV: 
![image](https://user-images.githubusercontent.com/28574252/118863359-6b57de00-b8a4-11eb-8a87-39661f007ed2.png)

Website: 
![image](https://user-images.githubusercontent.com/28574252/118863420-7a3e9080-b8a4-11eb-8931-3c59723e9f74.png)

**Comment by yroskov** [comment]
- [ ] Families from unranked group Amphisbaenia  go to superfamily NotAssigned - **It's a best what we can do on our side**
![image](https://user-images.githubusercontent.com/28574252/118863977-1ff1ff80-b8a5-11eb-8d15-6e5598f702ae.png)

**Comment by yroskov** [comment]
- [ ] Empty subfamily Calabariinae in ord Squamata - superfam Booidea - fam Boidae
![image](https://user-images.githubusercontent.com/28574252/118864379-8b3bd180-b8a5-11eb-81c1-ffe6a603800f.png)

Website says, 1 sp Calabaria reinhardtii. 
https://reptile-database.reptarium.cz/species?genus=Calabaria&species=reinhardtii&search_param=%28%28taxon%3D%27Calabariinae%27%29%29 
The species is in subfamily NotAssigned in DEV:
https://data.dev.catalogueoflife.org/dataset/2144/classification?taxonKey=Squamata-Booidea-Boidae-Calabaria%20reinhardtii%20%28Schlegel%2C%201851%29

**Comment by yroskov** [comment]
- [ ] **genus Buhoma** in NotAssigned family in superfam Colubroidea - fam Colubridae.
No idea what is a right place for the genus - website does not give answer.

**Comment by yroskov** [comment]
- [ ] family Xenotyphlopidae misplaced in NotAssigned superfamily of Squomata order.
Should be in Superfamily Typhlopoidea:
![image](https://user-images.githubusercontent.com/28574252/118867280-83316100-b8a8-11eb-82bc-212b5d68cadb.png)

**Comment by yroskov** [comment]
- [  ] order Crocodylia: there are no separation of children between 2 subfamilies in Alligatoridae family on the website.

DEV: 
![image](https://user-images.githubusercontent.com/28574252/118867936-3d28cd00-b8a9-11eb-9198-7be155c94e63.png)

Website: order Crocodylia - suborder Eusuchia
Family Alligatoridae 
    Subfamily Alligatorinae
    Subfamily Caimaninae

![image](https://user-images.githubusercontent.com/28574252/118868427-ccce7b80-b8a9-11eb-9269-507d0c4aa8bb.png)

**Comment by yroskov** [comment]
**TESTS OF FINAL VERSION (2020-12) on prod**: https://data.catalogueoflife.org/dataset/1008/classification

- [ ] Metadata: updated

- [ ] Sector: established

- [x] Imported 11440 spp vs 10233 in ac19 (+1207, hmm, might be)

**Comment by yroskov** [comment]
**ISSUES**
- [ ] **Inconsistent Name**, 5. Left as they are, with quotation marks.
![image](https://user-images.githubusercontent.com/28574252/119369644-08868e00-bc7a-11eb-9b58-74158962ac76.png)


- [x] Blacklisted Epithet, 19. Incorrectly parsed names, marked as infraspecific names. All blocked in CoL.
https://data.catalogueoflife.org/catalogue/3/dataset/1008/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=blacklisted%20epithet&limit=100&offset=0
_Example:_
![image](https://user-images.githubusercontent.com/28574252/119369481-d6752c00-bc79-11eb-9434-ef0249047706.png)

**Comment by yroskov** [comment]
**TASKS**

![image](https://user-images.githubusercontent.com/28574252/119373425-06263300-bc7e-11eb-81f4-d2ef3854a18b.png)

- [x] ACC-SYN (same acc; same auth) - all syns blocked in CoL (in every(?) species)

Resolved 2021-05-24

**Comment by yroskov** [comment]
**ReptileDB ver 2020-12; Received by COL: 2021-05-03 - synced 2021-05-24**

**Comment by yroskov** [comment]
**ReptiveDB ver 2021-05**; received by CoL 2021-05-23. Imported on prod 2021-06-23 (**with accepted subsps**).

**Comment by yroskov** [comment]
**TASKS** 2021-06-23

![image](https://user-images.githubusercontent.com/28574252/123164946-360d5580-d439-11eb-85ee-f01e508a34a7.png)

- [ ] Broken decisions, 6490. RematchAll

**Comment by yroskov** [comment]
ReptileDB in ac21:

**Comment by yroskov** [comment]
TASKS after deletion of decisions **reptileDB + blocked + species**:
![image](https://user-images.githubusercontent.com/28574252/130263172-e82a2b58-7fe4-42a7-9fbe-07eee997309f.png)

**Comment by yroskov** [comment]
New version 2021-11. 
Dump received 2021-11-15. 
>The importer failed for reptiledb, getting stuck on something with distribution gazetteers.

**Comment by yroskov** [comment]
- [x] ISSUES assessed
![image](https://user-images.githubusercontent.com/28574252/142020033-6139e2e0-054c-42d5-9f69-c8cdac0ad3c7.png)

- [ ] Doubtful Name, 89 https://data.catalogueoflife.org/catalogue/3/dataset/1008/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=doubtful%20name&limit=100&offset=0
@gdower, in this report, there are misparsed names which interpreted like that (page from authorstring is moved to species epithet):
Anolis boulengeri **:242** O'Shaughnessy, 1881 - in original database Anolis boulengeri O'Shaughnessy, 1881**: 242**
Anolis turmalis **:278** O'Shaughnessy, 1875 - in original database  Anolis turmalis O'Shaughnessy, 1875**: 278**  

- can we do something about this case

**Comment by yroskov** [comment]
TASKS 2021-11-16
![image](https://user-images.githubusercontent.com/28574252/142029115-574d8beb-3acb-497f-9076-30c09472960e.png)

- [x] Broken decisions, 629; rematchAll = 204 left; deleted all

**Comment by yroskov** [comment]
Markus: **some vernacular names have the language given at the front of the actual name** e.g. (E) Freckled Monitor or (G) Trauerwaran (https://github.com/CatalogueOfLife/data/issues/352#event-5625694715)

https://data.catalogueoflife.org/dataset/1008/taxon/Reptilia-Squamata-Platynota-Varanidae-Varanus%20tristis-41ecd4c74f9a68152e708c6f4640ae6f

@gdower, can your convertor script resolve this?

**Comment by yroskov** [comment]
_Attention_: two separate genera **Macrelaps** and **Micrelaps** in the family: Atractaspididae.

Peter, 2022-01-14: Yes, that’s correct (and potentially confusing): two genera (within the same family) that are not even closely related.

**Comment by yroskov** [comment]
Revisiting "decisions" after fixes https://github.com/CatalogueOfLife/testing/issues/184#issuecomment-1055567444

TASKS 2022-03-04
![image](https://user-images.githubusercontent.com/28574252/156837952-fa7119a3-c336-441d-95e9-9fef243ae4a6.png)

Resolved 2022-03-04:
![image](https://user-images.githubusercontent.com/28574252/156839168-daf852ea-4604-4ab8-a073-598a072d831c.png)

Synced 2022-03-04

**Comment by yroskov** [comment]
Doing cleaning of outdated decisions...
2024-02-07: 1,351 outdated decisions left in CoL, mainly in ReptileDB. The same subspecies is accepted name and synonym to its parent species.

**Comment by yroskov** [comment]
**ReptileDB ver 2023-09 / 2023-09-30**; dump received from Peter 2024-03-21, plus classification harvested from http://www.reptile-database.org/db-info/taxa.html; imported 2024-03-21

Tested on DEV https://github.com/CatalogueOfLife/testing/issues/134#issuecomment-2013245082

- [x] Imported: 12162 spp (vs 11690 Nov 2021)
- [x] Metadata: OK
- [ ] Classification: 
- Empty subfamilies in the family Alligatoridae; all children genera placed out of subfamilies 
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/015077a0-3f23-4604-94e3-88b191db632c)
- Genus Calabaria is out of subfamily Calabariinae
- Empty subfamily Elapinae; children genera placed out of subfamily 

- [ ] Sectors: 4 orders, ok
- [ ] Extinct taxa: n/a

Metrics

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/06b889fc-4dcc-45e9-9990-0ab437d90b9c)

ISSUES assessed 2024-03-22

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/13263484-edcf-489a-98db-f4332f143859)

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/deb2f26e-61ca-4ba6-912c-4217fd7a7a56)

**Comment by yroskov** [comment]
Have look on Ablepharus (Morethia) anomalus (Adelaidensis) Peters, 1874

**Comment by yroskov** [comment]
There are species names with very long authorstrings, for example: 
_Bothriechis khwargi_ **Arteaga, Pyron, Batista, Vieira, Pelayo, Smith, Barrio-Amorós, Koch, Agne, Valencia, Bustamante, Harris & Guayasamin, 2024** (https://zoobank.org/NomenclaturalActs/8BFF5643-306F-435A-B074-668B41C43291)
_Bothriechis rahimi_ **Arteaga, Pyron, Batista, Vieira, Pelayo, Smith, Barrio-Amorós, Koch, Agne, Valencia, Bustamante, Harris & Guayasamin, 2024**
etc.

**Comment by yroskov** [comment]
**ReptileDB ver 2024-02 / 2024-02-**; dump received from Peter 2024-03-30, plus classification harvested from http://www.reptile-database.org/db-info/taxa.html; imported 2024-04-01

- [x] Imported: 12162 spp (vs 12162 in previous iteration; 11690 in Nov 2021)
- [x] Metadata: version applied as "2024-03 / 2024-03-28" following this page http://www.reptile-database.org/db-info/news.html
- [ ] Classification: genera Lankascincus & Ristella are outside class Reptilia
- Empty subfamilies in the family Alligatoridae; all children genera placed out of subfamilies Alligatorinae & Caimaninae
- Genus Calabaria is out of subfamily Calabariinae
- Empty subfamily Elapinae; children genera placed out of subfamily 
- [x] Sectors: OK; 34 sectors: 4 suborders, 15 superfamilies & 15 families
- [x] Extinct taxa: n/a

Metrics

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/fce0f6e3-82f8-4b6b-8b3c-f4a546567ce6)

**Comment by yroskov** [comment]
**ReptileDB ver 2024-03 / 2024-03-28**; new iteration imported 2024-04-02

_Classification:_

- [x] Genera Lankascincus & Ristella are outside class Reptilia = FIXED
- [ ] Empty subfamilies in the family Alligatoridae; all children genera placed out of subfamilies Alligatorinae & Caimaninae = 
All genera are in Alligatorinae (incl. genus Caiman, by mistake) and Caimaninae is empty = IGNORE Alligatorinae and BLOCK Caimaninae
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/df24c893-af73-43ed-a520-58661e0a84ad)
- [x] Genus Calabaria is out of subfamily Calabariinae = FIXED
- [ ] Empty subfamily Elapinae; children genera placed out of subfamily = BLOCK empty Elapinae
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/bafc83f7-a404-4b5c-b0a8-179d020d73ae)

**Comment by yroskov** [comment]
- [x] Missing brackets in some subsequent combinations https://github.com/CatalogueOfLife/data/issues/667#event-13072129254 = FIXED 2024-06-07

**Comment by yroskov** [comment]
**ReptileDB ver 2024-03 / 2024-03-28**; new iteration imported 2024-06-07

- [x] Imported: 12162 spp (vs 12162 in previous iteration)
_Classification:_
- [x] Empty subfamilies in the family Alligatoridae; all children genera placed out of subfamilies Alligatorinae & Caimaninae = 
All genera are in Alligatorinae (incl. genus Caiman, by mistake) and Caimaninae is empty = **need to IGNORE Alligatorinae and BLOCK Caimaninae** = decision is in place 2024-06-07
- [x] Empty subfamily Elapinae; children genera placed out of subfamily = **need to BLOCK empty Elapinae** = decision is in place 2024-06-07
- [x] Sectors: OK

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/bf4bc190-319e-4d6f-b38e-d52ed789bc2e)

Resolved 2024-06-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/e4f31035-0957-49ce-8765-347045fe75df)

**Synced 2024-06-07**

**Comment by yroskov** [comment]
- [x] Incorrect names in six ReptileDB superfamilies: https://github.com/CatalogueOfLife/data/issues/976#issuecomment-2710609452 
2025-03-10: I have changed name statuses & rank for superfamilies ReptileDB _Dibamia, Diploglossa, Gekkota, Iguania, Platynota_ & _Scincomorpha_ as "provisionally accepted" & "unranked". **Re-synced**.

**Comment by gdower** [comment]
The ReptileDB 2025-09-21 update is imported.

**Comment by yroskov** [comment]
Cross-mapping ReptileDB vs ITIS classification

_Class Reptilia_

= **order Crocodilia** (3 fam 27 spp)
= **order Rhynchocephalia** (1 fam 1 sp)

**order Squamata** 

ReptileDB | ITIS
-- | --
12,108 spp | 10,151 spp
1 suborder | 5 suborders
14 "superfamilies" | no superfamilies
**attach families** | 
Anolidae (Anolis) | ~~Dactyloidae (Anolis)~~
Calabaria in Boidae | ~~Calabariidae (Calabaria)~~
Candoia in Boidae | ~~Candoiidae (Candoia)~~
in Boidae | ~~Charinidae~~
Eryx in Boidae | ~~Erycidae (Eryx)~~
in Boidae | ~~Sanziniidae~~

omitted families:

ReptileDB | ITIS
-- | --
Atractaspididae = add in infraorder Alethinophidiain | included in Lamprophiidae 
Cyclocoridae = add in infraorder Alethinophidia | in Colubridae
Micrelapidae = add in infraorder Alethinophidia | in Lamprophiidae 
Prosymnidae = add in infraorder Alethinophidia | in Lamprophiidae 
Psammodynastidae = add in infraorder Alethinophidia | in Lamprophiidae 
Psammophiidae = add in infraorder Alethinophidia | in Lamprophiidae 
Psammophiidae = add in infraorder Alethinophidia | in Lamprophiidae 
Pseudoxyrhophiidae = add in infraorder Alethinophidia | in Lamprophiidae 

~ **order Testudines** 
366 spp vs 371 spp
= suborder Cryptodira
Differences in suborder Pleurodira = **attach families**

**Comment by yroskov** [comment]
**ReptileDB ver 2025-09 / 2025-09-21**; imported 2024-10-24

- [x] Imported: 12502 spp (vs 12162 in previous iteration)
- [x] Classification: ITIS as a master classification. See cross-map above. _(family Boidae taken s.l. as in ReptileDB; 8 families taken s.str. as in ReptileDB - ITIS included them mainly in Lamprophiidae)_
- Empty subfamily Caimaninae (fam Alligatoridae); genus Caiman placed in Alligatorinae by mistake. = IGNORE Alligatorinae and BLOCK Caimaninae = decisions confirmed 2025-10-24 ; Empty subfamily Elapinae; children genera placed out of subfamily = BLOCK Elapinae = decision confirmed 2025-10-24
- [x] Sectors: 82 sectors after re-assembly in ITIS classification, 2025-10-27. 
- [x] Distribution: OK
- [x] Common names: OK

Metrics:

<img width="1587" height="4536" alt="Image" src="https://github.com/user-attachments/assets/e9517801-7d1b-4dff-8ab7-a02e02498411" />

ISSUES assessed 2025-10-24

<img width="1239" height="1717" alt="Image" src="https://github.com/user-attachments/assets/1f010be3-bac6-4fe1-bdc7-a862ec775a3e" />

TASKS 

<img width="1449" height="1063" alt="Image" src="https://github.com/user-attachments/assets/a36cbec6-a347-4080-93d5-06be475d9005" />

- Broken decisions, 2592 = deleted
- Outdated decisions, 30 = deleted

- [x] The problem with 1,810 subspecies: subspecies exists as an accepted taxon and a synonym to its parent species. https://www.checklistbank.org/catalogue/3/dataset/1008/duplicates?acceptedDifferent=true&authorshipDifferent=false&catalogueKey=3&category=trinomial&limit=900&minSize=2&mode=STRICT&offset=0&status=accepted&status=synonym = Synonyms BLOCKED, but 4 cases of amb syns = re-synced 2025-10-28

- [x] Species _Sphenomorphus veunsaiense_ is placed in subfamily Lygosominae, whereas other 115 spp of _Sphenomorphus_ are placed in subfamily Sphenomorphinae (in ReptileDB est!) = BLOCKED 

Resolved 2025-10-27:

<img width="1563" height="1047" alt="Image" src="https://github.com/user-attachments/assets/2e8a894a-d03c-4b3d-900e-63dd4971cf4f" />

**Synced 2025-10-27**

**Comment by yroskov** [comment]
PU is invited to check results 2025-10-27 in https://preview.catalogueoflife.org/data/dataset/1008

**Comment by yroskov** [comment]
- [x] ReptileDB in ITIS classification = IGNORE suborder Eusuchia & suborder Sphenodontida = re-synced 2025-10-27

**Comment by yroskov** [comment]
**ReptileDB ver 2026-02 / 2026-02-11**; imported 2026-02-17

- [x] Imported: 12568 spp (vs 12502)
- [x] Classification: ITIS as a master classification. See cross-map above. _(family Boidae taken s.l. as in ReptileDB; 8 families taken s.str. as in ReptileDB - ITIS included them mainly in Lamprophiidae)_
( Empty subfamily Caimaninae (fam Alligatoridae); genus Caiman placed in Alligatorinae by mistake. = IGNORE Alligatorinae and BLOCK Caimaninae = decisions confirmed 2025-10-24 ; Empty subfamily Elapinae; children genera placed out of subfamily = BLOCK Elapinae = decision confirmed 2025-10-24 )
- [x] Sectors: 82 sectors after re-assembly in ITIS classification, 2025-10-27. 
Broken: genus Buhoma in family Lamprophiidae (as in ITIS) = FIXED. ReptileDB: incertae sedis in superfamily Elapoidea = Elapoidea is absent in ITIS.
- [x] Distribution: OK
- [x] Common names: OK
- [x] Extinct flag: n/a

Import:

<img width="1815" height="5079" alt="Image" src="https://github.com/user-attachments/assets/3fd993d1-a6bf-48bc-80c7-149fe2f99f7d" />

ISSUES

<img width="1224" height="2257" alt="Image" src="https://github.com/user-attachments/assets/8b779bc2-8e2e-4479-b40b-b9b7ce1c888c" />

TASKS

<img width="1656" height="1203" alt="Image" src="https://github.com/user-attachments/assets/f8d66ef4-d024-41d3-9d37-591931af09c0" />

- Broken decisions, 85 = deleted
- Outdated decisions, 23 = deleted

Resolved 2026-02-17:

<img width="1664" height="1184" alt="Image" src="https://github.com/user-attachments/assets/3b9a6e22-c92c-4532-b899-45e09ad47c42" />

**Synced 2026-02-17**

**Comment by yroskov** [comment]
**ReptileDB ver 2026-06 / 2026-06-24**; imported 2026-06-26

- [x] Imported: 12650 spp (vs 12568)
- [x] Metadata: version is different with those on download page, because GO received another db dump of 2026-06-24 fopr CoL
- [x] Classification: ITIS as a master classification. See cross-map above. _(family Boidae taken s.l. as in ReptileDB; 8 families taken s.str. as in ReptileDB - ITIS included them mainly in Lamprophiidae)_
( Empty subfamily Caimaninae (fam Alligatoridae); genus Caiman placed in Alligatorinae by mistake. = IGNORE Alligatorinae and ~~BLOCK~~ IGNORE Caimaninae = decision changed 2026-06-26; Empty subfamily Elapinae; children genera placed out of subfamily = BLOCK Elapinae = decision confirmed 2026-06-26 )
- [x] Sectors: 82 sectors; no broken sectors reported https://www.checklistbank.org/project/3/sector?broken=true&limit=100&offset=0&subjectDatasetKey=1008 
Broken: genus Buhoma in family Lamprophiidae (as in ITIS) = FIXED. ReptileDB: incertae sedis in superfamily Elapoidea = Elapoidea is absent in ITIS.
- [x] Distribution: OK
- [x] Common names: OK
- [x] Extinct flag: n/a

Import:

<img width="1762" height="5563" alt="Image" src="https://github.com/user-attachments/assets/dc6aecf5-0a28-4236-afb2-37fd289938ce" />

ISSUES

<img width="1314" height="2561" alt="Image" src="https://github.com/user-attachments/assets/6eeaf3df-1015-4097-87fe-2300d033929a" />

TASKS

<img width="1794" height="1265" alt="Image" src="https://github.com/user-attachments/assets/4bdf5f01-5a50-41ec-92cf-74c443c3b821" />

- Broken decisions, 15 = deleted
- Outdated decisions, 1 = deleted

Resolved 2026-06-26:

<img width="1860" height="1293" alt="Image" src="https://github.com/user-attachments/assets/c378b418-3675-426c-9768-95c49eb23af7" />

**Synced 2026-06-26**
