### ISSUE TITLE
Brassicaceae: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#130]
New updated dataset is available: see https://github.com/CatalogueOfLife/data/issues/264

Imported on prod as "Update on the Brassicaceae Species Checklist" id 2305, no short name.
https://data.catalogueoflife.org/dataset/2305/about

**Comment by yroskov** [comment]
- [x] Imported 3925 spp (vs 3778 in ac19)

- [x] Sector: re-established

- [ ] Metadata: @chantalhuijbers https://data.catalogueoflife.org/dataset/2305/about

- [x] Classification: family - genera (no authorstrings) - species - infra

**Comment by yroskov** [comment]
- [ ] No parent-child relationships between species and subspecies/varieties. Subspecies dropped in NotAssigned species:

![image](https://user-images.githubusercontent.com/28574252/118875217-65b4c500-b8b1-11eb-9741-f9cfb08e29fd.png)

Examples: 
Acuston perenne subsp. obovatum (Boiss. & Kotschy) Mabb. & Al-Shehbaz

Aethionema saxatile subsp. athoum (Griseb.) Hayek and other 8 subspp.

Alyssum diffusum subsp. calabricum Španiel, Marhold, N.G.Passal. & Lihová + 2 ssp

Alyssum wulfenianum subsp. ovirense (A.Kern.) Magauer, Schönswetter & Frajman + 1 ssp

- [ ] Example of NotAssigned subspecies:
![image](https://user-images.githubusercontent.com/28574252/118875734-073c1680-b8b2-11eb-84ba-c882fd5b8877.png)

**Comment by yroskov** [comment]
- [ ] Type subspecies/variety incorrectly have authorstrings (autonyms should have no authorstrings according the Code):
_Example:_
Aethionema saxatile subsp. saxatile (L.) R.Br.
Alyssum diffusum subsp. diffusum Ten.

**Comment by yroskov** [comment]
- [ ] Names with hybrid formulas get "unranked" status and placed id NotAssigned nodes.

![image](https://user-images.githubusercontent.com/28574252/118876756-3bfc9d80-b8b3-11eb-9efa-0609563b9cdd.png)

**Comment by yroskov** [comment]
**ISSUES** assessed

- [x] Subspecies Assigned, 1. - Incorrectly parsed name Eutrema giganteum G.Q.Hao, Al-Shehbaz & J.Quan Liu, PhytoKeys 82: 21 (2017).    

&nbsp; | accepted | Eutrema giganteum liu | &nbsp; | Eutrema | giganteum | liu | &nbsp; | species
-- | -- | -- | -- | -- | -- | -- | -- | --
- FIXED via complex decision

- [x] Partially Parsable Name, 46 - Something wrong with parsing trinomials in synonyms. Blocked in CoL.

![image](https://user-images.githubusercontent.com/28574252/118879289-250b7a80-b8b6-11eb-9f64-c6d612a18109.png)

- [x] Indetermined, 52 - The same issue as above, but more names. Blocked in CoL.

- [ ] Parent Species Missing, 712 - should be related to NoAssigned trinomials reported above

**Comment by yroskov** [comment]
**TASKS** 

![image](https://user-images.githubusercontent.com/28574252/118879770-baa70a00-b8b6-11eb-9f97-445b1ad03e11.png)

Resolved 2021-05-19:

![image](https://user-images.githubusercontent.com/28574252/118880306-52a4f380-b8b7-11eb-87b1-cfa470bebfec.png)

**Comment by yroskov** [comment]
**Synced with reported problems and incomplete metadata 2021-05-19**

**Comment by mdoering** [comment]
> No parent-child relationships between species and subspecies/varieties. Subspecies dropped in NotAssigned species:

This causes unbearable troubles in the assembly it seems:
<img width="428" alt="Screenshot 2021-05-20 at 11 20 06" src="https://user-images.githubusercontent.com/327505/118953801-70c52f00-b95d-11eb-9c97-dbfb2c3864ea.png">

We need to make sure that the implicit species is not created but is reusing the sibling species!

**Comment by yroskov** [comment]
**Re-synced 2021-05-25** after blocking accepted trinomials in NotAssigned species.

**Comment by yroskov** [comment]
**Metadata patch** created 2021-06-29

alias: Brassicaceae
contributor:
 - 
  organisation: Agriculture and Agri-Food Canada
  country: CA
taxonomicScope: Mustard or cabbage family
geographicScope: global
confidence: 5
completeness: 100

**Comment by yroskov** [comment]
Comment from Alexey Seregin, MW, 2024-03-19

_In my opinion, there is now a very problematic area in the Catalog of Life for temperate floras - Brassicaceae. Of course, cruciferous vegetables are especially frustrating (many omissions). Below are two short lists of passes - forward them to the base owners. I don’t really know who to contact directly._

_It seems to me that the transfer of Brassicaceae and Geranium to either Gewaerts or Hassler (it doesn’t matter who - the state of nomenclature and synonymy is better there in any case) will be a big positive step in the development of the Catalogue of Life._

No hits (Brassicaceae):
Cardamine seidlitziana
Crambe tchalenkoae
Draba algida
Draba czuensis
Draba kodarica
Draba metaarctica
Draba tschuktschorum
Erysimum altaicum
Hesperis ciscaucasica
Hornungia angustilimbata
Lepidium affine
Lepidium lyratum
