### ISSUE TITLE
Strepsiptera Database (id 1103): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#143]
New version arrived on **2021-07-01** as an export from Aphia in WoRMS package. 

Imported in the checklistbank: https://data.catalogueoflife.org/dataset/1103/about 2021-07-01.

**Comment by yroskov** [comment]
**Metadata**

Need to be confirmed with Jeya:

- [ ] Short name appears as **WoRMS Strepsiptera** 
- [ ] WoRMS logo is applied 
- [ ] Description
- [ ] Contact (email address displayed)
- [ ] Kathirithamby, Jeyaraney as Editor
- [ ] Does applied ORCID correct: 0000-0001-9907-4779 https://orcid.org/0000-0001-9907-4779
- [ ] Contributor (organisation): University of Oxford, Department of Zoology, United Kingdom & Vlaams Instituut voor de ZeeBelgium
- [ ] Taxonomic scope (English name for the Top taxon): Strepsiptera

**Comment by yroskov** [comment]
**Imported** 625 spp vs 602 in ac19
gen 59. fam 17, superfam 4

**Comment by yroskov** [comment]
**Classification**

https://data.catalogueoflife.org/dataset/1103/classification?taxonKey=xG--incertae-sedis--SUPERFAMILY

- [ ] All superfamilies (4) are empty, all families are in NotAssigned superfamily
- [ ] Two families without children: Dioxoceridae & Hylechthridae

![image](https://user-images.githubusercontent.com/28574252/124175744-991f6d80-da73-11eb-9fd2-19638eb955a9.png)

**Comment by yroskov** [comment]
**ISSUES**

https://data.catalogueoflife.org/dataset/1103/issues

![image](https://user-images.githubusercontent.com/28574252/124176626-bef94200-da74-11eb-8a75-0febc99f5abf.png)

**Comment by yroskov** [comment]
**TASKS**

![image](https://user-images.githubusercontent.com/28574252/124176940-37f89980-da75-11eb-9a15-693cddf5a0bc.png)

- [ ] accepted species Xenos oxyodontes Nakase & Kato, 2013 appears twice in the checklist
- [ ] family Phthanoxenidae appears twice in the checklist: as accepted & provisionally accepted

**Comment by yroskov** [comment]
**Strepsiptera in the July 29/ac21**: credited as _WoRMS Strepsiptera_. However, spp stats reflects old checklist: 602/11
 
_Metadata as displayed:_
Short name
WoRMS Strepsiptera
Full name
World Strepsiptera Database
Version / Issued
ver. (07/2021) / 2021-07-01
DOI
10.48580/d4sb-3c3
Contact
Kathirithamby, Jeyaraney
Editor
Kathirithamby, Jeyaraney
Contributor
University of Oxford Department of ZoologyUnited Kingdom
Vlaams Instituut voor de ZeeBelgium
Taxonomic coverage
Animalia > Arthropoda > Insecta: Strepsiptera
Living species
602
Extinct species
11
Subgenus
2
Genus
47
Family
12
Order
1
Synonyms
231
Common names
0
Total number of names
908
Abstract
This global species list of "twisted-wing" parasitoids is part of the Aphia platform, an infrastructure designed to capture taxonomic and related data and information, including an online editing environment. It is the core platform that underpins the World Register of Marine Species (WoRMS) and all its related global, regional and thematic species databases, but it also allows the storage of non-marine data. World Register of Marine Species database, which aims to provide the most authoritative list of names of all marine species globally. Data have been contributed to the Catalogue of Life via the WoRMS, hosted by the Flanders Marine Institute (VLIZ).
Taxonomic scope
Strepsiptera
Geographic scope
Global
Temporal scope
1758-2021
License
cc by
Checklist Confidence

Completeness
Url (website)
https://strepsiptera.aphia.org
ISSN
-
GBIF key
-
Identifiers
-
Citation
Kathirithamby, J. (2021). World Strepsiptera Database. In O. Bánki, Y. Roskov, L. Vandepitte, R. E. DeWalt, D. Remsen, P. Schalk, T. Orrell, M. Keping, & J. Miller, Catalogue of Life Checklist (ver. (07/2021). https://doi.org/10.48580/d4sb-3c3
Source
-

**Comment by yroskov** [comment]
**Strepsiptera in the preview release 2021-08-24**: credited as _Strepsiptera Database_ with unchanged spp stats 602/11.

_Metadata as displayed:_
Short name
WoRMS Strepsiptera
Full name
World Strepsiptera Database
Version / Issued
ver. (07/2021) / 2021-07-01
DOI
10.48580/d4sb-3c3
Contact
Kathirithamby, Jeyaraney
Editor
Kathirithamby, Jeyaraney
Contributor
University of Oxford Department of ZoologyUnited Kingdom
Vlaams Instituut voor de ZeeBelgium
Taxonomic coverage
Animalia > Arthropoda > Insecta: Strepsiptera
Living species
602
Extinct species
11
Subgenus
2
Genus
47
Family
12
Order
1
Synonyms
231
Common names
0
Total number of names
908
Abstract
This global species list of "twisted-wing" parasitoids is part of the Aphia platform, an infrastructure designed to capture taxonomic and related data and information, including an online editing environment. It is the core platform that underpins the World Register of Marine Species (WoRMS) and all its related global, regional and thematic species databases, but it also allows the storage of non-marine data. World Register of Marine Species database, which aims to provide the most authoritative list of names of all marine species globally. Data have been contributed to the Catalogue of Life via the WoRMS, hosted by the Flanders Marine Institute (VLIZ).
Taxonomic scope
Strepsiptera
Geographic scope
Global
Temporal scope
1758-2021
License
cc by
Checklist Confidence
Completeness
Url (website)
https://strepsiptera.aphia.org
ISSN
GBIF key
Identifiers
Citation
Kathirithamby, J. (2021). World Strepsiptera Database. In O. Bánki, Y. Roskov, L. Vandepitte, R. E. DeWalt, D. Remsen, P. Schalk, T. Orrell, M. Keping, & J. Miller, Catalogue of Life Checklist (ver. (07/2021). https://doi.org/10.48580/d4sb-3c3
Source

**Comment by yroskov** [comment]
- [x] Sector order Strepsiptera re-assembled & synced 2021-08-24.

**Comment by yroskov** [comment]
**WoRMS Strepsiptera, ver. 2025-05-01** for AC25

ISSUES assessed 2025-05-22

![Image](https://github.com/user-attachments/assets/7e4aad65-443d-4b84-a076-423101a494bb)

TASKS

![Image](https://github.com/user-attachments/assets/8482c4b1-23e5-4353-86b2-a8861a4e947a)

- Broken decisions, 2 = deleted

Resolved 2025-05-22:

![Image](https://github.com/user-attachments/assets/ea41a59a-4a74-476e-ac38-0d2f31474219)

**Synced 2025-05-22**
