### ISSUE TITLE
The Scorpion Files (id1164): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#150]
A new version has been crawled and imported by @gdower in July 2021: ver. **Jul 2021 / 2021-07-27**

**Imported:** 2,594 spp (vs 2,526 in ac21)

**Metadata:** OK

**Classification:** OK

**Sector:** OK

**Comment by yroskov** [comment]
**ISSUES**: assessed & resolved 
![image](https://user-images.githubusercontent.com/28574252/130274965-2db8f324-9a20-4360-841d-e2acaac6fdf8.png)

**Comment by yroskov** [comment]
**TASKS**
![image](https://user-images.githubusercontent.com/28574252/130275011-f2997d10-26eb-4f84-b5c4-eb8b88e8e52a.png)

- [x] Broken decision: 1. Deleted.

**Comment by yroskov** [comment]
**The Scorpion Files of Apr 2023 / 2023-04-24**; crawled & imported by Geoff 2023-04-24

- [ ] Imported: 2,741 spp (vs 2,684 in May 22) (website says "Number of species in the world: 2754". Missing 13 spp)
- [x] Metadata: OK
- [ ] Classification: missing family Pseudochactidae (spelled as "Pseudo-chactidae" in the menu)
- [ ] Sector: OK

![image](https://user-images.githubusercontent.com/28574252/234110335-f3c1ed3e-a33b-4876-9e14-51d9c42ddc73.png)

ISSUES assessed 2023-04-24

![image](https://user-images.githubusercontent.com/28574252/234111931-7f060b3d-7dcf-4f03-9137-930202b1d07c.png)

**Comment by yroskov** [comment]
**The Scorpion Files of Apr 2024 / 2024-04-22**; crawled & imported by Geoff 2024-04-22

- [x] Imported:  2,821 spp (vs 2,766) (website says "Number of species in the world: 2820")
- [x] Metadata: OK 
- [x] Classification: OK (family Pseudochactidae (spelled as "Pseudo-chactidae" in the menu) = checked)
- [x] "Nomen nudum" names: OK, marked as prov acc (checked Brachistosternus castroi; Brachistosternus holmbergi; Thestylus  signatus; Babycurus brignolii)
- [x] Sector: OK

Metrics

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/91d95ab6-754e-4830-8da8-d5b702161bbc)

ISSUES assessed 2024-05-01

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/b884aeee-3356-41f1-8946-58e0643b28d1)

TASKS no new issues

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/50c6767c-1bca-42a5-8794-8c39a049b4ed)

- Broken decision, 1 = deleted

**Synced 2024-05-01**

**Comment by yroskov** [comment]
**The Scorpion Files of Apr 2025 / 2025-04-14**; crawled & imported by Geoff 2025-04-14

- [x] Imported: 2,888 spp (vs 2,821) (website says "Number of species in the world: 2872")
- [x] Metadata: OK 
- [x] Classification: OK 
- [x] "Nomen nudum" names: OK, 27 names pre-flagged as prov acc (checked Brachistosternus castroi; Brachistosternus holmbergi; Thestylus  signatus; Babycurus brignolii)
- [x] Sector: OK

Metrics

![Image](https://github.com/user-attachments/assets/e94217cb-2f83-4945-94a9-9f39e9d75371)

ISSUES assessed 2025-04-18

![Image](https://github.com/user-attachments/assets/7f122f16-d6f1-46bc-95ae-515d073c4ff4)

TASKS = no issues

![Image](https://github.com/user-attachments/assets/ad62ccfe-a106-4860-b28f-3ce9b1141755)

**Synced 2025-04-18**

**Comment by yroskov** [comment]
**The Scorpion Files of Jul 2026 / 2026-07-06**;  imported by Geoff 2026-06-07

- [x] Imported: 2,953 spp (vs 2,888) (website says "Number of species in the world: 2937")
- [x] Metadata: OK 
- [x] Classification: OK 
- [x] "Nomen nudum" names: no; there are no names pre-flagged as prov acc in this harvest; 13 acc species + 1 genus (Tibetiomachus Lourenço & Qi, 2006) & 3 subspecies have nom status Doubtful = flagged as Prov Acc via decisions
- [x] Sector: broken - missing subject = FIXED (order Scorpiones in class Archnida)

Import

<img width="1935" height="4590" alt="Image" src="https://github.com/user-attachments/assets/5a1af38a-ea16-4846-a7ad-a9e78e1f1473" />

ISSUES assessed 2026-07-07

<img width="1387" height="532" alt="Image" src="https://github.com/user-attachments/assets/35af45cf-6d90-46ee-87e2-186230a89656" />

TASKS = no issues

**Synced 2026-07-07**
