### ISSUE TITLE
CoL of April 2022

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#188]
- [x] ITIS of 2022-03-28; imported & **synced 2022-04-01**. New sectors: mite families Erythraeidae, Listropsoralgidae, Pachylaelapidae. Should be re-done: superfamily Erythraeoidea as a sector, instead of family Erythraeidae = FIXED, **synced**

- [x] WoRMS of 2022-04-01; automatic import is expected as: 2 Apr (import), 3 Apr (sync), 4 Apr (verify);

- [x] Scarabs of 2022-04-11; imported 2022-04-11; **synced 2022-04-18**

- [x] Pterophoroidea of 2022-04-03; **synced 2022-04-22**

- [x] StaphBase - request for a new version sent; data received 2021-10-21; converting in TW; final draft imported as id20001 2022-04-18; resolved; **synced 2022-04-22** 

- [x] WCVP (Markus); imported to the PROD 2021-12-03 (https://github.com/CatalogueOfLife/testing/issues/177). Hybrid genera outside families. 
2021-12-22: Sector Acorales - Acoraceae established for the purpose of accessibility of Workbench tool (available inside the Project only). 2022-01-13: Sector WCVP-Acoraceae deleted; WCSP-Acoraceae re-established, synced.
Metadata need to be checked with Rafael.
2022-02-02: cannot do assembly of families until this will be fixed: https://github.com/CatalogueOfLife/checklistbank/issues/998 = FIXED
updated view imported 2022-02-14;
sectors re-assembled 2022-03; synced 2022-03-30, 2022-04-05; 2022-04-20

- [x] Update **SF Aphia** metadata: Colin Favret, the University of Montreal, Department of Biological Sciences  

- [ ] Species Fungorum Plus - Paul>"For the last few weeks I have been updating Species Fungorum and resolving some internal inconsistencies / errors in preparation for another download for COL+, partly prompted by a request from the GNI for a new download. I may have to get back to you if I forget how to ‘format’ the data, but this may be in early January.
Reminded 2022-01-25.

- [ ] Collembola.org - Anton> "Frans is happy with our (your) activities and happy to share the checklist as long as he doesn't need to do extra work :) To my knowledge he is updating the checklist regularly (~once a month). If I'm correct, Geoff now have a crawling script and can mine the checklist again for the next CoL version. Or do you need anything from my side to make it happen?
Reminded 2022-01-25. Crawler received and data harvested 2022-04-20.

- [ ] Systema Dipterorum, v 3.6 of 2022-02-14 received;

- [ ] Gelechiidae (new, not adopted yet, https://data.catalogueoflife.org/dataset/2362/names) imported 2022-02-11 - for March

- [ ] WSC: https://github.com/CatalogueOfLife/data/issues/414#issuecomment-1092924636; Hi Yuri, I will provide a new export **around June 15** when we typically compile the WSC archive version. Thanks, Daniel

**Other 11 GSDs for updates:** https://docs.google.com/spreadsheets/d/1WRxfYQF8h2Xiu3gNUvQ3de-zRH-BSq3wYWIAbHHBrhY/edit?usp=sharing

**Comment by yroskov** [comment]
- [ ] Ari:  Non-Latin letters in scientific names and authorships [#409 ](https://github.com/CatalogueOfLife/data/issues/409)

**Comment by yroskov** [comment]
Preview release started 2022-03-31

**Comment by yroskov** [comment]
- [ ] Whole CoL: Quite a few overlaps between sectors in accepted [genera](https://www.checklistbank.org/catalogue/3/duplicates?category=uninomial&limit=50&minSize=2&mode=STRICT&offset=0&rank=genus&rankDifferent=false&status=accepted&withDecision=false) & [species](https://www.checklistbank.org/catalogue/3/duplicates?authorshipDifferent=false&category=binomial&limit=50&minSize=2&mode=STRICT&offset=0&status=accepted&withDecision=false)

**Comment by yroskov** [comment]
Metadata updated.

Preview release started 2022-04-22,

**Comment by yroskov** [comment]
**PREVIEW of 2022-04-22**, checked 2022-04-25 

- [ ] Only 1 WoRMS checklist changed its species stats: WoRMS Oligochaeta 3505 (Mar) vs 3504 (Apr). @gdower, quite possible WoRMS were not updated this month. 

- [ ] RBG Kew logo is missing with WCVP

**Comment by yroskov** [comment]
See https://github.com/CatalogueOfLife/testing/issues/145#issuecomment-1108941360 for WoRMS

**Comment by yroskov** [comment]
- [ ] Problems with some diacritics in WoRMS checklists: 2022-03-02 (equal to the source data) vs 2022-04-04 (some diacritics stripped off)
https://www.checklistbank.org/dataset/1157/diff?attempts=25..27

![image](https://user-images.githubusercontent.com/28574252/165178775-8d713fb9-fa39-4c7c-bbe8-14411c6819e6.png)

**Comment by yroskov** [comment]
Preview release of 2022-04-25 failed (server crashed).

Preview release launched 2022-04-26 (1:14 pm server time), finished 6:16 pm.

**Comment by yroskov** [comment]
Preview release of 2022-04-26 checked and submitted for deployment to the prod.

**Comment by yroskov** [comment]
Markus, 2022-04-27: please do not modify any data in the COL project today - there is sth seriously wrong with references. I have to modify the database directly to fix that and wont be able to finish this before your day tomorrow start
