### ISSUE TITLE
CoL of May 2022

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#191]
- [x] ITIS of 2022-04-26; imported 2022-05-04; 
new GSDs: families Trombiculidae [2745 spp.] & Leeuwenhoekiidae [282 spp.];
**synced 2022-05-05** 

- [x] WoRMS of 2022-05-01; imported 2022-05-04 (manually); **synced 2022-05-05**

- [x] Scarabs of 2022-05-02; imported 2022-05-04; **synced 2022-05-05**

- [x] Collembola.org - Anton> "Frans is happy with our (your) activities and happy to share the checklist as long as he doesn't need to do extra work :) To my knowledge he is updating the checklist regularly (~once a month). If I'm correct, Geoff now have a crawling script and can mine the checklist again for the next CoL version. Or do you need anything from my side to make it happen?
Reminded 2022-01-25. Crawler received and **data harvested 2022-04-20**.
GO: a new crawler (incl. distribution data). 
**synced 2022-05-12**

- [x] Systema Dipterorum, v 3.6 of 2022-02-14 received; **synced 2022-05-20**

- [ ] Pterophoroidea ?

- [ ] Species Fungorum Plus - Paul>"For the last few weeks I have been updating Species Fungorum and resolving some internal inconsistencies / errors in preparation for another download for COL+, partly prompted by a request from the GNI for a new download. I may have to get back to you if I forget how to ‘format’ the data, but this may be in early January.
Reminded 2022-01-25. Paul>I should be in a position to start preparing the download in the middle of May

- [ ] LepIndex "2022-04-39 / 2022-04-30" imported 2022-04-29; green light for assembly: DH eml of 2022-05-04

- [ ] Gelechiidae (new, not adopted yet, https://data.catalogueoflife.org/dataset/2362/names) imported 2022-02-11 - for March

- [ ] WSC: https://github.com/CatalogueOfLife/data/issues/414#issuecomment-1092924636; Hi Yuri, I will provide a new export **around June 15** when we typically compile the WSC archive version. Thanks, Daniel

**Other 11 GSDs for updates:** https://docs.google.com/spreadsheets/d/1WRxfYQF8h2Xiu3gNUvQ3de-zRH-BSq3wYWIAbHHBrhY/edit?usp=sharing

**Comment by yroskov** [comment]
- [ ] Extra space in names with hybrid mark in WPlants & WFerns only https://github.com/CatalogueOfLife/data/issues/431

**Comment by yroskov** [comment]
- [ ] diacritics in authorstrings of WoRMS names: https://github.com/CatalogueOfLife/data/issues/433

**Comment by yroskov** [comment]
- [x] Order Ranunculales, a sector of WPlants was synced 2022-05-11 (see https://github.com/CatalogueOfLife/data/issues/437)

**Comment by yroskov** [comment]
Preview release launched **2022-05-13**.

**CoL Preview of 2022-05-13**, tests of 2022-05-16. Stats = OK.

**Comment by yroskov** [comment]
- [x] Metadata updated

What's new in May 2022 edition?
70 checklists have been updated:
    Collembola.org
    ITIS (new checklists: families Trombiculidae & Leeuwenhoekiidae)
    Scarabs
    Systema Dipterorum
    WoRMS, 65 checklists

**Comment by yroskov** [comment]
Preview release launched 2022-05-.

**Comment by yroskov** [comment]
**CoL of 2022-05-20** deployed to PROD 2022-05-23.
