### ISSUE TITLE
Gelechiidae (id 2362): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#198]
_New GSD for June 2022 release_

- [x] **Metadata** in CLB (2022-05-27)

_Short Name:_ Gelechiidae
_Full Name:_ Catalogue of the Gelechiidae of the World
_Version / Issued:_ 1.1.22.126 (06 May 2022) / 2022-05-06 
_Abstract:_ This GSD is derived from the Gelechiidae list maintained by Klaus Sattler (NHM UK). The database has been edited for inclusion as a structured dataset in the Catalogue of Life by Donald Hobern.
_Creator:_ Hobern, Donald; Sattler, Klaus
_Editor:_ Hobern, Donald
~~_Taxonomic scope:_ Gelechiidae~~ English name of the taxon: Gelechiid moths (as in ITIS; = PATCHED); Twirler moths or gelechiid moths (as in Wikipedia)
_Geographic scope:_ global
_Temporal scope:_ All taxa described to present
_Checklist Confidence:_ 5
_Completeness:_ 99%

**Comment by yroskov** [comment]
- [x] Imported: 5,638 spp 
![image](https://user-images.githubusercontent.com/28574252/170720759-a8f64e77-0a16-448e-a4ca-78c844818e14.png)

**Comment by yroskov** [comment]
- [x] Classification: ranks-in-use [kingdom-phylum-class-order-superfamily]-family-subfamily-genus-tribe (in subfamily Gelechiinae only)-species

Set of genera (some with status ProvAcc) and species (all with status ProvAcc) are in the root of the family tree. Few genera in the root of tree are empty (no spp), for example, Cochlevalva, Distinxia, Empista 

![image](https://user-images.githubusercontent.com/28574252/170721049-372facc8-6e99-4d0f-9ced-04f40a80a024.png)

- [ ] Family, subfamilies & tribes have no authorstrings. 

- [x] Sector: established as family Gelechiidae 2022-05-26

**Comment by yroskov** [comment]
**ISSUES** assessed 2022-05-27
![image](https://user-images.githubusercontent.com/28574252/170723733-e96679b0-1e18-4687-8338-f7734c41d8cf.png)

- Unusual Name Characters, 3: two synonyms with genus name in single quotation marks, 'Gelechia' dammersi Keifer, 1936; 'Gelechia' eldorada Keifer, 1936

- Wrong Monomial Case, 5: @dhobern, names need attention (looks like the subgenus isn't recognized by CLB correctly):  Scrobipalpula (psilella) Povolný, 1964; Scrobipalpula (psilella) japonica Povolný, 2000; Scrobipalpula (psilella) seniorum Povolný, 2000	
https://www.checklistbank.org/catalogue/3/dataset/2362/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=wrong%20monomial%20case&limit=100&offset=0

**Comment by yroskov** [comment]
**TASKS**
![image](https://user-images.githubusercontent.com/28574252/170744280-a07f13ab-51ba-47e2-96b5-6540b8a6ac44.png)

Resolved 2022-05-27:
![image](https://user-images.githubusercontent.com/28574252/170755560-6ec9a30b-1bbe-4a39-8cb4-e856464ed38c.png)

**Comment by yroskov** [comment]
**Synced 2022-05-27**

**Comment by dhobern** [comment]
The 'Gelechia' in single quotes represented uncertainty in the genus at the time the species as described. I've simply removed these because that seems best to reflect the intention (and we are not asserting anything on classification from synonyms).

The (psilella) ones were apparently intended as representations of a species group (not a formal subgenus). I've fixed these by simply losing the (psilella) and fixing the rank to genus.

The Phalaena Tinea stuff is some cases I missed. Linnaeus placed all Lepidoptera in six massive genera (including Phalaena) and then subdivided these with (still massive) named groups like Tinea - the way to map this against Linnaean ranks is unclear and different platforms do it differently, but the ICZN made some decisions which effectively treat the subdivisions as the actual genera. I have removed the Phalaena part for these names and fixed the ranks back to species.

The question marks are for a case where the original description is unclear on the intended genus. I have fixed this by treating it as the same genus as the earlier basionym to which it is now synonymised.

The square brackets in authorship are the standard practice throughout lepidopterology for some of the messier 18th/19th century publications. I'd like to leave those in place.

**Comment by dhobern** [comment]
I've uploaded a new version of the Gelechiidae dataset that fixes the issues on its side:

- Removed quotation marks from around 'Gelechia'
- Removed Linnaeus' Phalaena from Phalaena Tinea
- Removed Povolný's psilella species group references
- Fixed various question marks
- Fixed five cases where the same name/taxon was repeated within the dataset

The square brackets in authorship are normal practice in Lepidoptera nomenclature to address issues with some really messy publications. These should be retained.

I have also made changes to LepIndex within TaxonWorks to move five species from other families into the Gelechiidae when the Gelechiidae dataset now includes these. 

These two sets of changes should resolve all the ACC-ACC_spp_sameAuth cases, but I have not yet reimported the TaxonWorks LepIndex into CLB. I'll look first at some of the other reported issues in that dataset.

**Comment by yroskov** [comment]
Thank you, @dhobern ! I can see that you have imported a new version:  **Gelechiidae, ver. 1.1.22.148 (28 May 2022)**. We can go ahead with it (data synced now).

- [x] Imported: 5,632 spp (vs 5,638 spp, 06 May 2022)
- [x] Sector: OK

**TASKS** 2022-05-31
![image](https://user-images.githubusercontent.com/28574252/171270829-5c3fe6d8-16bf-4ef7-9e28-8636e3d4b444.png)

- [x] Broken decisions: 3; = deleted all.

Resolved 2022-05-31
![image](https://user-images.githubusercontent.com/28574252/171271282-4c0fccb7-a317-4b38-b3d2-e0ab8796cf92.png)

**Synced 2022-05-31**

**Comment by yroskov** [comment]
Gelechiidae 1.1.22.293 (20 Oct 2022) / 2022-10-20; **synced 2022-10-20**

**Comment by yroskov** [comment]
New version ready. DH, 2022-11-28:
>The Gelechiidae are "just" distribution and hostplant records.

**Version 1.1.22.332 (28 Nov 2022) / 2022-11-28**
- [x] Imported: 5,789 spp (vs 5,778 spp of 08 Jun 2022)
- [x] Metadata: OK
- [x] Sector: OK

![image](https://user-images.githubusercontent.com/28574252/204897391-d7400331-05e8-4002-8271-79e961babc80.png)

**Comment by yroskov** [comment]
ISSUES

- [ ] Parent Name Mismatch, 1: species _Scrobipalpulopsis stirodes_ appears as a child of the genus _Scrobipalpula_. https://www.checklistbank.org/catalogue/3/dataset/2362/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=parent%20name%20mismatch&limit=100&offset=0)

- [ ] Character encoding problems in some references (rare, not in the reports). _Example:_ https://preview.catalogueoflife.org/data/taxon/92MLR
![image](https://user-images.githubusercontent.com/28574252/204901613-f8847afb-4216-4456-9a71-7c14de8080a5.png)



![image](https://user-images.githubusercontent.com/28574252/204901833-736bc546-9a49-4911-8d02-370bfec87b0e.png)

**Comment by yroskov** [comment]
TASKS

![image](https://user-images.githubusercontent.com/28574252/204903048-4189be84-2920-4fd2-aeda-14f4b7957a65.png)

- Broken decision, 1: deleted.
- Identical subgenus, 1: subgenus Kiwaia (Empista) Povolný, 1968 and Kiwaia (Empista) Philpott, 1930 are both present as accepted: https://www.checklistbank.org/catalogue/3/dataset/2362/duplicates?catalogueKey=3&category=uninomial&limit=500&minSize=2&mode=STRICT&offset=0&rank=subgenus&status=accepted&withDecision=false

Resolved 2022-11-30:
![image](https://user-images.githubusercontent.com/28574252/204905577-de35c737-3426-493d-a56c-88d1a825ddba.png)

**Synced 2022-11-30**

**Comment by dhobern** [comment]
Thanks - I've dealt with these and re-uploaded the data.

**Comment by yroskov** [comment]
New version ready.
@dhobern, 2022-04-07: The Gelechiidae have been updated with six species I missed from 2020.

**Version 1.1.23.97 (07 Apr 2023)**; imported 2023-04-07

- [x] Imported: 5,808 spp (vs 5,789 spp in 1.1.22.332 (28 Nov 2022))
- [x] Metadata: OK
- [x] Sector: OK
- [x] Classification: OK
Empty genera (4 genera outside subfamilies): Anoecisis Walsingham, 1904; Distinxia Povolný, 1967; Empista Povolný, 1968; Gelechiodeorum Kusnetzov, 1941. 

![image](https://user-images.githubusercontent.com/28574252/230962398-89221784-3597-4c96-8ba0-b204135ed49c.png)

ISSUES assessed 2023-04-10

![image](https://user-images.githubusercontent.com/28574252/230963911-2f9f8417-000b-4e06-b3c9-dccc56cf11f1.png)

TASKS

![image](https://user-images.githubusercontent.com/28574252/230964037-6832527a-f020-4ab4-9780-b492c80ea1d5.png)

**Synced 2023-04-10**

**Comment by yroskov** [comment]
**Version 1.1.23.140 (20 May 2023)**; imported 2023-05-20

@dhobern, 2023-05-19: Seven new species in the Gelechiidae dataset and I've cleaned up the remaining red issues.

- [x] Imported: 5,816 spp (vs 5,809 spp in 1.1.23.111)
- [x] Metadata: OK
- [x] Sector: OK
- [x] Classification: OK

TASKS (no actions needed)

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/d780189c-0976-4170-a467-4f70b5c67014)

- Broken decisions, 2: deleted

Synced 2023-05-22

**Comment by yroskov** [comment]
**Version 1.1.23.152 (01 Jun 2023) / 2023-04-27**; imported 2023-06-01

@dhobern, 2023-05-19: Seven new species in the Gelechiidae dataset and I've cleaned up the remaining red issues.

- [x] Imported: 5,823 spp (vs 5,816 spp )
- [ ] Metadata: incorrect release date as "2023-04-27" (version of 01 Jun 2023 imported 2023-06-01)
- [x] Sector: OK
- [x] Classification: OK

TASKS = no actions

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/142f3158-14a6-407b-a96b-4fffb4c42fb1)

Not synced (awaiting correction in metadata)

**Comment by yroskov** [comment]
Re-synced 2023-06-02

**Comment by yroskov** [comment]
**Gelechiidae 1.1.23.196 (15 Jul 2023) / 2023-07-15**; imported 2023-07-15

- [x] Imported: 5,826 spp (vs 5,823 spp )
- [x] Metadata: OK
- [x] Classification: OK (selected genera & all spp in the Tree root already have "prov." status)
- [x] Sector: broken

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/c07f6457-cbb1-462d-a680-723463c1ff88)

ISSUES assessed 2023-07-17

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/fe4a02c9-721a-4365-9be2-789a8fecd4da)

TASKS = no actions

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/0494ce2b-900a-456b-b326-9d341d71ca4f)

**Synced 2023-07-17**

**Comment by yroskov** [comment]
**Gelechiidae 1.1.23.216 (04 Aug 2023) / 2023-08-04**; imported 2023-08-04

- [x] Imported: 5,827 spp (vs 5,826 spp )
- [x] Metadata: OK
- [x] Classification: OK (selected genera & all spp in the Tree root already have "prov." status)
- [x] Sector: OK

TASKS no issues

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/5755c1f4-0463-4d27-a7f0-2be08741ec7a)

**Synced 2023-08-11**

**Comment by yroskov** [comment]
**Gelechiidae ver 1.1.23.244 (01 Sep 2023) / 2023-09-01**; imported 2023-09-01

- [x] Imported: 5,828 spp (vs 5,827 spp )
- [x] Metadata: OK
- [x] Classification: OK (as above)
- [x] Sector: OK

TASKS = no issues

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/14e923ce-b50c-447d-bc78-53b30f9ab221)

**Synced 2023-09-06**

**Comment by yroskov** [comment]
**Gelechiidae ver 1.1.23.244 (01 Sep 2023) / 2023-09-01**; imported 2023-10-12

- [x] Imported: 5,844 spp (vs 5,828 spp )
- [x] Metadata: OK
- [x] Classification: OK (as above)
- [ ] Sector: OK

TASKS = no issues

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/be67eda8-203e-4dcd-80ef-32e6cc798645)

**Synced 2023-10-13**

**Comment by yroskov** [comment]
**Gelechiidae ver 1.1.23.315 (11 Nov 2023) / 2023-11-11**; imported 2023-11-11

- [x] Imported: 5847 spp (vs 5844 spp )
- [x] Metadata: OK
- [x] Classification: OK (as above)
- [x] Sector: OK

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/3a1c5730-f674-4de9-9e52-47edd9768bc7)

TASKS = no issues

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/59722771-2b85-43a5-a379-cc95b79ecb18)

**Synced 2023-11-13**

**Comment by yroskov** [comment]
**Gelechiidae ver 1.1.24.23 (23 Jan 2024) / 2024-01-23**; imported 2024-01-23

- [x] Imported: 5845 spp (vs 5847 spp )
- [x] Metadata: OK
- [x] Classification: OK (as above)
- [x] Sector: OK

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/d1dd6893-1dab-460e-8e8b-6c1ee0866e28)

ISSUES assessed 2024-02-02

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/c2cec6fe-9a89-45c3-abff-7b77afc08921)

- Infrageneric Field Misplaced, 2: two subgenera in the same genus, different styles of presentation (one as mononomial, another as combination):
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/0dfde8b7-c4c9-454e-8f09-79e88e3ebf63)

TASKS no issues

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/879ce23c-18a1-48de-b316-ec8c38fd3ef8)

**Synced 2024-02-02**

**Comment by dhobern** [comment]
@yroskov Updated with four more species

**Comment by yroskov** [comment]
**Gelechiidae ver 1.1.24.53 (22 Feb 2024) / 2024-02-22**; imported 2024-02-22

- [x] Imported: 5849 spp (vs 5845 spp) 

**Synced 2024-02-22**

**Comment by yroskov** [comment]
**Gelechiidae ver 1.1.24.73 (13 Mar 2024) / 2024-03-13**; imported 2024-03-13

- [x] Imported: 5849 spp (vs 5849 spp )
- [x] Metadata: OK
- [x] Classification: OK (as above)
- [x] Sector: OK

Metrics:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/7495c8d7-f319-4f69-9740-279b8ea4ab51)

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/431b9540-0392-4a0a-be47-320c75d17b28)

**Synced 2024-03-18**

**Comment by yroskov** [comment]
**Gelechiidae ver 1.1.24.104 (13 Apr 2024) / 2024-04-13**; imported 2024-04-13

- [x] Imported: 5850 spp (vs 5849 spp )
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK
- [x] Extinct flag: n/a
- [ ] No DOI

Metrics:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/3aada430-384e-4929-83c3-2321611f2f6d)

ISSUES assessed 2024-04-18

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/f8d9e8ac-a3f9-4891-b2cd-92c89ce53e2f)

TASKS no issues

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/3d64ba44-d7e0-4c65-9f8f-c97e948a0920)

**Synced 2024-04-18**

**Comment by yroskov** [comment]
**Gelechiidae ver 1.1.24.130 (09 May 2024) / 2024-05-09**; imported 2024-05-09

- [x] Imported: 5854 spp (vs 5850 spp )
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK
- [x] Extinct flag: n/a
- [ ] No DOI

Metrics:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/9a0f7495-9aa1-43ce-9990-123eafb8738a)

ISSUES assessed 2024-05-14

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/354b544b-7fa2-47c4-b723-f8e06ec9a9a2)

TASKS = no new issues

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/59cae26f-6a20-4221-9ae5-39a020f1f325)

**Synced 2024-05-14**

**Comment by yroskov** [comment]
OK, thanks! I will re-sync Gelechiidae for May edition as soon as I get green light to resume my work from Markus

**Comment by yroskov** [comment]
**Gelechiidae ver 1.1.24.136 (15 May 2024) / 2024-05-15**; imported 2024-05-15

- [x] Imported: 5937 spp (vs 5854 spp )
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK
- [x] Extinct flag: n/a
- [ ] No DOI

TASKS = no changes

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/b8091cdb-d258-4d06-bb9f-8a1ea4d83e77)

**Comment by dhobern** [comment]
The most recent shows as no changes because I accidentally imported it twice tonight. The previous import shows the change.

**Comment by yroskov** [comment]
It's only "no changes" in Tasks (not Diff tool), i.e. no new unresolved duplicated names. New sync will be done anyway.

**Comment by dhobern** [comment]
@yroskov 10 new species

**Comment by yroskov** [comment]
**Gelechiidae ver     1.1.24.227 (14 Aug 2024) / 2024-08-14**; imported 2024-08-14

- [x] Imported: 5947 spp (vs 5937 spp )
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK
- [x] Extinct flag: n/a
- [ ] No DOI

Metrics:

![image](https://github.com/user-attachments/assets/91b6e08f-b73d-4afe-9601-0bb78e84c51f)

ISSUES assessed 2024-08-19

![image](https://github.com/user-attachments/assets/aff38560-32cf-4dfd-be98-5336ac16ced7)

- [ ] Parent Name Mismatch, [5](https://www.checklistbank.org/catalogue/3/dataset/2362/workbench?issue=parent%20name%20mismatch&limit=100): five species with binomial combinations in genus **Thiotricha** are placed under **Polyhymno** genus in the classification. - for attention of @dhobern 
https://www.checklistbank.org/dataset/2362/classification?taxonKey=8615
= For now, I ~~flagged~~ tried to flag all 5 as "provisionally accepted" 
Bug (@thomasstjerne or @mdoering) - decisions are not displayed in the interface (or not applies?):
![image](https://github.com/user-attachments/assets/eed2bf8d-600e-4d5f-b8b1-b33e5b0fd290)

@dhobern, you might be also interested to look through the reports _Unlikely Year_, [19](https://www.checklistbank.org/dataset/2362/names?issue=unlikely%20year) - a letter present in the year; _Related Name Missing_, [1688](https://www.checklistbank.org/dataset/2362/names?issue=related%20name%20missing) 

TASKS = no new issues

![image](https://github.com/user-attachments/assets/f1895c21-3e3b-4786-a4ba-49e203d0f4e2)

**Synced 2024-08-19**

**Comment by dhobern** [comment]
@yroskov New combinations and synonymy

**Comment by yroskov** [comment]
**Gelechiidae ver 1.1.24.260 (16 Sep 2024) / 2024-09-16**; imported 2024-09-16

- [x] Imported: 5943 spp (vs 5937 spp )
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK
- [x] Extinct flag: n/a
- [ ] No DOI

Metrics:

![image](https://github.com/user-attachments/assets/6202a5bc-f9a6-4fe7-ba1b-9123c775ba4f)

ISSUES assessed 2024-09-18

![image](https://github.com/user-attachments/assets/069ad66b-feeb-409e-a726-fad3d1d840ca)

- [ ] Infrageneric Field Misplaced [2](https://www.checklistbank.org/dataset/2362/names?issue=infrageneric%20field%20misplaced) - _@dhobern, there two different presentations of subgenus here.  I think, CLB expected subgenus shown as uninomial in CLB. i.e. Mimomeris Povolný, 1978 (corrected via complex decision in CoL)

TASKS = no new issues

![image](https://github.com/user-attachments/assets/2b2573b7-4cd2-41ba-838e-bad056a05e42)

**Synced 2024-09-18**

**Comment by yroskov** [comment]
**Gelechiidae ver. 1.1.24.291 (17 Oct 2024) / 2024-10-17**; imported 2024-10-17

- [x] Imported: 5944 spp (vs 5943 spp )
- [x] Metadata: OK; Field _Citation_: **Hobern, D., & Sattler, K.** (2024). Catalogue of World Gelechiidae **(D. Hobern & S. Lee, Eds.**; 1.1.24.291 (17 Oct 2024)).
- [x] Classification: OK. Subfamilies have no authorstrings. There are 3 empty genera out of subfamilies: Anoecisis Walsingham, 1904; Cochlevalva M.M. Omelko, 1986; Gelechiodeorum Kusnetzov, 1941
- [x] Sector: OK
- [x] Extinct flag: n/a
- [ ] No DOI

Metrics:

![image](https://github.com/user-attachments/assets/9f15c5f0-e3c5-4f1b-89e0-c4c815559b6e)

TASKS = no new issues

![image](https://github.com/user-attachments/assets/1966a8fb-86ef-4379-8bf7-1adcea9710b8)

**Synced 2024-10-22**

**Comment by yroskov** [comment]
@dhobern, I am forwarding this comment from Stephen to you: 

Stephen Garnett, wrote 2024-11-18:

>>Gelechidae links to no website but this one seems to be the list [gelechiidae.github.io/species/](https://urldefense.com/v3/__https:/gelechiidae.github.io/species/*/__;Iw!!DZ3fjg!8yS59-z9TzFgpGTldrG-2qwz4C67weNYK-P4iZiLgDt6Y1kIRvfeHeWBNlhZio6nC8jKh6I_C1ZSD2SAffJNZfJvqGD7ezyB$)

If you would like to include the link in Gelechiidae metadata, please, do.

**Comment by dhobern** [comment]
Really interesting - I'll follow up with Sangmi and Richard to see what their plans are. This is not directly connected to the Gelechiidae dataset (which is now newer than theirs in at least some respects). It looks like it is hosted in TW, which is excellent. More soon.

**Comment by dhobern** [comment]
Four new species - The other TW site will use data from this GSD, but is not yet a source.

**Comment by yroskov** [comment]
**Gelechiidae ver. 1.1.24.366 (31 Dec 2024) / 2024-12-31**; imported 2024-12-31

- [x] Imported: 5948 spp (vs 5944 spp )
- [x] Metadata: OK
- [x] Classification: OK. Subfamilies have no authorstrings. There are 3 empty genera out of subfamilies: Anoecisis Walsingham, 1904; Cochlevalva M.M. Omelko, 1986; Gelechiodeorum Kusnetzov, 1941
- [x] Sector: OK
- [x] Extinct flag: n/a
- [ ] No DOI

Metrics:

![image](https://github.com/user-attachments/assets/6adc5855-7077-402c-aa72-09439b87d86d)

ISSUES assessed 2025-01-15

![image](https://github.com/user-attachments/assets/ee1243b7-c1ec-4981-9c21-b7712127a93d)

TASKS = no new issues

![image](https://github.com/user-attachments/assets/53b584a6-393b-42db-a8b7-c0e455e04016)

**Synced 2025-01-15**

**Comment by dhobern** [comment]
@yroskov Significant reworking to reflect changes in family classification

**Comment by yroskov** [comment]
**Gelechiidae ver. 1.1.25.025 / 2025-01-25**; imported 2025-01-25

- [x] Imported: 5996 spp (vs 5948 spp )
- [x] Metadata: OK
- [x] Classification: OK. Subfamilies have no authorstrings. There are empty genera: e.g. Anoecisis Walsingham, 1904; Cochlevalva M.M. Omelko, 1986; Coloptilia Fletcher, 1940; Gelechiodeorum Kusnetzov, 1941
- [x] Sector: OK
- [x] Extinct flag: n/a
- [ ] URL to the species page: NO
- [ ] No DOI

Metrics:

![Image](https://github.com/user-attachments/assets/b49a5fe5-e9f4-43d6-90b3-fd59f91fe627)

ISSUES assessed 2025-02-13

![Image](https://github.com/user-attachments/assets/e5387f93-b3d6-4248-9b3a-043fe3b6c045)

TASKS

![Image](https://github.com/user-attachments/assets/a048f3f3-727f-4033-8eca-e7379f77c5ed)

@dhobern, for your attention:

- [ ] There are 3 pairs of accepted species with slightly different authorstrings **M. Omelko & N. Omelko, 2020** vs **Omelko & Omelko, 2020**: Photodotis crockeri, Photodotis decolorata & Photodotis imperfecta 
https://www.checklistbank.org/dataset/2362/duplicates?authorshipDifferent=true&category=binomial&limit=100&minSize=2&mode=STRICT&offset=0&status=accepted

_For the CoL of Feb 2025, I have blocked species with **Omelko & Omelko, 2020**_

Resolved 2025-02-13:

![Image](https://github.com/user-attachments/assets/b1933bdc-49ba-4a37-8642-8f1548d80cb5)

**Synced 2025-02-13**

**Comment by dhobern** [comment]
New species from two new papers @yroskov

**Comment by dhobern** [comment]
New synonym@yroskov

**Comment by yroskov** [comment]
**Gelechiidae ver. 1.1.25.114 / 2025-04-24**; imported 2025-04-24

- [x] Imported: 6002 spp (vs 5996 spp )
- [x] Metadata: OK
- [x] Classification: OK (see above). 
- [x] Sector: OK
- [x] Extinct flag: n/a
- [ ] URL to the species page: NO
- [ ] No DOI

Metrics:

![Image](https://github.com/user-attachments/assets/f270d7ed-eaf7-4c5e-b481-3b432da62461)

ISSUES assessed 2025-05-02

_@dhobern, for your attention:_ 
- [ ] Parent Name Mismatch, [1](https://www.checklistbank.org/catalogue/3/dataset/2362/workbench?issue=parent%20name%20mismatch&limit=100): species Coloptilia conchylidella in the genus Catatinagma  = 2025-05-02 _prov acc_ in CoL 

![Image](https://github.com/user-attachments/assets/695211da-8dd8-4252-9177-44cc9821f497)

TASKS = no new issues

- Broken decisions, 1 = deleted

**Synced 2025-05-02**

**Comment by dhobern** [comment]
Thanks - sorted that out @yroskov

**Comment by yroskov** [comment]
**Gelechiidae ver. 1.1.25.123 / 2025-05-03**; imported 2025-05-03

- [x] Imported: 6002 spp (vs 6002 spp )
- [x] Metadata: OK
- [x] Classification: OK (see above). 
- [x] Sector: OK
- [x] Extinct flag: n/a
- [ ] URL to the species page: NO
- [ ] No DOI

Metrics:

![Image](https://github.com/user-attachments/assets/1d6b53ec-f830-4e14-b4c8-041612c282e5)

ISSUES assessed 2025-06-02

![Image](https://github.com/user-attachments/assets/dad0630f-29e8-4597-bbbc-34fb14f03ee7)

TASKS = no new issues

![Image](https://github.com/user-attachments/assets/e840e9bd-a6d0-4e64-8fde-9c293b5f3cee)

**Synced 2025-06-02**

**Comment by dhobern** [comment]
@yroskov New species added

**Comment by yroskov** [comment]
**Gelechiidae ver. 1.1.25.229 / 2025-08-17**; imported 2025-08-17

- [x] Imported: 6004 spp (vs 6002 spp )
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK
- [x] Extinct flag: n/a
- [ ] URL to the species page: NO
- [ ] No DOI

Metrics:

<img width="1485" height="3776" alt="Image" src="https://github.com/user-attachments/assets/58c071a1-0b98-4de7-9f15-2ff2af8a2940" />

ISSUES assessed 2025-09-03

<img width="918" height="947" alt="Image" src="https://github.com/user-attachments/assets/55651e5d-bb8e-4855-9387-4c29f24abe2f" />

_@dhobern, for your attention:_ 
- No Species Included, [4](https://www.checklistbank.org/catalogue/3/dataset/2362/workbench?issue=no%20species%20included&limit=100): 
Anoecisis Walsingham, 1904 = no action
Cochlevalva M.M. Omelko, 1986 = also subgenus Parachronistis (Cochlevalva) M.M. Omelko, 1986 = BLOCKED as accepted genus
Gelechiodeorum Kusnetzov, 1941 = no action
Kiwaia (Kiwaia) Philpott, 1930 = no action

TASKS = no new issues

**Synced 2025-09-03**

**Comment by dhobern** [comment]
@yroskov New species

**Comment by yroskov** [comment]
**Gelechiidae ver. 1.1.25.254 / 2025-09-11**; imported 2025-09-11

- [x] Imported: 6005 spp (vs 6004 spp)

**Re-synced for CoL of Sep 2025-09-11**

**Comment by dhobern** [comment]
@yroskov Three new species

**Comment by yroskov** [comment]
**Gelechiidae ver.  1.1.25.285 / 2025-10-12**; imported 2025-10-12

- [x] Imported: 6008 spp (vs 6004 spp )
- [x] Metadata: OK
- [x] Classification: OK
- [x] Sector: OK
- [x] Extinct flag: n/a
- [ ] URL to the species page: NO
- [ ] No DOI

Metrics:

<img width="1581" height="4519" alt="Image" src="https://github.com/user-attachments/assets/6ff6e0bc-61c9-41a7-af07-b3a2cfb274f7" />

ISSUES assessed 2025-10-22

<img width="1275" height="1060" alt="Image" src="https://github.com/user-attachments/assets/0a436b5e-b95f-4309-8c12-ffffc19f8d4e" />

- No Species Included, [4](https://www.checklistbank.org/catalogue/3/dataset/2362/workbench?issue=no%20species%20included&limit=100) = BLOCKED = **Request failed with status code 400**

TASKS = no new issues

<img width="1444" height="1047" alt="Image" src="https://github.com/user-attachments/assets/2f2cd35a-baed-4828-b18d-f8bd055f4447" />

**Synced 2025-10-22**

**Comment by dhobern** [comment]
@yroskov New genus and two new species.

**Comment by yroskov** [comment]
**Gelechiidae ver. 1.1.25.304 / 2025-10-31**; imported 2025-10-31

- [x] Imported: 6010 spp (vs 6008 spp )

TASKS = no new issues

**Synced 2025-10-31**

**Comment by dhobern** [comment]
@yroskov New species

**Comment by yroskov** [comment]
**Gelechiidae ver. 1.1.25.327 / 2025-11-23**; imported 2025-11-23

- [x] Imported: 6011 spp (vs 6010 spp )

TASKS = no new issues

**Synced 2025-11-24**

**Comment by dhobern** [comment]
@yroskov Three new species

**Comment by yroskov** [comment]
**Gelechiidae ver. 1.1.25.352 / 2025-12-18**; imported 2025-12-18

- [x] Imported: 6014 spp (vs 6011 spp )

TASKS = no new issues

**Synced 2025-12-18**

**Comment by dhobern** [comment]
One new species

**Comment by yroskov** [comment]
**Gelechiidae ver. 1.1.26.046 / 2026-02-15**; imported 2026-02-14 (server date)

- [x] Imported: 6015 spp (vs 6014 spp )

Import:

<img width="1781" height="5086" alt="Image" src="https://github.com/user-attachments/assets/fa5e132d-1b63-4b9f-b430-545fd13829b8" />

TASKS = no new issues

**Synced 2026-03-09**

**Comment by dhobern** [comment]
New species added @yroskov

**Comment by yroskov** [comment]
**Gelechiidae ver. 1.1.26.101 / 2026-04-11**; imported 2026-04-11 

- [x] Imported: 6018 spp (vs 6015 spp )

TASKS = no new issues

- Broken decisions, 4 = deleted
- Outdated decisions, 4 = deleted

**Synced 2026-04-13**

**Comment by dhobern** [comment]
Another paper - five new species, more synonyms, some distributions and type material records

**Comment by yroskov** [comment]
**Gelechiidae ver. 1.1.26.111 / 2026-04-21**; imported 2026-04-21 

- [x] Imported: 6020 spp (vs 6018 spp )

Import:

<img width="1884" height="5082" alt="Image" src="https://github.com/user-attachments/assets/8e1ca2c4-4edf-4f06-8ef0-8dfd4deabd04" />

TASKS = no new issues

<img width="1803" height="1184" alt="Image" src="https://github.com/user-attachments/assets/3a9d2080-df5b-4d48-8cba-3bd5311ca0b0" />

**Synced 2026-04-24**

**Comment by dhobern** [comment]
@yroskov 17 new species

**Comment by dhobern** [comment]
@yroskov - Two more species

Also - please update this dataset, Alucitoidea and Pterophoroidea in the next release because the distribution data should now be more interoperable.

**Comment by yroskov** [comment]
Thank you! Alucitoidea, Gelechiidae & Pterophoroidea are scheduled now for June edition

**Comment by yroskov** [comment]
**Gelechiidae ver. 1.1.26.141 / 2026-05-21**; imported 2026-05-21 

- [x] Imported: 6039 spp (vs 6020 spp)
- [x] Metadata: OK
- [x] Sector: OK

Import:

<img width="1861" height="5559" alt="Image" src="https://github.com/user-attachments/assets/bcede251-5cdb-48ad-acfd-c53cb87c99b0" />

TASKS = no new issues

<img width="1863" height="1293" alt="Image" src="https://github.com/user-attachments/assets/b8627d23-cf10-4b94-bb25-406f37c7d36f" />

**Synced 2026-06-04**

**Comment by dhobern** [comment]
@yroskov New genus, species and combination.

**Comment by yroskov** [comment]
**Gelechiidae ver. 1.1.26.198 / 2026-07-17**; imported 2026-07-17

- [x] Imported: 6040 spp (vs 6039 spp)
- [x] Metadata: OK
- [x] Sector: OK

TASKS = no new issues

**Synced 2026-07-28**
