### ISSUE TITLE
UCD, Aphelinidae on DEV: tests

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#205]
Family Aphelinidae exported from TW in CoLDP and uploaded on DEV 2022-08-03:

Family Aphelinidae of approx. 1,100 spp

**Comment by yroskov** [comment]
**Tests of data ver. 2022-08-03** 

- [ ] Imported: 326 spp (looks as too low figure)
![image](https://user-images.githubusercontent.com/28574252/185639250-a3af9088-b715-4e24-9fb8-4d1a3bf112fb.png)

**Comment by yroskov** [comment]
data of 2022-08-03

- [ ] Classification
![image](https://user-images.githubusercontent.com/28574252/185640651-15b4c3e9-6af9-4e04-80fa-dae724f2db0d.png)

**Comment by yroskov** [comment]
- [ ] Classification

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/591676e3-13d5-4300-ad0a-a4680113acfa)

**Superfamily Chalcidoidea** Latreille, 1817 = 27706 spp (_vs 19835 spp in UCD of Sep 2007_), (5 subgen), 2274 gen, (1 subtribe), 40 tribes , 81 subfam, 28 fam
https://www.checklistbank.org/dataset/124661/taxon/92634

**Superfamily Mymarommatoidea** Debauche, 1948 = 36 spp (_taxon name is not present in UCD of Sep 2007_), 6 gen, 2 fam
https://www.checklistbank.org/dataset/124661/taxon/92929

**Superfamily Serphitoidea** Brues, 1937 = 15 spp (_vs 11 spp in UCD of Sep 2007_), 5 gen, 2 fam
https://www.checklistbank.org/dataset/124661/taxon/93061

**Comment by yroskov** [comment]
Classification (continue), **superfamily Chalcidoidea**  
https://www.checklistbank.org/dataset/124661/classification?taxonKey=92634

- [ ] 28 families, and **26 (of 81) subfamilies are outside families** (in the root of superfamily Chalcidoidea)
- [ ] **10 (of 40) tribes are outside families** (in the root of superfamily Chalcidoidea)
- [ ] **32 genera are outside families** (in the root of superfamily Chalcidoidea)

**Comment by yroskov** [comment]
Classification (continue), **superfamily Chalcidoidea**
https://www.checklistbank.org/dataset/124661/classification?taxonKey=92634

- [ ] Few empty tribes. _Examples:_ Heydenini Hedqvist, 1961
- [ ] Few empty genera. _Examples:_ Ablerus Howard, 1894; Systasis Walker, 1834; Pegoscapus Cameron, 1906; Ceratosolen Mayr, 1885;

**Comment by yroskov** [comment]
- [ ] Duplicated genera (one empty, another entry with children spp)
_Examples:_ one Ablerus Howard, 1894 is empty, another Ablerus Howard, 1894 has children; one Systasis Walker, 1834 is empty, another Systasis Walker, 1834 has children; Pegoscapus Cameron, 1906; Ceratosolen Mayr, 1885; Tetrapus Mayr, 1885

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/5f843531-6394-49d8-bfc7-f2e05f545e16)

**Comment by yroskov** [comment]
- [ ] Few species outside genus
_Examples:_ Celesterion reticulatum Hansson, 2020 & Solenotus fletcheri Cockerell, 1889 (in fam Eulophidae); †Butiokeras costae Burks & Heraty, 2020
https://www.checklistbank.org/dataset/124661/classification?taxonKey=92774

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/86d628b5-4d8e-478d-9b63-00f2190634aa)

**Comment by yroskov** [comment]
- [ ] Doubtful Name, 2: Charitopus |near| andalusicus Mercet; Diplolepis varians |var| Spinola
https://www.checklistbank.org/dataset/124661/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=doubtful%20name&limit=50&offset=0

**Comment by yroskov** [comment]
- [ ] Unparsable Authorship, 6
https://www.checklistbank.org/dataset/124661/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=unparsable%20authorship&limit=50&offset=0

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/b28804ba-c961-49e5-94cf-5ab2b2ebe285)

**Comment by yroskov** [comment]
- [ ] Subspecies Assigned, 7 - I am not sure that all of these names have a rank of "subspecies". More look like two-words epithets as names were published originally.
https://www.checklistbank.org/dataset/124661/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=subspecies%20assigned&limit=50&offset=0

**Comment by yroskov** [comment]
- [ ] Uppercase Epithet, 14: Examples: Achrysocharoides a; Entedon e; Anaphes (Patasson) [species not specified] euryale (Debauche, 1948); Anisopteromalus [species not specified] brasiliensis (Domenichini, 1951) = need to be blocked in CoL

https://www.checklistbank.org/dataset/124661/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=uppercase%20epithet&limit=50&offset=0

**Comment by yroskov** [comment]
- [ ] Multi Word Epithet, 21: _Examples_ see above, plus: Cynips n. 27; Ichneumon 2 maculatus Fabricius, 1793
https://www.checklistbank.org/dataset/124661/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=multi%20word%20epithet&limit=50&offset=0

**Comment by yroskov** [comment]
- [ ] Parsed Name Differs, 92. _Examples_, see above, plus: Chrysocharis sp.; Chrysocharoideus sp.; Cynips 1; Cynips 12; Entedon e; Entedon f; Achrysocharis formosus [sic] (Silvestri, 1914)  - synonyms
https://www.checklistbank.org/dataset/124661/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=parsed%20name%20differs&limit=50&offset=0

**Comment by yroskov** [comment]
**TASKS**

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/6591994d-3200-40a9-91c7-e13e5ee7702f)

**Comment by yroskov** [comment]
_@gdower, we need to investigate these reports on duplicates:_ 

- [ ] [ACC-ACC species (same authors) 0 of 872](https://www.checklistbank.org/catalogue/3/dataset/124661/duplicates?_colCheck=c2): 872 identical species - _OTUs or something different caused it?_
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/c29d27f7-efee-4463-9fad-98de5e7c0cda)

- [ ] [ACC-SYN species (different accepted, same authors) 0 of 79](https://www.checklistbank.org/catalogue/3/dataset/124661/duplicates?_colCheck=c6): very strange report - _the same name repeted 2-, 3-, 4- times_ 
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/7d7eeddf-ae06-4909-92ca-5afb0778ff68)

- [ ] [Identical genus 0 of 107](https://www.checklistbank.org/catalogue/3/dataset/124661/duplicates?_colCheck=b4) - _Strange: identical genera with the same position in the classification, but with different IDs_

_...and also:_

- [ ] [ACC-SYN species (same accepted, same authors) 0 of 1089](https://www.checklistbank.org/catalogue/3/dataset/124661/duplicates?_colCheck=c7) - _easy resolvable in CLB. Double check: does TW-CLB script translate it correctly? (such report typical for some other GSDs)_

- [ ] [SYN-SYN species (different accepted, same authors) 0 of 2473](https://www.checklistbank.org/catalogue/3/dataset/124661/duplicates?_colCheck=c12) - _**not easy resolvable in CLB**. Double check: does TW-CLB script translate it correctly?_

- [ ] [SYN-SYN species (same accepted, same authors) 0 of 111](https://www.checklistbank.org/catalogue/3/dataset/124661/duplicates?_colCheck=c14) - _easy resolvable in CLB. Double check: does TW-CLB script translate it correctly?

**Comment by yroskov** [comment]
- [ ] Set of subfamilies outside family: https://preview.catalogueoflife.org/?taxonKey=C93CN--incertae-sedis--FAMILY
_@gdower, any ideas, what could be causing this?_

**Comment by yroskov** [comment]
**2nd proof of 2024-05-07**:

John:

Sorry but there are still many errors in how the ‘unassigned’ subfamilies and tribes are being pulled (and many of the incertae sedis taxa I pointed out before.

John

Some of these are not pulling correctly - the following are all valid families:
Azotidae
Ceidae
Cerocephalidae
Chalcedectidae
Chrysolampidae (Chrysolampinae, Philomidinae)
Coelocybidae
Diparidae
Eurytomidae (Eurytominae, Heimbrinae, Rileyinae)
Herbertiidae
Macromesidae
Metapelmatidae
Micradelidae
Neanastatidae
Neodiparidae
     Not assigned subfamilies
- the following are all valid families:
Hetreulophidae
Heydeniidae (why listed twice?)
Idioporidae
Lycisidae
Mellanosomellidae
Moranilidae
Ooderidae
     Not assigned tribes

YR: _Azotidae, Ceidae, Cerocephalidae, etc. are flagged as “bare names” in CLB, and are not included in CoL. Why, if John says they are valid families? (These families rejected by the CLB produce “not assigned” subfamilies & tribes)._

**Comment by yroskov** [comment]
PROOF 3

**UCD Draft ver. 0.41.0 / 2024-05-08**; imported 2024-05-08

- [x] Imported: 31282 spp (vs 30447 in proof 2)
- [ ] Metadata:  no metadata yet
- [x] Classification: 3 superfamilies (22 families, 21 genera & spp outside superfamilies - not going in CoL)
Superfamily Chalcidoidea Latreille, 1817 = 28880 (28072) spp
Superfamily Mymarommatoidea Debauche, 1948 = 36 spp (36 spp)
Superfamily Serphitoidea Brues, 1937 = 15 spp (15 spp)
**plus extra taxa now added as sisters to 3 superfamilies**: infraorder Proctotrupomorpha, superfamily Apoidea - not going in CoL
- [x] Sectors: OK
- [ ] flag "extinct":  OK  (201 spp); seems **not all taxa above species have extinct flag**, for example, Gallorommatidae https://www.checklistbank.org/dataset/124661/classification?taxonKey=93975   
- [x] Names with square brackets: [species not specified], 13 synonyms = **blocked** = CONFIRMED; only one ~~"bare name"~~ [GENUS NOT SPECIFIED] pygmaeacannae.  = now it's not a bare name, BLOCKED
- [x] Names with [sic] portion: no in the import 

Metrics

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/b3867a07-742b-49de-accd-ed116a917526)

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/3f6dd0ca-68ed-47fc-88d5-6e2d11a88d35)

- Broken decisions, 0

**Comment by yroskov** [comment]
**Missing families in UCD@CoL** 


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/yroskov/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/yroskov/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


UCD   master (web) - Chalcidoidea -   https://ucd.chalcid.org/#/taxonomicTree?rootTaxonID=455458&rootTaxonName=Chalcidoidea | 2nd proof 2024-05-07 | 3rd proof 2024-05-08
-- | -- | --
Agaonidae | Agaonidae Walker, 1846 | Agaonidae Walker, 1846
Aphelinidae | Aphelinidae Thomson, 1876 | Aphelinidae Thomson, 1876
Asaphesinae |   |  
Aspidopleura |   |  
Austrosystasinae |   |  
Azotidae |   | Azotidae Nikol'skaya & Yasnosh, 1966
Boucekiidae | Boucekiidae Gibson, 2003 | Boucekiidae Gibson, 2003
Calesidae | Calesidae Mercet, 1929 | Calesidae Mercet, 1929
Callimomoinae |   |  
Ceidae |   | Ceidae Bouček, 1961
Cerocephalidae |   | Cerocephalidae Gahan, 1946
Chalcedectidae |   | Chalcedectidae Ashmead, 1904
Chalcididae | Chalcididae Latreille, 1817 | Chalcididae Latreille, 1817
Chrysolampidae |   | Chrysolampidae Dalla Torre, 1898
Cleonymidae | Cleonymidae Walker, 1837 | Cleonymidae Walker, 1837
Coelocybidae |   | Coelocybidae Bouček, 1988
Cynipencyrtidae |   | Cynipencyrtidae Trjapitzin, 1973
Diparidae |   | Diparidae Thomson, 1876
Ditropinotellinae |   |  
Diversinitidae | †Diversinitidae Haas, Burks & Krogmann, 2018 | †Diversinitidae Haas, Burks & Krogmann, 2018
Elachertoidea |   |  
Encyrtidae | Encyrtidae Walker, 1837 | Encyrtidae Walker, 1837
Enoggerinae |   |  
Eopelma |   |  
Epichrysomallidae | Epichrysomallidae Hill & Riek, 1967 | Epichrysomallidae Hill & Riek, 1967
Eubeckerella |   |  
Eucharitidae | Eucharitidae Walker, 1846 | Eucharitidae Walker, 1846
Eulophidae | Eulophidae Westwood, 1829 | Eulophidae Westwood, 1829
Eunotidae | Eunotidae Ashmead, 1904 | Eunotidae Ashmead, 1904
Eupelmidae | Eupelmidae Walker, 1833 | Eupelmidae Walker, 1833
Eurytomidae |   | Eurytomidae Walker, 1832
Eutrichosomatidae | Eutrichosomatidae Peck, 1951 | Eutrichosomatidae Peck, 1951
Glyphotoma |   |  
Herbertiidae |   | Herbertiidae Bouček, 1988
Hetreulophidae |   | Hetreulophidae Girault, 1915
Heydeniidae |   | Heydeniidae Hedqvist, 1961 & Heydenidae Hedqvist, 1961
Idioporidae |   | Idioporidae LaSalle, Polaszek & Noyes, 1997
Jambiya |   |  
Keryinae |   |  
Leptoomidae | †Leptoomidae Gibson, 2023 | †Leptoomidae Gibson, 2023
Leucospidae | Leucospidae Walker, 1834 | Leucospidae Walker, 1834
Lithobelyta |   |  
Lyciscidae |   | Lyciscidae Bouček, 1958
Macromesidae |   | Macromesidae Graham, 1959
Megastigmidae | Megastigmidae Thomson, 1876 | Megastigmidae Thomson, 1876
Melanosomellidae |   | Melanosomellidae Girault, 1913
Metapelmatidae |   | Metapelmatidae Bouček, 1988
Micradelinae |   |  
Moranilidae |   | Moranilidae Bouček, 1988
Mymaridae | Mymaridae Haliday, 1833 | Mymaridae Haliday, 1833
Neanastatidae |   | Neanastatidae Kalina, 1984
Neapterolelapinae |   | Neodiparidae Bouček, 1961
Neodiparidae |   |  
Ooderidae |   | Ooderidae Bouček, 1958
Ormyridae | Ormyridae Förster, 1856 | Ormyridae Förster, 1856
Parasaphodinae |   | Pelecinellidae Ashmead, 1899
Pelecinellidae | Pelecinellidae Ashmead, 1899 | Perilampidae Förster, 1856
Perilampidae | Perilampidae Förster, 1856 |  
Pirenidae | Pirenidae Haliday, 1844 | Pirenidae Haliday, 1844
Promerisus | Protoitidae Ulmer &   Krogmann, 2023
Protoitidae |   | Protoitidae Ulmer & Krogmann, 2023
Pteromalidae | Pteromalidae Dalman, 1820 | Pteromalidae Dalman, 1820
Pyramidophoriella |   |  
Rivasia |   |  
Rotoitidae | Rotoitidae Bouček & Noyes, 1987 | Rotoitidae Bouček & Noyes, 1987
Selimnus |   |  
Sennia |   |  
Signiphoridae | Signiphoridae Howard, 1894 | Signiphoridae Howard, 1894
Spalangiidae | Spalangiidae Haliday, 1833 | Spalangiidae Haliday, 1833
Storeyinae |   |  
Sympotomus |   |  
Systasidae |   | Systasidae Bouček, 1988
Tanaostigmatidae | Tanaostigmatidae Ashmead, 1904 | Tanaostigmatidae Ashmead, 1904
Tetracampidae | Tetracampidae Förster, 1856 | Tetracampidae Förster, 1856
Torymidae | Torymidae Walker, 1833 | Torymidae Walker, 1833
Trichogrammatidae | Trichogrammatidae Haliday, 1851 | Trichogrammatidae Haliday, 1851
Tripteromalus |   |  
  |   |  
  | 46 families missing | 24 families missing



</body>

</html>

**Comment by yroskov** [comment]
- [x] Metadata: filed by YR 2024-05-08 from the website https://ucd.chalcid.org. Need an approval. Remove "Draft" from the ShortName

Logo?

**Comment by yroskov** [comment]
- [ ] Heyden**ii**dae Hedqvist, 1961 & Heydenidae Hedqvist, 1961

**Comment by yroskov** [comment]
2024-05-10:
>Looks fantastic!!! Thanks for working with us. As for a logo… I will work on this with Jim next week :-)
I am okay for a go. All the best, John

**Comment by yroskov** [comment]
- [x] https://github.com/CatalogueOfLife/data/issues/660 = fixed via Workbench & re-synced 2024-06-03
_Attention!_ TASKS tool does not allow to identify these issues properly and fix them. Requires a lot of time.  
**It might be a barrier for frequent updates**

**Comment by yroskov** [comment]
**UCD of Apr 2025 / ~~2025-04-02, 2025-04-18~~ 2025-04-21**; imported 2025-04-16, re-imported 2025-04-18, re-imported 2025-04-22

- [x] Imported: 30035 spp (vs 31282 spp) = **-1247** - ?; ver. 2025-04-22 30631 spp = **-651** GO: _data problem that needs to be fixed inside TW_
- [x] Metadata: OK
- [ ] Classification: 3 superfamilies (22 families, 21 genera & spp outside superfamilies - not going in CoL)
plus extra taxa now added as sisters to 3 superfamilies: infraorder Proctotrupomorpha, superfamily Apoidea - not going in CoL
- 11 subfamilies outside families (not assigned) 
![Image](https://github.com/user-attachments/assets/8fb01528-ad0c-4301-a450-08cc83f5f19e)

- [x] Sectors: OK 
- [x] flag "extinct":  No = FIXED (203 spp, 39 gen, 3 fam)
- [x] Names with square brackets: [species not specified] (10 synonyms); [GENUS NOT SPECIFIED] pygmaeacannae.  = bare name 
- [x] Names with _[sic]_ portion: no in the import 
- [x] Names with _sp._ portion (25) = blocked 
- [ ] Links to species pages at https://ucd.chalcid.org: NO
- [ ] DOI: 

Metrics

![Image](https://github.com/user-attachments/assets/aa02da6e-4ebb-4892-aee6-ab462694e657)

![Image](https://github.com/user-attachments/assets/f2d7b912-7c6a-44e3-aee2-204adb9f7e99)

ISSUES assessed 2024-04-18; re-assessed 2024-04-22

![Image](https://github.com/user-attachments/assets/fa9f7200-54fd-4062-8ad3-5b3b9c1e7ee2)

- [x] Rank Name Suffix Conflict, [444](https://www.checklistbank.org/catalogue/3/dataset/124661/workbench?issue=rank%20name%20suffix%20conflict&limit=100) = only 3 accepted (not a genus) = IGNORED 2025-04-18

TASKS

![Image](https://github.com/user-attachments/assets/334ebf3b-af96-4a0c-9e18-e3d3f8f9f807)

- Broken decisions, 924 = deleted
- Outdated decisions, 2 = no action

- Issue [SYN-SYN species (different accepted, same authors), 8 of 105](https://www.checklistbank.org/catalogue/3/dataset/124661/duplicates?_colCheck=c12) should be resolved automatically after resolution of ACC-ACC species (same authors)

Resolved 2025-04-18:

![Image](https://github.com/user-attachments/assets/35daf76a-d2e1-4ee1-aca9-81de777f53fa)

TASKS 2025-04-22

![Image](https://github.com/user-attachments/assets/db04cbb5-ae5b-48ea-a041-2fa1bccf23d7)

- Manuscript names, 0
- Broken decisions, 0
- Outdated decisions, 1 = no action

Resolved 2025-04-22:

![Image](https://github.com/user-attachments/assets/0b948446-502a-492f-922b-cbe0c39d271f)

Synced 2025-04-18, **re-synced 2025-04-22**
