### ISSUE TITLE
CoL of January 2023

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#216]
- [x] WoRMS of 2023-01-01; imported 2023-01-02; **synced 2023-01-03**

- [x] ITIS of 2022-12-21; imported 2023-01-03; unable to resolve all Tasks https://github.com/CatalogueOfLife/backend/issues/1182#issuecomment-1371403830; **synced 2023-01-05**

- [x] Scarabs of 2023-01-03; imported 2023-01-03; **synced 2023-01-03**

- [x] 3i Auchenorrhyncha; imported 2023-01-04; synced 2023-01-05; **re-synced 2023-01-06**

- [x] SF Isoptera; imported 2023-01-04; **synced 2023-01-06**

- [x] WCO (Opiliones) - checked with Adriano; imported 2023-01-04; **synced 2023-01-06** Waiting for the list of authors (metadata) confirmation from Adriano 

- [ ] Eumycetoza.com of Jan 2023; imported 2023-01-12; **synced 2023-01-12**

- [x] WOL by John Abbott, 0.29.6 / 2022-12-08 https://www.checklistbank.org/dataset/125101/imports. To be adopted by TG. https://github.com/CatalogueOfLife/testing/issues/215
Donald, 2023-01-12 >This is to confirm that the only aspect the TG thought still needed addressing for John Abbott's Odonata dataset was to check that he was happy with the metadata. If this has been done, please proceed and add the dataset to replace the Jan van Tol checklist.
**Synced 2023-01-12**

- [ ] Species Fungorum Plus - Paul>"For the last few weeks I have been updating Species Fungorum and resolving some internal inconsistencies / errors in preparation for another download for COL+, partly prompted by a request from the GNI for a new download. I may have to get back to you if I forget how to ‘format’ the data, but this may be in early January.
2022-01-25 >I should be in a position to start preparing the download in the middle of May
2022-06-23 >If I do not complete the task by this time next week (last day of June; just over 500 left) I will just ‘hide’ the names from access via the web site and internally tag them as not yet fully looked for.
2022-10-26 >I have recently set a deadline for completion of all the new stuff by the end of the month and then November will be dedicated to resolving a few inconsistencies in Species Fungorum and initiating the download.
2022-12-22: >The problem this year is that every mycological taxonomist on the planet was playing ‘catch-up’ due to two years of restrictions caused by COVID. This has resulted in typically five email every day with one or more updates and missing names, some of which (over 300) are still in my ‘Pending-IF’ mail folder … and over 4500 new names and new type designations published in 2022. So, it’s clear the download will be in 2023.

**Other 11 GSDs for updates:** https://docs.google.com/spreadsheets/d/1WRxfYQF8h2Xiu3gNUvQ3de-zRH-BSq3wYWIAbHHBrhY/edit?usp=sharing

**Comment by yroskov** [comment]
- [ ] Family Polemoniaceae (World Plants) problem: https://github.com/CatalogueOfLife/data/issues/497

**Comment by yroskov** [comment]
PREVIEW started 2023-01-06 (server time 10:24 pm)

**Comment by yroskov** [comment]
- [ ] **nomen.eumycetozoa.com**: bug in synonymy. Export files need to be re-converted & re-imported in CLB https://github.com/CatalogueOfLife/data/issues/500

**Comment by yroskov** [comment]
PREVIEW started 2023-01-11 (server time 7:04 pm)

**Comment by yroskov** [comment]
PREVIEW started 2023-01-12 (server time 10:04 pm)

**Comment by yroskov** [comment]
**COL23.1, 2023-01-12, id 9859** is ready for deployment as January edition - for attention of @olafbanki & @mdoering

**Comment by olafbanki** [comment]
Published today online: https://www.catalogueoflife.org/data/metadata
