### ISSUE TITLE
Towards 2023 Annual Checklist

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#217]
Delivery date: June 2023

@olafbanki, Ed, @dhobern, you are very welcome to add milestones & targets for 2023 Annual Checklist (i.e. "must-to-do" GSDs, changes in the classification, etc.)

**Comment by yroskov** [comment]
TASKS 2023-05-01

![image](https://user-images.githubusercontent.com/28574252/235510882-a532b8c1-29e0-4f57-b0fb-46eeef1932bc.png)

**Comment by yroskov** [comment]
ACC-ACC sp, same auth


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/yroskov/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/yroskov/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



scientificName | Status | Authorship | Rank | Classification
-- | -- | -- | -- | --
Alekhosara reticulata | accepted | Aristov, 2008 | species | 1.   Grylloblattina>
2.   Megakhosaridae>
3.   Alekhosara
 
Alekhosara reticulata | accepted | Aristov, 2008 | species | 1.   Locustavidae>
2.   Locustavinae>
3.   Alekhosara
 
Clonia (Clonia) zernyi | accepted | Kaltenbach, 1971 | species | 1.   Saginae>
2.   Clonia>
3.   Clonia (Clonia)
 
Clonia (Clonia) zernyi | accepted | Kaltenbach, 1971 | species | 1.   Saginae>
2.   Clonia>
3.   Clonia (Clonia)
 
Dermomurex kilikiensis | accepted | Landau, Harzhauser,   İslamoğlu & Silva, 2013 | species | 1.   Muricidae>
2.   Aspellinae>
3.   Dermomurex
 
Dermomurex kilikiensis | accepted | Landau, Harzhauser,   İslamoğlu & Silva, 2013 | species | 1.   Muricidae>
2.   Aspellinae>
3.   Dermomurex
 
intermedia | accepted |   | species | 1.   Platycopida>
2.   Kloedenellidae>
3.   Kloedenella
 
intermedia | accepted |   | species | 1.   Beyrichioidea>
2.   Beyrichiidae>
3.   Beyrichia
 
koslowi | accepted |   | species | 1.   Planariidae>
2.   Polycelis>
3.   Polycelis
 
koslowi | accepted |   | species | 1.   Planariidae>
2.   Polycelis>
3.   Polycelidia
 
Lipsothrix jiri | accepted | Podenas, 2020 | species | 1.   Limoniidae>
2.   Limoniinae>
3.   Lipsothrix
 
Lipsothrix jiri | accepted | Podenas, 2020 | species | 1.   Liomoniidae>
2.   Eriopterinae>
3.   Lipsothrix
 
Necrocarcinus rathbunae | accepted | Roberts, 1962 | species | 1.   Necrocarcinoidea>
2.   Necrocarcinidae>
3.   Necrocarcinus
 
Necrocarcinus rathbunae | accepted | Roberts, 1962 | species | 1.   Dorippoidea>
2.   Necrocarcinidae>
3.   Necrocarcinus
 
Ovipoculum album | accepted | Zhu L. Yang & R.   Kirschner | species | 1.   Agaricomycetes>
2.   Auriculariales>
3.   Ovipoculum
 
Ovipoculum album | accepted | Zhu L. Yang & R.   Kirschner | species | 1.   Peronosporales>
2.   Pythiaceae>
3.   Ovipoculum
 
Palaeomesorthopteron pullus | accepted | Aristov, Grauvogel-Stamm   & Marchal-Papier, 2011 | species | 1.   Alexarasniidae>
2.   Nestorembiinae>
3.   Palaeomesorthopteron
 
Palaeomesorthopteron pullus | accepted | Aristov, Grauvogel-Stamm   & Marchal-Papier, 2011 | species | 1.   Grylloblattina>
2.   Mesorthopteridae>
3.   Palaeomesorthopteron
 
Paranecrocarcinus libanoticus | accepted | Förster, 1968 | species | 1.   Necrocarcinoidea>
2.   Paranecrocarcinidae>
3.   Paranecrocarcinus
 
Paranecrocarcinus libanoticus | accepted | Förster, 1968 | species | 1.   Dorippoidea>
2.   Necrocarcinidae>
3.   Paranecrocarcinus
 
Propontocypris dromas | accepted | Aiello, Barra &   Bonaduce, 2000 | species | 1.   Pontocypridoidea>
2.   Pontocyprididae>
3.   Propontocypris
 
Propontocypris dromas | accepted | Aiello, Barra &   Bonaduce, 2000 | species | 1.   Pontocypridoidea>
2.   Pontocyprididae>
3.   Propontocypris
 
Protonecrocarcinus ovalis | accepted | (Stenzel, 1945) | species | 1.   Necrocarcinoidea>
2.   Paranecrocarcinidae>
3.   Protonecrocarcinus
 
Protonecrocarcinus ovalis | accepted | (Stenzel, 1945) | species | 1.   Dorippoidea>
2.   Necrocarcinidae>
3.   Protonecrocarcinus
 
Pseudonecrocarcinus gamma | accepted | (Roberts, 1962) | species | 1.   Necrocarcinoidea>
2.   Paranecrocarcinidae>
3.   Pseudonecrocarcinus
 
Pseudonecrocarcinus gamma | accepted | (Roberts, 1962) | species | 1.   Dorippoidea>
2.   Necrocarcinidae>
3.   Pseudonecrocarcinus
 
Pseudonecrocarcinus quadriscissus | accepted | (Noetling, 1881) | species | 1.   Necrocarcinoidea>
2.   Paranecrocarcinidae>
3.   Pseudonecrocarcinus
 
Pseudonecrocarcinus quadriscissus | accepted | (Noetling, 1881) | species | 1.   Dorippoidea>
2.   Necrocarcinidae>
3.   Pseudonecrocarcinus
 
Shirakiacris yunkweiensis | accepted | (Chang, 1937) | species | 1.   Eyprepocnemidinae>
2.   Eyprepocnemidini>
3.   Shirakiacris
 
Shirakiacris yunkweiensis | accepted | (Chang, 1937) | species | 1.   Eyprepocnemidinae>
2.   Eyprepocnemidini>
3.   Shirakiacris
 
Steinernema australe | accepted | Edgington, Buddie, Tymo,   Hunt, Nguyen, France, Merino & Moore, 2009 | species | 1.   Strongyloidoidea>
2.   Steinernematidae>
3.   Steinernema
 
Steinernema australe | accepted | Edgington, Buddie, Tymo,   Hunt, Nguyen, France, Merino & Moore, 2009 | species | 1.   Strongyloidoidea>
2.   Steinernematidae>
3.   Steinernema
 



</body>

</html>
scientificName	Status	Authorship	Rank	Classification
Alekhosara reticulata	accepted	Aristov, 2008	species	[1. Grylloblattina>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=05fdb86b-29c7-4357-a0e4-9212072ce9a5)
				[2. Megakhosaridae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=e6f7f59f-d822-4b9f-ba2b-8116c01661e1)
				[3. Alekhosara](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=73b692f2-58e9-48f2-b380-f458307f2495)
				
Alekhosara reticulata	accepted	Aristov, 2008	species	[1. Locustavidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=5b2dfc89-e7fa-4a86-88b6-9f9b282ac003)
				[2. Locustavinae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=efcc11dc-8710-474d-95da-21aa5b9f2775)
				[3. Alekhosara](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=fa03ee2e-8bd6-45f6-bd24-58e5266f3037)
				
Clonia (Clonia) zernyi	accepted	Kaltenbach, 1971	species	[1. Saginae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=d6088e2b-92aa-4216-9306-f340de6d7da9)
				[2. Clonia>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=e3a2f72f-437c-46ae-bbda-3dbc58f709f6)
				[3. Clonia (Clonia)](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=1801de25-7d1f-4095-b069-9d3efb5f8b6c)
				
Clonia (Clonia) zernyi	accepted	Kaltenbach, 1971	species	[1. Saginae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=d6088e2b-92aa-4216-9306-f340de6d7da9)
				[2. Clonia>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=e3a2f72f-437c-46ae-bbda-3dbc58f709f6)
				[3. Clonia (Clonia)](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=1801de25-7d1f-4095-b069-9d3efb5f8b6c)
				
Dermomurex kilikiensis	accepted	Landau, Harzhauser, İslamoğlu & Silva, 2013	species	[1. Muricidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=8f17c207-f575-4b54-9119-2fa15f95b3fe)
				[2. Aspellinae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=b8fd52e4-0786-4b5d-8706-0724cb832e2c)
				[3. Dermomurex](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=3fbeff1d-fb76-4bf3-a99a-bfcdfe3ccb0e)
				
Dermomurex kilikiensis	accepted	Landau, Harzhauser, İslamoğlu & Silva, 2013	species	[1. Muricidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=8f17c207-f575-4b54-9119-2fa15f95b3fe)
				[2. Aspellinae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=b8fd52e4-0786-4b5d-8706-0724cb832e2c)
				[3. Dermomurex](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=3fbeff1d-fb76-4bf3-a99a-bfcdfe3ccb0e)
				
intermedia	accepted		species	[1. Platycopida>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=99313ea9-738e-4167-a8fb-0df944047143)
				[2. Kloedenellidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=d21bd94e-03e4-4a9c-90cc-8c3f9e940788)
				[3. Kloedenella](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=002ddd13-2699-4737-8b1b-ba89cbb07fd0)
				
intermedia	accepted		species	[1. Beyrichioidea>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=55f6d897-096b-426d-b41e-4df4692734d3)
				[2. Beyrichiidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=a6675d37-50d8-4d00-a2ad-8b6cda09c78b)
				[3. Beyrichia](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=c4cdc305-1a71-45c8-b66c-604aaaa875cb)
				
koslowi	accepted		species	[1. Planariidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=7136de2d-6bd8-4ed9-8058-dbeb1b3a39d5)
				[2. Polycelis>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=f2c7c411-bb69-4423-85ef-9bcfce0b2abf)
				[3. Polycelis](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=2282153b-4bc4-4b59-b5c0-9912e22dbd36)
				
koslowi	accepted		species	[1. Planariidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=7136de2d-6bd8-4ed9-8058-dbeb1b3a39d5)
				[2. Polycelis>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=f2c7c411-bb69-4423-85ef-9bcfce0b2abf)
				[3. Polycelidia](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=7f12b972-4125-40ab-ae17-44baba6d6a82)
				
Lipsothrix jiri	accepted	Podenas, 2020	species	[1. Limoniidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=86abfa8a-03fd-45db-a7cf-d6fb1bed1f7e)
				[2. Limoniinae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=6cce7f1f-d9bf-4c8a-b9b9-d1228a65c790)
				[3. Lipsothrix](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=83dfb1b1-a36e-4901-88ef-7e09d09074f0)
				
Lipsothrix jiri	accepted	Podenas, 2020	species	[1. Liomoniidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=83051559-d6d4-4b4a-a0c8-95da0b665e36)
				[2. Eriopterinae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=36b0ba25-de25-4a1b-8eea-9a86edc777fc)
				[3. Lipsothrix](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=f34f89a2-e46f-4518-b5c3-fd69991b8a02)
				
Necrocarcinus rathbunae	accepted	Roberts, 1962	species	[1. Necrocarcinoidea>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=1a947255-1f2a-40c8-9cfb-b3359ce65622)
				[2. Necrocarcinidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=9fffe24f-536d-4f9a-b61c-c4caf7227d93)
				[3. Necrocarcinus](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=70cb744a-bd1f-450e-ad99-0c3881fe868f)
				
Necrocarcinus rathbunae	accepted	Roberts, 1962	species	[1. Dorippoidea>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=d34c3ead-2267-4a5a-a2cf-b38671abead6)
				[2. Necrocarcinidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=6145e801-fbcc-4655-a527-951a29844a99)
				[3. Necrocarcinus](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=0ab3e8c0-45a4-41ae-806e-abacc07cb59a)
				
Ovipoculum album	accepted	Zhu L. Yang & R. Kirschner	species	[1. Agaricomycetes>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=368da5dd-a99c-4e3d-95ac-71fc8f0e85a2)
				[2. Auriculariales>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=ba4da40b-14de-472d-a365-b4e7ae540d40)
				[3. Ovipoculum](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=0cd650a2-61ca-4e5b-b99f-e47b36e37db2)
				
Ovipoculum album	accepted	Zhu L. Yang & R. Kirschner	species	[1. Peronosporales>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=a5eabe35-446b-442d-9125-2be4f6eb132d)
				[2. Pythiaceae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=ad8aa70b-4dfb-4c62-a5e3-f5971d4abe5d)
				[3. Ovipoculum](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=61cc3736-9e8f-42a2-ab4a-634fdc0f95a2)
				
Palaeomesorthopteron pullus	accepted	Aristov, Grauvogel-Stamm & Marchal-Papier, 2011	species	[1. Alexarasniidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=dd63505d-8803-4ab1-8183-8108bbd7be39)
				[2. Nestorembiinae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=06e07505-1822-48fa-9d9d-4f92813a730a)
				[3. Palaeomesorthopteron](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=3793597c-257e-4786-b104-c3b20b3dd73e)
				
Palaeomesorthopteron pullus	accepted	Aristov, Grauvogel-Stamm & Marchal-Papier, 2011	species	[1. Grylloblattina>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=05fdb86b-29c7-4357-a0e4-9212072ce9a5)
				[2. Mesorthopteridae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=675f9582-4bdf-4f67-8962-b377728b5ec9)
				[3. Palaeomesorthopteron](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=91605a74-996f-444c-95c4-b84fd409ef27)
				
Paranecrocarcinus libanoticus	accepted	Förster, 1968	species	[1. Necrocarcinoidea>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=1a947255-1f2a-40c8-9cfb-b3359ce65622)
				[2. Paranecrocarcinidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=1e6e4ee3-b6e3-48a9-ac29-3c14657a9d97)
				[3. Paranecrocarcinus](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=a10725a8-ab13-4207-ae80-7476758aefad)
				
Paranecrocarcinus libanoticus	accepted	Förster, 1968	species	[1. Dorippoidea>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=d34c3ead-2267-4a5a-a2cf-b38671abead6)
				[2. Necrocarcinidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=6145e801-fbcc-4655-a527-951a29844a99)
				[3. Paranecrocarcinus](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=b4395375-d955-4fcf-88fa-872d0e80ac8d)
				
Propontocypris dromas	accepted	Aiello, Barra & Bonaduce, 2000	species	[1. Pontocypridoidea>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=508209e7-367e-4d95-9b12-73404d4987e5)
				[2. Pontocyprididae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=002bcd34-cae1-4a90-a351-96e24f112483)
				[3. Propontocypris](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=0c0debce-c4b8-4241-9820-8459c6873130)
				
Propontocypris dromas	accepted	Aiello, Barra & Bonaduce, 2000	species	[1. Pontocypridoidea>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=508209e7-367e-4d95-9b12-73404d4987e5)
				[2. Pontocyprididae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=002bcd34-cae1-4a90-a351-96e24f112483)
				[3. Propontocypris](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=0c0debce-c4b8-4241-9820-8459c6873130)
				
Protonecrocarcinus ovalis	accepted	(Stenzel, 1945)	species	[1. Necrocarcinoidea>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=1a947255-1f2a-40c8-9cfb-b3359ce65622)
				[2. Paranecrocarcinidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=1e6e4ee3-b6e3-48a9-ac29-3c14657a9d97)
				[3. Protonecrocarcinus](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=8abd81f7-e01a-4241-a824-b892c1a44329)
				
Protonecrocarcinus ovalis	accepted	(Stenzel, 1945)	species	[1. Dorippoidea>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=d34c3ead-2267-4a5a-a2cf-b38671abead6)
				[2. Necrocarcinidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=6145e801-fbcc-4655-a527-951a29844a99)
				[3. Protonecrocarcinus](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=7a037476-5f5c-468e-bb1f-48426709156e)
				
Pseudonecrocarcinus gamma	accepted	(Roberts, 1962)	species	[1. Necrocarcinoidea>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=1a947255-1f2a-40c8-9cfb-b3359ce65622)
				[2. Paranecrocarcinidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=1e6e4ee3-b6e3-48a9-ac29-3c14657a9d97)
				[3. Pseudonecrocarcinus](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=117f33a5-8a0c-44d2-81fd-49f4f4a02490)
				
Pseudonecrocarcinus gamma	accepted	(Roberts, 1962)	species	[1. Dorippoidea>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=d34c3ead-2267-4a5a-a2cf-b38671abead6)
				[2. Necrocarcinidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=6145e801-fbcc-4655-a527-951a29844a99)
				[3. Pseudonecrocarcinus](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=7c20cd2f-adfb-484c-80e5-d9c57957ad7c)
				
Pseudonecrocarcinus quadriscissus	accepted	(Noetling, 1881)	species	[1. Necrocarcinoidea>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=1a947255-1f2a-40c8-9cfb-b3359ce65622)
				[2. Paranecrocarcinidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=1e6e4ee3-b6e3-48a9-ac29-3c14657a9d97)
				[3. Pseudonecrocarcinus](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=117f33a5-8a0c-44d2-81fd-49f4f4a02490)
				
Pseudonecrocarcinus quadriscissus	accepted	(Noetling, 1881)	species	[1. Dorippoidea>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=d34c3ead-2267-4a5a-a2cf-b38671abead6)
				[2. Necrocarcinidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=6145e801-fbcc-4655-a527-951a29844a99)
				[3. Pseudonecrocarcinus](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=7c20cd2f-adfb-484c-80e5-d9c57957ad7c)
				
Shirakiacris yunkweiensis	accepted	(Chang, 1937)	species	[1. Eyprepocnemidinae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=817bfeb8-be73-4d4c-9556-c83561087313)
				[2. Eyprepocnemidini>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=0997e96e-5b10-426f-9ac1-da275be8423a)
				[3. Shirakiacris](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=942b8a75-bac8-4f38-8d77-233a542cf479)
				
Shirakiacris yunkweiensis	accepted	(Chang, 1937)	species	[1. Eyprepocnemidinae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=817bfeb8-be73-4d4c-9556-c83561087313)
				[2. Eyprepocnemidini>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=0997e96e-5b10-426f-9ac1-da275be8423a)
				[3. Shirakiacris](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=942b8a75-bac8-4f38-8d77-233a542cf479)
				
Steinernema australe	accepted	Edgington, Buddie, Tymo, Hunt, Nguyen, France, Merino & Moore, 2009	species	[1. Strongyloidoidea>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=279e4c49-ab0e-4ee0-bfc9-edad1b16fae1)
				[2. Steinernematidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=8e422b61-2bbf-49a2-928c-d2b7d6b9c5f2)
				[3. Steinernema](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=cf563211-ec58-43b5-b7d3-2f27c42b99f5)
				
Steinernema australe	accepted	Edgington, Buddie, Tymo, Hunt, Nguyen, France, Merino & Moore, 2009	species	[1. Strongyloidoidea>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=279e4c49-ab0e-4ee0-bfc9-edad1b16fae1)
				[2. Steinernematidae>](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=8e422b61-2bbf-49a2-928c-d2b7d6b9c5f2)
				[3. Steinernema](https://www.checklistbank.org/dataset/3/classification?sourceTaxonKey=cf563211-ec58-43b5-b7d3-2f27c42b99f5)

**Comment by yroskov** [comment]
https://github.com/CatalogueOfLife/data/milestone/4

**Comment by yroskov** [comment]
- [ ] Redundant, accepted higher taxa **There are still 215 redundant families and above in the COL checklist** (https://github.com/CatalogueOfLife/data/issues/463)

https://www.checklistbank.org/catalogue/3/duplicates?catalogueKey=3&category=uninomial&limit=100&minSize=2&mode=STRICT&offset=0&rank=family&rank=class&rank=order&rank=phylum&rank=suborder&rank=infraorder&rank=superfamily&rank=subfamily&rank=suprageneric%20name&rank=superorder&rank=subclass&rank=superclass&rank=subphylum&rankDifferent=false&status=accepted&withDecision=false

**There is no CLB tool to resolve these issues!**

**Comment by dhobern** [comment]
@yroskov - do you have any suggestion what such a tool would look like? From a quick scan, I can see that a few relate to different treatment in two datasets, but others (like the Systema Dipterorum ones) seem to be the result of trying to normalise denormalised datasets which may not have used their columns in exactly the way we expect. See the Ceratopogoninae example. It would be valuable to review these and communicate with the dataset holders or with whoever wrote the script to scrape them.

**Comment by yroskov** [comment]
> do you have any suggestion what such a tool would look like?

Yes, I have. CoL@CLB needs two tools (both are similar to TASKS manager with minor improvements; TASKS reports on duplicates across GSDs should include GSD name and **full** classification (preferably with ranks)):
(1) TASKS for the GSD vs whole CoL (i.e. all CoL sectors)
(2) TASKS for the project (i.e. reports on duplicates for whole CoL). A mock-up of this tool is already available inside the project menu, but it is not functional - decisions are not applicable, export CSV file does not have indication of source GSD.

**Comment by yroskov** [comment]
- [x] family Xenoturbellidae is in phylum Not Assigned = FIXED 2023-05-23 https://github.com/CatalogueOfLife/testing/issues/45#issuecomment-1559391135

**Comment by yroskov** [comment]
- [x] Old abstract in World Ferns. It's a new one in CLB = re-synced 2023-05-31 = Need to be checked in the PREVIEW
- [x] Sector Caryophyllales of World Plants re-synced 2023-05-31

**Comment by yroskov** [comment]
Release Alias Template changed as  **COL{date,yy}** (see https://github.com/CatalogueOfLife/testing/issues/201#issuecomment-1209435378)

PREVIEW release started 2023-05-31, 3:17 pm (server time)

**Comment by yroskov** [comment]
PREVIEW release started 2023-05-31, 5:51 pm (server time)

**Comment by yroskov** [comment]
- [ ] 2023-06-02, there are **23 broken sectors in WoRMS** today (https://www.checklistbank.org/catalogue/3/sector?broken=true&limit=100&offset=0).

@gdower, taken in account what @mdoering says about sectors management in CLB [here ](https://github.com/CatalogueOfLife/data/issues/535), how WoRMS pipelines dealing with broken sectors. 

Did we have so many broken sectors in the imports of previous months? (My recollection, no).

**Comment by yroskov** [comment]
- [ ] Empty creator, editor, contributor fields in WoRMS metadata https://github.com/CatalogueOfLife/testing/issues/227#issuecomment-1574363577

**Comment by yroskov** [comment]
PREVIEW release started 2023-06-07, 5:26 pm (server time)

**Comment by yroskov** [comment]
PREVIEW release started 2023-06-08, 7:11 pm (server time)

**Comment by yroskov** [comment]
- [ ] search for possible overlaps in the classification in whole CoL:
- accepted species with identical authorstrings, 0: https://www.checklistbank.org/catalogue/3/duplicates?authorshipDifferent=false&catalogueKey=3&category=binomial&limit=500&rankDifferent=false&status=accepted

- accepted species with different authorstrings, 281: https://www.checklistbank.org/catalogue/3/duplicates?authorshipDifferent=true&catalogueKey=3&category=binomial&limit=500&rankDifferent=false&status=accepted.

**Comment by yroskov** [comment]
- [ ] Species entry **Status unresolved** in _Brassicaceae_
https://www.catalogueoflife.org/data/search?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=extinct&facet=environment&limit=50&offset=0&q=Status%20unresolved&sortBy=taxonomic

See also https://github.com/CatalogueOfLife/data/issues/527

**Comment by yroskov** [comment]
PREVIEW release started 2023-06-12, 10:54 pm (server time)

**Comment by yroskov** [comment]
- [x] Species Fungorum Plus, ver Jan 2023 / 2023-01-17 (imported 2023-01-19) re-synced 2023-06-13.
- [x] Sector Ranunculales of World Plants re-synced 2023-06-13.

**Comment by yroskov** [comment]
PREVIEW release started 2023-06-13, 8:16 pm (server time)

**Comment by yroskov** [comment]
PREVIEW release started 2023-06-14, 7:36 pm (server time)

**Comment by yroskov** [comment]
PREVIEW release started 2023-06-15, 2:47 pm (server time)
Finished as COL23, Catalogue of Life Checklist, Annual Checklist 2023, id 9904, 2023-06-15 4:07 pm
Deployed to the preview website 2023-06-15

**Comment by yroskov** [comment]
PREVIEW release started 2023-06-17, 11:03 pm (server time)

**Comment by yroskov** [comment]
@olafbanki, do you have a final decision on replacement of Siphonaptera and continuation with all SFs checklists in AC23? 
Have you updated AC23 metadata as you wish?

We have two days on this week to finalize remaining issues. 

If all are fine from your point of view, the checklist with id 9905 of June 18th at https://www.checklistbank.org/dataset/9905 is ready as 2023 Annual Checklist.

**Comment by yroskov** [comment]
@olafbanki, 2023-06-22:
>On SF, it is clear that at least for now SF Cockroach cannot be used by COL because of a license that is not supported. It needs to be removed from the COL Checklist, but can live in ChecklistBank for now. 

- [x] SF Cockroach removed (i.e. sectors deleted) 2023-06-22

PREVIEW release started 2023-06-22, 5:20 pm (server time)

**Comment by yroskov** [comment]
@olafbanki, 2023-06-22:

> I am still waiting for Matt's guidance on **SF Coreoidea** and **SF Mantodea**. **Phoronida**, Emig, might request a license that is more restrictive than what seems to be common scientific practice. Discussion is still ongoing, but possibly it has to be removed. For next months we might consider a replacement from WoRMS. 

>It looks like we are heading to publication of AC 2023 **on either next Tuesday or Wednesday**. [2023-06-27 -28]

**Comment by yroskov** [comment]
- [x] **LWS fleas**: Lewis Flea (Siphonaptera) World Species List replaced Parhost World Database of Fleas 2023-06-22

PREVIEW release started 2023-06-22, 7:38 pm (server time)

**Comment by yroskov** [comment]
PREVIEW release started 2023-06-22, 5:49 pm (server time)

**Comment by yroskov** [comment]
PREVIEW release started 2023-06-26, 9:45 pm (server time) = 23.45 Leiden

**Comment by yroskov** [comment]
- [x] 2023-06-27, full title of id 54170 is changed back as **Robert E. Lewis World Species Flea (Siphonaptera) List**

**Comment by olafbanki** [comment]
Licenses changed to CC-BY from the following GSDS:

Cilcat https://www.checklistbank.org/dataset/1113/about, 
Fada Rotifera https://www.checklistbank.org/dataset/1047/about, 
Globis https://www.checklistbank.org/dataset/1046/about, 
Mites GSD Phytoseiidae https://www.checklistbank.org/dataset/1070/about
Mites GSD Tenuipalpidae https://www.checklistbank.org/dataset/1078/about
PBI Plant Bug https://www.checklistbank.org/dataset/1171/about
Phoronida https://www.checklistbank.org/dataset/1104/about
Taxapad https://www.checklistbank.org/dataset/1068/about
Tineidae https://www.checklistbank.org/dataset/1031/about
Zoological-Botanical Database (Vespoidea) https://www.checklistbank.org/dataset/1037/about

**Comment by olafbanki** [comment]
CC-BY license added to the COL Checklist

**Comment by olafbanki** [comment]
Metadata of creators of the COL Checklist changed to also include: Diana Hernández, Camila Plata, Thomas Jeppesen, and Ari Örn; Dave Remsen removed.

COL Checklist 2023 dedicated to the memory of David Remsen

**Comment by yroskov** [comment]
PREVIEW release started 2023-06-27, 8:38 pm (server time) = 22.38 Leiden
Finished as COL23, Catalogue of Life Checklist, Annual Checklist 2023, id 9909, 2023-06-27, 9:58 pm
Deployed to the preview website - not yet

**Comment by olafbanki** [comment]
The AC2023 is published.
