### ISSUE TITLE
CoL of April 2023

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#222]
- [x] WoRMS of 2023-04-01; imported 2023-04-06; **synced 2023-04-06**

- [x] ITIS of 2023-03-30;  imported 2023-04-05; **synced 2023-04-12**

- [x] Scarabs of 2023-04-04; imported 2023-04-06; **synced 2023-04-07**

- [x] 3i Auchenorrhyncha of Apr 2023 / 2023-04-12; imported 2023-04-12; **synced 2023-04-17**

- [x] 3i Curculio of Apr 2023 / 2023-04-12; imported 2023-04-12; synced 2023-04-13; re-imported with fixes 2023-04-17; **synced 2023-04-17**

- [x] SF Isoptera of 2023-04-12; imported 2023-04-12; **synced 2023-04-17**

- [x] WCO (Opiliones) of 2023-04-12; imported 2023-04-12; **synced 2023-04-17**

- [x] WOL (Odonata) of 2023-04-12; imported 2023-04-12; **synced 2023-04-17**

- [x] Tortricid.net ver. 4.0 / 2018-12-31; imported 2023-02-15; **synced 2023-03-24**

- [x] Global Lepidoptera Index; synced 2023-03-24; ver of  2023-03-18; ver 0.32.1 / 2023-04-03 synced 2023-04-03; ver 0.32.2 / 2023-04-08 **synced 2023-04-10**

- [x] Pterophoroidea; imported 2023-01-05; **synced 2023-03-24**

- [x] Gelechiidae of 1.1.23.97 (07 Apr 2023); **synced 2023-04-10**

- [x] WWW; imported 2023-03-10; **synced 2023-04-12**

**Comment by yroskov** [comment]
- [x] family Masaridae from ZOBODAT Vespoidea re-synced 2023-03-15 after blocking genus Chrysis (https://github.com/CatalogueOfLife/data/issues/285)

**Comment by yroskov** [comment]
- [x] WoRMS Oligochaeta temporarily re-synced 2023-03-15 after blocking family family Branchiobdellidae in WoRMS order Oligochaeta incertae sedis (https://github.com/CatalogueOfLife/data/issues/516)

**Comment by yroskov** [comment]
- [ ] "s.str." in authorstrings of type subspecies https://github.com/CatalogueOfLife/data/issues/522

**Comment by yroskov** [comment]
- [ ] See also broken sectors in WCVP: https://github.com/CatalogueOfLife/backend/issues/1216
At least, family **Zingiberaceae** need to be re-synced

**Comment by yroskov** [comment]
- [x] family Asteraceae from World Plants ver. 15.0 of Mar 2023 re-synced  2023-04-18 after fix in authorstring according https://github.com/CatalogueOfLife/data/issues/526

**Comment by yroskov** [comment]
PREVIEW release started 2023-04-18, 6:11 pm (server time)

**Comment by yroskov** [comment]
PREVIEW release started 2023-04-19, 8:14 pm (server time)

**Comment by yroskov** [comment]
@olafbanki & @mdoering, COL23.4, 2023-04-19, id 9887 is ready for deployment as CoL of April.

**Comment by yroskov** [comment]
2023-04-25: deployed to the portal.
