### ISSUE TITLE
CoL of May 2023

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#225]
- [x] WoRMS of 2023-05-01; imported 2023-05-02; **synced 2023-05-03**

- [x] ITIS of 2023-04-26 with new global sectors decapod infraorder Anomura (in whole now), mite family Parholaspididae & superfamily Ascoideais (in whole now); imported 2023-05-01; **synced 2023-05-01**

- [x] Scarabs of 2023-05-09; imported 2023-05-09; **synced 2023-05-09**

- [x] The Scorpion Files of Apr 2023 / 2023-04-24 crawled & imported 2023-04-25; **synced 2023-04-25**

- [x] Collembola.org of Apr 2023 / 2023-04-24 crawled & imported 2023-04-24; **synced 2023-04-27**

- [x] 3i Auchenorrhyncha of 2023-05-10; imported 2023-05-10; **synced 2023-05-11**

- [x] 3i Curculio of 2023-05-10; imported 2023-05-10; **synced 2023-05-11**

- [x] SF Isoptera of 2023-05-10; imported 2023-05-10; **synced 2023-05-11**

- [x] WCO (Opiliones) of 2023-05-10; imported 2023-05-10; **synced 2023-05-12**

- [x] WOL (Odonata) of 2023-05-10; imported 2023-05-10; **synced 2023-05-12**

- [x]  Gelechiidae of 1.1.23.111 (21 Apr 2023); imported 2023-04-21; synced 2023-04-21; **re-synced 2023-04-27**

- [x] World Plants of 2023-05-01; imported 2023-05-02; **synced 2023-05-08**

- [x] World Ferns of 2023-05-01; imported 2023-05-01; **synced 2023-05-05**

**Comment by yroskov** [comment]
- [ ] Conflicts in Lepidoptera classification: https://github.com/CatalogueOfLife/testing/issues/224

**Comment by yroskov** [comment]
PREVIEW release started 2023-04-26, 9:47 pm (server time)

**Comment by yroskov** [comment]
- [ ] Resolving duplicates in CoL: ACC-ACC sp, same auth, 16 duplicates https://github.com/CatalogueOfLife/testing/issues/217#issuecomment-1530093493

SF Orthoptera re-synced 2023-05-01

**Comment by yroskov** [comment]
- [x] _Vespa analis_ is not a synonym of _Polistes testaceicolor_ https://github.com/CatalogueOfLife/data/issues/288
Name _Vespa analis_ blocked. Family Eumenidae from ZOBODAT Vespoidea ver. 4.0 of Oct 2011 **re-synced 2023-05-02**.

**Comment by yroskov** [comment]
- [ ] GLI (a new alias for Global Lepidoptera Index? **How this change affects stat reports?**) = re-synced 2023-05-09.
**Need to check results before release**

**Comment by yroskov** [comment]
- [x] WoRMS: TASKS resolution: https://github.com/CatalogueOfLife/testing/issues/227

**Comment by yroskov** [comment]
PREVIEW release started 2023-05-10, 5:35 pm (server time)

(WPlants & re-synced WoRMS)

**Comment by yroskov** [comment]
PREVIEW release started 2023-05-12, 6:49 pm (server time)

**Comment by yroskov** [comment]
PREVIEW release started 2023-05-15, 7:30 pm (server time)
