### ISSUE TITLE
CoL of October 2023

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#236]
- [x] WoRMS of 2023-10-01 (_check auths/eds in WoRMS Mollusca & Nemys_); imported 2023-10-02; **synced 2023-10-03**

- [x] ITIS of 2023-09-26; imported 2023-10-02; **synced 2023-10-02**

- [ ] Scarabs - no update in Oct

- [x] 3i Auchenorrhyncha (_check duplicates in synonymy with uninomials_ = FIXED); imported 2023-10-04; **synced 2023-10-04**

- [x] Entiminae; imported 2023-10-04; **synced 2023-10-05**

- [x] SF Isoptera; imported 2023-10-04, re-imported 2023-10-05; **synced 2023-10-05**

- [x] WCO (Opiliones); imported 2023-10-04; **synced 2023-10-05**

- [x] WOL (Odonata); imported 2023-10-04; **synced 2023-10-05**

- [x] GLI 1.1.23.269 / 2023-09-26; imported 2023-09-26; **synced 2023-10-12**

- [x] Gelechiidae 1.1.23.244 (01 Sep 2023) / 2023-09-01; imported 2023-09-01; **synced 2023-10-13**

- [x] Pterophoroidea 1.1.23.284 (11 Oct 2023) / 2023-01-05; imported 2323-10-11; **synced 2023-10-13**

- [x] World Plants ver 16.4 of 2023-09-20; imported 2023-09-22; **synced 2023-09-22**

- [x] World Ferns ver 16.4 of 2023-09-20; imported 2023-09-21; **synced 2023-09-22**

- [x] PaleoBioDB of 2022-03-01 / 2022-03-01; **synced 2023-09-21**

=============================

- Hepialidae (Lepidoptera) Oct/Nov

- WCVP ver 11.0 / 2023-04-20

- ScaleNet

- LPSN

- Species Files via TW (in Oct - Nov (Dec))

- FishBase - ?

- Paris/DBTNT - ?

- UCD

- Species Fungorum via API (should be confirmed by Paul)

- LDL Neuropterida

**Comment by yroskov** [comment]
- [ ] Subclass Ammonoidea and order Belemnitida from PaleoBioDB are listed as direct children of Animalia. In August version, they were listed under Mollusca/Cephalopoda: https://github.com/CatalogueOfLife/data/issues/565

All 3 PaleoBioDB sectors are broken now: missing subjects. 

2023-09-21: all subjects in 3 sectors updated. Sectors synced.

**Comment by yroskov** [comment]
- [ ] Empty superclass Aplacophora https://github.com/CatalogueOfLife/testing/issues/70#issuecomment-1730255125

**Comment by mdoering** [comment]
> * [ ]  Data of **PaleoBioDB ver 2022-03-01 / 2022-03-01** in CLB are in absolute mess. It's not the version, which was used before in the CoL (Feb 2018 / 2018-02-16).
> 
> Plus, dagger symbols are missing with taxa of all ranks.
> 
> @mdoering, @gdower, do we have an option to re-store PaleoBioDB checklist of Feb 2018 / 2018-02-16 in the CoL?

We do have the ACEF 2019 version of PBDB: https://github.com/CatalogueOfLife/data/raw/master/ACEF/174.tar.gz
But I am not convinced we should use it. Its old and probably very patchy. But give it a try on dev if it matches your expectations.

PaleoBioDB is known to be a problematic source with an old, custom export script by GBIF that never was great as the source db is difficult to understand. It would be best to contact them for a proper export, maybe using the new IPT?

Another option would be to use the COL AC23 release as the sector(s) to sync from. This way you get all existing data. The source metadata would be entirely wrong, but you would just add a complete patch to it to be PBDB again.

**Comment by yroskov** [comment]
~~PREVIEW release started 2023-09-22, XXX pm (server time)~~
Check: (1) Subclass Ammonoidea and order Belemnitida from PaleoBioDB; (2) classification in Mollusca; (3) families Surianaceae & Pentaphragmataceae

**Comment by yroskov** [comment]
- [ ] Check this report https://www.checklistbank.org/dataset/3/names?nameType=placeholder for _incertae sedis names_ after WoRMS update (https://github.com/CatalogueOfLife/data/issues/567)

**Comment by dhobern** [comment]
Yes - small changes in Gelechiidae and Pterophoroidea. Also one taxon removed from Hepialidae and ongoing updates to GLI. Thanks.

**Comment by yroskov** [comment]
PREVIEW release started 2023-10-04, 9:36 pm (server time)

**Comment by yroskov** [comment]
PREVIEW release started 2023-10-??,  pm (server time)

- [ ] Check total species numbers in Eumycetozoa.com after a block of incertae sedis names (2 orders, 3 families https://www.checklistbank.org/catalogue/3/dataset/1053/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&q=incertae%20sedis)

**Comment by yroskov** [comment]
PREVIEW release started 2023-10-13, 5:53 pm (server time)

**Comment by yroskov** [comment]
PREVIEW release started 2023-10-16, 3:05 pm (server time)

**Comment by yroskov** [comment]
For attention of @olafbanki, @mdoering: CoL of October (id 272972) is ready for deployment to the portal.

**Comment by olafbanki** [comment]
@mdoering CoL of October can be published online; blog post written. Thanks @yroskov and @gdower!

**Comment by mdoering** [comment]
done https://www.catalogueoflife.org/data/metadata
