### ISSUE TITLE
CoL of November 2023

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#239]
- [x] WoRMS of 2023-11-01 (_check auths/eds in WoRMS Mollusca & Nemys_); all syncs of 2023-11-03 failed (https://github.com/CatalogueOfLife/backend/issues/1269); **synced 2023-11-07**

- [x] ITIS of 2023-10-31 (incl. a new global checklist for the mite superfamily Anystoidea); imported 2023-11-02; **synced 2023-11-03** - CHECK ITIS SYNC! = all 122 failed; **synced 2023-11-07**

- [x] Scarabs of 2023-11-06; imported 2023-11-06; **synced 2023-11-07**

- [x] 3i Auchenorrhyncha of Nov 2023; imported 2023-11-08; **synced 2023-11-10**

- [x] Entiminae of Nov 2023; imported 2023-11-09; **synced 2023-11-09**

- [x] SF Isoptera of 2023-11-08; imported 2023-11-09; **synced 2023-11-09**

- [x] WCO (Opiliones) of 2023-11-08; imported 2023-11-09; **synced 2023-11-09**

- [x] WOL (Odonata) of 2023-11-08; imported 2023-11-09; **synced 2023-11-10**

- [x] GLI synced 2023-11-07, **re-synced 2023-11-13**

- [x] Gelechiidae ver 1.1.23.315 (11 Nov 2023) / 2023-11-11; imported 2023-11-11; **synced 2023-11-13**

- [ ] Pterophoroidea = There is no update since CoL of Oct 2023. No need to re-sync.

- [x] Hepialidae (Lepidoptera), new; ver 1.0 of ?; imported 2023-10-01; **synced 2023-10-27**

- [x] PaleoBioDB replaced with previous version of Feb 2018 / 2018-02-16 (id 268676); synced 2023-11-06 **= Need to be re-imported when 'extinct' flag appear in Options for import. This will resolve issue of non-extinct genera in PaleoBioDB sectors.** 

- [x] World Plants ver 18.1 of 2023-11-08; imported 2023-11-15; **synced 2023-11-15**

- [x] World Ferns ver 18.1 of 2023-11-08; imported 2023-11-14; **synced 2023-11-15**

- [x] WCVP-Fabaceae ver. 2023v.4 / 2023-08-02; **synced 2023-11-13** 

- [x] SF Orthoptera ver. 0.35.2 / 2023-11-09; imported 2023-11-14; **synced 2023-11-15**

=============================

- Conifers as a part of WFO - Nov?

- UCD in Nov?

- WCVP ver 11.0 / 2023-04-20

- ScaleNet

- LPSN

- Species Files via TW (in Nov - Dec) - check with Heidi on a new **SF Permopsocida** (39 paleospp) 

- FishBase - ?

- Paris/DBTNT - ?

- Species Fungorum via API (should be confirmed by Paul)

- LDL Neuropterida

=============================

_Filling gaps:_

Suborder **Symphyta** (Hymenoptera) https://github.com/CatalogueOfLife/data/issues/579
Class/order **Diplura** https://github.com/CatalogueOfLife/data/issues/577
Order **†Permopsocida** (Insecta) https://github.com/CatalogueOfLife/data/issues/578
Family **Promecheilidae** (Tenebrionoidea, Coleoptera) https://github.com/CatalogueOfLife/data/issues/580

**Comment by dhobern** [comment]
The COL TG has approved the replacement of the family Hepialidae (Lepidoptera) with this new dataset:

https://www.checklistbank.org/dataset/265709/about

**Comment by yroskov** [comment]
- [ ] WCO (Opiliones): check authorstrings with extinct taxa (https://github.com/CatalogueOfLife/data/issues/569)

**Comment by yroskov** [comment]
- [ ] PaleoBioDB update of Oct: missing "extinct" flag with 4615 spp (data absent in CLB source). Consider reverting to a previous cleaned version.

**Comment by sergbolshakov** [comment]
Hello!
In [the latest version](https://download.checklistbank.org/job/19/191b3a57-ca05-4fc0-9a87-1c2aa1768e06.zip) for names from Bryonames in the status of synonyms there are no links.
But online in the link field there are links to the name page in Tropicos.
E. g. https://www.checklistbank.org/dataset/272972/name/4a2f4d14-e255-4c55-a8a4-b5df5608bf6 vs `grep Takakiophyta NameUsage.tsv`
Is this a bug or a feature?

**Comment by yroskov** [comment]
- [ ] Fixed bug which caused unstable UUID identifiers. Now need to re-sync all sectors in: https://github.com/CatalogueOfLife/general/issues/100#issuecomment-1785659250

**Comment by yroskov** [comment]
Donald, 2023-10-29: _... I needed to confirm to you that the Taxonomy Group supports the two decisions here:
https://docs.google.com/document/d/1YLcC7dHrMA40UKViZ5ww39Yc99IcgGCo/edit?usp=sharing&ouid=113140186902620905250&rtpof=true&sd=true
https://docs.google.com/document/d/1HUkQxthfXSb6Sr8BNv2837T7bUGas95-3XE73GS_X-w/edit
Please do anything else that needs to happen to replace these sections in COL._

**Comment by gdower** [comment]
@sergbolshakov, that's likely an exporter bug. Please open a ticket [here](https://github.com/catalogueoflife/backend/issues).

**Comment by yroskov** [comment]
PREVIEW release started 2023-11-07, 11:06 pm (server time)

**Comment by yroskov** [comment]
- [ ] Check GSD logos (they disappeared in Oct release or earlier), see https://github.com/CatalogueOfLife/portal/issues/206

**Comment by yroskov** [comment]
PREVIEW release started 2023-11-10, 10:08 pm (server time)

**Comment by yroskov** [comment]
- [ ] Systema Dipterorum **re-synced 2023-11-13** https://github.com/CatalogueOfLife/testing/issues/127#issuecomment-1808599903

**Comment by yroskov** [comment]
- [x] Missing Nomenclatural Code setting. https://github.com/CatalogueOfLife/data/issues/583
Gymnodinium, Microsporidia and WCVP-Fabaceae, Tortricid.net re-synced 2023-11-13

Are there any other GSDs with missing Codes?

**Comment by yroskov** [comment]
PREVIEW release started 2023-11-13, 9:27 pm (server time)

**Comment by yroskov** [comment]
PREVIEW release started 2023-11-16, 1:50 pm (server time)


- [ ] "supersp" = species aggregate in SF Orthoptera

**Comment by yroskov** [comment]
@olafbanki, @mdoering, CoL of November (id 277686) is completed now and ready for deployment to the portal

**Comment by mdoering** [comment]
The IDs are wrong, so this cannot go live

**Comment by yroskov** [comment]
Hopefully the release will only be needed after you fix the problem. Please follow your schedule, and finally do a release & deployment. (Also please do all re-syncs if & where they will be needed).

**Comment by mdoering** [comment]
As far as I can see we should only need to do another release. That means you gotta stop working towards the December release in the project. If we are lucky I have found a way to bypass the problem already.

**Comment by mdoering** [comment]
It took a while, but I fixed various smaller bugs related to name matches, updated the matched content of previous releases and . The [preview release](https://preview.catalogueoflife.org/data/taxon/4CGXP) from today looks good to me to go now: https://www.checklistbank.org/dataset/3:188/

There are only 91 names left in this release with temporary identifiers - all of which are expected as they are not proper names found in the names index:

                  id                  |    rank    |              scientific_name               |              authorship              
--------------------------------------+------------+--------------------------------------------+--------------------------------------
 5V8By6INFvNu8_0b6z1Wj2               | TRIBE      | *TPorricondylinae                          | 
 KbK6J-xP-OuB4tqupz_Rn0               | SPECIES    | [Dexia] parvicornis                        | Wulp, 1867
 NCrEer0DO2v59hdy0tEEv2               | GENUS      | [Nepalia]                                  | 
 NSBBIFVNQcfe4CG17VksY0               | SPECIES    | [Dexia] suavis                             | Wulp, 1867
 TO75R9RJKuv27ONhm71Cm1               | SPECIES    | [non-Uristidae] albinus                    | (K.H. Barnard, 1932)
 TS4pLEaQLFtY8hoT-RFyY2               | SPECIES    | [Degeeria] albomarginata                   | Wulp, 1890
 Wxt6H0mL3mc14OThEma8S2               | SPECIES    | [Dexia] triquetra                          | Macquart, 1844
 _991TVUzYENX5067eJeMK                | GENUS      | [Drapetis]                                 | 
 aHB53udeRkexA8GttL1Rk0               | TRIBE      | *TLestremiinae                             | 
 aVCwmB9u-7st3d99ioZMG                | SPECIES    | “Montereina” purcina                       | (Ev. Marcus & Er. Marcus, 1967)
 c2y7Z7G2XnvU40IsR8pZO1               | GENUS      | [Cylindromyia]                             | 
 eDWzqBexTRNJ-hF5tWBho0               | SPECIES    | “Montereina” mortenseni                    | (Ev. Marcus & Er. Marcus, 1963)
 mQ6NFkWDxiAs7CKrZkmaQ2               | TRIBE      | *TTachininae                               | 
 oaWKt1qQ5c9Y5pk8UjWPT0               | GENUS      | [Dexiosoma]                                | 
 vHTK1vefBjv9Dxuws3R062               | TRIBE      | *FSteganinae                               | 
 9702b1a2-c387-420a-8599-7068de247eb7 | SPECIES    | × jezoensoides                             | 
 AwinGc_VmDPG-GC28f56O2               | SPECIES    | [Dexia] genuina                            | Wulp, 1867
 GlcctmdWZXdz5WGpSrpG70               | SPECIES    | [Degeeria] longipes                        | Wulp, 1890
 O3FEgXNx7ytE0OGFg5G2-0               | SPECIES    | “Montereina” branneri                      | (MacFarland, 1909)
 RAXSo2G9eK7F2OZQFTbk_                | SPECIES    | [Degeeria] cruralis                        | Giglio-Tos, 1893
 UIX5gtQL1eNBAdgjyCEnR                | SUBTRIBE   | *FTephritini                               | 
 _p_P1A4kkyNkA4a5GIPP3                | SPECIES    | [Drapetis] marginata                       | Meigen, 1838
 _r45Wpma9OsT3p9xGzUY50               | SPECIES    | [Ctenophorocera] polleniina                | Bezzi, 1908
 jv7jifn3RWdW6h_BqZsRs0               | SPECIES    | [Dexia] convexa                            | Walker, 1849
 udlVyL_A3ftq9GW8CfXku2               | SPECIES    | “Montereina” flindersi                     | (Burn, 1962)
 2UfB6IIWU_7fB8Afskckq2               | SPECIES    | [Degeeria] mexicana                        | Giglio-Tos, 1893
 2b74879d-a3a1-4977-abda-20cdd0ca235d | SPECIES    | [GENUS NOT SPECIFIED] duchaillui           | Rehn, 1960
 3IgDbhvIyHABBdx7P8rmp0               | TRIBE      | *TLomatiinae                               | 
 AAAVGG0GqKv32Ses62x1d                | SPECIES    | CHironomus flaviventris                    | Johannsen, 1907
 JspKrX83T4td8OtxuqA2x1               | SPECIES    | [Dexia] triangularis                       | Wulp, 1867
 N3_v1har24OG6hM340f_7                | GENUS      | [Dexia]                                    | 
 NAOtE-EVuBPw-ps5A-koj0               | SPECIES    | “Montereina” lippa                         | (Á. Valdés, 2001)
 ToVhTo0okFcq3xFgsQCyr1               | SPECIES    | [non-Uristidae] dawsoni                    | Hurley, 1963
 TwXnah5pUCuAE_KgQtPKd                | SPECIES    | “Montereina” aurila                        | (Marcus & Marcus, 1967)
 U1k-k5vKFTPT-SDRqdVZl1               | GENUS      | [non-Uristidae]                            | 
 XN5rz8dAMeQz7pSOTE8nU2               | SPECIES    | [Nepalia] filipes                          | Kieffer, 1911
 oNw6xnICbMt13O-U8zHg_1               | SPECIES    | [non-Uristidae] georgianus                 | (Schellenberg, 1931)
 p9QltgYJq3eR4dofyB_Fq1               | SPECIES    | “Montereina” coerulescens                  | (Bergh, 1888)
 3db5f536-9a79-42c5-a77c-584439ad023d | SPECIES    | × columbiana                               | 
 FLfM6MMqhac470HcPnIMy                | TRIBE      | *FTephritinae                              | 
 IpzF50saHScGA0pBK5lZX0               | TRIBE      | *FDrosophilinae                            | 
 PIa_2SG_EzA1AtCWpbtE1                | SPECIES    | [Dexia] effulgens                          | Wood, 1874
 PIu996n8jN8J1_PwKoDCb                | SPECIES    | [Dexia] brunnicornis                       | Macquart, 1844
 SVLUyRp2UyA86CSHpHkEu                | SPECIES    | [non-Uristidae] natalensis                 | K.H. Barnard, 1916
 c14_chhPCttDCWwt1dCBj1               | SPECIES    | “Montereina” aurea                         | (Eliot, 1903)
 cnu-OEvOR2s69pywlVy6X                | SPECIES    | [Degeeria] leucocyla                       | Wulp, 1890
 e8dd62ff-85ed-4215-a4be-18a105027d1a | SPECIES    | Psyllaphorura unnamed                      | Shveenkova, YB & Babenko, AB, 2021
 hzzTuWIAJh809h5Qjg3-M                | SPECIES    | [Dexia] cremides                           | Walker, 1849
 l4GcO0R_s-dV-4lfWTYe1                | SPECIES    | [Degeeria] insecta                         | Giglio-Tos, 1893
 mjaijsHZ02tk9KqonG29k0               | TRIBE      | *FEristalinae                              | 
 n91g9J22QbA36K9TBYL8Z                | SPECIES    | [Dexia] dejeanii                           | Robineau-Desvoidy, 1830
 suSFcNI-jD9T5SAUckGON                | TRIBE      | *FChironominae                             | 
 wV1Ta8kIQ99i8SvfyaZnz0               | SPECIES    | [Cylindromyia] lobata                      | Sabrosky, 1967
 3bf368f7-754c-4ac1-a1fc-a24be6162bea | FAMILY     | Not assigned                               | 
 3ce10f7f-08e1-4392-9c3f-afb4d48909ba | SPECIES    | × medusae-populina                         | 
 4WXY-4w3qqtb0K8zid9VA0               | SPECIES    | “Montereina” phoca                         | (Ev. Marcus & Er. Marcus, 1967)
 PkMiuN7vt2sw7lBD9GbTw                | SPECIES    | “Montereina” rubra                         | (Bergh, 1905)
 TEQWQ9aSLJeW9dD3ouiI-2               | SPECIES    | “Montereina” greeleyi                      | (MacFarland, 1909)
 b8911045-62e8-421f-8d3b-0f0aee52095a | SUBSPECIES | [GENUS NOT SPECIFIED] lunatum inconjunctum | Pic, 1920
 e-epdnq3p9838lyeRDfIC1               | SPECIES    | DIzygomyza barnesi                         | Hendel, 1933
 eqwilEkCt_fx0lZ3BhASd1               | SPECIES    | “Montereina” achroma                       | (Á. Valdés, 2001)
 f85Z-6Mf84fAEW8cT6okT2               | SPECIES    | [Degeeria] nigrocostalis                   | Wulp, 1890
 o6mI1lfB7pOx-GgfaiS7E1               | SPECIES    | DIzygomyza cambii                          | Hendel, 1931
 vnmSZ7K_hcPc94JDrtmbW0               | SPECIES    | [Dexia] basalis                            | Walker, 1849
 xC6dbIj2pEP278xJknih-2               | SPECIES    | [Drapetis] luteipes                        | Le Peletier & Audinet-Serville, 1828
 3ad0e30f-8260-4cb4-a710-a3d0182be96a | SUBSPECIES | [GENUS NOT SPECIFIED] lunatum rufithorax   | Pic, 1920
 63607f12-54b8-4e99-ab24-89a404086d45 | SUBSPECIES | Cyphoderus undescribed species             | Bellini, BC & Zeppelini, D, 2004
 6u5GCGl9VnQ8AhZPzGXnk1               | SPECIES    | [Dexia] fuscanipennis                      | Macquart, 1844
 DZb8gEcewgOm9lQW-d2gi0               | GENUS      | [Degeeria]                                 | 
 UmTHbxW6FDOq0dv-OCYbN0               | SPECIES    | [Dexiosoma] partita                        | Bigot, 1889
 Uu7Cx337P4ck34-oTV3FQ1               | GENUS      | [Ctenophorocera]                           | 
 V45QAYHdGFfk-0HHVRQvx0               | SPECIES    | “Montereina” erubescens                    | (Bergh, 1884)
 YXXr3mBfngOf4d4b1PC8F1               | SPECIES    | “Montereina” lancei                        | (Millen & Bertsch, 2000)
 YYPOVp2EvUQq0CrqB8jYc1               | SPECIES    | [Degeeria] dicax                           | Giglio-Tos, 1893
 akTFCpE-1QOC2SyGSeyDz                | SPECIES    | [Degeeria] basalis                         | Wulp, 1890
 fNXoRltkU77MExCDFw7UG                | SPECIES    | [Dexia] melanocera                         | Robineau-Desvoidy, 1830
 nQKX2cFQ9d7xDK2tRZmI31               | SPECIES    | [Dexia] tenuicornis                        | Wulp, 1867
 qXZWnNrUXGck-46G4dCkd                | SPECIES    | [Dexia] ogoa                               | Walker, 1849
 xFmu4fXrsFAx5tuCZxXyC0               | SPECIES    | [Degeeria] nervosa                         | Wulp, 1890
 yu5gw_t8zJsSDlQ9a_ECs                | SPECIES    | [Dexia] abzoe                              | Walker, 1849
 Acs99raPvKtl8C_j_2UIn0               | TRIBE      | *FTachininae                               | 
 ObC5Q_jv9_Oh0_iw4aPre2               | SPECIES    | [Dexia] analis                             | Say, 1829
 OgzH9Wv_Blvy9hsKfnSAJ0               | TRIBE      | *FChloropinae                              | 
 ftQN0s0BC1uYBSfJjOlS90               | SPECIES    | “Montereina” lentiginosa                   | (Millen, 1982)
 kg8XK9Wvihcx1pwmDf0ca1               | SPECIES    | “Montereina” punctifera                    | (Abraham, 1877)
 mUZKRYirioNH8StXdh5JK2               | TRIBE      | *FTrypetinae                               | 
 pJKMRqxoUKAH8xQ_JLPGB1               | SPECIES    | [Dexia] nivifera                           | Walker, 1849
 q5ymOW_aPiv984EYR_YlY1               | SPECIES    | “Montereina” labifera                      | (Abraham, 1877)
 q6CIODPIc5NE0xOximbP92               | SPECIES    | [Dexia] gortys                             | Walker, 1849
 vXoqVXchnoQAEKCTox_g82               | SPECIES    | [Degeeria] nigriventris                    | Williston, 1896
 z1G_gqwpbn9mAd9sfqLvY0               | SPECIES    | [Dexia] plana                              | Walker, 1849
(91 rows)

The id reports are also better than the recent ones before:
https://download.checklistbank.org/releases/3/188/

**Comment by mdoering** [comment]
published: https://www.catalogueoflife.org/2023/11/24/release
