### ISSUE TITLE
CoL of December 2023

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#242]
- [x] WoRMS of 2023-12-01; imported 2023-12-04; **synced 2023-12-05** 

- [x] ITIS of 2023-11-17; imported 2023-11-27; synced 2023-12-04; new version 2023-12-08; imported 2023-12-11; **synced 2023-12-12**

- [x] Scarabs of 2023-12-04; imported 2023-12-04; **synced 2023-12-04**

- [x] 3i Auchenorrhyncha  imported 2023-12-07; **synced 2023-12-08**

- [x] Entiminae imported 2023-12-07; **synced 2023-12-08**

- [x] SF Isoptera imported 2023-12-07; **synced 2023-12-07**

- [x] SF Orthoptera imported 2023-12-11; **synced 2023-12-11**

- [x] WCO (Opiliones) imported 2023-12-07; **synced 2023-12-07**

- [x] WOL (Odonata) imported 2023-12-07; **synced 2023-12-07**

- [x] GLI ver. 1.1.23.336 / 2023-12-02; imported 2023-12-02; **synced 2023-12-12*

- [ ] Gelechiidae (Lepidoptera) - no update

- [ ] Pterophoroidea (Lepidoptera) - no update

- [ ] Hepialidae (Lepidoptera) - no update

- [x] World Plants ver 18.2 of 2023-11-25; imported 2023-12-03; **synced 2023-12-06**

- [x] World Ferns ver 18.2 of 2023-11-25; imported 2023-11-30; **synced 2023-12-04**

- [x] Bryonames ver Nov 2023 / 2023-11-07; imported 2023-11-07; synced 2023-12-01; Dec 2023 / 2023-12-04; imported 2023-12-04; **synced 2023-12-05**

=============================

- Systema Dipterorum ver. 4.5 of Nov 2023 received 2023-11-16

- Conifers as a part of WFO - Nov?

-  ScaleNet

- UCD in Nov?

- WCVP ver 11.0 / 2023-04-20

- LPSN

- Species Files via TW (in Nov - Dec) - check with Heidi on a new **SF Permopsocida** (39 paleospp) 

- FishBase - ?

- Paris/DBTNT - ?

- Species Fungorum via API (should be confirmed by Paul)

- LDL Neuropterida

=============================

_Filling gaps:_

Suborder **Symphyta** (Hymenoptera) https://github.com/CatalogueOfLife/data/issues/579
Class/order **Diplura** https://github.com/CatalogueOfLife/data/issues/577
Order **†Permopsocida** (Insecta) https://github.com/CatalogueOfLife/data/issues/578
Family **Promecheilidae** (Tenebrionoidea, Coleoptera) https://github.com/CatalogueOfLife/data/issues/580

**Comment by yroskov** [comment]
Phylum **Chordata** classification (id 279229): https://www.checklistbank.org/dataset/279229/classification

COL Checklist Chordata Higher Classification, ver 1.0 / 2023-11-27

**Comment by yroskov** [comment]
- [x] Missing PaleoBioDB logo = FIXED 2023-11-29

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/74a7f1b5-8dc3-45e9-92be-182c2b9c5b45)

**Comment by yroskov** [comment]
- [ ] Overlap between WCVP-Fabaceae & WWW: https://github.com/CatalogueOfLife/data/issues/597

**Comment by yroskov** [comment]
- [ ] self-synonymizes taxa caused by removal square brackets and changed subgenera handling (https://github.com/CatalogueOfLife/data/issues/598)

- Systema Dipterorum 
- GLI 
- 3i Auchenorrhynca

**Comment by yroskov** [comment]
PREVIEW release started 2023-12-06, 10:05 pm (server time)

**Comment by yroskov** [comment]
PREVIEW release started 2023-12-07, 8:17 pm (server time)

**Comment by yroskov** [comment]
PREVIEW release started 2023-12-12, 8:14 pm (server time) _with full set of updates_

**Comment by yroskov** [comment]
- [ ] Orphan decisions  (https://github.com/CatalogueOfLife/checklistbank/issues/1333#event-11233969229)
aka new report **Stale Decisions** in CoL-3: 5312 names (COL23.12, id 281620)

https://www.checklistbank.org/catalogue/3/tasks
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/d87941da-c8dc-4f2d-95e1-4296c5fcc6dd)

woops! There is no tool to delete all these decisions in CoL-3:
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/e2390818-e6c5-4236-8fb4-f5fc31183cc1)

There is no report on orphan decisions in GSD Tasks (_Species Fungorum plus as an example_): 
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/7fa6521f-baed-4365-ac97-03541eb937c4)

**Comment by yroskov** [comment]
PREVIEW release started 2023-12-13, 9:36 pm (server time) _- cleaned up Ambig Syn decisions for Collembola.org_

**Comment by yroskov** [comment]
- [ ] Outdated decisions - _continue_ (https://github.com/CatalogueOfLife/checklistbank/issues/1333#event-11233969229)
aka new report Stale Decisions in CoL-3: 5312 names (COL23.12, id 281620)

Cleaned up names from GSDs 2023-12-14:
Collembola.org
Species Fungorum Plus
Scarabs
ThripsWiki
World Ferns
(World Plants) in progress

**Comment by yroskov** [comment]
PREVIEW release started 2023-12-15, 2:41 am (server time)

**Comment by yroskov** [comment]
For attention of @olafbanki, @mdoering: COL23.12, **id 281951**, 2023-12-15 is ready for deployment as CoL of December.

**Comment by yroskov** [comment]
Deployed to the portal 2023-12-27

**Comment by yroskov** [comment]
- [ ] Incorrect DOI for monthly update of the World Entiminae Database #606 https://github.com/CatalogueOfLife/data/issues/606
