### ISSUE TITLE
Towards 2024 Annual Checklist

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#264]
Delivery date: June 2024

_Re-synced:_ Alucitoidea, Collembola.org, Global Gracillariidae, ITIS, MOWD, Pterophoroidea, ReptileDB, Species Fungorum Plus, StaphBase, Taxapad Ichneumonoidea, TITAN, UCD, WCVP (fully updated now), WTaxa, ZOBODAT Vespoidea

**Comment by yroskov** [comment]
- [x] DUPLICATED TAXA of higher ranks

- [x] WoRMS of 2024-06-01; imported 2024-06-02; 2024-06-03 - Editors in WoRMS Nemys & MolluscaBase = OK

- [ ] ITIS = not for AC24

- [x] Scarabs received 2024-06-03; imported 2024-06-03; **synced 2024-06-03**

**_FROM TaxonWorks:_**

- [x] 3i Auchenorrhyncha imported 2024-06-03; **synced 2024-06-04**
- [x] Entiminae imported 2024-06-03; **synced 2024-06-04**
- [x] WCO (Opiliones) imported 2024-06-03; **synced 2024-06-04**
- [x] WOL (Odonata) imported 2024-06-03; **synced 2024-06-04**
- [x] SF Isoptera imported 2024-06-03; **synced 2024-06-04**
- [x] SF Orthoptera imported 2024-06-03; **synced 2024-06-04**

_monthly started from January 2024:_
- [x] SF Dermaptera imported 2024-06-03; **synced 2024-06-05**
- [x] SF Plecoptera  imported 2024-06-03; **synced 2024-06-05**
- [x] SF Psocodea  imported 2024-06-03; **synced 2024-06-05**

_monthly started from March 2024:_
- [x] SF Aphid imported 2024-06-03; **synced 2024-06-05**
- [x] SF Chrysididae imported 2024-06-03; **synced 2024-06-05**
- [x] SF Coreoidea imported 2024-06-03; **synced 2024-06-05**
- [ ] SF Lygaeoidea imported 2024-06-03; **no sync in June**
- [x] SF Mantodea imported 2024-06-03; **synced 2024-06-05**
- [x] SF Phasmida imported 2024-06-03; **synced 2024-06-05**

_single update in a year (January):~ 

~~SF Coleorrhyncha 
SF Embioptera
SF Grylloblattodea 
SF Mantophasmatodea 
SF Zoraptera~~

**_LEPIDOPTERA:_**

- [x] GLI ver 1.1.24.153 / 2024-06-01; synced 2024-06-05; ver. 0.41.1 / 2024-06-06 **re-synced  2024-06-06**
- [ ] Alucitoidea (Lepidoptera) = no new ver. on 2024-06-06
- [ ] Gelechiidae (Lepidoptera) = no new ver. on 2024-06-06
- [ ] Hepialidae (Lepidoptera)  = no new ver. on 2024-06-06
- [ ] Pterophoroidea (Lepidoptera)  = no new ver. on 2024-06-06
- [x] Sesiidae (Lepidoptera) = no new ver. on 2024-06-06; imported 2024-06-15; **synced 2024-06-17**
- [x] Geometridae (Lepidoptera) ver. 1.1.24.158 (6 Jun 2024) / 2024-06-06; **synced 2024-06-06**
- [x] Global Gracillariidae of 2024-03-15; **synced 2024-05-14** 

**_OTHER:_**

- [ ]  UCD - ask for logo

- [x] Systema Dipterorum ver. 5.2 of 2024-05-15; received 2024-05-16; imported 2024-06-01; **synced 2024-06-03**

- [x] World Ferns ver. 19.3 of 2024-05-18; imported 2024-05-21; **synced 2024-05-21**

- [x] World Plants ver. 19.3 of 2024-05-18 - changes in the classification = OK; imported 2024-05-22; **synced 2024-05-22**

- [x] Eumycetozoa.com received 2024-05-22; imported 2024-06-03; **synced 2024-06-04**

- [x] RWC: Rotifer World Catalogue ver. 1.0 / 2024-06-05 https://www.checklistbank.org/dataset/298081/about; synced 2024-06-06, **re-synced 2024-06-11**

- [x] WCVP ver 13.0 / 2024-05-16, imported 2024-06-08; **synced 2024-06-11**

- [ ] WCVP-Fabaceae 2024v.5 / 2024-05-16, imported 2024-06-05

=============================

- SF Permopsocida _is not yet in CoL_; I have submitted its adoption to the CoL Taxon Group.  (see email of 2023-11-10, Heidi)

-  ScaleNet

- WCVP ver 11.0 / 2023-04-20

- LPSN see https://github.com/CatalogueOfLife/data/issues/202#issuecomment-1970787286 . @mdoering via Slack 2024-05-06: _heard back from LPSN - they have good progress, but the API with classification will be public and usable by us at the end of May - so we might be able to get LPSN into the June release_ YR: _LPSN - good! But we have no June release. It will be AC24 in June. It's risky to publish AC24 with new dataset. Especially, without Taxonomy Group assessment of LPSN and approval of ITIS replacement. Let's do it in July-August_

- Rotifers

- FishBase - ?

- Paris/DBTNT - ?

- LDL Neuropterida


=============================

_Filling gaps:_

Suborder **Symphyta** (Hymenoptera) https://github.com/CatalogueOfLife/data/issues/579
Class/order **Diplura** https://github.com/CatalogueOfLife/data/issues/577
Order **†Permopsocida** (Insecta) https://github.com/CatalogueOfLife/data/issues/578
Family **Promecheilidae** (Tenebrionoidea, Coleoptera) https://github.com/CatalogueOfLife/data/issues/580

**Comment by yroskov** [comment]
**Duplicated taxa**

TASKS, 2024-05-23:
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/ccc66562-2b19-41a4-b46f-f32fa09e953f)

- [x] [Identical family 19](https://www.checklistbank.org/dataset/3/duplicates?_colCheck=b3): 11 of 19 cases WoRMS Mollusca vs PaleoBioDB (check for genera first)
WoRMS Mollusca:  superorder †Ammonoida Haeckel, 1866 with 3 spp = BLOCKED 2024-05-23, re-synced
PaleoBioDB: order †Ammonoidea with 9488 spp
3 cases remain unresolved on 2024-05-31.
1 case remains on 2024-06-04 (Systema Dipterorum re-synced 2024-06-04).

- [x] Identical subfamilies, 18 https://www.checklistbank.org/catalogue/3/duplicates?catalogueKey=3&category=uninomial&codeDifferent=false&limit=50&offset=0&rank=supergenus&rank=suprageneric%20name&rank=subtribe&rank=infratribe&rank=tribe&rank=supertribe&rank=infrafamily&rank=family&rank=subfamily&rank=epifamily&rank=grandfamily&rank=superfamily&rank=megafamily&rank=gigafamily&rank=subsection%20zoology&rank=supersection%20zoology&rank=section%20zoology&rank=falanx&rank=parvorder&rank=infraorder&rank=suborder&rank=minorder&rank=hypoorder&rank=order&rank=superorder&rank=nanorder&rank=grandorder&rank=magnorder&rank=mirorder&rank=infracohort&rank=gigaorder&rank=subcohort&rank=cohort&rank=phylum&rank=subphylum&rank=superphylum&rank=infraphylum&rank=parvphylum&rank=superclass&rank=class&rank=subclass&rank=infraclass&rankDifferent=false&status=accepted&withDecision=false
= RESOLVED 2024-06-04

- [x] [Identical tribe 2](https://www.checklistbank.org/dataset/3/duplicates?_colCheck=b6)  = RESOLVED
Re-synced StaphBase, Collembola.org 

- [x] [Identical genus 2404](https://www.checklistbank.org/dataset/3/duplicates?_colCheck=b4)

- [x] Identical species [ACC-ACC species (same authors) 251](https://www.checklistbank.org/dataset/3/duplicates?_colCheck=c2)
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/0d200a87-0b81-4c32-9e49-6f4e59c6502a)
3 duplicated paleospecies across Species Files = DELETED in Grylloblattodea:
Alekhosara reticulata Aristov, 2008 in Grylloblattodea and in Orthoptera
Palaeomesorthopteron pullus Aristov, Grauvogel-Stamm & Marchal-Papier, 2011 in Grylloblattodea and in Embioptera
Thaumatophora pronotalis Riek, 1976 in Grylloblattodea and in Plecoptera
3 duplicated species in [WFO Plant List 2023-12](https://www.checklistbank.org/dataset/2004/taxon/wfo-0001091673-2023-12) Larix czekanowskii, Picea fennica & Pinus hakkodensis = DELETED in the project Tree (Assembly)

**2024-06-05:**
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/9d9cdf87-fb7c-4660-9ac6-5947ac5694c4)
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/30450053-9773-46c5-aa65-1226e60ebaee)



- [ ] [Manuscript names 912](https://www.checklistbank.org/dataset/3/workbench?nomstatus=manuscript&limit=50) = Error 404
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/11aaf5ae-1029-4be8-a5ad-b3c261565ccf)

**Comment by yroskov** [comment]
- [x] Config Title changed 2024-05-29
[project] - Options - Edit [Settings]:
Was:
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/82ef8188-1899-4290-9f13-ff2542dbef5e)
Changed as:
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/467466f5-f117-4eb0-bcda-56399735c2fa)

**Comment by yroskov** [comment]
@aoern, we are preparing 2024 Annual Checklist in June. Would you be able to run your checks BEFORE final release? I am going to close first draft by 10-11th June. If I send you a link to the interim version in COLDP, would you be so kind to do checks?

**Comment by aoern** [comment]
Yes, of course! Ariyroskov ***@***.***> kirjoitti 30.5.2024 kello 23.40:﻿
@aoern, we are preparing 2024 Annual Checklist in June. Would you be able to run your checks BEFORE final release? I am going to close first draft by 10-11th June. If I send you a link to the interim version in COLDP, would you be so kind to do checks?

**Comment by yroskov** [comment]
PREVIEW release started 2024-05-31, 12:54 pm (server time)
Finished as Annual Checklist 2024, id [297740](https://www.checklistbank.org/dataset/297740/about), 2024-05-31, 2:16 pm
Deployed to the preview website 2024-05-31

CHECKS

- [x] Title alias: OK
- [ ] Recommended citation: Bánki... (2024). **Catalogue of Life Checklist (Annual Checklist 2024). Catalogue of Life.** https://doi.org/10.48580/dg82x = has no much sense = for attention of @olafbanki

**Comment by yroskov** [comment]
- [x] Incorrect names in Species Fungorum https://github.com/CatalogueOfLife/data/issues/659 = FIXED 2024-05-31
**Re-synced 2024-05-31**

**Comment by yroskov** [comment]
- [x] Self-synonymized taxa in UCD https://github.com/CatalogueOfLife/data/issues/660
2024-05-31: resolved up to Centrodora oophagus
2024-06-03: fixed & re-synced 2024-06-03

**Comment by yroskov** [comment]
PREVIEW release started 2024-06-04, 4:21 pm (server time)
Finished as Annual Checklist 2024, id [298077](https://www.checklistbank.org/dataset/298077/about), 2024-06-04, 5:46 pm
Deployed to the preview website 2024-06-04

_See duplicated uninomial taxa_ (Systema Dipterorum  & GLI need to be re-synced)

**Comment by yroskov** [comment]
- [x] World Plants overlapped with RJB Geranium = FIXED 2024-06-04. WP Geraniaceae re-synced.

**Comment by yroskov** [comment]
PREVIEW release started 2024-06-05, 10:11 pm (server time)
Finished as Annual Checklist 2024, id [298097](https://www.checklistbank.org/dataset/298097/about), 2024-06-05
Deployed to the preview website 2024-06-06

**Comment by yroskov** [comment]
PREVIEW release started 2024-06-06, 3:44 pm (server time)
Finished as Annual Checklist 2024, id [298177](https://www.checklistbank.org/dataset/298177/about), 2024-06-06
Deployed to the preview website 2024-06-06

**Comment by yroskov** [comment]
PREVIEW release started 2024-06-06, 6:45 pm (server time)
Finished as Annual Checklist 2024, id [298184](https://www.checklistbank.org/dataset/298184/about), 2024-06-06, 8:18 pm
Deployed to the preview website 2024-06-07

_with RWC_

**Comment by yroskov** [comment]
See https://github.com/CatalogueOfLife/data/issues/668
https://github.com/CatalogueOfLife/data/issues/669#event-13080073794
https://github.com/CatalogueOfLife/data/issues/667#issuecomment-2155102700


2024-06-07, require re-sync: 
Systema Dipterorum = re-synced 2024-06-07
ReptileDB (re-check TASKS, sectors, classification) = re-synced 2024-06-07
WCVP = re-synced 2024-06-07. ATTENTION: merge sector detected:
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/1d543865-beb6-49cc-b5ce-2b0b17e1c009)

**Comment by yroskov** [comment]
CoL TASKS of 2024-06-07:
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/07b5cd9e-d062-48f3-8228-7f97572afece)
https://www.checklistbank.org/catalogue/3/tasks

@mdoering, that is very much wrong. (You'll understand the problem when open ACC-ACC species (different authors) 36349 or ACC-ACC species (same authors) 47911)

So far, [298184](https://www.checklistbank.org/dataset/298184/about) is a best candidate for AC24.

**Comment by mdoering** [comment]
any idea where that is coming from? SD syncs?

**Comment by yroskov** [comment]
@mdoering, it was happened after I applied some "polishing" in AC24 draft and completed re-syncs of 3 GSDs:
_Systema Dipterorum = re-synced 2024-06-07
ReptileDB (re-check TASKS, sectors, classification) = re-synced 2024-06-07 
WCVP = re-synced 2024-06-07_ 

As I can see, the main problem caused by WCVP. I did re-sync of all global sectors one-by-one, because I saw "merge sector" in the list of sectors. Results look awful: WCVP species duplicated World Plants, but allocated in wrong families. I believe, it happened due to changed IDs (but I have re-synced the same version of WCVP which was used before (according to metadata) and all sectors were shown as healthy).

_Species statistics comparison (Preview 2024-06-06 (id 298184) = before WCVP sync, i.e. as it should be:_
  | Project3 | Preview 2024-06-06 (id 298184)
-- | -- | --
Tracheophyta | 415458 | 359898
Liliopsida | 88508 | 81334
Magnoliopsida | 311532 | 263146
Ginkgoopsida | 333 | 333
Pinopsida | 833 | 833
Polypodiopsida | 12392 | 12392

**Comment by mdoering** [comment]
I have an idea of what goes wrong with WCVP. They do not have stable family identifiers and the same identifier can point to a different family next time.
If we rematch all WCVP sectors and resync afterwards it should be fine again

**Comment by yroskov** [comment]
How to do rematch for WCVP?

**Comment by mdoering** [comment]
https://api.checklistbank.org/dataset/3/sector/1698
>"subjectDatasetKey":2232,
"subject":{
"id":"xS",
"name":"Rubiaceae",
"rank":"family",
"status":"accepted",
"broken":false,
"label":"Rubiaceae",
"labelHtml":"Rubiaceae",
}

but xS points to [Campanulaceae](https://api.checklistbank.org/dataset/2232/taxon/xS).

**Comment by mdoering** [comment]
rematching via UI does not help, let me see how we can best address this one...

**Comment by yroskov** [comment]
For attention of @olafbanki & @mdoering:

In a case if Markus meet problems with the Project3 cleaning from unwanted WCVP records which were synced on 2024-06-07, **the candidate of 2024-06-06 for the 2024 Annual Checklist is ready in CLB** with id [298184](https://www.checklistbank.org/dataset/298184/about).

Its preview is here https://preview.catalogueoflife.org/data/metadata 

_(If fixes will be successful, RWC import of 2024-06-10 should be re-synced = RWC SYNCED 2024-06-11)_.

**Comment by mdoering** [comment]
@yroskov I rematched all 111 WCVP sectors and mostly they updated fine:

> {"broken":13,"updated":96,"unchanged":2,"total":111}

But there are [13 broken sectors](https://www.checklistbank.org/catalogue/3/sector?broken=true&limit=100&mode=attach&offset=0&subjectDatasetKey=2232) now which I will try to solve manually through the UI.

<img width="1006" alt="image" src="https://github.com/CatalogueOfLife/testing/assets/327505/33d1ff26-45ec-4d1b-aff6-80ad3e1a9954">

**Comment by mdoering** [comment]
I simply matched again and resolved all sectors now:
> {"broken":1,"updated":12,"unchanged":98,"total":111}

The reason not all rematched fine in the beginning was that we cannot have 2 sectors with the same subject - and because IDs were wrong some ids were already (falsely) taken and the rematch failed. Doing it a second time removed that problem.

The single sector still reported as broken is the merge sector without any subject - I will see that we change the reporting to exclude those

**Comment by mdoering** [comment]
@yroskov I will trigger syncs now for all of WCVP to replace the bad data

**Comment by yroskov** [comment]
Thanks! Go ahead

**Comment by yroskov** [comment]
WCVP syncs completed. Tasks in Project 3:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/50cc2859-a5a6-40c3-969a-5280c9c03f02)

@mdoering, TASKS in Project 3 look good after the cleanings. 
But species number in Tracheophyta show 2,818 extra species comparing with expected number as in Preview 2024-06-06 (id 298184):

  | Preview 2024-06-06 (id 298184) | Project3_before cleaning | Project3_after cleaning |  
-- | -- | -- | -- | --
Tracheophyta | 359898 | 415458 | 362716 | +2,818
Liliopsida | 81334 | 88508 | 83494 | +2,160
Magnoliopsida | 263146 | 311532 | 263804 | +658
Ginkgoopsida | 333 | 333 | 333 | =
Pinopsida | 833 | 833 | 833 | =
Polypodiopsida | 12392 | 12392 | 12392 |  =

On my end, I cannot find and check these unexpected extra species.

**Comment by mdoering** [comment]
well, it is a newer version of WCVP. The 298184 preview used data synced from [WCVP attempt 17-18](https://www.checklistbank.org/dataset/298184/source/2232), version `10.0 / 2022-10-27`
The [current](https://www.checklistbank.org/catalogue/3/dataset/2232/metadata) is version `13.0 / 2024-05-16`

The entire [current WCVP has 365.790 species](https://www.checklistbank.org/dataset/2232/imports), the older version [10 (attempt 18) had 357.450 species](https://www.checklistbank.org/dataset/2232/imports/18).

**Comment by yroskov** [comment]
Thanks! That's explains difference.

**Comment by mdoering** [comment]
WCVP Tracheophyta species counts are
 - [121.178 in 298184 preview](https://www.checklistbank.org/dataset/298184/names?TAXON_ID=TP&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&rank=species&sectorDatasetKey=2232&sortBy=taxonomic&status=accepted&status=provisionally%20accepted)
 - [123.996 in current project](https://www.checklistbank.org/catalogue/3/names?TAXON_ID=bfb709db-491c-48b6-80f5-32ef14f63e4f&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&rank=species&sectorDatasetKey=2232&sortBy=taxonomic&status=accepted&status=provisionally%20accepted)

So WCVP species in COL have increased by 2.818 just as you have observed. In the entire WCVP dataset the increase was 8.340 species, but we only use parts of it.

**Comment by mdoering** [comment]
btw, the [WCVP Fabaceae](https://www.checklistbank.org/dataset/2304/imports) people have also updated their annual version some weeks ago. Do you foresee a problem to sync that one also?

<img width="667" alt="image" src="https://github.com/CatalogueOfLife/testing/assets/327505/cf92baac-333e-4d7e-8316-483ebd1d6cfb">

new 2024 version available:
<img width="588" alt="image" src="https://github.com/CatalogueOfLife/testing/assets/327505/9cfe216d-1b6f-4b64-a2d4-2871939183b1">


2023 version we use:
<img width="599" alt="image" src="https://github.com/CatalogueOfLife/testing/assets/327505/60aaa67b-d49a-4a4e-bf12-40b8cce3fa2b">

**Comment by yroskov** [comment]
WCVP-Fabaceae: ...Do you foresee a problem to sync that one also?

Unfortunately, yes. Two issues: [Broken decisions: 4308](https://www.checklistbank.org/catalogue/3/decision?broken=true&limit=100&offset=0&subjectDatasetKey=2304) and nested WWW genera need to be re-done.

Let see, what we can do on a week of 17th June

**Comment by mdoering** [comment]
update decisions for ambiguous synonyms are a lot of work. Maybe we should think about flagging them automatically if another synonym with the same name exists in a dataset. Then we could remove the entire status, have just synonyms and make our work a little bit simpler.

**Comment by yroskov** [comment]
...update decisions for ambiguous synonyms

This depends on data "quality" in the checklist imported in CLB: some GSD have very simple cases which can be easily resolved automatically; others need investigation on what was happened (chresonym is only one case). It would be nice if we succeed to classify such cases and work out protocols.

**Comment by yroskov** [comment]
PREVIEW release started 2024-06-17, 4:43 pm (server time)
(_First PREVIEW after fixes in WCVP sectors & re-sync_) 
Finished as Annual Checklist 2024, id [298597](https://www.checklistbank.org/dataset/298597/about), 2024-06-17, 6:19 pm
Deployed to the preview website 2024-06-17

**Comment by yroskov** [comment]
Dear @aoern,

I would believe, we have completed our first "proof" of the 2024 Annual Checklist now (https://preview.catalogueoflife.org/).    

Here is its CoLDP export [https://urldefense.com/v3/__https://download.checklistbank.org/job/f0/f0fec354-bc73-4352-8f22-eaef1d246b4f.zip__;!!DZ3fjg!6N3jNoLLrkKddZmy9RWHZX3aD6T-3rAyB4OcdnZWyGkiGVihO7z4AVDlg0qof2pEM0BjAwiCLOGRENi83ccQ2EbezU0$](https://urldefense.com/v3/__https:/download.checklistbank.org/job/f0/f0fec354-bc73-4352-8f22-eaef1d246b4f.zip__;!!DZ3fjg!6N3jNoLLrkKddZmy9RWHZX3aD6T-3rAyB4OcdnZWyGkiGVihO7z4AVDlg0qof2pEM0BjAwiCLOGRENi83ccQ2EbezU0$)  [700.6 MB]

Could you please do your routine checks? Do not dig too deep. We'll have a few days to fix only real disaster (if there is one).

**Comment by aoern** [comment]
I am able to download it tomorrow and start checking. Ariyroskov ***@***.***> kirjoitti 18.6.2024 kello 16.49:﻿
Dear @aoern,
I would believe, we have completed our first "proof" of the 2024 Annual Checklist now (https://preview.catalogueoflife.org/).
Here is its CoLDP export https://urldefense.com/v3/https://download.checklistbank.org/job/f0/f0fec354-bc73-4352-8f22-eaef1d246b4f.zip;!!DZ3fjg!6N3jNoLLrkKddZmy9RWHZX3aD6T-3rAyB4OcdnZWyGkiGVihO7z4AVDlg0qof2pEM0BjAwiCLOGRENi83ccQ2EbezU0$  [700.6 MB]
Could you please do your routine checks? Do not dig too deep. We'll have a few days to fix only real disaster (if there is one).

**Comment by yroskov** [comment]
- [x] Ari, 2024-06-19: _The Id of >620.000 names have been changed from good old 5-character id's to 22-character monster strings._
https://github.com/CatalogueOfLife/data/issues/676

= FIXED 2024-06-21 (MD: _To fix the problem I have rematched the entire project and there is no missing match any longer. Doing a new release now_)

**Comment by yroskov** [comment]
New **release of 2024-06-21** completed by Markus id [298708](https://www.checklistbank.org/dataset/298708/about)
Deployed to the preview website 2024-06-21

CHECKS of 2024-06-21:
- [x] GSD stats = OK

- [x] Incorrect GSD version in Source Datasets page (says "Annual Checklist 2024" for all GSDs instead of individual versions of GSDs) - for attention of @mdoering  = FIXED 2024-06-24
https://preview.catalogueoflife.org/data/source-datasets
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/2021bd47-c253-4f11-8c84-f7f7f7b16fc4)

https://github.com/CatalogueOfLife/backend/issues/1333
also https://github.com/CatalogueOfLife/portal/issues/213

- [x] GSD version is missing in the recommended bibliographic citation (important!):
for example: https://preview.catalogueoflife.org/data/dataset/2207
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/b95b313e-4eab-4c2f-9fd6-8d523032f534)

https://github.com/CatalogueOfLife/portal/issues/212

**Comment by yroskov** [comment]
PREVIEW release started by Markus 2024-06-24, 1:46 pm (server time)
(_After https://github.com/CatalogueOfLife/backend/issues/1333#issuecomment-2186627873_)
Finished as Annual Checklist 2024, id [298863](https://www.checklistbank.org/dataset/298863/about), 2024-06-24, 3:12 pm
Deployed to the preview website 2024-06-24

CHECKS of 2024-06-24:

- [x] Incorrect GSD version in Source Datasets page = FIXED
- [x] GSD version is still missing in the recommended bibliographic citation = @mdoering, the GSD version is important in the bibliographic citation. Old version of GSD might be re-published in the CoL from one month/yeat to the next, and we need to indicate which version is in use in the each edition of the CoL. 
Agreed solution: version should become a part of the GSD Title in the citation; put it in brackets after the title, e.g. _UCD Community. (2024). Universal Chalcidoidea Database curated in TaxonWorks **(version May 2024)**. In O. Bánki..._  
- [x] Taxonomic Coverage (taxon & classification string) is missing now in a set of GSD metaadata (N/A value appears) = FIXED (2024-06-25)
_for example:_
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/159975c7-37c0-4b0d-b1a1-7c8f9e563410)
https://preview.catalogueoflife.org/data/dataset/1061
https://preview.catalogueoflife.org/data/dataset/1169
https://preview.catalogueoflife.org/data/dataset/1089
https://preview.catalogueoflife.org/data/dataset/1065
https://preview.catalogueoflife.org/data/dataset/1204
https://preview.catalogueoflife.org/data/dataset/1101
etc.

- [x] Sync of SF Plecoptera was cancelled (!) on 2024-06-05. Re-synced 2024-06-24. Requires re-release.

- [x] @gdower, UCD metadata are empty in CLB, could you please fix this = FIXED 2024-06-25 
https://preview.catalogueoflife.org/data/dataset/124661
https://www.checklistbank.org/dataset/124661/about

**Comment by yroskov** [comment]
- [x] https://github.com/CatalogueOfLife/data/issues/679
Sector **class Myxozoa** deleted. Two **classes Malacosporea & Myxosporea** established as new sectors. Re-synced 2024-06-25.

**Comment by yroskov** [comment]
PREVIEW release started 2024-06-25, 3:45 pm (server time)
Finished as Annual Checklist 2024, id [298890](https://www.checklistbank.org/dataset/298890/about), 2024-06-25, 5:11 pm
Deployed to the preview website 2024-06-25

**Comment by yroskov** [comment]
PREVIEW release started 2024-06-25, 6:30 pm (server time)
(_check list of GSDs_)
Finished as Annual Checklist 2024, id [298894](https://www.checklistbank.org/dataset/298894/about), 2024-06-25, 8:09 pm
Deployed to the preview website 2024-06-25

- [x] Version in all WoRMS checklists appears as "ver. (06/2024)" = FIXED 2024-06-25 as "06/2024" & will be also corrected in the next export.

**Comment by yroskov** [comment]
PREVIEW release started 2024-06-25, 8:41 pm (server time)
Finished as Annual Checklist 2024, id [298904](https://www.checklistbank.org/dataset/298904/about), 2024-06-25
Deployed to the preview website 2024-06-26

**Comment by mdoering** [comment]
@yroskov @gdower the UCD metadata contains 2 paragraphs of lists of contributors. That should really be in the contributors sections, thats exactly what its for:
> List of Active Curators: Roger Burks (site designer) Newport Beach, CA, USA; Lucian Fusu, Al. I. Cuza University, Iasi, Romania; D. Christopher Darling, Royal Ontario Museum, Toronto, ON, Canada; John Heraty, University of California, Riverside, CA, USA; Petr Janšta, Charles University, Prague, Czech Republic; Mircea-Dan Mitroiu, Al. I. Cuza University, Iasi, Romania; Pâmella Machado Saguiah, Ciências Biológicas pela Universidade Federal do Espírito Santo, Brazil; Natalie Dale-Skey, The Museum of Natural History, London, United Kingdom; James B. Woolley, Texas A&M University, College Station, TX, USA
>TaxonWorks Development and Outreach Team: Matt Yoder, Dmitry Dmitriev, José Luis Pereira, Hernán Lucas Pereira, Deborah Paul.

The description also contains species numbers which quickly get out of date. I would propose to remove that sentence as we already have more than 31.000 species than mentioned:
> As of today, the UCD contains 27968 valid species (including some subspecies) and 2295 valid genera (including some subgenera).

**Comment by yroskov** [comment]
UCD metadata will stay as they are now, until UCD group change their mind and text on the website.

**Comment by yroskov** [comment]
Dear @olafbanki, the dataset id [298904](https://www.checklistbank.org/dataset/298904/about) of 2024-06-25 is finalized now as 2024 Annual Checklist.

**Comment by mdoering** [comment]
> UCD metadata will stay as they are now, until UCD group change their mind and text on the website.

But it's not good practice the way it is

**Comment by yroskov** [comment]
I'll pass your concerns to UCD team ;)
in July

**Comment by olafbanki** [comment]
The AC2024 has been published!

**Comment by yroskov** [comment]
Many thanks. Congratulations!

(for the memory: id [299029](https://www.checklistbank.org/dataset/299029/about) of 2024-06-27)

**Comment by yroskov** [comment]
Just in case, recommended citations for GSDs on this page of the portal https://www.catalogueoflife.org/about/colusage#recommended-citations **do not include Catalogue of Life portion** at all. It would be better if the citation style on this page matches the citation style on the GSD page https://www.catalogueoflife.org/data/dataset/1161

Brinda, J. C., & Atwood, J. J. (2024). Bryophyte Nomenclator (14 May 2024). https://doi.org/10.48580/dg6lk-8zmp
vs
Brinda, J. C., & Atwood, J. J. (2024). Bryophyte Nomenclator (version 14 May 2024). _In O. Bánki, Y. Roskov, M. Döring, G. Ower, D. R. Hernández Robles, C. A. Plata Corredor, T. Stjernegaard Jeppesen, A. Örn, L. Vandepitte, D. Hobern, P. Schalk, R. E. DeWalt, K. Ma, J. Miller, T. Orrell, R. Aalbu, J. Abbott, R. Adlard, C. Aedo, et al., Catalogue of Life (Annual Checklist 2024). Catalogue of Life, Amsterdam, Netherlands._ https://doi.org/10.48580/dg6lk-8zmp
