### ISSUE TITLE
CoL of July 2024

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#265]
- [x] WoRMS of 2024-07-01 (see ver); imported 2024-07-03; **synced 2024-07-03**
Version / Issued 2024-07-01 / 2024-07-01

- [x] ITIS of 2024-06-26; imported 2024-07-01; barrier https://github.com/CatalogueOfLife/testing/issues/8#issuecomment-2207227175; **synced 2024-07-08**

- [x] Scarabs 2024-07-08; imported 2024-07-08; **synced 2024-07-08**

**_FROM TaxonWorks:_**

- [x] 3i Auchenorrhyncha https://github.com/CatalogueOfLife/testing/issues/135 imported 2024-07-05; **sinced 2024-07-15**
- [x] Entiminae https://github.com/CatalogueOfLife/testing/issues/128 imported 2024-07-05; **sinced 2024-07-16**
- [x] WCO (Opiliones) https://github.com/CatalogueOfLife/testing/issues/13 imported 2024-07-05; **sinced 2024-07-16**
- [x] WOL (Odonata) https://github.com/CatalogueOfLife/testing/issues/215 imported 2024-07-05; **sinced 2024-07-15**
- [x] SF Isoptera https://github.com/CatalogueOfLife/testing/issues/171 imported 2024-07-05; **sinced 2024-07-15**
- [x] SF Orthoptera https://github.com/CatalogueOfLife/testing/issues/166 imported 2024-07-05; **sinced 2024-07-16**

_monthly started from January 2024:_
- [x] SF Dermaptera https://github.com/CatalogueOfLife/testing/issues/155 imported 2024-07-05; **sinced 2024-07-17**
- [x] SF Plecoptera https://github.com/CatalogueOfLife/testing/issues/158 imported 2024-07-05; **sinced 2024-07-17**
- [x] SF Psocodea https://github.com/CatalogueOfLife/testing/issues/160 imported 2024-07-05; **sinced 2024-07-17**

_monthly started from March 2024:_
- [x] SF Aphid https://github.com/CatalogueOfLife/testing/issues/172 imported 2024-07-05; **sinced 2024-07-17**
- [x] SF Chrysididae https://github.com/CatalogueOfLife/testing/issues/164 imported 2024-07-05; **sinced 2024-07-17**
- [x] SF Coreoidea https://github.com/CatalogueOfLife/testing/issues/167 imported 2024-07-05; **sinced 2024-07-17**
- [x] SF Lygaeoidea https://github.com/CatalogueOfLife/testing/issues/168 imported 2024-07-05; **sinced 2024-07-17**
- [x] SF Mantodea https://github.com/CatalogueOfLife/testing/issues/169 imported 2024-07-05; **sinced 2024-07-17**
- [x] SF Phasmida https://github.com/CatalogueOfLife/testing/issues/170 imported 2024-07-05; **sinced 2024-07-17**

_single update in a year (January):_ 

~~SF Coleorrhyncha 
SF Embioptera
SF Grylloblattodea 
SF Mantophasmatodea 
SF Zoraptera~~

**_LEPIDOPTERA:_**

- [x] GLI https://github.com/CatalogueOfLife/testing/issues/195 imported 2024-07-16; **synced 2024-07-18**
- [x] Alucitoidea (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/255 imported 2024-07-04; **synced 2024-07-18**
- [ ] Gelechiidae (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/198 = no new ver. on 2024-07-18
- [ ] Hepialidae (Lepidoptera)  https://github.com/CatalogueOfLife/testing/issues/240 = no new ver. on 2024-07-18
- [x] Pterophoroidea (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/179 imported 2024-07-17; **synced 2024-07-18**
- [x] Sesiidae (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/228 imported 2024-06-15; **synced 2024-06-17**
- [ ] Geometridae (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/258 = no new ver. on 2024-07-18
- [x] Global Gracillariidae https://github.com/CatalogueOfLife/testing/issues/187 imported 2024-06-21; **synced 2024-07-18**

**_OTHER:_**

- [ ]  ~~UCD~~ - ask for logo with new update

- [x] WCVP-Fabaceae 2024v.5 / 2024-05-16, imported 2024-06-05; **synced 2024-07-09**

- [x] World Plants ver. 19.4, 2024-06-30; imported 2024-07-03; **synced 2024-07-08**

- [x] World Ferns ver. 19.4, 2024-06-30; imported 2024-07-08; **synced 2024-07-09**

- [ ] World List of Cycads; received 2024-07-11

- [ ] Systema Dipterorum ver. 5.3_2024-07-17

=============================

- SF Permopsocida _is not yet in CoL_; I have submitted its adoption to the CoL Taxon Group.  (see email of 2023-11-10, Heidi)

-  ScaleNet

- LPSN see https://github.com/CatalogueOfLife/data/issues/202#issuecomment-1970787286 . @mdoering via Slack 2024-05-06: _heard back from LPSN - they have good progress, but the API with classification will be public and usable by us at the end of May - so we might be able to get LPSN into the June release_ YR: _LPSN - good! But we have no June release. It will be AC24 in June. It's risky to publish AC24 with new dataset. Especially, without Taxonomy Group assessment of LPSN and approval of ITIS replacement. Let's do it in July-August_

- FishBase - ?

- Paris/DBTNT - ?

- LDL Neuropterida

=============================

_Filling gaps:_

Suborder **Symphyta** (Hymenoptera) https://github.com/CatalogueOfLife/data/issues/579
Class/order **Diplura** https://github.com/CatalogueOfLife/data/issues/577
Order **†Permopsocida** (Insecta) https://github.com/CatalogueOfLife/data/issues/578
Family **Promecheilidae** (Tenebrionoidea, Coleoptera) https://github.com/CatalogueOfLife/data/issues/580

**Comment by yroskov** [comment]
_Re-synced:_

World Plants Santalaceae 2024-07-01,

**Comment by yroskov** [comment]
- [x] Begoniaceae family was lost in the latest World Plants export. (in Cucurbitales) = FIXED in WP ver. 19.4, Jun 2024 / 2024-06-30, and in July edition

**Comment by yroskov** [comment]
https://www.checklistbank.org/catalogue/3/options: settings changed as 
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/9f088291-69a3-403e-b569-f70eee27895c)

PREVIEW release started 2024-07-09, 4:47 pm (server time)
(check title; ITIS classification inside sectors)
Finished as COL24.7, id [299638](https://www.checklistbank.org/dataset/299638/about), 2024-07-09, 6:20 pm
Deployed to the preview website 2024-07-09

CHECKS of 2024-08-7-09:

- [ ] New sources from xCoL in the list of Source Datasets at https://preview.catalogueoflife.org/data/source-datasets - for @mdoering attention
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/f7e1875a-9e8d-44e7-b400-8d5e6396a3b3)

- [x] Title: OK
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/d026c380-de0f-4c5b-aa7d-b42f9b354273)

- [x] ITIS classification inside sectors: OK. Listed rank changes do not affect CoL.

- [x] World Plants: 202,751 spp (now) vs 200,391 before = +2,360 - ? = yes (Begoniaceae 2,131)

**Comment by yroskov** [comment]
PREVIEW release started 2024-07-17, 5:39 pm (server time)
Finished as COL24.7, id [299967](https://www.checklistbank.org/dataset/299967/about), 2024-07-17, 7:05 pm
Deployed to the preview website 2024-07-17

**Comment by yroskov** [comment]
Ahead of time. @olafbanki & @mdoering, there is a high chance that CoL of July will be ready on this week, before Markus goes on vacation. I'll let you know the results for your Friday morning.

**Comment by olafbanki** [comment]
Thanks Yuri!

**Comment by yroskov** [comment]
PREVIEW release started 2024-07-18, 3:39 pm (server time)
Finished as COL24.7, id [300004](https://www.checklistbank.org/dataset/300004/about), 2024-07-18, 5:13 pm
Deployed to the preview website 2024-07-18

- [x] Alien sources are present in the list of Source Datasets https://preview.catalogueoflife.org/data/source-datasets = _for attention of @thomasstjerne or @mdoering_  

![image](https://github.com/user-attachments/assets/80bc1588-edd2-4ed9-b8a7-b02163906183)

**Comment by yroskov** [comment]
For attention of @olafbanki & @mdoering: COL24.7, id [300004](https://www.checklistbank.org/dataset/300004/about) is ready  as CoL of July.

(See the bug with "alien sources" in the list of Source Datasets reported above)

**Comment by mdoering** [comment]
published

**Comment by olafbanki** [comment]
Blog post made

**Comment by redewalt** [comment]
Congratulations on getting the next iteration out.

R. Edward DeWalt
University of Illinois
Illinois Natural History Survey
1816 S Oak St.
Champaign, Illinois 61820
***@***.***
217-649-7414
________________________________
