### ISSUE TITLE
CoL of August 2024

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#266]
- [x] WoRMS of 2024-08-01; imported 2024-08-02; **synced 2024-08-03**

- [x] ITIS of 2024-07-23; imported 2024-08-05; **synced 2024-08-06**
 
- [x] Scarabs of 2024-08-05; imported 2024-08-05; **synced 2024-08-06**

**_FROM TaxonWorks:_**

- [x] 3i Auchenorrhyncha https://github.com/CatalogueOfLife/testing/issues/135; imported 2024-08-06; **synced 2024-08-07**
- [x] Entiminae https://github.com/CatalogueOfLife/testing/issues/128; imported 2024-08-06; **synced 2024-08-07** 
- [x] WCO (Opiliones) https://github.com/CatalogueOfLife/testing/issues/13; imported 2024-08-06; **synced 2024-08-08** 
- [x] WOL (Odonata) https://github.com/CatalogueOfLife/testing/issues/215; imported 2024-08-06; **synced 2024-08-08**   
- [x] SF Isoptera https://github.com/CatalogueOfLife/testing/issues/171; imported 2024-08-06; **synced 2024-08-09**   
- [x] SF Orthoptera https://github.com/CatalogueOfLife/testing/issues/166; imported 2024-08-06; **synced 2024-08-09**  

_monthly started from January 2024:_
- [x] SF Dermaptera https://github.com/CatalogueOfLife/testing/issues/155; imported 2024-08-06; **synced 2024-08-12**  
- [x] SF Plecoptera https://github.com/CatalogueOfLife/testing/issues/158; imported 2024-08-06; **synced 2024-08-12**
- [x] SF Psocodea https://github.com/CatalogueOfLife/testing/issues/160; imported 2024-08-06; **synced 2024-08-12**

_monthly started from March 2024:_
- [x] SF Aphid https://github.com/CatalogueOfLife/testing/issues/172; imported 2024-08-06; **synced 2024-08-13**
- [x] SF Chrysididae https://github.com/CatalogueOfLife/testing/issues/164; imported 2024-08-06; **synced 2024-08-13**
- [x] SF Coreoidea https://github.com/CatalogueOfLife/testing/issues/167; imported 2024-08-06; **synced 2024-08-13**
- [x] SF Lygaeoidea https://github.com/CatalogueOfLife/testing/issues/168; imported 2024-08-06; **synced 2024-08-13**
- [x] SF Mantodea https://github.com/CatalogueOfLife/testing/issues/169; imported 2024-08-06; **synced 2024-08-15**
- [x] SF Phasmida https://github.com/CatalogueOfLife/testing/issues/170; imported 2024-08-06; **synced 2024-08-15**

_single update in a year (January):_ 

~~SF Coleorrhyncha 
SF Embioptera
SF Grylloblattodea 
SF Mantophasmatodea 
SF Zoraptera~~

**_LEPIDOPTERA:_**

- [ ] GLI https://github.com/CatalogueOfLife/testing/issues/195 = no new ver. on 2024-08-19
- [ ] Alucitoidea (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/255 = no new ver. on 2024-08-19
- [x] Gelechiidae (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/198; imported 2024-08-14; **synced 2024-08-19**
- [ ] Hepialidae (Lepidoptera)  https://github.com/CatalogueOfLife/testing/issues/240 = no new ver. on 2024-08-19
- [x] Pterophoroidea (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/179; imported 2024-08-02; **synced 2024-08-19**
- [ ] Sesiidae (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/228 = no new ver. on 2024-08-19 
- [ ] Geometridae (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/258 = no new ver. on 2024-08-19
- [x] Global Gracillariidae https://github.com/CatalogueOfLife/testing/issues/187; ver. 2024-07-01 / 2024-07-01; imported 2024-07-21; **synced 2024-08-19**

**_OTHER:_**

- [ ]  ~~UCD~~ - ask for logo with new update

- [x] World List of Cycads; received 2024-07-11; imported  2024-08-14; **synced 2024-07-15**

- [x] Systema Dipterorum ver. 5.3_2024-07-17; imported 2024-08-12; **synced 2024-08-22**

=============================

- SF Permopsocida _is not yet in CoL_; I have submitted its adoption to the CoL Taxon Group.  (see email of 2023-11-10, Heidi)

-  ScaleNet

- LPSN see https://github.com/CatalogueOfLife/data/issues/202#issuecomment-1970787286 . @mdoering via Slack 2024-05-06: _heard back from LPSN - they have good progress, but the API with classification will be public and usable by us at the end of May - so we might be able to get LPSN into the June release_ YR: _LPSN - good! But we have no June release. It will be AC24 in June. It's risky to publish AC24 with new dataset. Especially, without Taxonomy Group assessment of LPSN and approval of ITIS replacement. Let's do it in July-August_
Markus Göker, 2024-08-22: _I presume, however, that we can finish the API in September [2024]._

- FishBase - ?

- Paris/DBTNT - ?

- LDL Neuropterida

=============================

_Filling gaps:_

Suborder **Symphyta** (Hymenoptera) https://github.com/CatalogueOfLife/data/issues/579
Class/order **Diplura** https://github.com/CatalogueOfLife/data/issues/577
Order **†Permopsocida** (Insecta) https://github.com/CatalogueOfLife/data/issues/578
Family **Promecheilidae** (Tenebrionoidea, Coleoptera) https://github.com/CatalogueOfLife/data/issues/580

**Comment by yroskov** [comment]
PREVIEW release started 2024-08-12, 7:00 pm (server time)
Finished as COL24.8, id [301450](https://www.checklistbank.org/dataset/301450/about), 2024-08-12, 6:58 pm
Deployed to the preview website 2024-08-12

**Comment by yroskov** [comment]
PREVIEW release started 2024-08-15, 6:57 pm (server time)
Finished as COL24.8, id [301523](https://www.checklistbank.org/dataset/301523/about), 2024-08-15
Deployed to the preview website 2024-08-16

- [x] Incorrect Alias for cycad checklist in the PREVIEW. = FIXED 2024-08-16, metadata patch adjusted  
![image](https://github.com/user-attachments/assets/b5e4836a-65e4-4616-885d-6e099006a59e)

**Comment by yroskov** [comment]
PREVIEW release started 2024-08-16, 12:51 pm (server time)
Finished as COL24.8, id [301531](https://www.checklistbank.org/dataset/301531/about), 2024-08-12, 8:27 pm
Deployed to the preview website 2024-08-16

- [x] WLoC is submitted to Michael for the review (metadata!).

**Comment by yroskov** [comment]
PREVIEW release started 2024-08-19, 2:09 pm (server time)
**FAILED**
![image](https://github.com/user-attachments/assets/f27d877c-33e3-4554-ac4a-ae0d3a04e753)

**Comment by yroskov** [comment]
PREVIEW release started 2024-08-20, 1:13 pm (server time)
Finished as COL24.8, id [301619](https://www.checklistbank.org/dataset/301619/about), 2024-08-20, 3:01 pm
Deployed to the preview website 2024-08-20

**Comment by yroskov** [comment]
PREVIEW release started 2024-08-22, 7:03 pm (server time)
Finished as COL24.8, id [301667](https://www.checklistbank.org/dataset/301667/about), 2024-08-22
Deployed to the preview website 2024-08-23

**Comment by yroskov** [comment]
For attention of @olafbanki & @mdoering: COL24.8, id [301667](https://www.checklistbank.org/dataset/301667/about) is ready now as CoL of August.

**Comment by yroskov** [comment]
2024-08-30: observed on production.

Another version [301819](https://www.checklistbank.org/dataset/301819/about) of 2024-08-29 was deployed without my knowledge
