### ISSUE TITLE
CoL of September 2024

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#269]
- [x] WoRMS of 2024-09-01; imported 2024-09-02; **synced 2024-09-03**

- [x] ITIS of 2024-08-16; imported 2024-09-03; **synced 2024-09-11** 
 
- [x] Scarabs of 2024-09-03; imported 2024-09-03; **synced 2024-09-11**

**_FROM TaxonWorks:_**

- [x] 3i Auchenorrhyncha https://github.com/CatalogueOfLife/testing/issues/135; imported 2024-09-06; **synced 2024-09-12**
- [x] Entiminae https://github.com/CatalogueOfLife/testing/issues/128; imported 2024-09-06; **synced 2024-09-12**
- [x] WCO (Opiliones) https://github.com/CatalogueOfLife/testing/issues/13; imported 2024-09-06; **synced 2024-09-13**
- [x] WOL (Odonata) https://github.com/CatalogueOfLife/testing/issues/215; imported 2024-09-06; **synced 2024-09-13**
- [x] SF Isoptera https://github.com/CatalogueOfLife/testing/issues/171; imported 2024-09-06; **synced 2024-09-13**
- [x] SF Orthoptera https://github.com/CatalogueOfLife/testing/issues/166; imported 2024-09-06; **synced 2024-09-13**

_monthly started from January 2024:_
- [x] SF Dermaptera https://github.com/CatalogueOfLife/testing/issues/155; imported 2024-09-06; **synced 2024-09-16**
- [x] SF Plecoptera https://github.com/CatalogueOfLife/testing/issues/158; imported 2024-09-06; **synced 2024-09-16**
- [x] SF Psocodea https://github.com/CatalogueOfLife/testing/issues/160; imported 2024-09-06; **synced 2024-09-16**

_monthly started from March 2024:_
- [x] SF Aphid https://github.com/CatalogueOfLife/testing/issues/172; imported 2024-09-06; **synced 2024-09-17**
- [x] SF Chrysididae https://github.com/CatalogueOfLife/testing/issues/164; imported 2024-09-06; **synced 2024-09-17**
- [x] SF Coreoidea https://github.com/CatalogueOfLife/testing/issues/167; imported 2024-09-06; **synced 2024-09-17**
- [x] SF Lygaeoidea https://github.com/CatalogueOfLife/testing/issues/168; imported 2024-09-06; **synced 2024-09-17**
- [x] SF Mantodea https://github.com/CatalogueOfLife/testing/issues/169; imported 2024-09-06; **synced 2024-09-17**
- [x] SF Phasmida https://github.com/CatalogueOfLife/testing/issues/170; imported 2024-09-06; **synced 2024-09-17**

_single update in a year (January):_ 

~~SF Coleorrhyncha 
SF Embioptera
SF Grylloblattodea 
SF Mantophasmatodea 
SF Zoraptera~~

**_LEPIDOPTERA:_**
                                                 = no new ver. on 2024-09-
- [x] **GLI** https://github.com/CatalogueOfLife/testing/issues/195; imported 2024-08-26, 2024-09-12; **synced 2024-09-18**
- [ ] Alucitoidea (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/255 
- [x] **Gelechiidae** (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/198; imported 2024-08-26, 2024-09-16; **synced 2024-09-18**
- [ ] Hepialidae (Lepidoptera)  https://github.com/CatalogueOfLife/testing/issues/240 
- [ ] Pterophoroidea (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/179 
- [ ] Sesiidae (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/228
- [ ] Geometridae (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/258 
- [ ] Global Gracillariidae https://github.com/CatalogueOfLife/testing/issues/187

**_OTHER:_**

- [x] Bryonames of 2024-08-09; imported 2024-08-10; **synced 2024-09-09**
- [ ]  ~~UCD~~ - ask for logo with new update
- [ ] TITAN of 2024-07-23 (need a crawling) / crawled 2024-09-12; imported 2024-09-16
- [ ] The Scorpion Files (in Apr)
- [ ] Collembola (in Jan-Mar)
- [ ] WSC (Markus view vs ACEF export)
- [ ] Reptile Database of Aug/Sep 2024; next database release scheduled for Dec 2024.
- [ ] Systema Dipterorum ver. 5.4
- [ ] World Ferns ver. 24.9 of 2024-09-18
- [ ] World Plants ver. 24.9 of 2024-09-18

=============================

- SF Permopsocida _is not yet in CoL_; I have submitted its adoption to the CoL Taxon Group.  (see email of 2023-11-10, Heidi)

-  ScaleNet

- LPSN see https://github.com/CatalogueOfLife/data/issues/202#issuecomment-1970787286 . @mdoering via Slack 2024-05-06: _heard back from LPSN - they have good progress, but the API with classification will be public and usable by us at the end of May - so we might be able to get LPSN into the June release_ YR: _LPSN - good! But we have no June release. It will be AC24 in June. It's risky to publish AC24 with new dataset. Especially, without Taxonomy Group assessment of LPSN and approval of ITIS replacement. Let's do it in July-August_
Markus Göker, 2024-08-22: _I presume, however, that we can finish the API in September [2024]._

- FishBase - ?

- Paris/DBTNT - ?

- LDL Neuropterida

- WorldPlants new versioning after ver. 19.4, Jun 2024 - now year+month, e.g. 24.8 (August 27th, 2024)
 
=============================

_Filling gaps:_

Suborder **Symphyta** (Hymenoptera) https://github.com/CatalogueOfLife/data/issues/579
Class/order **Diplura** https://github.com/CatalogueOfLife/data/issues/577
Order **†Permopsocida** (Insecta) https://github.com/CatalogueOfLife/data/issues/578
Family **Promecheilidae** (Tenebrionoidea, Coleoptera) https://github.com/CatalogueOfLife/data/issues/580

**Comment by mdoering** [comment]
[WSC update](https://github.com/CatalogueOfLife/testing/issues/190#issuecomment-2308760240)?

**Comment by yroskov** [comment]
PREVIEW release started 2024-09-11, 7:32 pm (server time)
Finished as COL24.9, id [302939](https://www.checklistbank.org/dataset/302939/about), 2024-09-11
Deployed to the preview website 2024-09-11

- [x] check ITIS version = 2024-08-20 / 2024-08-20

**Comment by yroskov** [comment]
PREVIEW release started 2024-09-17, 7:10 pm (server time)
Finished as COL24.9, id [303350](https://www.checklistbank.org/dataset/303350/about), 2024-09-17, 8:45 pm
Deployed to the preview website 2024-09-17

- [x] check TW/SF metadata

**Comment by yroskov** [comment]
PREVIEW release started 2024-09-18, 8:46 pm (server time)
Finished as COL24.9, id [303376](https://www.checklistbank.org/dataset/303376/about), 2024-09-18
Deployed to the preview website 2024-09-19

**Comment by yroskov** [comment]
PREVIEW release started 2024-09-19, 5:03 pm (server time)
Finished as COL24.9, id [303391](https://www.checklistbank.org/dataset/303391/about), 2024-09-19, 6:37 pm
Deployed to the preview website 2024-09-19

**Comment by yroskov** [comment]
@olafbanki & @mdoering, COL24.9, id [303391](https://www.checklistbank.org/dataset/303391/about) is completed now as CoL of September.

**Comment by yroskov** [comment]
Deployed to the portal 2024-09-24

**Comment by yroskov** [comment]
Release started 2024-09-24, 1:46 pm (server time)
Finished as COL24.9, id [303608](https://www.checklistbank.org/dataset/303608/about), 2024-09-24
Deployed to the preview website 2024-09-25

_(see re-synced WCVP Lamiaceae; check metadata)_

CHECKS of 2024-09-25

- [ ] **None of searches work in the preview release** (and in COL24.9, id 303608 in CLB https://www.checklistbank.org/dataset/303608/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&sortBy=taxonomic) 

- [x] Tree browse = OK 
- [x] GSD metadata = OK
- [x] Spp stats unchanged 
- [ ] Species pages lost
![image](https://github.com/user-attachments/assets/f7411de8-be70-4c83-9072-70d88a619460)

For attention of @mdoering: seems, COL24.9, id [303608](https://www.checklistbank.org/dataset/303608/about) is corrupted (perhaps, indexing stage failed). I'll kick off a new release now.

**Comment by yroskov** [comment]
Release started 2024-09-25, 1:19 pm (server time)
Finished as COL24.9, id [303642](https://www.checklistbank.org/dataset/303642/about), 2024-09-25, 2:52 pm
Deployed to the preview website 2024-09-25

- [x] Lamiaceae checked = OK

**Comment by mdoering** [comment]
Sorry, I did not announce it. But it was expected that the search for the release is not working. I am rebuilding the index. But the full new release is also fine

**Comment by yroskov** [comment]
Preview site is very unstable now (2024-09-25, 11.00 am Champaign): search page may work, in next seconds might be empty [https://preview.catalogueoflife.org/data/search?facet=rank&facet=issue&facet=status&facet=[…]ubspecies&rank=variety&sortBy=taxonomic&status=accepted](https://preview.catalogueoflife.org/data/search?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=extinct&facet=environment&limit=50&offset=0&rank=subspecies&rank=variety&sortBy=taxonomic&status=accepted)
COLCOL

![image](https://github.com/user-attachments/assets/85e7492c-d664-4b0d-a2a6-5266abdcda41)

Search option become down completely around 11.10 am (Champaign)

**Comment by mdoering** [comment]
As I said, we are still swapping the indices and this new release needed to be indexed again.
The index should be up to date soon though (only the private candidate and old monthly releases were missing and needed to be added now), so we can then publish the release once you've given the ok

**Comment by yroskov** [comment]
I am not able to do full check on the PREVIEW website now, but you can deploy release [303642](https://www.checklistbank.org/dataset/303642/about) of 2024-09-25 as final once the re-indexing project is complete.

**Comment by yroskov** [comment]
2024-09-29: [303642](https://www.checklistbank.org/dataset/303642/about) observed in the production portal.

- [x] 2024-09-30: Searches, GSD metadata, position & metadata of Lamiaceae = OK
