### ISSUE TITLE
WoRMS Mollusca dev: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#27]
**WoRMS Mollusca dev (2251) of Feb 15, 2021**
https://data.catalogueoflife.org/dataset/2251

**Comment by yroskov** [comment]
**ISSUES** @yroskov 2021-02-15

- [ ] **Unlikely Year** (2)
https://data.catalogueoflife.org/dataset/2251/verbatim?issue=unlikely%20year

Indeed, reference has a year "2920" in MolluscaBase:
http://www.molluscabase.org/aphia.php?p=taxdetails&id=1419197
and
http://www.molluscabase.org/aphia.php?p=taxdetails&id=1354186
Original description:  Ortea J., Moro L. & Espinosa J. **(2920)**. Una nueva...

**Comment by yroskov** [comment]
- [ ] **Multi Word Epithet** for YR to resolve in CoL:
https://data.catalogueoflife.org/dataset/2251/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&issue=multi%20word%20epithet&limit=50&offset=0

- [ ] **Doubtful Name** for YR to resolve in CoL:
https://data.catalogueoflife.org/dataset/2251/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&issue=doubtful%20name&limit=50&offset=0

- [ ] **Parent Name Mismatch** for YR to resolve in CoL:
https://data.catalogueoflife.org/dataset/2251/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&issue=parent%20name%20mismatch&limit=50&offset=0

**Comment by yroskov** [comment]
- [ ] **Unmatched Name Brackets** (16) - missing one bracket in each authorstring
https://data.catalogueoflife.org/dataset/2251/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&issue=unmatched%20name%20brackets&limit=50&offset=0

**Comment by yroskov** [comment]
- [ ] **Missing genus** for YR to resolve in CoL
https://data.catalogueoflife.org/dataset/2251/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&issue=missing%20genus&limit=50&offset=0

**Comment by yroskov** [comment]
- [ ] **Accepted Name Missing** (45)
https://data.catalogueoflife.org/dataset/2251/verbatim?issue=accepted%20name%20missing

**Comment by yroskov** [comment]
- [ ] **Parsed Name Differs** (64) & **Unusual Name Characters** (97) for YR to resolve in CoL

**Comment by yroskov** [comment]
- [ ] **Not Interpreted** (1053) - @Geoff , Kadija, how important this report is?

**Comment by yroskov** [comment]
**TASKS** WoRMS Mollusca dev (2251) of Feb 16, 2021
https://data.catalogueoflife.org/catalogue/3/dataset/2251/tasks

![image](https://user-images.githubusercontent.com/28574252/108559831-77da9380-72c1-11eb-88ee-d272899c2caa.png)

**Comment by yroskov** [comment]
- [ ] ACC-ACC sp (same auth) – empty Genus, SpecificEpithet & Authorship fields
https://data.catalogueoflife.org/catalogue/3/dataset/2251/duplicates?authorshipDifferent=false&category=binomial&limit=500&minSize=2&mode=STRICT&offset=0&status=accepted&withDecision=false

![image](https://user-images.githubusercontent.com/28574252/108559933-9b054300-72c1-11eb-8f1d-d74b0d500846.png)

**Comment by yroskov** [comment]
- [ ] **ACC-SYN sp (diff acc, same auth)** – do the MolluscaBase authors know these cases?
https://data.catalogueoflife.org/catalogue/3/dataset/2251/duplicates?acceptedDifferent=true&authorshipDifferent=false&category=binomial&limit=500&minSize=2&mode=STRICT&offset=0&status=accepted&status=synonym&withDecision=false

- [ ] **SYN-SYN sp (diff acc, diff auth)** – there are names without authorstring in the report. These names had portion “sensu” in the original database. Is it clearinghouse behavior? CoL is unable to mark these names as “Misapplied”.
Example: Acanthochites aeneus, Anatina tasmanica
_See in MolluscaBase:_ 
http://www.molluscabase.org/aphia.php?p=taxdetails&id=152656
Anatina tasmanica sensu Hutton, 1873 accepted as Offadesma angasi (Crosse & P. Fischer, 1864)
http://www.molluscabase.org/aphia.php?p=taxdetails&id=537493
Anatina tasmanica sensu Hutton, 1873 accepted as Offadesma angasi (Crosse & P. Fischer, 1864)
