### ISSUE TITLE
CoL of October 2024

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#270]
- [x] WoRMS of 2024-10-01; imported 2024-10-02; **synced 2024-10-03**

- [x] ITIS of 2024-09-20; imported 2024-10-01; **synced 2024-10-03**
 
- [x] Scarabs of 2024-10-09; imported 2024-10-09; **synced 2024-10-09**

**_FROM TaxonWorks:_**

- [x] 3i Auchenorrhyncha https://github.com/CatalogueOfLife/testing/issues/135; imported 2024-10-08; **synced 2024-10-10**
- [x] Entiminae https://github.com/CatalogueOfLife/testing/issues/128; imported 2024-10-08; **synced 2024-10-10**
- [x] WCO (Opiliones) https://github.com/CatalogueOfLife/testing/issues/13; imported 2024-10-08; **synced 2024-10-10**
- [x] WOL (Odonata) https://github.com/CatalogueOfLife/testing/issues/215; imported 2024-10-08; **synced 2024-10-10**
- [x] SF Isoptera https://github.com/CatalogueOfLife/testing/issues/171; imported 2024-10-09; **synced 2024-10-11**
- [x] SF Orthoptera https://github.com/CatalogueOfLife/testing/issues/166; imported 2024-10-09; **synced 2024-10-11**

_monthly started from January 2024:_
- [x] SF Dermaptera https://github.com/CatalogueOfLife/testing/issues/155; imported 2024-10-09; **synced 2024-10-11**
- [x] SF Plecoptera https://github.com/CatalogueOfLife/testing/issues/158; imported 2024-10-09; **synced 2024-10-15** 
- [x] SF Psocodea https://github.com/CatalogueOfLife/testing/issues/160; imported 2024-10-09; **synced 2024-10-15** 

_monthly started from March 2024:_
- [ ] SF Aphid https://github.com/CatalogueOfLife/testing/issues/172; imported 2024-09-09 = no new version
- [x] SF Chrysididae https://github.com/CatalogueOfLife/testing/issues/164; imported 2024-10-09; **synced 2024-10-16**
- [x] SF Coreoidea https://github.com/CatalogueOfLife/testing/issues/167; imported 2024-10-09; **synced 2024-10-16**
- [x] SF Lygaeoidea https://github.com/CatalogueOfLife/testing/issues/168; imported 2024-10-09; **synced 2024-10-16**
- [x] SF Mantodea https://github.com/CatalogueOfLife/testing/issues/169; imported 2024-10-09; **synced 2024-10-16**
- [x] SF Phasmida https://github.com/CatalogueOfLife/testing/issues/170; imported 2024-10-09; **synced 2024-10-16**

_started from October 2024:_
- [x] SF Permopsocida of Oct 2024 / 2024-10-09; imported 2024-10-09; **synced 2024-10-09**

_single update in a year (January):_ 

~~SF Coleorrhyncha 
SF Embioptera
SF Grylloblattodea 
SF Mantophasmatodea 
SF Zoraptera~~

**_LEPIDOPTERA:_**
                                          
- [x] **GLI** https://github.com/CatalogueOfLife/testing/issues/195; ver 1.1.24.271 / 2024-09-27; imported 2024-09-27; **synced 2024-10-22**
- [ ] Alucitoidea (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/255 
- [x] **Gelechiidae** (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/198; ver. 1.1.24.291 (17 Oct 2024); imported 2024-10-17; **synced 2024-10-22**
- [ ] Hepialidae (Lepidoptera)  https://github.com/CatalogueOfLife/testing/issues/240 
- [ ] Pterophoroidea (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/179 
- [ ] Sesiidae (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/228
- [ ] Geometridae (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/258 
- [x] **Global Gracillariidae** https://github.com/CatalogueOfLife/testing/issues/187 ver 2024-10-01; imported 2024-10-20; **synced 2024-10-22**

**_OTHER:_**

- [ ]  ~~UCD~~ - ask for logo with new update
- [ ] The Scorpion Files (in Apr)
- [ ] Collembola (in Jan-Mar)
- [ ] WSC (Markus view vs ACEF export)
- [ ] Reptile Database of Aug/Sep 2024; next database release scheduled for Dec 2024.
- [ ] Systema Dipterorum ver. 5.4 (2024-09-06), ver. 5.5 (2024-10-01)
- [x] World Ferns ver. 24.9 of 2024-09-18; imported 2024-09-18; synced 2024-09-30; new ver. of 2024-10-05; **synced 2024-10-08**
- [x] World Plants ver. 24.9 of 2024-09-18; imported 2024-09-19; **synced 2024-10-02**
- [x] WFO Pinopsida ver. 2024-06 / 2024-06-20; imported 2024-06-19; **synced 2024-10-22**

=============================

- SF Permopsocida _is not yet in CoL_; I have submitted its adoption to the CoL Taxon Group.  (see email of 2023-11-10, Heidi)

-  ScaleNet

- LPSN see https://github.com/CatalogueOfLife/data/issues/202#issuecomment-1970787286 . @mdoering via Slack 2024-05-06: _heard back from LPSN - they have good progress, but the API with classification will be public and usable by us at the end of May - so we might be able to get LPSN into the June release_ YR: _LPSN - good! But we have no June release. It will be AC24 in June. It's risky to publish AC24 with new dataset. Especially, without Taxonomy Group assessment of LPSN and approval of ITIS replacement. Let's do it in July-August_
Markus Göker, 2024-08-22: _I presume, however, that we can finish the API in September [2024]._
Markus Göker, 2024-10-14: ...most likely this will go online between November 4 and November 8 [2024]

- FishBase - ?

- Paris/DBTNT - ?

- LDL Neuropterida

- WorldPlants new versioning after ver. 19.4, Jun 2024 - now year+month, e.g. 24.8 (August 27th, 2024)
 
=============================

_Filling gaps:_

Suborder **Symphyta** (Hymenoptera) https://github.com/CatalogueOfLife/data/issues/579
Class/order **Diplura** https://github.com/CatalogueOfLife/data/issues/577
Order **†Permopsocida** (Insecta) https://github.com/CatalogueOfLife/data/issues/578
Family **Promecheilidae** (Tenebrionoidea, Coleoptera) https://github.com/CatalogueOfLife/data/issues/580

**Comment by yroskov** [comment]
- WCVP Lamiaceae re-synced 2024-09-23 (rank "subvariety" was eliminated from accepted taxa) = included in CoL of September

**Comment by yroskov** [comment]
- [x] Rid off accepted names with "Infraspecific Names" rank https://github.com/CatalogueOfLife/testing/issues/271#issuecomment-2386203267 = completed 2024-10-01.

**Comment by yroskov** [comment]
Release started 2024-10-03, 2:51 pm (server time)
Finished as COL24.10, id [304127](https://www.checklistbank.org/dataset/304127/about), 2024-10-03, 4:17 pm
Deployed to the preview website 2024-10-03

- [ ] World Plants 202751 vs 202618 = -133 spp

**Comment by yroskov** [comment]
Release started 2024-10-16, 6:49 pm (server time)
Finished as COL24.10, id [304565](https://www.checklistbank.org/dataset/304565/about), 2024-10-16, 8:23 pm
Deployed to the preview website 2024-10-16

**Comment by yroskov** [comment]
@dhobern, just let you know, I am going to sync updated (if any) Lepidoptera checklists for _CoL of October_ on next Mn-Tu, 21-22 Oct.

**Comment by dhobern** [comment]
Gelechiidae has just been updated, and I believe GLI has been updated within the last month. Thanks.

**Comment by yroskov** [comment]
Release started 2024-10-22, 4:28 pm (server time)
Finished as COL24.10, id [304708](https://www.checklistbank.org/dataset/304708/about), 2024-10-22
Deployed to the preview website 2024-10-22

- [x] Check version/date of WFO Pinopsida = OK

**Comment by yroskov** [comment]
@olafbanki, @mdoering, COL24.10, id [304708](https://www.checklistbank.org/dataset/304708/about) is ready as CoL of October.

**Comment by yroskov** [comment]
Observed at the portal 2024-10-25
