### ISSUE TITLE
CoL of November 2024

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#273]
- [x] WoRMS of 2024-11-01; imported 2024-11-02; **synced 2024-11-03**. _See problems between Turbellarians and Cestoda, Monogenea, Trematoda._ New export for WoRMS Turbellarians 2024-11-07; imported 2024-11-08; **synced 2024-11-08**. Also re-synced WoRMS Monogenea, Mollusca 2024-11-08 (duplicates cleaned up).

- [x] ITIS of 2024-10-22; imported 2024-11-04; **synced 2024-11-06**
 
- [x] Scarabs of 2024-11-04; imported 2024-11-04; **synced 2024-11-06**

**_FROM TaxonWorks:_**

- [x] 3i Auchenorrhyncha https://github.com/CatalogueOfLife/testing/issues/135; (with new sector family Membracidae; MOWD retired) of Nov 2024 / 2024-11-04; imported 2024-11-05; **synced 2024-11-07**
- [x] Entiminae https://github.com/CatalogueOfLife/testing/issues/128; of Nov 2024 / 2024-11-04; imported 2024-11-05; **synced 2024-11-07**
- [x] WCO (Opiliones) https://github.com/CatalogueOfLife/testing/issues/13; of Nov 2024 / 2024-11-04; imported 2024-11-04; **synced 2024-11-11**
- [x] WOL (Odonata) https://github.com/CatalogueOfLife/testing/issues/215; of Nov 2024 / 2024-11-04; imported 2024-11-04; **synced 2024-11-11**
- [x] SF Isoptera https://github.com/CatalogueOfLife/testing/issues/171; of Nov 2024 / 2024-11-04; imported 2024-11-04; **synced 2024-11-11**
- [x] SF Orthoptera https://github.com/CatalogueOfLife/testing/issues/166; of Nov 2024 / 2024-11-04; imported 2024-11-05; **synced 2024-11-11**

_monthly started from January 2024:_
- [x] SF Dermaptera https://github.com/CatalogueOfLife/testing/issues/155; of Nov 2024 / 2024-11-04; imported 2024-11-05; **synced 2024-11-13**
- [x] SF Plecoptera https://github.com/CatalogueOfLife/testing/issues/158; of Nov 2024 / 2024-11-04; imported 2024-11-05; **synced 2024-11-13**
- [x] SF Psocodea https://github.com/CatalogueOfLife/testing/issues/160; of Nov 2024 / 2024-11-04; imported 2024-11-05; **synced 2024-11-13**

_monthly started from March 2024:_
- [x] SF Aphid https://github.com/CatalogueOfLife/testing/issues/172; of Nov 2024 / 2024-11-04; imported 2024-11-05; **synced 2024-11-13**
- [x] SF Chrysididae https://github.com/CatalogueOfLife/testing/issues/164; of Nov 2024 / 2024-11-04; imported 2024-11-05; **synced 2024-11-13**
- [x] SF Coreoidea https://github.com/CatalogueOfLife/testing/issues/167; of Nov 2024 / 2024-11-04; imported 2024-11-05; **synced 2024-11-13**
- [x] SF Lygaeoidea https://github.com/CatalogueOfLife/testing/issues/168; of Nov 2024 / 2024-11-04; imported 2024-11-05; **synced 2024-11-13**
- [x] SF Mantodea https://github.com/CatalogueOfLife/testing/issues/169; of Nov 2024 / 2024-11-04; imported 2024-11-05; **synced 2024-11-13**
- [x] SF Phasmida https://github.com/CatalogueOfLife/testing/issues/170; of Nov 2024 / 2024-11-04; imported 2024-11-05; **synced 2024-11-13**

_started from October 2024:_
- [x] SF Permopsocida = _one more update in Nov, then add to _single update in a year_ group_; of Nov 2024 / 2024-11-04; imported 2024-11-05; **synced 2024-11-13** 

_single update in a year (January):_ 

~~SF Coleorrhyncha 
SF Embioptera
SF Grylloblattodea 
SF Mantophasmatodea 
SF Zoraptera~~

**_LEPIDOPTERA:_**
                                          
- [x] **GLI** https://github.com/CatalogueOfLife/testing/issues/195; **synced 2024-11-13**
- [ ] Alucitoidea (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/255 
- [ ] Gelechiidae (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/198; 
- [ ] Hepialidae (Lepidoptera)  https://github.com/CatalogueOfLife/testing/issues/240 
- [x] **Pterophoroidea** (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/179; **synced 2024-11-13**
- [x] **Sesiidae** (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/228; **synced 2024-11-13**
- [ ] Geometridae (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/258 
- [ ] Global Gracillariidae https://github.com/CatalogueOfLife/testing/issues/187 

**_OTHER:_**

- [ ]  ~~UCD~~ - ask for logo with new update
- [ ] The Scorpion Files (in Apr)
- [ ] Collembola (in Jan-Mar)
- [ ] WSC (Markus view vs ACEF export)
- [ ] Reptile Database of Aug/Sep 2024; next database release scheduled for Dec 2024.
- [ ] Systema Dipterorum ver. 5.4 (2024-09-06), ver. 5.5 (2024-10-01)
- [x] AntCat of 2024-08-16; imported 2024-08-16; synced 2024-11-01, **re-synced 2024-11-04**
- [ ] World Plants (in full) ver 24-11 of 2024-11-06; received 2024-11-06
- [ ] World Ferns ver 24-11 of 2024-11-06; received 2024-11-06; **synced 2024-11-13**

=============================

-  ScaleNet

- LPSN see https://github.com/CatalogueOfLife/data/issues/202#issuecomment-1970787286 . mdoering via Slack, 2024-05-06: _heard back from LPSN - they have good progress, but the API with classification will be public and usable by us at the end of May - so we might be able to get LPSN into the June release_ YR: _LPSN - good! But we have no June release. It will be AC24 in June. It's risky to publish AC24 with new dataset. Especially, without Taxonomy Group assessment of LPSN and approval of ITIS replacement. Let's do it in July-August_
Markus Göker, 2024-08-22: _I presume, however, that we can finish the API in September [2024]._
Markus Göker, 2024-10-14: ...most likely this will go online between November 4 and November 8 [2024]

- FishBase - ?

- Paris/DBTNT - ?

- LDL Neuropterida

 
=============================

_Filling gaps:_

Suborder **Symphyta** (Hymenoptera) https://github.com/CatalogueOfLife/data/issues/579
Class/order **Diplura** https://github.com/CatalogueOfLife/data/issues/577
~~Order **†Permopsocida** (Insecta) https://github.com/CatalogueOfLife/data/issues/578~~ = DONE
Family **Promecheilidae** (Tenebrionoidea, Coleoptera) https://github.com/CatalogueOfLife/data/issues/580

**Comment by yroskov** [comment]
Release started 2024-11-04, 6:56 pm (server time)
Finished as COL24.11, id [304972](https://www.checklistbank.org/dataset/304972/about), 2024-11-04, 8:36 pm
Deployed to the preview website 2024-11-04

- [x] 3i Auchenorrhyncha = OK (3i Auchenorrhyncha + 3,536 spp vs 3,184 spp in MOWD)
- [x] AntCat = OK (ITIS -10,213; AntCat +15,107 spp)
- [x] WoRMS Mollusca: extinct 41621 vs 42010 = +389 = CHECK for possible overlap with PaleoBioBD = No, all is OK

- [ ] WoRMS Turbellarians: 5894 vs 26070 = + 20,176 = what's happened?

Overlap on species level with Cestoda, Monogenea & Trematoda (~19,574 spp) https://www.checklistbank.org/dataset/3/duplicates?authorshipDifferent=false&category=binomial&limit=100&minSize=2&mode=STRICT&offset=0&status=accepted

  | Oct (spp) | Nov (spp) | diff
-- | -- | -- | --
WoRMS Turbellarians | 5894 | 26070 | + 20176
WoRMS Cestoda | 2678 | 2684 |  
WoRMS Monogenea | 5717 | 5771 |  
WoRMS Trematoda | 10994 | 11203 |  
  |   | Ce+Mo+Tr 19658 | diff 518

_Sectors in CoL of Oct 2024:_

Turbellarians: 
Animalia: Xenacoelomorpha, Platyhelminthes

Animalia > Platyhelminthes > Rhabditophora: Cestoda
Animalia > Platyhelminthes > Rhabditophora: Monogenea
Animalia > Platyhelminthes > Rhabditophora: Trematoda

**Comment by yroskov** [comment]
Release started 2024-11-08, 5:56 pm (server time)
Finished as COL24.11, id [305071](https://www.checklistbank.org/dataset/305071/about), 2024-11-08, 7:30 pm
Deployed to the preview website 2024-11-08

- [x] WoRMS Turbellarians = FIXED
- [x] Duplicated identical species in entire CoL:
![image](https://github.com/user-attachments/assets/8a34c32c-bdf7-4443-9ced-e3fdbfd2bddb)

Duplicates inside WCO Pinopsida resolved; re-synced.

4 remains, 2024-11-11:
![image](https://github.com/user-attachments/assets/0ab0d1b9-57e9-46f1-b3cb-17e6b58e8709)
_SF Permopsocida_	- Idelopsocus diradiatus Rasnitsyn & Krassilov, 1996		
Permopsocida>    Martynopsocidae>    Idelopsocus
_SF Psocodea_ - Idelopsocus diradiatus Rasnitsyn & Krassilov, 1996	
Psocodea>    Dinopsocidae>    Idelopsocus = genus Idelopsocus BLOCKED in SF Psocodea 2024-11-13
_SF Permopsocida_ - Idelopsocus galinae Novokshonov, 2001		
Permopsocida>    Martynopsocidae>    Idelopsocus
_SF Psocodea_ - Idelopsocus galinae Novokshonov, 2001		
Psocodea>    Dinopsocidae>    Idelopsocus

_SF Permopsocida_ - Idelopsocus mutovinus Rasnitsyn & Aristov, 2013		
Permopsocida>    Martynopsocidae>    Idelopsocus
_SF Psocodea_ - Idelopsocus mutovinus Rasnitsyn & Aristov, 2013		
Psocodea>    Dinopsocidae>    Idelopsocus

_HymIS Crabronidae & Rhopalosomatidae_ - Propalosoma gutierrezae Dlussky & Rasnitsyn, 1999		
Vespoidea>    Rhopalosomatidae>    Propalosoma = genus Propalosoma BLOCKED from Rhopalosomatidae re-synced 2024-11-13.
_AntCat_ - Propalosoma gutierrezae Dlussky & Rasnitsyn, 1999		
Formicidae>    Myrmeciinae>    Propalosoma

2024-11-13:
![image](https://github.com/user-attachments/assets/8c517a1f-77cf-4c62-bcb8-7368e8ca3899)

**Comment by yroskov** [comment]
- [x] World Plants: block truncated names in synonymy (e.g. species names without first epithet in the source file)

See https://github.com/CatalogueOfLife/testing/issues/4#issuecomment-2458271825 & https://github.com/CatalogueOfLife/data/issues/719#issuecomment-2456705890

= FIXED through decisions in the current WP ver. 24.9, Sep 2024 / 2024-09-18:

Taraxacum - a synonym of Taraxacum laceratum (Brenner) Brenner
(Asteraceae - re-synced 2024-11-11)

Aeginetia - synonym of Christisonia scortechinii Prain
(Lamiales - re-synced 2024-11-11)

**Comment by yroskov** [comment]
Release started 2024-11-11, 10:37 pm (server time)
Finished as COL24.11, id [305121](https://www.checklistbank.org/dataset/305121/about), 2024-11-12, 12:15 am
Deployed to the preview website 2024-11-12

**Comment by yroskov** [comment]
Release started 2024-11-13, 8:54 pm (server time)
Finished as COL24.11, id 305168, id [305168](https://www.checklistbank.org/dataset/305168/about), 2024-11-13, 10:30 pm
Deployed to the preview website 2024-11-13 = failed & failed on 2024-11-14; deployment command does not work = FIXED

**Comment by yroskov** [comment]
Subkingdom Pteridobiotina Britton & Brown introduced in the tree 2024-11-14.

**Comment by yroskov** [comment]
Release started 2024-11-14, 7:57 pm (server time)
Finished as COL24.11, id [305197](https://www.checklistbank.org/dataset/305197/about), 2024-11-14, 7:30 pm
Deployed to the preview website 2024-11-14

**Comment by yroskov** [comment]
@olafbanki, @mdoering, COL24.11, id [305197](https://www.checklistbank.org/dataset/305197/about) is completed now as the CoL of November.

**Comment by olafbanki** [comment]
Meta data of the project was updated. A new release was executed. Post now committed. CoL of November ready to be published.

**Comment by mdoering** [comment]
published

**Comment by yroskov** [comment]
Observed at the portal 2024-11-20.

**Wrong version** was published: id [305232](https://www.checklistbank.org/dataset/305232/about), not id [305197](https://www.checklistbank.org/dataset/305197/about) which was submitted
