### ISSUE TITLE
CoL of December 2024

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#275]
- [x] WoRMS of 2024-12-01; **synced 2024-12-03**

- [x] ITIS of 2024-11-19; imported 2024-12-02; **synced 2024-12-02** (incl. cyanobacteria as a part of pre-existing Bacteria sector)
 
- [x] Scarabs of 2024-12-04; imported 2024-12-04; **synced 2024-12-04**

**_FROM TaxonWorks:_**

_Please do syncs of all TW checklists in this month without assessment & resolution of issues_

- [x] 3i Auchenorrhyncha https://github.com/CatalogueOfLife/testing/issues/135; imported 2024-12-07; **synced 2024-12-09**
- [x] Entiminae https://github.com/CatalogueOfLife/testing/issues/128; **synced 2024-12-09**
- [x] WCO (Opiliones) https://github.com/CatalogueOfLife/testing/issues/13; **synced 2024-12-09**
- [x] WOL (Odonata) https://github.com/CatalogueOfLife/testing/issues/215; **synced 2024-12-09**
- [x] SF Isoptera https://github.com/CatalogueOfLife/testing/issues/171; **synced 2024-12-09**
- [x] SF Orthoptera https://github.com/CatalogueOfLife/testing/issues/166; **synced 2024-12-09**

_monthly started from January 2024:_
- [x] SF Dermaptera https://github.com/CatalogueOfLife/testing/issues/155; **synced 2024-12-09**
- [x] SF Plecoptera https://github.com/CatalogueOfLife/testing/issues/158; **synced 2024-12-09**
- [x] SF Psocodea https://github.com/CatalogueOfLife/testing/issues/160; **synced 2024-12-09**

_monthly started from March 2024:_
- [x] SF Aphid https://github.com/CatalogueOfLife/testing/issues/172; **synced 2024-12-09**
- [x] SF Chrysididae https://github.com/CatalogueOfLife/testing/issues/164; **synced 2024-12-09**
- [x] SF Coreoidea https://github.com/CatalogueOfLife/testing/issues/167; **synced 2024-12-09**
- [x] SF Lygaeoidea https://github.com/CatalogueOfLife/testing/issues/168; **synced 2024-12-09**
- [x] SF Mantodea https://github.com/CatalogueOfLife/testing/issues/169; **synced 2024-12-09**
- [x] SF Phasmida https://github.com/CatalogueOfLife/testing/issues/170; **synced 2024-12-09**

_single update in a year (January):_ 

~~SF Coleorrhyncha 
SF Embioptera
SF Grylloblattodea 
SF Mantophasmatodea 
SF Permopsocida (started from October 2024:)
SF Zoraptera~~

**_LEPIDOPTERA:_**
                                          
- [x] **GLI** https://github.com/CatalogueOfLife/testing/issues/195; imported 2024-11-30; **synced 2024-12-02**
- [ ] Alucitoidea (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/255 
- [ ] Gelechiidae (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/198; 
- [ ] Hepialidae (Lepidoptera)  https://github.com/CatalogueOfLife/testing/issues/240 
- [ ] Pterophoroidea (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/179 
- [x] **Sesiidae** (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/228; imported 2024-11-30; **synced 2024-12-02**
- [ ] Geometridae (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/258 
- [ ] Global Gracillariidae https://github.com/CatalogueOfLife/testing/issues/187 

**_OTHER:_**

- [ ]  ~~UCD~~ - ask for logo with new update
- [ ] The Scorpion Files (in Apr)
- [ ] Collembola (in Jan-Mar)
- [ ] WSC (Markus view vs ACEF export)
- [ ] Reptile Database of Aug/Sep 2024; next database release scheduled for Dec 2024.
- [ ] Systema Dipterorum ver. 5.4 (2024-09-06), ver. 5.5 (2024-10-01); imported 2024-11-13, 2024-11-21; **synced 2024-11-25**
- [ ] World Plants (in full) ver 24-11 of 2024-11-06; received 2024-11-06
- [ ] World Ferns ver 24-11 of 2024-11-06; received 2024-11-06

=============================

-  ScaleNet

- LPSN see https://github.com/CatalogueOfLife/data/issues/202#issuecomment-1970787286 . mdoering via Slack, 2024-05-06: _heard back from LPSN - they have good progress, but the API with classification will be public and usable by us at the end of May - so we might be able to get LPSN into the June release_ YR: _LPSN - good! But we have no June release. It will be AC24 in June. It's risky to publish AC24 with new dataset. Especially, without Taxonomy Group assessment of LPSN and approval of ITIS replacement. Let's do it in July-August_
Markus Göker, 2024-08-22: _I presume, however, that we can finish the API in September [2024]._
Markus Göker, 2024-10-14: ...most likely this will go online between November 4 and November 8 [2024]

- FishBase - ?

- Paris/DBTNT - ?

- LDL Neuropterida

 
=============================

_Filling gaps:_

Suborder **Symphyta** (Hymenoptera) https://github.com/CatalogueOfLife/data/issues/579
Class/order **Diplura** https://github.com/CatalogueOfLife/data/issues/577
Superfamily **Cucujoidea** by Tommy McElrath
Coleoptera families **Dermestidae, Derodontidae, Mycetophagidae, plus Bostrichidae, Nosodendridae, Jacobsoniidae** by Jiří Háva https://github.com/CatalogueOfLife/data/issues/840
Rhysodidae & Trogossitidae (Coleoptera) to start by Lesley

**Comment by yroskov** [comment]
- [ ] Systema Dipterorum: check for names with the portion [GENUS NOT SPECIFIED] (decision **block** - _Request failed with status code 400_)

**Comment by yroskov** [comment]
Release started 2024-11-25, 6:45 pm (server time)
Eml rcvd 2024-11-26, 4:27 am (10:26 am server time) >>Hello yroskov, Your ProjectRelease #322 of project Catalogue of Life **was canceled**. Thanks, ChecklistBank

**Comment by yroskov** [comment]
Release started 2024-11-26, 1:46 pm (server time)
Finished as COL24.11, id [305456](https://www.checklistbank.org/dataset/305456/about), 2024-11-26, 5:26 pm
Deployed to the preview website 2024-11-26

- [x] Systema Dipterorum: empty families https://github.com/CatalogueOfLife/testing/issues/127#issuecomment-2501757196 = FIXED 2024-11-26

**Comment by yroskov** [comment]
Release started 2024-11-27, 5:15 pm (server time)
Finished as COL24.11, id [305504](https://www.checklistbank.org/dataset/305504/about), 2024-11-27, 7:09 pm
Deployed to the preview website 2024-11-27

>_Hello yroskov,
We are sorry, but an error has occurred processing your **DwCA download** from "Catalogue of Life, version 2024-11-27".
If the problem persists, contact us at [jobs@checklistbank.org](mailto:jobs@checklistbank.org) or post to our mailinglist.
Please include the key (a4b85779-1ca2-4b1f-9ffd-0df60c299afe) of the failed processing job.
Thanks, ChecklistBank_

**Comment by yroskov** [comment]
Release started 2024-12-02, 9:01 pm (server time)
Finished as COL24.12, id [305830](https://www.checklistbank.org/dataset/305830/about), 2024-12-02, 9:59 pm
Deployed to the preview website 2024-12-02

_(GLI, Sesiidae, ITIS)_

**Comment by yroskov** [comment]
Use https://www.checklistbank.org/catalogue/3/tasks - From this source only before the next PREVIEW

**Comment by yroskov** [comment]
Release started 2024-12-16, 2:31 pm (server time)
Finished as COL24.12, id [306527](https://www.checklistbank.org/dataset/306527/about), 2024-12-16, 3:29 pm
Deployed to the preview website 2024-12-16

- [x] _Check SF Phasmida due to strange sector ": Phasmida" https://www.checklistbank.org/catalogue/3/sector/sync?sectorKey=1434_ = position in the tree is OK
- [x] Check 3i sectors (comment from Geoff) = only one, suborder:
[Auchenorrhyncha](https://www.checklistbank.org/catalogue/3/assembly?sourceTaxonKey=319&datasetKey=2317) = healthy 2024-12-16
- [x] ACC-ACC same sp same auth: 171 pair, mainly Systema Dipterorum vs CCW  
![image](https://github.com/user-attachments/assets/6e1768da-3b28-4564-8336-731bb0672485)
https://www.checklistbank.org/dataset/3/duplicates?authorshipDifferent=false&category=binomial&limit=100&minSize=2&mode=STRICT&offset=0&status=accepted
Systema Dipterorum vs CCW = RESOLVED, re-synced
3i Auchenorrhyncha - Pendarini>Chlorotettix>Chlorotettix (Chlorotettix)  = RESOLVED, sector suborder Auchenorrhyncha resynced
WoRMS Monogenea - Gyrodactylidea>Gyrodactylidae>Gyrodactylus = RESOLVED, re-synced
Entiminae - Entiminae>Naupactini>Megalostylus = RESOLVED, re-synced

- [ ] Credits to GSDs are disappeared in the Tree in production & preview portals, see https://github.com/CatalogueOfLife/portal/issues/220

- [x] Systema Dipterorum needs to be re-done (all previous decisions were vanished with unexpected import of 2024-11-28)
![image](https://github.com/user-attachments/assets/0b73171d-fbad-4270-9a90-618c217ccb5b)

 = DONE 2024-12-19

**Comment by yroskov** [comment]
2024-12-19, Tasks Project3:

![image](https://github.com/user-attachments/assets/bf209f22-690e-459b-98aa-8cc691d90545)

**Comment by yroskov** [comment]
Release started 2024-12-19, 2:39 pm (server time)
Finished as COL24.12, id [306706](https://www.checklistbank.org/dataset/306706/about), 2024-12-19, 3:38 pm
Deployed to the preview website 2024-12-19

- [x] Systema Dipterorum, empty families **Cryomyidae** (subfam Aphaniosominae = ignore) & **Empiidae** = blocked

**Comment by yroskov** [comment]
@olafbanki, @mdoering, you can go ahead with COL24.12, id [306706](https://www.checklistbank.org/dataset/306706/about) as the CoL of December.

I did my best to rework Systema Dipterorum this week.

**Comment by olafbanki** [comment]
Thanks Yuri

**Comment by olafbanki** [comment]
Checks and blog post completed. @mdoering ready to publish

**Comment by mdoering** [comment]
out

**Comment by yroskov** [comment]
Thanks. 

Merry Christmas & Happy New Year to everyone! 

See you next year.
