### ISSUE TITLE
CoL of January 2025

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#276]
- [x] WoRMS of 2025-01-01; imported 2025-01-02; **synced 2025-01-03**

- [x] ITIS of 2024-12-16; imported 2025-01-02; **synced 2025-01-06**

- [x] Scarabs of 2025-01-06; imported 2025-01-06; **synced 2025-01-08**

**_FROM TaxonWorks:_**

- [x] 3i Auchenorrhyncha https://github.com/CatalogueOfLife/testing/issues/135; imported 2025-01-02; **synced 2025-01-06**
- [x] Entiminae https://github.com/CatalogueOfLife/testing/issues/128; imported 2025-01-02; **synced 2025-01-06**
- [x] WCO (Opiliones) https://github.com/CatalogueOfLife/testing/issues/13; imported 2025-01-02; **synced 2025-01-08**
- [x] WOL (Odonata) https://github.com/CatalogueOfLife/testing/issues/215; imported 2025-01-02; **synced 2025-01-08**
- [x] SF Isoptera https://github.com/CatalogueOfLife/testing/issues/171; imported 2025-01-02; **synced 2025-01-08**
- [x] SF Orthoptera https://github.com/CatalogueOfLife/testing/issues/166; imported 2025-01-02; **synced 2025-01-08**

_monthly started from January 2024:_
- [x] SF Dermaptera https://github.com/CatalogueOfLife/testing/issues/155; imported 2025-01-03; **synced 2025-01-09**
- [x] SF Plecoptera https://github.com/CatalogueOfLife/testing/issues/158; imported 2025-01-03; **synced 2025-01-09**
- [x] SF Psocodea https://github.com/CatalogueOfLife/testing/issues/160; imported 2025-01-03; **synced 2025-01-09**

_monthly started from March 2024:_
- [x] SF Aphid https://github.com/CatalogueOfLife/testing/issues/172; imported 2025-01-03; **synced 2025-01-09**
- [x] SF Chrysididae https://github.com/CatalogueOfLife/testing/issues/164; imported 2025-01-03; **synced 2025-01-10**
- [x] SF Coreoidea https://github.com/CatalogueOfLife/testing/issues/167; imported 2025-01-03; **synced 2025-01-10**
- [x] SF Lygaeoidea https://github.com/CatalogueOfLife/testing/issues/168; imported 2025-01-03; **synced 2025-01-10**
- [x] SF Mantodea https://github.com/CatalogueOfLife/testing/issues/169; imported 2025-01-03; **synced 2025-01-10**
- [x] SF Phasmida https://github.com/CatalogueOfLife/testing/issues/170; imported 2025-01-03; **synced 2025-01-10**

_single update in a year (January):_ 

- [x] SF Coleorrhyncha ver. Jan 2025 / 2025-01-02; imported 2025-01-03, re-imported 2025-01-10; synced 2025-01-09, **re-synced 2025-01-13**
- [x] SF Embioptera ver. Jan 2025 / 2025-01-02; imported 2025-01-03, re-imported 2025-01-10; synced 2025-01-09, **re-synced 2025-01-13**
- [x] SF Grylloblattodea ver. Jan 2025 / 2025-01-02; imported 2025-01-03, re-imported 2025-01-10; synced 2025-01-09, **re-synced 2025-01-13**
- [x] SF Mantophasmatodea ver. Jan 2025 / 2025-01-02; imported 2025-01-03, re-imported 2025-01-10; synced 2025-01-09, **re-synced 2025-01-13**
- [x] SF Permopsocida (started from October 2024:) ver. Jan 2025 / 2025-01-02; imported 2025-01-03; **synced 2025-01-09**
- [x] SF Zoraptera ver. Jan 2025 / 2025-01-02; imported 2025-01-03, re-imported 2025-01-10; synced 2025-01-09, **re-synced 2025-01-13**

**_LEPIDOPTERA:_**
                                          
- [x] **GLI** https://github.com/CatalogueOfLife/testing/issues/195; ver 1.1.24.365 / 2024-12-30; imported 2024-12-30; **synced 2025-01-15**
- [ ] Alucitoidea (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/255 
- [x] **Gelechiidae** (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/198; ver 1.1.24.366 (31 Dec 2024) / 2024-12-31; imported 2024-12-31; **synced 2025-01-15**
- [ ] Hepialidae (Lepidoptera)  https://github.com/CatalogueOfLife/testing/issues/240 
- [ ] Pterophoroidea (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/179 
- [x] **Sesiidae** (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/228; ver 2024-12-29 / 2024-12-29; imported 2024-12-28; **synced 2025-01-15**
- [ ] Geometridae (Lepidoptera) https://github.com/CatalogueOfLife/testing/issues/258 
- [ ] Global Gracillariidae https://github.com/CatalogueOfLife/testing/issues/187 

**_OTHER:_**

- [ ]  ~~UCD~~ - ask for logo with new update
- [ ] The Scorpion Files (in Apr)
- [ ] WSC (Markus view vs ACEF export)
- [ ] Reptile Database of Aug/Sep 2024; next database release scheduled for Dec 2024.
- [x] Systema Dipterorum ver. 5.6 (2024-12-10); received 2024-12-16; imported 2025-01-13; **synced 2025-01-17**
- [x] World Plants (in full & partial) ~~ver 24-11 of 2024-11-06; received 2024-11-06~~ ver 25-01 of 2025-01-02; received 2025-01-02; imported 2025-01-08; **synced 2025-01-13**
- [x] World Ferns ~~ver 24-11 of 2024-11-06; received 2024-11-06~~ ver 25-01 of 2025-01-03; received 2025-01-03; imported 2025-01-08; **synced 2025-01-13**
- [x] Collembola.org of Jan 2025 / 2025-01-09; crawled & imported 2025-01-09; **synced 2025-01-14**

=============================

-  ScaleNet

- LPSN see https://github.com/CatalogueOfLife/data/issues/202#issuecomment-1970787286 . mdoering via Slack, 2024-05-06: _heard back from LPSN - they have good progress, but the API with classification will be public and usable by us at the end of May - so we might be able to get LPSN into the June release_ YR: _LPSN - good! But we have no June release. It will be AC24 in June. It's risky to publish AC24 with new dataset. Especially, without Taxonomy Group assessment of LPSN and approval of ITIS replacement. Let's do it in July-August_
Markus Göker, 2024-08-22: _I presume, however, that we can finish the API in September [2024]._
Markus Göker, 2024-10-14: ...most likely this will go online between November 4 and November 8 [2024]

- FishBase - ?

- Paris/DBTNT - ?

- LDL Neuropterida

 
=============================

_Filling gaps:_

Suborder **Symphyta** (Hymenoptera) https://github.com/CatalogueOfLife/data/issues/579
Class/order **Diplura** https://github.com/CatalogueOfLife/data/issues/577
Superfamily **Cucujoidea** by Tommy McElrath 
Coleoptera families **Dermestidae, Derodontidae, Mycetophagidae**, plus **Bostrichidae, Nosodendridae, Jacobsoniidae** by Jiří Háva https://github.com/CatalogueOfLife/data/issues/840
**Rhysodidae & Trogossitidae** (Coleoptera) to start by Lesley

=============================

- [ ] Translate AC19 datasets from ACEF to CoLDP, fix possible issues detected by CLB: https://github.com/CatalogueOfLife/data/issues/886
- [x] Missing bracket in authorship https://github.com/CatalogueOfLife/data/issues/899 (WTaxa [x] 2025-01-14; all fixed on 2025-01-15; re-synced)
- [x] Duplicated families/taxa in COL https://github.com/CatalogueOfLife/data/issues/900 = FIXED 2025-01-14. **Keep an eye on next months**

**Comment by yroskov** [comment]
Release started 2025-01-06, 5:37 pm (server time)
Finished as COL25.01, id [307232](https://www.checklistbank.org/dataset/307232/about), 2025-01-06, 6:43 pm (server time)
Deployed to the preview website 2025-01-07

**Comment by yroskov** [comment]
Release started 2025-01-13, 7:53 pm (server time)
Finished as COL25.01, id , 2025-01-13, 9:00 pm (server time)
Deployed to the preview website 2025-01-14

**Comment by yroskov** [comment]
Release started 2025-01-14, 9:14 pm (server time)
Finished as COL25.01, id [307513](https://www.checklistbank.org/dataset/307513/about), 2025-01-14, 10:22 pm (server time)
Deployed to the preview website 2025-01-14

- [x] _Check Calendra and authorship Clairville, J.P.de]_ = OK
- [x] _Check duplicated families/taxa in COL_ https://github.com/CatalogueOfLife/data/issues/900
only Rhynchodeminae left in WoRMS Turbellarians. Empty blocked; re-synced 2025-01-15.
- [ ] World Plants

**Comment by yroskov** [comment]
Release started 2025-01-15, 7:42 pm (server time)
Finished as COL25.01, id [307564](https://www.checklistbank.org/dataset/307564/about), 2025-01-15, 8:47 pm (server time)
Deployed to the preview website 2025-01-15

**Comment by yroskov** [comment]
Release started 2025-01-17, 8:15 pm (server time)
Finished as COL25.01, id [307664](https://www.checklistbank.org/dataset/307664/about), 2025-01-17, 9:23 pm (server time)
Deployed to the preview website 2025-01-21

**Comment by yroskov** [comment]
@olafbanki, @mdoering, COL25.01, id [307664](https://www.checklistbank.org/dataset/307664/about) of 2025-01-17 is ready for deployment as the CoL of January 2025.

**Comment by olafbanki** [comment]
@yroskov thanks!

**Comment by yroskov** [comment]
Deployed 2025-01-28
