### ISSUE TITLE
WoRMS Actiniaria (former Hexacoral) (id 1176): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#31]
Was **WoRMS Hexacoral** in ac19, now **WoRMS Actiniaria** id 1176 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1176

- [x] _Sector_ **order Actiniaria**. Attention: Subclass Hexacorallia was established, other orders in class Anthozoa dropped under Not assigned subclass.

- [ ] _Metadata:_ Big problem. It looks like metadata were not updated from the yaml: at least, title, abstract, license, version, release are different

Geoff: Here's what are in the yaml file:
---
    title: 'World List of Actiniaria'
    alias: WoRMS_Actiniaria
    description: 'A compilation of publications concerning taxonomy, nomenclature, and geographic distribution of extant hexacorallians - members of cnidarian order Actiniaria (sea anemones in the strict sense)'
    organisations: 'Ohio State University; Department of Evolution, Ecology and Organismal Biology (EEOB); Kansas University Natural History Museum'
    contact: info@marinespecies.org
    authorsAndEditors: 'Daly, M.; Fautin, D.'
    geographicScope: Global
    taxonomicScope: Actiniaria
    code: null
    gazetteer: mrgid
    license: cc-by-nc
    version: 'ver. (03/2021)'
    released: '2021-03-01'
    website: 'http://www.marinespecies.org'
    logo: null
    citation: 'Daly, M.; Fautin, D. (2021). World List of Actiniaria. Accessed at  on 2021-03-01'

It's failing to parse because they don't provide the organisations, authorsAndEditors, and contact correctly.
I think we need a verbatim version of those Person and Organisation fields where the info is not separated.

- [ ] Khadija: pls change style of all Aliases: no underscore between WoRMS and taxon name: WoRMS Actiniaria

- [x] Alias and Title were changed manually as WoRMS Actiniaria: World List of Actiniaria
However, GSD still appears in the Assembly tree and checklist bank as WoRMS Hexacoral. @gdower, can we change short & full name for this GSD on "basic level", not through standard patches?

- [x] _Imports:_ 1162 spp vs 1138 in ac19

**Comment by yroskov** [comment]
**ISSUES** selected only 2021-03-10 

- [ ] **Subspecies Assigned, 15**   - incorrect software behavior @mdoering  
https://data.catalogueoflife.org/catalogue/3/dataset/1176/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&issue=subspecies%20assigned&limit=100&offset=0
All synonyms. Binomial names such as:
Actinothoe sancti matthaei (Mc Murrich, 1893)
Anthopleura sanctae helenae Carlgren, 1941
Bolocera mc murrichi Kwietniewski, 1898
Sagartia sancti matthaei McMurrich, 1893
etc
interpreted as subspecies?

YR: all names blocked.

**Comment by yroskov** [comment]
**TASKS** 2021-03-10

![image](https://user-images.githubusercontent.com/28574252/110661459-35063000-818a-11eb-80e1-a0aed5524b67.png)

Might be interesting for WoRMS authors:

- [ ] SYN-SYN species (diff acc, same auth)
https://data.catalogueoflife.org/catalogue/3/dataset/1176/duplicates?acceptedDifferent=true&authorshipDifferent=false&category=binomial&limit=500&minSize=2&mode=STRICT&offset=0&status=synonym

- [ ] SYN-SYN infraspecies (diff acc, same auth)
https://data.catalogueoflife.org/catalogue/3/dataset/1176/duplicates?acceptedDifferent=true&authorshipDifferent=false&category=trinomial&limit=500&minSize=2&mode=STRICT&offset=0&status=synonym

Resolved 2021-03-10:
![image](https://user-images.githubusercontent.com/28574252/110663142-ca55f400-818b-11eb-814e-02efcb32675d.png)

**Comment by yroskov** [comment]
**Not synced yet because of problem with metadata.**

**Comment by yroskov** [comment]
Checks at preview (of 2021-04-05)

Suborder Nynantheae in the Tree. WoRMS: Suborder Nynantheae accepted as Enthemonae (Collapsed and reorganized by Rodríguez et al. 2014).

Difficult to complete comparison due to many non-basic ranks in the classification and "accepted as" taxa in WoRMS.

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 1 names with portion _incertae sedis_ = 1 prov acc IGNORED

ISSUES assessed 2025-05-21

![Image](https://github.com/user-attachments/assets/e89ab6d9-14c2-4c56-89f8-b69974c7fc6a)

TASKS

![Image](https://github.com/user-attachments/assets/bd2d6840-e1d4-4d3e-8cc8-8491567acf31)

- Broken decisions, 4 = deleted

Resolved 2025-05-21:

![Image](https://github.com/user-attachments/assets/14fab9e1-62dc-40d2-9c8f-871d674dfbf0)

**Synced 2025-05-21**
