### ISSUE TITLE
WoRMS Amphipoda: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#32]
**WoRMS Amphipoda**, id 1202 on prod, ver. 2021-03-01
https://data.catalogueoflife.org/catalogue/3/dataset/1202/meta

- [x] _Sector:_ **order Amphipoda**
- [ ] _Metadata:_ were not updated
- [x] _Imports:_  10303 spp vs 10164 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-10

- [ ] **Not Interpreted**, 11838. What does it mean?

**Comment by yroskov** [comment]
**TASKS** 2021-03-10

![image](https://user-images.githubusercontent.com/28574252/110700273-61837180-81b5-11eb-8c79-99d3b97896e7.png)

**Comment by yroskov** [comment]
**Synced 2021-03-10.** 

Aaaah, old metadata! Sync should be repeated after we sort metadata problem.

**Comment by yroskov** [comment]
@bart-v, _here is a comment received in the CoL email box:_

From: Ernie Spencer 
Date: Fri, 7 Jan 2022 at 22:36
Subject: 2sp2000: pelagonicus instead of pellagonicus?
To: Species 2000 Secretariat <sp2000@sp2000.org>

7AN2022

Secretariat:

Niphargus pellagonicus S. Karaman, 1943 is the only species scientific name in COL that contains pellag.

Epithet pellagonicus is likely a misspelling of pelagonicus.

Compare with Salmo pelagonicus Karaman, 1938.

Ernie Spencer

Ernest Newell Spencer
Austin, Texas, USA
sites.google.com/site/piecesebook
sites.google.com/site/piecesebook2
sites.google.com/site/piecesebook3

**Comment by bart-v** [comment]
Not really, see the original descrption: Karaman, S. (1943). Die Unterirdischen Amphipoden Südserbiens. Ohridski Zbornik. Srpska Kraljevska Akademija. Posebna izdanja: prirodnjački i matematički spisi, knjiga 85. 34, 163-212
https://www.marinespecies.org/aphia.php?p=taxdetails&id=546705

![image](https://user-images.githubusercontent.com/15011629/148853256-f25e748e-b5b0-4cc8-9257-59366cc97074.png)

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/182642136-a356887a-51b0-43f4-8de3-3917975131a4.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/182642487-d8da40ef-1160-4942-99bf-3fc6d102be06.png)

Re-synced 2022-08-03

**Comment by yroskov** [comment]
**ver 2023-05-01**

TASKS

![image](https://user-images.githubusercontent.com/28574252/236892805-a1e3b14b-58fa-4620-9de9-92ec86619955.png)

- Broken decisions, 6: all deleted

Resolved 2023-05-08

![image](https://user-images.githubusercontent.com/28574252/236893388-0aa821c6-2941-4390-9e12-e0531746e1df.png)

**Re-synced 2023-05-08**

**Comment by yroskov** [comment]
**ver 2023-06-01**

TASKS
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/92606a69-aac9-4edd-ab04-606fda13dd54)

- Broken decisions, 6: all deleted

Resolved 2023-06-06:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/16994158-df3b-4b03-9868-60171af6512c)

**Re-synced 2023-06-06**

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 81 names with portion _incertae sedis_ = 62 acc & 10 prov acc = 63 spp & subspp = BLOCKED

ISSUES assessed 2025-05-20

![Image](https://github.com/user-attachments/assets/2f507276-94c6-4340-86b4-9058330f5eaf)

TASKS

![Image](https://github.com/user-attachments/assets/ed079f88-4439-4f7f-901f-83148419069f)

- Broken decisions, 96 = deleted

Resolved 2025-05-20:

![Image](https://github.com/user-attachments/assets/7161fe13-45be-4f1d-a46a-470661e8c686)

**Synced 2025-05-20**

**Comment by yroskov** [comment]
**ver. 2026-01-01**

TASKS

<img width="1671" height="1203" alt="Image" src="https://github.com/user-attachments/assets/6fdb5a64-f1de-43dd-b472-54a3235d0eb4" />

Resolved 2026-01-13:

<img width="1671" height="1184" alt="Image" src="https://github.com/user-attachments/assets/bc33da83-73c6-4032-95c3-2b59fcac6547" />

**Re-synced 2026-01-13**
