### ISSUE TITLE
WoRMS Antipatharia: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#33]
**WoRMS Antipatharia**, id 1194 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1194

- [x] _Sector:_ order Antipatharia
- [ ] _Metadata:_ Not updated
- [x] _Imports:_  279 spp vs 267 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-11
- [x]

**Comment by yroskov** [comment]
**TASKS** 2021-03-11

![image](https://user-images.githubusercontent.com/28574252/110823045-51bc6980-8257-11eb-8ffa-6bed64d231a2.png)

Resolved:

![image](https://user-images.githubusercontent.com/28574252/110823289-947e4180-8257-11eb-87bd-4b03ca1b37e6.png)

**Comment by yroskov** [comment]
Not synced yet

**Comment by yroskov** [comment]
Checks at https://preview.catalogueoflife.org/ (of 2021-04-05)

Spp: 279 - 267 (ac19) = +12

Genus Arachnopathes is present in the Tree. It was also present in ac19. WoRMS: Genus Arachnopathes Milne Edwards H., 1857 accepted as Antipathes Pallas, 1766. 

Not Assigned Subfamily - Genus Acanthosaropathes. WoRMS: Genus Acanthosaropathes Opresko, 2019 is not assigned in any subfamily 

Other taxa matched WoRMS. Conclusion: no obvious misinterpretation.

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

ISSUES assessed 2025-05-21

![Image](https://github.com/user-attachments/assets/c8ec0c99-c743-4001-abcf-c1b8d6889c3a)

TASKS = no new issues

- Broken decisions, 1 = deleted

**Synced 2025-05-21**

**Comment by yroskov** [comment]
See https://github.com/CatalogueOfLife/data/issues/1683

WoRMS Antipatharia of 2026-08-01 / 2026-08-01

- [ ] Classification: order Antipatharia - 11 Family - 5 Subfamily - 53 Genus - 1 Subgenus - 307 Species - 3 Subspecies - ~~3 Variety - 2 Subvariety~~

= variety & subvariety ranks excluded; re-synced 2026-08-26
