### ISSUE TITLE
WoRMS Appendicularia: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#34]
**WoRMS Appendicularia**, id 1178 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1178

- [x] _Sector:_ class Appendicularia (wasn't broken)
- [ ] _Metadata:_ Not updated
- [x] _Imports:_  68 spp vs 68 in ac19

**Comment by yroskov** [comment]
**ISSUES** 2021-03-11
- [x] assessed

Top issue Not Interpreted, 68. Vast majority related to the fields:
col:nameID
col:referenceID
col:relatedNameID
col:type      basionym

**Comment by yroskov** [comment]
**TASKS** 2021-03-11

![image](https://user-images.githubusercontent.com/28574252/110825336-892c1580-8259-11eb-84ee-6d85aead6bc1.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/110825508-bc6ea480-8259-11eb-94d2-b3a2cdc4e9bb.png)

**Comment by yroskov** [comment]
Synced, nut need re-sync after we resolve metadata updates

**Comment by yroskov** [comment]
Checks at preview (of 2021-04-05):

Spp 68-68 = 0

WoRMS: Species Chunopleura microgaster Lohmann, 1914 (nomen dubium). It is not present in CoL.
