### ISSUE TITLE
WoRMS Ascidiacea: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#35]
**WoRMS Ascidiacea***, id 1186 on prod
https://data.catalogueoflife.org/dataset/1186

- [ ] _Sector:_ class Ascidiacea (wasn't broken)
- [ ] _Metadata:_ Not updated
- [ ] _Imports:_  2935 spp vs 2925 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-11
-[x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-11

![image](https://user-images.githubusercontent.com/28574252/110832647-2b9bc700-8261-11eb-93aa-1ef2aec8a947.png)

Resolved: 

![image](https://user-images.githubusercontent.com/28574252/110832823-5d149280-8261-11eb-9e14-798360c8a057.png)

**Comment by yroskov** [comment]
Synced 2021-03-11, bu needs re-sync after we resolve metadata problem.

**Comment by yroskov** [comment]
Checks at preview (of 2021-04-05):

Spp 2935-2925=+10

All taxa are in place as expected.
