### ISSUE TITLE
WoRMS Asteroidea: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#36]
**WoRMS Asteroidea**, id 1095 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1095

- [x] _Sector:_ class Asteroidea
The sector appeared as class Asteroidea in col - subfilum Asterozoa in WoRMS Asteroidea:
![image](https://user-images.githubusercontent.com/28574252/110858452-b55a8d00-827f-11eb-88fd-b6b22783c6fb.png)

- [ ] _Metadata:_ Not updated
- [x] _Imports:_  2194 spp vs 1935 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-11

- [x] assessed
- [x] Indetermined, 1 - blocked in CoL

**Comment by yroskov** [comment]
**TASKS** 2021-03-11

![image](https://user-images.githubusercontent.com/28574252/110859655-5dbd2100-8281-11eb-8aed-51c2e8c40186.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/110866957-982bbb80-828b-11eb-9c5b-5e943b565db8.png)

**Comment by yroskov** [comment]
Not synced

**Comment by yroskov** [comment]
**ver 2021-11-01**

TASKS = no changes
![image](https://user-images.githubusercontent.com/28574252/140379459-d54e7337-cc52-4816-a7a3-b7dfb659eb66.png)

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/182643461-a0aeca41-05f4-4f60-ac01-eac12e4e3e7d.png)

Resolved
![image](https://user-images.githubusercontent.com/28574252/182643732-a86fdc6a-1834-41d1-86a3-d8f9a27c9966.png)

Re-synced 2022-08-03

**Comment by yroskov** [comment]
**ver 2023-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/88262b59-8050-489b-8410-335d96268db8)

- Broken decisions, all deleted

Resolved 2023-05-09

**Re-synced 2023-05-09**

**Comment by yroskov** [comment]
**ver 2023-06-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/80fa513b-0d14-4e83-8eb9-14d841a637cd)

- Broken decisions, 3: all deleted

Resolved 2023-06-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/b3f10eda-5bdf-4bd9-ac37-624ac7d8d84a)

**Re-synced 2023-06-07**

**Comment by yroskov** [comment]
**ver 2024-05-01** 

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/f8814293-530b-41b5-8605-8de03e08c9b0)

Resolved 2024-05-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/495a0fe8-829a-42ba-8c13-a77327809c0c)

**Re-synced 2024-05-07**

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

ISSUES assessed 2025-05-21

![Image](https://github.com/user-attachments/assets/54e61161-e4f9-4169-b4e3-188ae1096529)

TASKS

![Image](https://github.com/user-attachments/assets/facfce1d-b70b-4197-b926-9f315140375e)

- Broken decisions, 40 = deleted

Resolved 2025-05-21:

![Image](https://github.com/user-attachments/assets/7d1b2764-b9b9-4aa6-82f1-e7d9b2543331)

**Synced 2025-05-21**

**Comment by yroskov** [comment]
**ver. 2026-01-01**

TASKS

<img width="1671" height="1203" alt="Image" src="https://github.com/user-attachments/assets/bf1890f1-19a8-4056-b456-ec8f628d3a84" />

Resolved 2026-01-13:

<img width="1671" height="1184" alt="Image" src="https://github.com/user-attachments/assets/beaf3012-24ed-4086-981a-11113e54446d" />

**Re-synced 2026-01-13**
