### ISSUE TITLE
WoRMS Brachyura: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#39]
**WoRMS Brachyura**, id 1108 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1108

- [ ] _Sector:_ NOT ASSEMBLED. Reason: the infraorder Brachyura is missing in the classification of WoRMS Brachyura export. 
Original classification in WoRMS:
Animalia (Kingdom) Arthropoda (Phylum) Crustacea (Subphylum) Multicrustacea (Superclass) Malacostraca (Class) Eumalacostraca (Subclass) Eucarida (Superorder) Decapoda (Order) Pleocyemata (Suborder) **Brachyura (Infraorder)**. Direct children (4) : Section Eubrachyura, Section Podotremata, Genus Zoea Bosc, 1801 (taxon inquirendum), Section Dromiacea 

![image](https://user-images.githubusercontent.com/28574252/110990109-7b998d00-8338-11eb-8711-09de91f55a63.png)

@gdower, could you pls help me to understand why infraorder Brachyura and sections are missing WoRMS Brachyura export? Is it export problem or because of interpretation by CoL+ software?

- [ ] _Metadata:_
- [ ] _Imports:_  spp vs in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-12

- [x] Subspecies Assigned, 3
All synonyms; names like that: Dromia (Cryptodromia) de manii Alcock, 1900; Para-Lio-thelphusa mainitensis Balss, 1937; Para-Peri-thelphusa sucki Balss, 1937    name status attributed as "species aggregate". Changed to "species" via editorial decisions.

- [x] Unparsable Authorship, 745. Names with "complex" authorstring, like that _De Haan, 1833 [in De Haan, 1833-1850]_. No problem.

**Comment by yroskov** [comment]
**TASKS** 2021-03-12

![image](https://user-images.githubusercontent.com/28574252/110996604-c4097880-8341-11eb-8e50-0a5731c390c8.png)

- [ ] Identical superfamily, 6. Superfamily repeated twice, second time without authorstring. **UNRESOLVED**
https://data.catalogueoflife.org/catalogue/3/dataset/1108/duplicates?category=uninomial&limit=500&minSize=2&mode=STRICT&offset=0&rank=superfamily&withDecision=false


  | xT |   | accepted | Dromioidea |   | superfamily | Animalia>Arthropoda>Crustacea>Malacostraca>Eumalacostraca>Decapoda>Pleocyemata
-- | -- | -- | -- | -- | -- | -- | --
  | urn:lsid:marinespecies.org:taxname:106690 |   | accepted | Dromioidea | De Haan, 1833 [in De Haan, 1833-1850] | superfamily | Animalia>Arthropoda>Crustacea>Malacostraca>Eumalacostraca>Decapoda>Pleocyemata>Dromioidea>Dynomenidae>Acanthodromiinae>Acanthodromia>Podotremata
  | urn:lsid:marinespecies.org:taxname:106700 |   | accepted | Majoidea | Samouelle, 1819 | superfamily | Animalia>Arthropoda>Crustacea>Malacostraca>Eumalacostraca>Decapoda>Pleocyemata>Pinnotheroidea>Pinnotheridae>Pinnotherinae>Abyssotheres>Eubrachyura>Heterotremata
  | x3X |   | accepted | Majoidea |   | superfamily | Animalia>Arthropoda>Crustacea>Malacostraca>Eumalacostraca>Decapoda>Pleocyemata
  | x45 |   | accepted | Ocypodoidea |   | superfamily | Animalia>Arthropoda>Crustacea>Malacostraca>Eumalacostraca>Decapoda>Pleocyemata
  | urn:lsid:marinespecies.org:taxname:106707 |   | accepted | Ocypodoidea | Rafinesque, 1815 | superfamily | Animalia>Arthropoda>Crustacea>Malacostraca>Eumalacostraca>Decapoda>Pleocyemata>Pinnotheroidea>Pinnotheridae>Pinnotherinae>Abyssotheres>Eubrachyura>Thoracotremata
  | urn:lsid:marinespecies.org:taxname:106708 |   | accepted | Pinnotheroidea | De Haan, 1833 [in De Haan, 1833-1850] | superfamily | Animalia>Arthropoda>Crustacea>Malacostraca>Eumalacostraca>Decapoda>Pleocyemata>Pinnotheroidea>Pinnotheridae>Pinnotherinae>Abyssotheres>Eubrachyura>Thoracotremata
  | xK |   | accepted | Pinnotheroidea |   | superfamily | Animalia>Arthropoda>Crustacea>Malacostraca>Eumalacostraca>Decapoda>Pleocyemata
  | urn:lsid:marinespecies.org:taxname:439089 |   | accepted | Pseudothelphusoidea | Ortmann, 1893 | superfamily | Animalia>Arthropoda>Crustacea>Malacostraca>Eumalacostraca>Decapoda>Pleocyemata>Pinnotheroidea>Pinnotheridae>Pinnotherinae>Abyssotheres>Eubrachyura>Heterotremata
  | x3D |   | accepted | Pseudothelphusoidea |   | superfamily | Animalia>Arthropoda>Crustacea>Malacostraca>Eumalacostraca>Decapoda>Pleocyemata
  | x34 |   | accepted | Xanthoidea |   | superfamily | Animalia>Arthropoda>Crustacea>Malacostraca>Eumalacostraca>Decapoda>Pleocyemata
  | urn:lsid:marinespecies.org:taxname:106703 |   | accepted | Xanthoidea | MacLeay, 1838 | superfamily | Animalia>Arthropoda>Crustacea>Malacostraca>Eumalacostraca>Decapoda>Pleocyemata>Pinnotheroidea>Pinnotheridae>Pinnotherinae>Abyssotheres>Eubrachyura>Heterotremata




Resolved:

**Comment by yroskov** [comment]
Not synced: sector(s) not established.

**Comment by yroskov** [comment]
Synced 2021-04-02

**Comment by yroskov** [comment]
**Broken hierarchy:** https://github.com/CatalogueOfLife/testing/issues/141

**2021-07-01**: temporarily fix by @gdower for July edition only

New **classification**: 
![image](https://user-images.githubusercontent.com/28574252/124182273-3ed6da80-da7c-11eb-9029-d8304028b409.png)

**Sectors:**  two sections Eubrachyura & Podotremata 
Establishing new sectors...
Was:
![image](https://user-images.githubusercontent.com/28574252/124182924-20251380-da7d-11eb-9729-8ad03aa6db54.png)
Deleted sector in suborder Pleocyemata. 
_Next:_
Delete 2 subtrees in superfam Cryptochiroidea & Cyclodorippoidea (children of infraorder NotAssigned in suborder Pleocyemata)
Set up infraorder Brachyura in suborder Pleocyemata.
Drag&drop two sections Eubrachyura & Podotremata in infraorder Brachyura.

**Comment by yroskov** [comment]
**ver 2021-11-01**

TASKS - no changes

![image](https://user-images.githubusercontent.com/28574252/140379870-8c8e5cde-63c5-4ad4-b3ac-63523a5f80a0.png)

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/182644791-50699a9f-9531-4367-b7dd-56349c61e831.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/182645865-a741795d-1b19-4216-bca4-d6cd129857af.png)

Re-synced 2022-08-03

**Comment by yroskov** [comment]
Dear @bart-v, 
Global Names developers pointed to the problem with presentation of multiple references in one(?) of WoRMS records:
https://www.catalogueoflife.org/data/taxon/96NL

Broken delimiters? Could you please have a look from your side?

@gdower also pointed:
record_id | 7QGWB

These IDs also have that issue:

-[ RECORD 1 ]-----
record_id | 96NH
length    | 236307
-[ RECORD 2 ]-----
record_id | 96NJ
length    | 236307
-[ RECORD 3 ]-----
record_id | 96MZ
length    | 236307
-[ RECORD 4 ]-----
record_id | 96N5
length    | 236307
-[ RECORD 5 ]-----
record_id | 96N2
length    | 236307
-[ RECORD 6 ]-----
record_id | 96N8
length    | 236307
-[ RECORD 7 ]-----
record_id | 96NL
length    | 236307

**Comment by bart-v** [comment]
We don't use double quotes as delimiters in our export. still COL tries to use them.
This reference has a starting double quote, but not a closing one
https://www.marinespecies.org/aphia.php?p=sourcedetails&id=261114

Title
```
"Molecular phylogeny of the genus Cronius Stimpson, 1860, with reassignment of C. tumidulus and several American species of Portunus to the genus Achelous De Haan, 1833 (Brachyura: Portunidae).
```
Removing it will fix this

**Comment by yroskov** [comment]
Thanks, @bart-v!

@mdoering, usage of double quotes as delimiters in CLB/CoL - is it a good idea?

**Comment by mdoering** [comment]
ColDP has defined that data files should be either TAB delimted without quoting or CSV with optional quoting as per [RFC 4180](https://tools.ietf.org/html/rfc4180). Contrary to dwc archives there is no meta file that can individually define other delimiters or quotes. If the CSV format is used, RFC4180 should be followed which says:

> Each field may or may not be enclosed in double quotes (however
>        some programs, such as Microsoft Excel, do not use double quotes
>        at all).  If fields are not enclosed with double quotes, then
>        double quotes may not appear inside the fields.  For example:
> 
>        "aaa","bbb","ccc" CRLF
>        zzz,yyy,xxx
> 
>    6.  Fields containing line breaks (CRLF), double quotes, and commas
>        should be enclosed in double-quotes.  For example:
> 
>        "aaa","b CRLF
>        bb","ccc" CRLF
>        zzz,yyy,xxx
> 
>    7.  If double-quotes are used to enclose fields, then a double-quote
>        appearing inside a field must be escaped by preceding it with
>        another double quote.  For example:
> 
>        "aaa","b""bb","ccc"


That means if a value starts with an unescaped quote then it is taken as the start of the optional quote.

If WoRMS never wants to use quotes it must take care that
 - no commas must appear in any of the values - sth very unlikely
 - no quote is used as a start value

`TSV` might be a simpler format to use - usually you can avoid tabs and carriage returns within data entirely by just replacing them on the fly with a simple space. Then there is no need to escape or quote anything else.

https://github.com/CatalogueOfLife/coldp/blob/master/README.md#data-files

**Comment by bart-v** [comment]
WoRMS is actually TSV (=TAB delimted without quoting)
Still COL parses the double quotes

**Comment by bart-v** [comment]
Anyway, double quote removed from this reference, so should all be OK

**Comment by mdoering** [comment]
Oh, quote with TAB are odd. I will look into this then on our side, thank for the hint!

**Comment by mdoering** [comment]
There was indeed a bug that caused quotes to be used for TAB files. I have fixed this now.

**Comment by mdoering** [comment]
While working on the quoting issue I found that the Reference.txt file using wrong columns (year, source + details are from ACEF times):

```
 ID	citation	author	title	year	source	details	doi	link	remarks
```

Here are the accepted ones which are more atomised, so the lumped bit in "details" find different homes:
https://github.com/CatalogueOfLife/coldp/blob/master/README.md#reference

**Comment by mdoering** [comment]
From what I can see in the WoRMS help the reference data should map nicely:
https://www.marinespecies.org/aphia.php?p=manual#topic5

> DOI = col:doi
> author = col: author
> year = col:issued
> title = col:title
> journal = col:containerTitle
> suffix = col:page (suffix is actually a mix of col:volume, issue, edition & page)

Alternatively ColDP accepts also [BibTex natively](https://github.com/CatalogueOfLife/coldp/blob/master/README.md#reference-bibtex). You seem to support that already:: https://www.marinespecies.org/aphia.php?p=manual#topic40


But checking the problematic [reference from above as BibTex](https://github.com/CatalogueOfLife/testing/files/9714648/WoRMS_SourceID_261114.txt) it still has a suboptimal journal value so there is no gain over TSV really:
`
    journal = {In: Crustacean Issues 18: Decapod Crustacean Phylogenetics, Martin, J.W., Crandall, K.A. & Felder, D.L. (eds)},
`

**Comment by bart-v** [comment]
OK, in WoRMS, `suffix` is not atomized to volume, issue, page, etc. so we cannot provide that.
We have now changed the column names to reflect the COLDP standard better.
`suffix` will be mapped to `col:page` from 2022-11-01 on wards
For `journal`, we have no alternative right now.
WoRMS is a taxonomic database, not full blown references database :)

**Comment by yroskov** [comment]
**Export of 2022-11-01**
Imported 2022-11-10.

- [ ] Broken sector for WoRMS Brachyura

**Comment by yroskov** [comment]
@gdower: WoRMS Brachyura removed from the piepline in March 2023 because it was finally totally breaking the CI pipeline.

@bart-v, CoL is unable to process WoRMS Brachyura since November 2022. Something wrong with exported CoLDP (my guess is explained above). Is there a chance to find what is wrong and do fix in June's export for Annual Checklist 2023?

**Comment by bart-v** [comment]
For the example https://www.marinespecies.org/aphia.php?p=taxdetails&id=240916 and as you explain: section & subsection are correctly placed between i.e. infraorder and superfamily in Zoology 
See https://en.wikipedia.org/wiki/Taxonomic_rank

WoRMS is exporting the full classification as seen on the URL above via the `parentID` field in file `Taxon.txt`
So I don't think there is an issue on the WoRMS side

**Comment by mdoering** [comment]
@yroskov this issue is old and full of all kinds of things. What is the actual current problem please to look at?

**Comment by mdoering** [comment]
The broken import since March looks like a backend bug, Im looking into this

**Comment by mdoering** [comment]
That issue was fixed many weeks ago and the dataset imports just fine - I did run an import just now.

**Comment by mdoering** [comment]
The [verbatim data](https://www.checklistbank.org/dataset/1108/verbatim/25297) for the family uses a mix of parentID and flat classification. The parentID links to the [superfamily](https://www.checklistbank.org/dataset/1108/verbatim/73222), which then links to the [subsection](https://www.checklistbank.org/dataset/1108/verbatim/28230) with a parentID to the section [Eubrachyura](https://www.checklistbank.org/dataset/1108/taxon/urn%3Alsid%3Amarinespecies.org%3Ataxname%3A106679) which contains a bad parentID `urn:lsid:marinespecies.org:taxname:106673` which does not exist! Because of that the flat classification is used and the flat section in ColDP is explicitly meant to be the [botanical rank of a section](https://github.com/CatalogueOfLife/coldp/blob/master/README.md#section). Thats why we get the troubles.

Solutions:

1. ideally we fix the broken parentID and include the sections parent [Eubrachyura](https://www.marinespecies.org/aphia.php?p=taxdetails&id=106679) in the archive.
2. Remove the section and subsection fields in the flat classification. Maybe even all flat classification fields as they are unused when the preferred parentID is given.

**Comment by bart-v** [comment]
OK, The parentID will be added in the next export 2023-06-01

**Comment by mdoering** [comment]
Thanks Bart. Looking at the [issues](https://www.checklistbank.org/dataset/1108/issues) there are 9 invalid parentID issues that might be good to fix:
https://www.checklistbank.org/dataset/1108/verbatim?issue=parent%20id%20invalid

There are also other invalid, i.e. non existing ids that should be fixed to avoid bad data, but they probably do not have that much of an impact as the one above:

 - [11 basionym id invalid](https://www.checklistbank.org/dataset/1108/verbatim?issue=basionym%20id%20invalid)
 - [15 invalid name ids](https://www.checklistbank.org/dataset/1108/verbatim?issue=name%20id%20invalid)
 - [7543 missing reference ids](https://www.checklistbank.org/dataset/1108/verbatim?issue=reference%20id%20invalid)

https://www.checklistbank.org/dataset/1108/issues

**Comment by mdoering** [comment]
@yroskov we should make sure in the future that we never have invalid id issues in sources. That is asking for trouble.

**Comment by bart-v** [comment]
We will soon replace Brachyura with DacaNet.
Once done we'll have a look at this.

**Comment by mdoering** [comment]
@yroskov please verify at least the other 8 broken parentID records to see if they do not introduce any fatal problems for COL.

**Comment by yroskov** [comment]
> @yroskov please verify at least the other 8 broken parentID records to see if they do not introduce any fatal problems for COL.

@gdower, could you please pick up this?

**Comment by yroskov** [comment]
- [ ] Sector: broken
_Step 1._ Two sectors deleted in Assembly
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/33c3fc1f-6455-411a-af54-8f1b6e1825b1)

_Step 2._ Replace button does not work (why?)
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/c57b4d9c-87ff-42df-b30d-a51f434c1244)

_Step 3._ Delete subtree does not work also
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/5ddddae7-f60f-4ebe-b3a7-e5311ddd3615)

<html><body>
<div class="headers-overview"><div class="url-preview"><div class="properties-view"><div class="tree-container">

  |  
-- | --
DELETE | https://api.checklistbank.org/dataset/3/tree/35f46bf2-29d1-4c6b-954a-ec69c1cb0d3b


</body>
</html>DELETE
	https://api.checklistbank.org/dataset/3/tree/35f46bf2-29d1-4c6b-954a-ec69c1cb0d3b
Status
404
Not Found
VersionHTTP/2
Transferred430 B (84 B size)
Referrer Policystrict-origin-when-cross-origin
Request PriorityHighest

	
access-control-allow-origin
	https://www.checklistbank.org/
age
	0
cache-control
	must-revalidate,no-cache,no-store
content-length
	84
content-type
	application/json
date
	Thu, 01 Jun 2023 20:22:23 GMT
vary
	Origin
via
	1.1 varnish (Varnish/6.0)
x-cache
	pass uncacheable
X-Firefox-Spdy
	h2
x-varnish
	837670324
	
Accept
	application/json, text/plain, */*
Accept-Encoding
	gzip, deflate, br
Accept-Language
	en-US,en;q=0.5
Authorization
	Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxNDQ0MTIwMi0xZmVlLTRiNDctOWJkOS1mNGE2OTEyMjBkOGIiLCJpc3MiOiJDb0wiLCJpYXQiOjE2ODU0NTAzODQsInN1YiI6Inlyb3Nrb3YiLCJleHAiOjE2ODYwNTUxODR9.xzz316Z6mbHq_l01JEm2UFye4tGzZCBW4LIe_PoLhviWBDfJ6FKw_zwAXiI3V1qZ
Connection
	keep-alive
DNT
	1
Host
	api.checklistbank.org
Origin
	https://www.checklistbank.org/
Referer
	https://www.checklistbank.org/
Sec-Fetch-Dest
	empty
Sec-Fetch-Mode
	cors
Sec-Fetch-Site
	same-site
TE
	trailers
User-Agent
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0

**Comment by yroskov** [comment]
- [x] Sector re-assembled 2023-06-02 https://github.com/CatalogueOfLife/checklistbank/issues/1240#issuecomment-1573746033 (by whom, when?).

**Comment by yroskov** [comment]
@bart-v, looking through Issues report in the checklistbank... (https://www.checklistbank.org/dataset/1108/issues)

Seems, year in the authorstrings is incorrectly spelled: 
Tanzanonautes Feldmann, O'Connor, Stevens, Gottfried, Roberts, Ngasala, Rasmusson & Kapilima, **21007**      = 2007
Tanzanonautes tuerkayi Feldmann, O'Connor, Stevens, Gottfried, Roberts, Ngasala, Rasmusson & Kapilima, **21007**    = 2007
Clampethildella spinosa Beschin, Busulini & Tessier, **20212**

**Comment by bart-v** [comment]
- Authorship -> fixed, some are false positives and we consider just OK
- Classification Rank Order Invalid for "section" -> don't agree with this. As explained before in
= https://github.com/CatalogueOfLife/testing/issues/141 and
= https://github.com/CatalogueOfLife/testing/issues/39#issuecomment-1541910973

**Comment by mdoering** [comment]
I just checked the very first record of the invalid rank order, "family" [Epialtidae](https://www.checklistbank.org/dataset/1108/verbatim/52266). Its parent is also a family called the same. It seems the first, link record is an [unaccepted subfamily Pliosomatinae in worms](https://www.marinespecies.org/aphia.php?p=taxdetails&id=439053), but is exported wrongly as a family?

**Comment by bart-v** [comment]
No, we export urn:lsid:marinespecies.org:taxname:439053 as subfamily
Names.txt line 11262
![image](https://github.com/CatalogueOfLife/testing/assets/15011629/3f791ac7-62d0-4f1e-9740-b812e71d0c92)

**Comment by mdoering** [comment]
The subfamily name indeed is there correctly, but the corresponding taxon urn:lsid:marinespecies.org:taxname:439053 does not use it, but instead has [col:nameID=urn:lsid:marinespecies.org:taxname:196143](https://www.checklistbank.org/dataset/1108/verbatim/52266) which is the family.

**Comment by mdoering** [comment]
Examples of missing synonyms/taxa:
 - unaccepted superfamily [Thioidea](https://www.marinespecies.org/aphia.php?p=taxdetails&id=439097) 
 - unaccepted family [Acanthonychidae](https://www.marinespecies.org/aphia.php?p=taxdetails&id=196144)
 - unaccepted family [Blastidae](https://www.marinespecies.org/aphia.php?p=taxdetails&id=196254)
 - unaccepted genus [Acites](https://www.marinespecies.org/aphia.php?p=taxdetails&id=450039)
 - unaccepted species [Amphitrite argentata](https://www.marinespecies.org/aphia.php?p=taxdetails&id=451960)
 - unaccepted genus Acanthus: 
<img width="1048" alt="image" src="https://github.com/CatalogueOfLife/testing/assets/327505/7cadc474-4c9e-430f-a1fc-0ff86da1fc73">

 It seems there is a systematic problem with unaccepted names.

**Comment by mdoering** [comment]
Should they not be synonyms? You list an accepted name for all of them in WoRMS at least, so I would expect them to show as synonyms in ColDP/CLB.

The original subfamily issue seems to be sth else though. Any idea how the wrong name id got into the export?

**Comment by bart-v** [comment]
Yes, they should.
For some reason we have limited synonyms to ranks equal or below species.
If we also list higher ranks, will this fix the synonym issue?

**Comment by mdoering** [comment]
That seems likely. It will at least remove most of the bare names I've listed above, although [601 of them were species](https://www.checklistbank.org/dataset/1108/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&rank=species&sortBy=taxonomic&status=bare%20name) - maybe these are all "chained" synonyms that have another synonym as their accepted name?

What is still puzzling me is how the wrong family nameID ended up in the subfamily taxon.

**Comment by bart-v** [comment]
Good
- now removed the limitation of synonyms to species and below
- chained synonyms was also such a limitation: removed that too

Both will be available in the next export 2023-07-01

**Comment by bart-v** [comment]
As you know WoRMS has no Taxon vs. Name concept. Everything is a name.
In Taxon.txt we list all accepted names and assign the NameID the ID of the accepted name. Which is itself for accepted names. <= fine

But, for the cases where an unaccepted taxon/name contains accepted children, we do a trick:
- we change the status of the name from unaccepted to "provisionally accepted" <= probably fine
- but we keep the same logic for the NameID as above <= this is the problem

So I propose, we keep the NameID and TaxonID the same in all cases. OK?
This may cause some side effects in i.e. Synonyms, but we can deal with this later

**Comment by mdoering** [comment]
That sounds right, yes. Just keep the nameID the same as the Taxon.ID or Synonym.ID.
And making unaccepted names which contain accepted children provisionally accepted is also the best option. Unaccepted names without accepted children should become synonyms with nameID = Synonym.ID

**Comment by bart-v** [comment]
OK done, will be available in next export 2023-07-01

**Comment by yroskov** [comment]
Dear @bart-v, would it be possible (as an exception) to do "manual" export of Brachyura and send it to @gdower? We are completing Annual Checklist 2023 on this week. It would be nice to have updated Brachyura in it.

**Comment by yroskov** [comment]
**ver 2023-06-06** (after all fixes); imported 2023-06-06

- [x] Imported: 9560 spp (vs 9593 spp in ver 2023-06-01)

- [ ] Metadata: there are empty fields
Publisher: No information
Creator: No information
Editor: No information
Contributor: No information
Citation: World List of marine Brachyura (ver. (06/2023)). (2023).. https://www.marinespecies.org
- [x] Classification: OK. Infraorder Brachyura - 8 sections (+ family †Montemagrechiridae) - subsection (in Eubrachyura) - superfamily - family - subfamily - genus - species  
- [x] Sector: OK (infraorder Brachyura)

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/40a6281d-767c-41bf-a86c-4086161535f0)

ISSUES assessed 2023-06-06

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/1f6642d1-5d4f-4e09-bd9e-1b0194a5a94e)

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/7806e506-77a1-43a7-9030-f8ec318edf89)

- Broken decisions, 39: deleted all

Resolved 2023-06-06:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/1b7d0f11-ca12-470d-bde2-80f8df3316a8)

**Synced 2023-06-06**

**Comment by yroskov** [comment]
- [ ] See https://github.com/CatalogueOfLife/data/issues/571

In the CoL:
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/9c5f98c7-e7eb-4485-b707-66ff5c491f9c)

WoRMS website:
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/0f105264-dfb9-4416-9c63-48deb1effe20)

**Comment by yroskov** [comment]
**ver 2024-05-01**

- [x] See https://github.com/CatalogueOfLife/data/issues/571 =FIXED

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/b5d85abe-ed4a-46fc-bbfd-10d92f44f4ec)

Resolved 2024-05-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/8a38ec19-0724-42b1-8cae-3bd2f2b15977)

**Re-synced 2024-05-07**

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 15 names with portion _incertae sedis_ = 2 acc & 12 prov acc IGNORED

ISSUES assessed 2025-05-20

![Image](https://github.com/user-attachments/assets/70faf487-b391-452e-ac3e-e027be53c222)

TASKS

![Image](https://github.com/user-attachments/assets/77ded489-6663-400a-97fa-718644c24f03)

- Broken decisions, 92 = deleted
- Outdated decisions, 4 = no action

Resolved 2025-05-20:

![Image](https://github.com/user-attachments/assets/e0833a63-9693-4f65-9107-a221204a4787)

**Synced 2025-05-20**
