### ISSUE TITLE
WoRMS Bryozoa: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#40]
**WoRMS Bryozoa**, id 1081 on prod
https://data.catalogueoflife.org/dataset/1081

- [ ] _Sector:_ phylum Bryozoa. Already established, remained untouched.
- [ ] _Metadata:_ Not updated
- [ ] _Imports:_  **20,562 spp** vs 5,611 in ac19  - **NEED TO BE CHECKED WITH WoRMS WHAT'S HAPPENED** (estimate ~6000 spp)

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-15

- [ ] Conflicting Nomenclatural Status, 3
https://data.catalogueoflife.org/dataset/1081/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&issue=conflicting%20nomenclatural%20status&limit=50&offset=0



Amathia tricornis Busk ms in Chimonides, 1987 | accepted | species aggregate | Vesiculariidae > Amathia

**Comment by yroskov** [comment]
**TASKS** 2021-03-15

![image](https://user-images.githubusercontent.com/28574252/111224228-21a0fd80-85ac-11eb-8e1c-2fa0d26e1177.png)

- [ ] **Identical genus**. Two genera split between different families
![image](https://user-images.githubusercontent.com/28574252/111227202-354e6300-85b0-11eb-82a1-86350f45aa18.png)

- [ ] **Any uninomial** duplicated. Two duplicated names genus vs suborder:

accepted | Esthonioporina | Lavrentjeva, 1975 | genus
-- | -- | -- | -- 
accepted | Esthonioporina | Astrova, 1978 | suborder   
accepted | Halloporina | Astrova, 1965 | suborder
accepted | Halloporina | Bassler, 1913 | genus

**Comment by yroskov** [comment]
Not synced because of not updated metadata.

**Comment by yroskov** [comment]
Checks at preview (of 2021-04-05)

Spp 20,562 - 5611 = +14,951, 15K of them extinct

Missing rank Suboder, but superfamilies are in place.

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/182646702-7075bba9-98b6-4164-9ec8-896f0f063a99.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/182658529-ceda9390-17cd-419e-962a-8c906d7683af.png)

- [ ] Some problems in the classification: 
- infraorders without children taxa
![image](https://user-images.githubusercontent.com/28574252/182659068-c5de53a7-f3c5-4249-90bc-85e45b2eb58f.png)

- "split" of families (TASKS report "Identical family") accepted family name with authorstring and without authorstring located in the same parent
https://www.checklistbank.org/catalogue/3/dataset/1081/duplicates?category=uninomial&limit=500&minSize=2&mode=STRICT&offset=0&rank=family&withDecision=false
![image](https://user-images.githubusercontent.com/28574252/182659577-401d4161-ea8b-42ce-ac2c-f0820170428e.png)

Re-synced 2022-08-03

**Comment by yroskov** [comment]
**ver 2023-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/666e9ded-e913-4c68-90f9-79f31023a6e3)

- Broken decisions, 2: all deleted

Resolved 2023-05-09

**Re-synced 2023-05-09**

**Comment by yroskov** [comment]
**ver 2023-06-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/8993f6ba-d753-4bdf-846e-bee3d5a37e0c)

- Broken decisions, 10: all deleted

Resolved 2023-06-06:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/b824ac4d-c24e-45d0-9728-174958df86fd)

**Re-synced 2023-06-06**

**Comment by yroskov** [comment]
**ver 2025-01-01**

Continue with **Either the opening or closing bracket is missing in the authorship**...
https://www.checklistbank.org/dataset/307413/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&issue=unmatched%20name%20brackets&limit=50&offset=0

@bart-v, double bracket in Eridotrypa maniformis (Owen, 1969)) † https://www.marinespecies.org/aphia.php?p=taxdetails&id=1410994

**Comment by bart-v** [comment]
Fixed

**Comment by yroskov** [comment]
@bart-v, two entries for the genus **Pavolunulites**:

https://www.marinespecies.org/aphia.php?p=taxdetails&id=1378588 = no species
https://www.marinespecies.org/aphia.php?p=taxdetails&id=1378597 

**Stictostega**
https://www.marinespecies.org/aphia.php?p=taxdetails&id=1378547  = no species
https://www.marinespecies.org/aphia.php?p=taxdetails&id=1378735

**Comment by bart-v** [comment]
Fixed in WoRMS

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 10 names with portion _incertae sedis_ = 1 acc & 8 prov acc IGNORED

TASKS

![Image](https://github.com/user-attachments/assets/3233ed84-5f05-4150-9a75-cf7bf9a9f0dc)

- Broken decisions, 22 = deleted

Resolved 2025-05-21:

![Image](https://github.com/user-attachments/assets/dd19bdae-3d8d-48cb-a2cd-ba5ed899568b)

**Synced 2025-05-21**
