### ISSUE TITLE
WoRMS Cephalochordata: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#42]
**WoRMS Cephalochordata**, id 1154 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1154

- [x] _Sector:_ established as subphyllum Cephalochordata (was a child class Leptocardii)
- [ ] _Metadata:_ Not updated
- [x] _Imports:_  30 spp vs 30 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-16

- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-16

 - [x] no issues

![image](https://user-images.githubusercontent.com/28574252/111371280-31c9e300-8667-11eb-9685-9cb6b5d31072.png)

**Comment by yroskov** [comment]
Not synced because of not updated metadata.
