### ISSUE TITLE
WoRMS Ceriantharia: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#43]
**WoRMS Ceriantharia**, id 1179 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1179

- [x] _Sector:_ established as subclass Ceriantharia
Old sectors (orders Penicillaria & Spirularia) were present in Assembly tree only:
![image](https://user-images.githubusercontent.com/28574252/111372444-a6e9e800-8668-11eb-8b62-b99e41706bc3.png)
- [ ] _Metadata:_ Not updated
- [ ] _Imports:_  135 spp vs in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-16

- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-16

![image](https://user-images.githubusercontent.com/28574252/111373413-d9481500-8669-11eb-8861-e35773a01bf7.png)

Resolved:

![image](https://user-images.githubusercontent.com/28574252/111373505-f41a8980-8669-11eb-8605-4322a1cfd8a6.png)

**Comment by yroskov** [comment]
Not synced
