### ISSUE TITLE
WoRMS Cestoda: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#44]
**WoRMS Cestoda**, id 1127 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1127

- [ ] _Sector:_
- [ ] _Metadata:_ Not updated
- [x] _Imports:_  2013 spp vs 1940 in ac19

WoRMS classification:
Biota Animalia (Kingdom) Platyhelminthes (Phylum) 
Direct children (3):
Subphylum Catenulida
Subphylum Rhabditophora
Class Turbellaria (not longer used; is a paraphyletic group)

![image](https://user-images.githubusercontent.com/28574252/111485380-925b2d80-8704-11eb-93c1-f5b42585377b.png)

As sectors appeared after the import, before re-assembly:
class Cestoda in CoL vs subphylum Rhabditophora in GSD
![image](https://user-images.githubusercontent.com/28574252/111485683-d51d0580-8704-11eb-8a8c-8bc42c56cef9.png)

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-17

- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-17

![image](https://user-images.githubusercontent.com/28574252/111504204-6dbb8180-8715-11eb-844b-fa26d1c38b71.png)

Resolved:

![image](https://user-images.githubusercontent.com/28574252/111504486-b5420d80-8715-11eb-8e23-0858ec33e43c.png)

**Comment by yroskov** [comment]
Synced 2021-03-17. **Sync need to be repeated after metadata fixes**

**Comment by yroskov** [comment]
**ver 2021-11-01**

TASKS - few new
![image](https://user-images.githubusercontent.com/28574252/140380384-53868154-554a-42b0-ae21-757a65357e20.png)

Resolved 2021-11-04
(Identical family & Identical genus = all cases parked as acc-prov acc by the dataprovider, no decisions necessary)
![image](https://user-images.githubusercontent.com/28574252/140380852-fd761d5b-6ea9-4cd3-940f-3fc896a83564.png)

**Comment by yroskov** [comment]
**ver 2023-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/f5da4acd-f664-4164-9a07-d8f75189433f)

- Broken decisions, 3: all deleted

Resolved 2023-05-09

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/f064c4a6-65c7-4c0b-aaef-1101b4f46575)

**Re-synced 2023-05-09**

**Comment by yroskov** [comment]
**ver 2024-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/4c5f0109-b3d3-42c0-afcd-1c0f796e54fa)

Resolved 2024-05-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/bf5907f2-e4a9-4bf5-a4e0-dd3060795041)

**Synced 2024-05-07**

**Comment by yroskov** [comment]
**ver 2024-05-01**

TASKS no new issues

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/d170137c-ba80-4985-badb-a90092f7dffb)

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 5 names with portion _incertae sedis_ = 3 prov acc IGNORED

@bart-v, synonym Baerietta ]aegerskioeldi (Janicki, 1926) Hsii, 1935 is misspelled https://www.checklistbank.org/dataset/1127/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=secondarySource&facet=group&issue=indetermined&limit=50&offset=0 

- Incorrect years in Bothriocephalus marginatus Krefft, 18711 _= 1871_ and in Circumoncobothrium yamaguti Jadhav, Gavhane & Sawapkar, 199 _= 1991_


ISSUES assessed 2025-05-20

![Image](https://github.com/user-attachments/assets/7903ed92-fe06-44a0-a6a1-afcc0f19e681)

TASKS

![Image](https://github.com/user-attachments/assets/ecfff6e3-9cc0-4b8e-88d0-9082f0efe3f0)

- Broken decisions, 31 = deleted

Resolved 2025-05-20:

![Image](https://github.com/user-attachments/assets/cb9838a8-bb30-43a8-bae3-a6601c9067e7)

**Synced 2025-05-20**

**Comment by bart-v** [comment]
All issues fixed in WoRMS

**Comment by yroskov** [comment]
- [x] Incomplete family Taeniidae: 8 spp in WoRMS & 60 spp in ITIS (i.e. including non-marine). See https://github.com/CatalogueOfLife/data/issues/358 = family Taeniidae BLOCKED in WoRMS Cestoda and established as a sector in ITIS 2025-11-04
