### ISSUE TITLE
WoRMS Xenoturbellida (id 1100): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#45]
**WoRMS Xenoturbellida**, id 1100 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1100

- [x] _Sector:_ subphylum Xenoturbellida established as a union with classification from WoRMS Turbellarians
- [ ] _Metadata:_ Not updated
- [x] _Imports:_  6 spp vs 6 in ac19

![image](https://user-images.githubusercontent.com/28574252/111497455-1f0ae900-870f-11eb-8784-80b7f33e5cc4.png)

Actions:
1) Delete subtree phylum Xenacoelomorpha [x]
2) Re-assemble classification for phylum Xenacoelomorpha from WoRMS Turbellarians
3) Establish sector for WoRMS Xenoturbellida

Classification in WoRMS Xenoturbellida:

![image](https://user-images.githubusercontent.com/28574252/111506756-f3d8c780-8717-11eb-89b4-97f36e0d2da4.png)

Sector is established as a union with classification from WoRMS Turbellarians

**Comment by yroskov** [comment]
**TASKS** 2021-03-17

No issues:
![image](https://user-images.githubusercontent.com/28574252/111509154-6fd40f00-871a-11eb-8f0d-37fc0cece9b5.png)

**Comment by yroskov** [comment]
- [x] Subphylum Xenoturbellida overlapped in WoRMS Turbellarians and WoRMS Xenoturbellida. Xenoturbellida BLOCKED in WoRMS Turbellarians 2023-05-11. https://github.com/CatalogueOfLife/testing/issues/46#issuecomment-1544675173
