### ISSUE TITLE
WoRMS Turbellarians: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#46]
**WoRMS Turbellarians**, id on prod
link 

- [ ] _Sector:_
- [ ] _Metadata:_
- [ ] _Imports:_  spp vs in ac19

Classification in the phylum Platyhelminthes should be assembled via WoRMS Turbellarians. See https://github.com/CatalogueOfLife/testing/issues/44

Actions:
1) Delete sectors in the phylum Platyhelminthes [x]
2) Delete subtree Platyhelminthes [x]
3) Assemble Platyhelminthes from WoRMS Turbellarians & sync [x]
4) Delete sector?
5) Establish other sectors for WoRMS Cestoda, WoRMS Monogenea, WoRMS Trematoda & WoRMS Turbellarians

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-17

**Comment by yroskov** [comment]
**TASKS** 2021-03-17

**Comment by yroskov** [comment]
- [x] Incorrect logo (fixed - second time?) 
![image](https://user-images.githubusercontent.com/28574252/123297892-99e95a00-d4dd-11eb-89fb-9fa91cb735c3.png)

**Comment by yroskov** [comment]
TASKS 2021-07-09

![image](https://user-images.githubusercontent.com/28574252/125091849-66d6c700-e096-11eb-8e48-348aaf90cbd7.png)

- [x] Broken decisions: 4; re-matched all: 4. Deleted all.

Resolved:

![image](https://user-images.githubusercontent.com/28574252/125092241-c0d78c80-e096-11eb-910f-87fbb246a0d5.png)

**Comment by yroskov** [comment]
**ver 2021-11-01**

TASKS - no changes
![image](https://user-images.githubusercontent.com/28574252/140418902-bf67ab13-e632-4d1f-aac0-a3fcc8e67be0.png)

- [x] Broken decisions, 9; RematchAll, 11 left; deleted all
- [x] Identical superfamily family, genus, subgenus: all cases are flagged as acc - prov acc by the dataprovider; no decisions needed.

Resolved 2021-11-04
![image](https://user-images.githubusercontent.com/28574252/140419417-2437d398-9acd-4e0c-a892-727f7eb374c2.png)

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/183093522-f3b221b8-c4f1-4fe3-b935-8d9aa4d7236a.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/183093905-8a094041-a45a-464e-b521-10df73088620.png)

2022-08-05: sync failed, err 503 (for attention of @mdoering)
![image](https://user-images.githubusercontent.com/28574252/183094422-ccc2a129-50f0-4f8f-bc51-36582e65ab04.png)

**Comment by yroskov** [comment]
**ver 2023-05-01**

TASKS

![image](https://user-images.githubusercontent.com/28574252/236927977-2d088014-fb3b-4bf3-a4ea-5d5c2d7cd6aa.png)

- Broken decisions, 13: all deleted

Resolved 2023-05-08

![image](https://user-images.githubusercontent.com/28574252/236929398-44245edf-7a9d-43fa-a777-5bc80ec68533.png)

**Re-synced 2023-05-08**

**Comment by yroskov** [comment]
- [x] Subphylum Xenoturbellida covered by both WoRMS Turbellarians and WoRMS Xenoturbellida. However, WoRMS Turbellarians has no children species. Xenoturbellida BLOCKED in WoRMS Turbellarians 2023-05-11. 
WoRMS Turbellarians **re-synced 2023-05-11**.

**Comment by yroskov** [comment]
**ver 2023-06-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/675ca571-65c1-4a1f-a2dd-45d6cc5172ee)

- Broken decisions, 6: all deleted

Resolved 2023-06-06:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/89ee8d9d-b278-4e21-bb65-2ddf1fe52c20)

**Re-synced 2023-06-06**

**Comment by yroskov** [comment]
**ver 2024-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/5b26abd1-6e2a-4c2d-9b15-8e51274d31ee)

Resolved 2024-05-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/c19f40be-a41f-4bde-84d1-12e179d6b3c4)

**Re-synced 2024-05-07**

**Comment by yroskov** [comment]
@bart-v, could you please help me to understand what's happened with _WoRMS Turbellarians_ export of 2024-11-01 (https://www.checklistbank.org/dataset/1193/imports).

_WoRMS Turbellarians_ of 2024-11-01 contains **26,086** accepted species compare with ~**5,894** in previous version of 2024-10-01.

As I succeed to find, WoRMS Turbellarians_ of 2024-11-01 overlaps with WoRMS Cestoda, Monogenea & Trematoda in this month. Over 19,500 species are identical (https://www.checklistbank.org/dataset/3/duplicates?authorshipDifferent=false&category=binomial&limit=100&minSize=2&mode=STRICT&offset=0&status=accepted).

I am concerned, did the classification in WoRMS was changed significantly in October, or is there something else causing the problem?

**Comment by bart-v** [comment]
It's not caused by a classification change, but by a merge of lists/contexts, which caused this side-effect

We'll see if we can either remove them again from WoRMS Turbellarians, or merge all 4 lists in one.
We are now discussing this with the editors

**Comment by yroskov** [comment]
Thinking further, I personally would be happy to have the entire WoRMS for CoL in the checklistbank as a single entry. We would then sync the "global sectors" from that export, just like we do with ITIS. 

As you know, checklistbank already has the whole WoRMS, but it is in DwC-A format (https://www.checklistbank.org/dataset/2011/imports). How difficult will it be for you to make this export to CoLDP?

Could you please bring the idea of ​​moving from 65 separate WoRMS checklists to a single WoRMS in CoL for the consideration of the WoRMS editors/leads?

... as a "data consolidation" step in CoL.

**Comment by bart-v** [comment]
We did this for traceability, visibility, and allows easy in- or exclusions of WoRMS GSDs
WoRMS is not the sum of the 65 lists, but much more.
This is something that needs some serious discussion/consideration both in the Data Management Team and the SC
We'll come back to this later.

**Comment by yroskov** [comment]
Just in case, CoL takes 130 global checklists from ITIS into the Global CoL: https://www.checklistbank.org/catalogue/3/sector?limit=100&offset=0&subjectDatasetKey=2144; and rest of ITIS (regional or incomplete checklists) go into Extended Catalogue for GBIF.

ITIS is a single entry in the checklistbank. All global checklists mapped as CoL sectors. I expect that Markus will implement metadata on sector level (now matadata are associated with GSD). So, each sector will be credited to own authors/editors as GSD has now.

**Comment by mdoering** [comment]
@bart-v I would very much support the idea of a single WoRMS list in ChecklistBank as the source for COL sectors. We are working on a new feature that allows to share many metadata files for sections of a dataset. That is needed for example for WFO who are also sharing a single dataset but want different attributions for parts we use. You could then attribute the respective community and list & cite the various responsible authors & contributors. Until that is done I very much see the value of having multiple WoRMS datasets. But once it's deployed I would hope all aggregated sources move towards that scheme

**Comment by bart-v** [comment]
I still can think of some restrictions caused by such a feature.
But let's consider and discuss this when this is deployed and stable.

For this specific Turbellarians problem, we are reverting this error.
We'll let you know when done

**Comment by bart-v** [comment]
Error has been fixed.
You should be able to re-download the 2024-11-01 version

**Comment by yroskov** [comment]
Thanks, Bart!

@gdower, could you please re-do a new import of WoRMS Turbellarians (id 1193)?

**Comment by yroskov** [comment]
**ver 2024-11-08** (replacement for ver. 2024-11-01); imported

- [x] Imported: 5906 spp (vs 26074 in ver. 2024-11-01 vs 5898 in ver. 2024-10-01) 
- [x] Metadata: 
- [x] Classification: OK (No species in the phylum Nemertea in kingdom Protozoa - phylum Euglenozoa = the are not sectors)
- [x] Sectors: OK, 2 phyla Xenacoelomorpha & Platyhelminthes

Metrics

![image](https://github.com/user-attachments/assets/b20abdfb-f3bd-4e0f-aaa6-7952dc4fa464)

TASKS

![image](https://github.com/user-attachments/assets/cb05253f-1768-4083-9054-9a1b5e712118)

- Broken decisions, 32 = deleted

Resolved 2024-11-08:

![image](https://github.com/user-attachments/assets/6557dc09-12f5-41a8-b318-12800ef4f1ad)

**Synced 2024-11-08**

**Comment by yroskov** [comment]
@bart-v, first of all - many thanks for the fixed version. It is now synced in CoL 0f November.

The editors might be interested to know, CLB detected two species entries: _Microstomum caerulescens_ (Schmarda, 1859) Graff, 1882 and _Microstomum caerulescens_ Graff, 1882:
https://www.marinespecies.org/turbellarians/aphia.php?p=taxdetails&id=481476
https://www.marinespecies.org/turbellarians/aphia.php?p=taxdetails&id=852508

**Comment by bart-v** [comment]
Thanks, forwarded to editors

_edit_: and apparently fixed later on, all OK

**Comment by yroskov** [comment]
@bart-v, resolving uninomial duplicates further... (WoRMS ver 2025-01-01)

**Infraphyllum Xenoturbellida** appears twice: in _WoRMS Turbellarians_ (0 sp; with direct parent Xenacoela) and in _WoRMS Xenoturbellida_ (6 spp; direct parent Xenacoelomorpha). At the moment, I blocked it in WoRMS Turbellarians @ CoL

**Comment by bart-v** [comment]
Only one entry for `Xenoturbellida`
Can you provide both AphiaID/LSID?

**Comment by bart-v** [comment]
Fixed, available in next export.

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 3 names with portion _incertae sedis_ = 2 prov acc IGNORED

@bart-v, for your/editors' attention:

- **Rhynchodemus** in a rank of superfamily inside family: https://www.marinespecies.org/turbellarians/aphia.php?p=taxdetails&id=414992  

ISSUES assessed 2025-05-20

![Image](https://github.com/user-attachments/assets/c3dd3fbe-8b77-4529-bde6-9c2f76a7bab2)

TASKS

![Image](https://github.com/user-attachments/assets/ea6949b3-08ed-4129-8f65-ab7109e0f2df)

- Broken decisions, 24 = deleted

Resolved 2025-05-20:

![Image](https://github.com/user-attachments/assets/63df0e81-e561-4b25-958b-51e2d231e952)

**Synced 2025-05-20**

**Comment by bart-v** [comment]
Rhynchodemus = fixed/deleted

**Comment by yroskov** [comment]
**ver. 2026-01-01**

TASKS

<img width="1671" height="1203" alt="Image" src="https://github.com/user-attachments/assets/3ae67601-4214-4bd9-82bf-3436f47f0aef" />

Resolved 2026-01-13:

<img width="1671" height="1184" alt="Image" src="https://github.com/user-attachments/assets/d1746d00-29e6-44bf-a022-a644ab148840" />

**Re-synced 2026-01-13**

**Comment by yroskov** [comment]
**ver. 2026-08-01** 

TASKS

<img width="1788" height="1291" alt="Image" src="https://github.com/user-attachments/assets/c2132894-29e1-436c-b18a-62345ac6b6f1" />

- Broken decisions, 5 = deleted

Resolved 2026-08-05:

<img width="1792" height="1293" alt="Image" src="https://github.com/user-attachments/assets/e9860057-10d3-4126-ad4e-ffe6a89250a4" />

**Re-synced 2026-08-05**
