### ISSUE TITLE
WoRMS Monogenea: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#47]
**WoRMS Monogenea**, id 1126 on prod
https://data.catalogueoflife.org/dataset/1126

- [x] _Sector:_ class Monogenea
- [ ] _Metadata:_ Not updated
- [ ] _Imports:_  5367 spp vs 4995 in ac19 -- ?

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-17

- [x] **Uppercase Epithet**, 6 - blocked in CoL
https://data.catalogueoflife.org/catalogue/3/dataset/1126/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&issue=uppercase%20epithet&limit=100&offset=0

- [ ] **Indetermined**, 47. Genus **Diplectanum [sensu lato]** split from Diplectanum. The case remain unresolved. 
https://data.catalogueoflife.org/catalogue/3/dataset/1126/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&issue=indetermined&limit=100&offset=0

**Comment by yroskov** [comment]
**TASKS** 2021-03-17

![image](https://user-images.githubusercontent.com/28574252/111516890-75355780-8722-11eb-8b9c-326424815333.png)

Resolved:

![image](https://user-images.githubusercontent.com/28574252/111517334-f4c32680-8722-11eb-9873-bef877d24215.png)

**Comment by yroskov** [comment]
Synced 2021-03-17. **Sync need to be repeated after metadata fixes**

**Comment by yroskov** [comment]
Checks at preview (of 2021-04-05)

Spp 5367 - 4995 = 372

All ranks are present correctly.

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/182877670-0015c9b4-c99c-43e9-b687-e90971fb0ca7.png)

Resolved:

- [ ] The same genus in the same parent family flagged as "Accepted" and second time as "Provisionally accepted" (5 pairs in the Task report Identical Genus:
https://www.checklistbank.org/catalogue/3/dataset/1126/duplicates?category=uninomial&limit=500&minSize=2&mode=STRICT&offset=0&rank=genus&withDecision=false
![image](https://user-images.githubusercontent.com/28574252/182878587-28e1052a-f710-49b6-9ed7-e83e0987c303.png)
 


Re-synced 2022-08-04

**Comment by yroskov** [comment]
**ver 2023-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/5518a09f-9a47-49c2-b124-0361bf91789e)

- Broken decisions, 3: all deleted

Resolved 2023-05-10

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/4ff7c05d-acb6-457a-bdc8-dd8ced5602d0)

**Re-synced 2023-05-10**

**Comment by yroskov** [comment]
**ver 2023-06-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/b26a58b2-5806-4bcb-adae-95b36e9436ca)

- Broken decisions, 4: all deleted

Resolved 2023-06-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/0062d9c6-390d-4890-99bd-8100f1199b16)

**Re-synced 2023-06-07**

**Comment by yroskov** [comment]
**ver. 2024-11-01**

TASKS 

![image](https://github.com/user-attachments/assets/711a8c76-9058-4b19-9a9f-16f4de3f34c6)

- Broken decisions, 27 = deleted

Resolved 2024-11-08

![image](https://github.com/user-attachments/assets/9827de87-7692-4270-a4c5-1f0d358c36b4)

**Re-synced 2024-11-08**

**Comment by yroskov** [comment]
**ver. 2025-01-01**

TASKS

![image](https://github.com/user-attachments/assets/08708d90-f190-496e-bab7-2e0a3c9b73f9)

- Broken decisions, 24 = deleted

Resolved 2025-01-13:

![image](https://github.com/user-attachments/assets/4025ed67-b985-41bd-9d93-cc274daa088d)

**Re-synced 2025-01-13**

**Comment by yroskov** [comment]
**ver. 2025-02-01**

TASKS

![Image](https://github.com/user-attachments/assets/7f1d2af3-1124-4260-9695-ebae0c42b3d9)

- broken decisions, 23 = deleted

Resolved 2025-02-06:

![Image](https://github.com/user-attachments/assets/1468af2e-a177-4d22-bf25-dbbd7c750dcb)

**Re-synced 2025-02-06**

**Comment by yroskov** [comment]
bart-v, (one more finding of today), there are two entries for **Gyrodactylus serrai Přikrylová, Truter, Luus‑Powell, Chakona & Smit, 2024** in Monogenea:
https://www.marinespecies.org/aphia.php?p=taxdetails&id=1775443
https://www.marinespecies.org/aphia.php?p=taxdetails&id=1775444

**Comment by bart-v** [comment]
Fixed in WoRMS

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 15 names with portion _incertae sedis_ = 9 acc & 6 prov acc IGNORED

@bart-v, FYI:

- Unmatched Name Brackets, [3](https://www.checklistbank.org/dataset/1126/names?issue=unmatched%20name%20brackets) 

ISSUES assessed 2025-05-21

![Image](https://github.com/user-attachments/assets/c325cc0e-fc75-431a-be7a-217caaacfd69)

TASKS

![Image](https://github.com/user-attachments/assets/fb763216-208b-4c9a-9c8c-b3f5ffff6ee7)

- Broken decisions, 23 = deleted

Resolved 2025-05-21:

![Image](https://github.com/user-attachments/assets/b1b72d22-9323-4972-9128-1b427ce8240a)

**Synced 2025-05-21**

**Comment by bart-v** [comment]
*sigh*
Unmatched Name Bracket = fixed

**Comment by yroskov** [comment]
**ver. 2025-09-01**

TASKS

<img width="1325" height="929" alt="Image" src="https://github.com/user-attachments/assets/339d0e6f-c915-490b-9a6f-a6e65c0e2dab" />

Resolved 2025-09-11:

<img width="1343" height="964" alt="Image" src="https://github.com/user-attachments/assets/1765acb8-b0da-40d7-850e-2b9ce239bd1a" />

**Re-synced 2025-09-11**

**Comment by yroskov** [comment]
**ver. 2026-09-01**

TASKS

<img width="1770" height="1228" alt="Image" src="https://github.com/user-attachments/assets/06ffad54-b7b1-4a71-ae45-a4f9cd05bc1d" />

- Broken decisions, 39 = deleted
- Outdated decisions, 2 = no action

@bart-v , it looks like **Aglaiogyrodactylus marinae Dalmas‑Branchi. Da Silva, Domingues, Robe & Vianna, 2026** is duplicated (at least, in the export for CoL)

Resolved 2026-09-04:

<img width="1800" height="1293" alt="Image" src="https://github.com/user-attachments/assets/461255af-61ca-4688-b01d-521b4ac7f2f0" />

**Re-synced 2026-09-04**

**Comment by bart-v** [comment]
Fixed in WoRMS
