### ISSUE TITLE
WoRMS Trematoda: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#48]
**WoRMS Trematoda**, id 1128 on prod
https://data.catalogueoflife.org/dataset/1128

- [ ] _Sector:_ class Trematoda
- [ ] _Metadata:_ Not updated
- [ ] _Imports:_ 7418 spp vs 5975 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-17

**Comment by yroskov** [comment]
**TASKS** 2021-03-17

![image](https://user-images.githubusercontent.com/28574252/111520246-ec201f80-8725-11eb-8e22-7fbbc3242f30.png)

- [ ] **Identical family**, 1   FOR ATTENTION OF WORMS AUTHORS  : two identical families, one is with typo in the authorstring
https://data.catalogueoflife.org/catalogue/3/dataset/1128/duplicates?category=uninomial&limit=500&minSize=2&mode=STRICT&offset=0&rank=family&withDecision=false

Moreauiidae Johnstone, 1915
Moreauiidae Johnston, 1915

Remain unresolved in CoL.

Resolved:

![image](https://user-images.githubusercontent.com/28574252/111521615-51284500-8727-11eb-845c-698bab786e1f.png)

**Comment by yroskov** [comment]
Synced 2021-03-17. **Sync need to be repeated after metadata fixes**

**Comment by yroskov** [comment]
Checks at preview (of 2021-04-05)

**Comment by yroskov** [comment]
**ver 2021-11-01**

TASKS - there are changes
![image](https://user-images.githubusercontent.com/28574252/140417627-9ce6cd7b-73bf-47cb-9b40-3545310e8272.png)

- [x] Broken decisions, 0
- [x] Identical family, genus: all cases are flagged as acc - prov acc by the dataprovider; no decisions needed.

Resolved 2021-11-04
![image](https://user-images.githubusercontent.com/28574252/140417929-746eeff1-be4c-435e-a592-81d4b1910576.png)

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/183090006-8bb38569-7031-4636-a42b-c859104e16ac.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/183090316-3db01e20-930d-49a5-9613-7971c7213592.png)

Synced 2022-08-05

**Comment by mdoering** [comment]
Ah, the importer is offline. Turned it back on again now

**Comment by yroskov** [comment]
Thanks! All remaining checklists synced now.

**Comment by yroskov** [comment]
**ver 2023-06-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/7aa2379d-ea88-4d1c-8cc0-e94e315cba16)

- Broken decisions, 15: all deleted

Resolved 2023-06-06:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/5c7e18ce-a344-46cd-97a8-905671f2c051)

**Re-synced 2023-06-06**

**Comment by yroskov** [comment]
**ver 2024-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/66012ea6-c0fd-4907-8a85-9c46f5ee9bed)

Resolved 2024-05-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/6d359e7a-13c1-4621-8b3f-843845d8e7ee)

**Re-synced 2024-05-07**

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 2 names with portion _incertae sedis_ = 2 prov acc IGNORED

@bart-v, few issues:
- Unlikely Year, [6](https://www.checklistbank.org/dataset/1128/names?issue=unlikely%20year) - _few years written as 1010, 1044, 1060 (shouldbe 1910, 1944, 1960, I guess)_
- Unparsable Authorship, [193](https://www.checklistbank.org/dataset/1128/names?issue=unparsable%20authorship) - _misspelled years, e.g. Rudolphi, 18189;  (Johnston, l9l7); La Valette, 185 or unnecessary dots (e.g. (Rudolphi, 1819) Looss, 1899.)_
- [ACC-ACC species (different authors) 6 of 20](https://www.checklistbank.org/catalogue/3/dataset/1128/duplicates?_colCheck=c1) - there are some suspicious duplicated names with slightly different authorstrings

ISSUES assessed 2025-05-20

![Image](https://github.com/user-attachments/assets/fe9b27fb-d60e-42cc-8038-0ad6a7e6b545)

TASKS

![Image](https://github.com/user-attachments/assets/525bceae-20ae-4f21-b50c-25d9fc2ea98c)

- Broken decisions, 99 = deleted

Resolved 2025-05-20:

![Image](https://github.com/user-attachments/assets/bd09195d-0c4a-4bc1-be39-3e3849e891d6)

**Synced 2025-05-20**

**Comment by bart-v** [comment]
- 6x Unlikely Year = fixed
- unparsable authorities of _Cercaria caribbea_ are unavailable names, they can/should stay

**Comment by yroskov** [comment]
**ver. 2025-10-01**

TASKS

<img width="1591" height="1063" alt="Image" src="https://github.com/user-attachments/assets/f9df2aa2-c84b-485c-9ebf-3b89198ea095" />

Resolved 2025-10-06:

<img width="1591" height="1047" alt="Image" src="https://github.com/user-attachments/assets/c3a46b5c-e4a5-401d-b3d2-9292c85d9bb9" />

**Re-synced 2025-10-06**

**Comment by yroskov** [comment]
**ver. 2026-08-01** 

TASKS

<img width="1813" height="1245" alt="Image" src="https://github.com/user-attachments/assets/87dc5e4a-2a2d-4541-8d42-3fa3f25f35df" />

- Broken decisions, 13 = deleted
- Outdated decisions, 1 = no action

Resolved 2026-08-05:

<img width="1820" height="1293" alt="Image" src="https://github.com/user-attachments/assets/4210fba7-21be-456e-8acb-f845ddcdad5a" />

**Re-synced 2026-08-05**
