### ISSUE TITLE
WoRMS Chaetognatha: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#49]
**WoRMS Chaetognatha**, id 1132 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1132

- [x] _Sector:_ phylum Chaetognatha (pre-existed)
- [ ] _Metadata:_ Not updated
- [ ] _Imports:_  132 spp vs 132 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-17

- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-17

No issues.

![image](https://user-images.githubusercontent.com/28574252/111528709-7a4cd380-872f-11eb-9d2f-08194a2e8d1c.png)

**Comment by yroskov** [comment]
Not synced.
