### ISSUE TITLE
WoRMS Copepoda: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#50]
**WoRMS Copepoda**, id 1191 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1191

- [x] _Sector:_ subclass Copepoda
- [ ] _Metadata:_ Not updated
- [x] _Imports:_  14751 spp vs 14740 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-17

- [x] **Multi Word Epithet**, 2 - blocked in CoL
https://data.catalogueoflife.org/catalogue/3/dataset/1191/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&issue=multi%20word%20epithet&limit=100&offset=0

- [x] **Indetermined**, 3, the same names are in Uppercase Epithet, Parsed Name Differs & Partially Parsable Name
- modified in CoL, but not properly resolved.
https://data.catalogueoflife.org/catalogue/3/dataset/1191/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&issue=indetermined&limit=100&offset=0

@mdoering, @gdower It looks like, parts of 3 names are misplaced in CoL fields by the parser. Presentation in WoRMS is OK:
http://www.marinespecies.org/copepoda/aphia.php?p=taxdetails&id=1374555

**Comment by yroskov** [comment]
**TASKS** 2021-03-17

![image](https://user-images.githubusercontent.com/28574252/111535742-71600000-8737-11eb-8d90-2fe7ccf732d7.png)

- [x] **ACC-ACC species (same authors)**:  110 names with empty fields. All blocked.
https://data.catalogueoflife.org/catalogue/3/dataset/1191/duplicates?authorshipDifferent=false&category=binomial&limit=500&minSize=2&mode=STRICT&offset=0&status=accepted    

![image](https://user-images.githubusercontent.com/28574252/111537367-59897b80-8739-11eb-91fc-f98005311c84.png)

**Comment by yroskov** [comment]
Not synced

**Comment by yroskov** [comment]
**ver 2021-11-01**

TASKS - few changes in Identical family, genus, uninomial; all resolved as acc - prov acc by the data provider, no decisions needed
![image](https://user-images.githubusercontent.com/28574252/140381373-b872c7e7-d4c2-41b4-83aa-94749e63b855.png)

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/182678893-b18904a2-1d64-46ec-b101-4da74747bf20.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/182679268-02eca96b-cf26-4bb9-9fb1-5a1f7db7c0a0.png)

Re-synced 2022-08-03

**Comment by yroskov** [comment]
**ver 2023-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/1661e137-2c7b-4e68-b689-960d7d2a208e)

- Broken decisions, 5: all deleted

Resolved 2023-05-09

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/1c511248-4fda-43c7-b493-065d61ff515b)

**Re-synced 2023-05-09**

**Comment by yroskov** [comment]
**ver 2024-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/6c7ed469-db8f-4714-ac1f-0a2ca504fcce)

Resolved 2024-05-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/e937ddce-b669-4d7a-bb67-68606b03fe68)

**Synced 2024-05-07**

**Comment by yroskov** [comment]
2024-09-23: rank "natio" excluded from accepted taxa in the sector.
Affected only 2 names: Mesocyclops leuckarti natio micrura Kiefer, 1929 & Oithona attenuata natio trisetosa Früchtl, 1923 
**Re-synced 2024-09-23**

**Comment by yroskov** [comment]
**ver 2025-01-01**

Continue with **Either the opening or closing bracket is missing in the authorship**...
https://www.checklistbank.org/dataset/307413/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&issue=unmatched%20name%20brackets&limit=50&offset=0

@bart-v, something with brackets in Tortanus (Boreotortanus) discaudatus (Thompson I.C. & Scott A.) In Herdman, Thompson & Scott, 1897) https://www.marinespecies.org/copepoda/aphia.php?p=taxdetails&id=720592

And missing bracket in Eucalanus elongatus elongatus (Dana, 1849-1852 https://www.marinespecies.org/copepoda/aphia.php?p=taxdetails&id=847452

**Comment by yroskov** [comment]
**ver 2025-01-01**

Continue with **Either the opening or closing bracket is missing in the authorship**...
https://www.checklistbank.org/dataset/307413/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&issue=unmatched%20name%20brackets&limit=50&offset=0

@bart-v, single bracket in Geeopsis Huys, 1996 in Huys, Gee, Moore & Hamond, 1996) https://www.marinespecies.org/copepoda/aphia.php?p=taxdetails&id=115442

**Comment by bart-v** [comment]
Fixed

**Comment by yroskov** [comment]
- [x] Class Copepoda missing in COL https://github.com/CatalogueOfLife/data/issues/1000

...but the sector is shown as healthy.

![Image](https://github.com/user-attachments/assets/b3ee0f9e-11c6-4a60-bde1-a847fee7a221)

MD: The sector has ranks configured which exclude the class itself 
Rank Class is included now, 2025-04-09.

**Re-synced 2025-04-09**

**Comment by yroskov** [comment]
@bart-v, unresolved homonymic subfamilies in Copepoda:

Cyclopinae Kiefer, 1927 (= prov acc in CoL now) vs Cyclopinae Dana, 1853-1855

**Comment by bart-v** [comment]
Feedback send to editors

**Comment by bart-v** [comment]
OK, fixed in WoRMS

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 13 names with portion _incertae sedis_ = 1 acc & 7 prov acc IGNORED; 2 syn BLOCKED

@bart-v, FYI:

- Unmatched Name Brackets, [3](https://www.checklistbank.org/dataset/1191/names?issue=unmatched%20name%20brackets) 

ISSUES assessed 2025-05-21

![Image](https://github.com/user-attachments/assets/c5f125a9-87ff-402c-8953-101f0bbac087)

TASKS

![Image](https://github.com/user-attachments/assets/919d1e93-d6dc-48f8-aab1-af07363e34e9)

- Broken decisions, 147 = deleted

Resolved 2025-05-21:

![Image](https://github.com/user-attachments/assets/fbda47be-27a1-4dd7-9084-c1b6f037240a)

**Synced 2025-05-21**

**Comment by bart-v** [comment]
Unmatched Name Brackets = fixed

**Comment by yroskov** [comment]
**ver. 2025-10-01**

TASKS

<img width="1591" height="1063" alt="Image" src="https://github.com/user-attachments/assets/9ecfd79c-ed85-4a88-a8b7-ee08db357f6c" />

Resolved 2025-10-06:

<img width="1591" height="1047" alt="Image" src="https://github.com/user-attachments/assets/4de89ec7-f120-4bd6-9ac2-08c9ef5899bc" />

**Re-synced 2025-10-06**

**Comment by yroskov** [comment]
**ver. 2025-12-12**

TASKS

<img width="1617" height="1063" alt="Image" src="https://github.com/user-attachments/assets/fb4dfe55-2839-4337-aa97-d121fcbc4f98" />

- Broken decisions, 8 = deleted

Resolved 2025-12-12:

<img width="1617" height="1047" alt="Image" src="https://github.com/user-attachments/assets/560acba6-4403-47ef-b6a5-8f632aabf517" />

**Re-synced 2025-12-12**

**Comment by yroskov** [comment]
**ver 2026-02-01**

TASKS

<img width="1652" height="1203" alt="Image" src="https://github.com/user-attachments/assets/3413ead9-6ad8-4c64-aeb9-f5b63589d796" />

Resolved 2026-02-04:

<img width="1661" height="1184" alt="Image" src="https://github.com/user-attachments/assets/d88983f0-a01c-4456-ad07-98fd0059bf38" />

**Re-synced 2026-02-04**

**Comment by yroskov** [comment]
@bart-v, there are double entries for _Hemidiaptomus ignatovi khlebovichi_:

https://www.marinespecies.org/copepoda/aphia.php?p=taxdetails&id=1867789
and
https://www.marinespecies.org/copepoda/aphia.php?p=taxdetails&id=1867750 

and for _Phyllodiaptomus (Ctenodiaptomus) praedictus sulawesensis_:

https://www.checklistbank.org/dataset/1191/taxon/urn%3Alsid%3Amarinespecies.org%3Ataxname%3A852026
and 
https://www.checklistbank.org/dataset/1191/taxon/urn%3Alsid%3Amarinespecies.org%3Ataxname%3A1863853

**Comment by bart-v** [comment]
Fixed in WoRMS
