### ISSUE TITLE
WoRMS Tantulocarida: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#51]
**WoRMS Tantulocarida**, id 1092 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1092

- [x] _Sector:_ subclass Tantulocarida
- [ ] _Metadata:_ Not updated
- [x] _Imports:_ 38 spp vs 38 in ac19

**Comment by yroskov** [comment]
**TASKS** 2021-03-17

- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-17

No issues

![image](https://user-images.githubusercontent.com/28574252/111538136-517e0b80-873a-11eb-9411-11d7693d54d2.png)

**Comment by yroskov** [comment]
WoRMS Copepoda, ver. (06/2022) / **2022-06-01**

- [x] **Broken sector**. Was **subclass** Tantulocarida in class Hexanauplia. Now **class** Tantulocarida in subphylum Crustacea
= Re-assembled, synced 2022-06-09
