### ISSUE TITLE
WoRMS Corallimorpharia: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#52]
**WoRMS Corallimorpharia**, id 1195 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1195

- [x] _Sector:_ order Corallimorpharia
- [ ] _Metadata:_ Not updated
- [x] _Imports:_  48 spp vs 48 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-17

- [ ] **Subspecies Assigned**, 3   - these are multi-word species (as names were published). I hope, clearinghouse did not convert them in subspecies.
synonym | Actinothrix sancti thomae Duchassaing de Fonbressin & Michelotti, 1860 
synonym | Actinotryx sancti thomae Duchassaing de Fonbressin & Michelotti, 1860
synonym | Rhodactis sancti thomae (Duchassaing & Michelotti, 1860)

**Comment by yroskov** [comment]
**TASKS** 2021-03-17

![image](https://user-images.githubusercontent.com/28574252/111543457-14694780-8741-11eb-9cb0-1ebb9506dcb2.png)

Resolved: 

![image](https://user-images.githubusercontent.com/28574252/111543567-3d89d800-8741-11eb-82fc-9a41c8865e51.png)

**Comment by yroskov** [comment]
Not synced
