### ISSUE TITLE
WoRMS Ctenophora: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#53]
**WoRMS Ctenophora**, id 1180 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1180

- [x] _Sector:_ Phylum Ctenophora (wasn't broken)
- [ ] _Metadata:_ Not updated
- [x] _Imports:_  214 spp vs 200 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-18
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-18

![image](https://user-images.githubusercontent.com/28574252/111690483-3c1ce600-87fb-11eb-8691-1bc79c977af4.png)

Resolved:

![image](https://user-images.githubusercontent.com/28574252/111690569-5b1b7800-87fb-11eb-81cd-a604176cf5ab.png)

**Comment by yroskov** [comment]
Synced 2021-03-18. **Sync need to be repeated after metadata fixes**

**Comment by yroskov** [comment]
**ver 2022-08-03**

TASKS
![image](https://user-images.githubusercontent.com/28574252/182679756-8206ed06-5a63-4357-996d-8daa41a3c319.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/182680022-69d562c8-88c8-4bca-ad4e-c06e8fd165e2.png)

Re-synced 2022-08-03

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 4 names with portion _incertae sedis_ = 3 prov acc IGNORED

ISSUES assessed 2025-05-22

![Image](https://github.com/user-attachments/assets/28f601f4-cbac-4588-a98a-99b5e2959979)

TASKS

![Image](https://github.com/user-attachments/assets/532ddca3-727c-45e1-acf3-41c7889a61e0)

- Broken decisions, 2 = deleted

Resolved 2025-05-22:

![Image](https://github.com/user-attachments/assets/a41cdc46-2f7c-481c-aa96-73cb3487fb79)

**Synced 2025-05-22**
