### ISSUE TITLE
WoRMS Cubozoa: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#54]
**WoRMS Cubozoa**, id 1181 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1181

- [x] _Sector:_ class Cubozoa (was not broken)
- [ ] _Metadata:_ Not updated
- [x] _Imports:_  49 spp vs 47 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-18
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-18

No issues.

![image](https://user-images.githubusercontent.com/28574252/111694319-bcdde100-87ff-11eb-8b77-f46524b22dd6.png)

**Comment by yroskov** [comment]
Not synced
