### ISSUE TITLE
WoRMS Cumacea (id 1058): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#55]
**WoRMS Cumacea**, id 1058 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1058

- [x] _Sector:_ order Cumacea. Was broken. Established.
- [ ] _Metadata:_ Not updated
- [x] _Imports:_  1734 spp vs 1734 in ac19
https://data.catalogueoflife.org/catalogue/3/dataset/1058

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-18
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-18

![image](https://user-images.githubusercontent.com/28574252/111696395-42629080-8802-11eb-9e7f-6eaafd0ccdfa.png)

Resolved:

![image](https://user-images.githubusercontent.com/28574252/111696496-5dcd9b80-8802-11eb-91f1-557724641e92.png)

**Comment by yroskov** [comment]
Not synced

**Comment by yroskov** [comment]
**ver 2021-11-01**

TASKS - no changes
![image](https://user-images.githubusercontent.com/28574252/140382176-0f79ccdf-4ba1-4abf-873e-c436b3a4f7c0.png)
