### ISSUE TITLE
WoRMS Echinoidea (id 1106): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#56]
**WoRMS Echinoidea**id 1106 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1106

- [x] _Sector:_ class Echinoidea (subphyla above are established - in phylum Echinodermata 
- [ ] _Metadata:_ Not updated
- [x] _Imports:_ 4273 spp vs 4152 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-19
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-19 

![image](https://user-images.githubusercontent.com/28574252/111800005-8785d180-8899-11eb-819d-8bec88e3c2f2.png)

- [x] **ACC-ACC species (same authors)**. Resolved in CoL. Might be interesting for WoRMS authors. 
Two species Macraster ibizaensis Jeannet, 1934 & Macraster obtritus Lambert, 1931 appear twice in the checklist.

**Comment by yroskov** [comment]
Synced. Sync need to be repeated after metadata fixes

**Comment by yroskov** [comment]
**ver 2023-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/8380cf2e-f2f6-4207-9edf-e44c1cfc8fbc)

- Broken decisions, 0

Resolved 2023-05-10

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/d25842e4-93b1-44a8-ac70-74623fe13823)

**Re-synced 2023-05-10**

**Comment by yroskov** [comment]
**ver 2023-06-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/9421e72a-d912-4d41-8e77-db4b1881f277)

- Broken decisions, 4: all deleted

Resolved 2023-06-08:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/26d138f0-02b0-4911-b2da-2b2264eae637)

**Re-synced 2023-06-08**

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 26 names with portion _incertae sedis_ = 8 acc & 15 prov acc IGNORED

ISSUES assessed 2025-05-21

![Image](https://github.com/user-attachments/assets/2f508464-efd1-4401-841c-597b5f787ec8)

TASKS

![Image](https://github.com/user-attachments/assets/d96bdc1d-eb2f-46e9-aadd-0bb089699e63)

Resolved 2025-05-21:

![Image](https://github.com/user-attachments/assets/97cb9883-2584-447a-8fe1-cf2fbf849f29)

**Synced 2025-05-21**

**Comment by yroskov** [comment]
**ver. 2026-01-01**

TASKS

<img width="1671" height="1203" alt="Image" src="https://github.com/user-attachments/assets/3b1588fe-c940-4c32-9b0f-733c7af04011" />

Resolved 2026-01-13:

<img width="1671" height="1203" alt="Image" src="https://github.com/user-attachments/assets/8f092286-aeeb-4875-bcd6-5e7050f9c748" />

**Re-synced 2026-01-13**
