### ISSUE TITLE
WoRMS Holothuroidea: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#57]
**WoRMS Holothuroidea**, id 1107 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1107

- [x] _Sector:_ class Holothuroidea established
- [ ] _Metadata:_ Not updated
- [x] _Imports:_  1815 spp vs 1808 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-
- [x] **Unparsable Authorship** - few names flagged as Misapplied Names ("non")

**Comment by yroskov** [comment]
**TASKS** 2021-03-19

![image](https://user-images.githubusercontent.com/28574252/111826097-4223cd00-88b6-11eb-9443-039d8d201077.png)

Resolved:

![image](https://user-images.githubusercontent.com/28574252/111826251-77c8b600-88b6-11eb-86d7-74d0d170415b.png)

**Comment by yroskov** [comment]
Synced 2021-03-19. **Sync need to be repeated after metadata fixes**

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/182681929-efc0e722-219a-49ad-abca-c340db8a6e7c.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/182682257-1e1172a0-517e-4966-9280-232c45bf7702.png)

Re-synced 2022-08-03

**Comment by yroskov** [comment]
**ver 2023-06-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/3d5ee1a6-cc7a-4898-8cfb-e16f0e001c24)

- Broken decisions, 2: all deleted

Resolved 2023-06-06:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/e45a3b61-da81-445f-b025-01996e8a4530)

**Re-synced 2023-06-06**

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 6 names with portion _incertae sedis_ = 1 acc & 2 prov acc IGNORED

ISSUES assessed 2025-05-21

![Image](https://github.com/user-attachments/assets/0484d39e-843c-4471-9d93-ee240d3a699b)

TASKS

![Image](https://github.com/user-attachments/assets/3bd7aaa2-dd39-460f-b887-f5dfd3d524f8)

- Broken decisions, 12 = deleted

Resolved 2025-05-21:

![Image](https://github.com/user-attachments/assets/c5115156-792f-4335-8482-be46e03d6c37)

**Synced 2025-05-21**
