### ISSUE TITLE
WoRMS Ophiuroidea (id 1059): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#58]
WoRMS Ophiuroidea, id 1059 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1059

- [x] _Sector:_ class Ophiuroidea established
- [ ] _Metadata:_ Not updated
- [x] _Imports:_  2409 spp vs 2379 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-19
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-19

![image](https://user-images.githubusercontent.com/28574252/111827865-6bddf380-88b8-11eb-9f18-f1bab93e4e2d.png)

Resolved:

![image](https://user-images.githubusercontent.com/28574252/111828212-f6beee00-88b8-11eb-87ba-cebfb29938a7.png)

**Comment by yroskov** [comment]
Synced 2021-03-19. **Sync need to be repeated after metadata fixes**

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/182904793-17840e1a-636c-45ce-930b-deb9b2684f1f.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/182905126-d43c9833-e9b7-46a5-a765-fd7bad839ec8.png)

Re-synced 2022-08-04

**Comment by yroskov** [comment]
**ver 2023-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/2be29b83-2688-4523-b985-77c83544ece4)

- Broken decisions, 2: all deleted

Resolved 2023-05-10

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/92eb73bf-aa00-43cb-98f9-fd37c85394b0)

**Re-synced 2023-05-10**

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 6 names with portion _incertae sedis_ = 6 prov acc IGNORED

ISSUES assessed 2025-05-22

![Image](https://github.com/user-attachments/assets/700175d4-ce1f-4bcd-97c7-2d3b51d1242b)

TASKS

![Image](https://github.com/user-attachments/assets/4f05ff0d-701c-43af-9b07-3d861471186b)

- Broken decisions, 14 = deleted

Resolved 2025-05-22:

![Image](https://github.com/user-attachments/assets/15672ec1-5b89-4117-8b02-f34121b7bac7)

**Synced 2025-05-22**
