### ISSUE TITLE
WoRMS Zoantharia (id 1197): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#59]
**WoRMS Zoantharia**, id 1197 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1197

- [ ] _Sector:_ order Zoantharia established
- [ ] _Metadata:_ Not updated
- [x] _Imports:_ 282 spp vs 288 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-19
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-19

No issues.

![image](https://user-images.githubusercontent.com/28574252/111832399-bb272280-88be-11eb-8d66-45e67423ef9c.png)

**Comment by yroskov** [comment]
Synced 2021-03-19. **Sync need to be repeated after metadata fixes**
