### ISSUE TITLE
Systema Dipterorum: **diptera-flat-dev** test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#6]

**Comment by yroskov** [comment]
- [ ] Cases of incorrectly applied brackets in accepted species authorstrings when Present_Genus = Original_Genus & Valid_Species = Species & Valid_Sp_Author = Author

_Example:_
https://data.catalogueoflife.org/dataset/2244/taxon/Limoniidae-Limoniinae-Limonia-Dicranomyia-phatta-7ab9fc7c3

Limonia (Dicranomyia) phatta **(Philippi, 1865)**  - should be **Philippi, 1865**
Synonyms
= Limnobia phatta **Philippi, 1865** (acceptable) 
= Limnobia stictica Blanchard, 1852
= Furcomyia blanchardi Alexander, 1913 

However, brackets are allready correct in cases, where Present_Genus ≠ Original_Genus & Valid_Species = Species & Valid_Sp_Author 

_We are building names and relationships from the following fields:_
acc: Present_Genus+Valid_Species+Valid_Sp_Author	
syn: Original_Genus+Species+Author+Year

_Tasks:_ apply year in accepted authorstring and decide where brackets should be added or not.

1) If Present_Genus = Original_Genus & Valid_Species = Species & Valid_Sp_Author = Author => take Author+Year, **no brackets**

2) If Present_Genus ≠ Original_Genus & Valid_Species = Species & Valid_Sp_Author = Author =>
take Author+Year, **add brackets**

3) If Present_Genus = Original_Genus & Valid_Species ≠ Species & Valid_Sp_Author = Author => no action

4) If Present_Genus = Original_Genus & Valid_Species = Species & Valid_Sp_Author ≠ Author => just keep Valid_Sp_Author, no year    _curious case_, but may appear

5) If Present_Genus ≠ Original_Genus & Valid_Species ≠ Species & Valid_Sp_Author ≠ Author => no action

6) If Present_Genus ≠ Original_Genus & Valid_Species = Species & Valid_Sp_Author ≠ Author => just keep Valid_Sp_Author, no year

**Comment by yroskov** [comment]
- [ ] Accepted name is repeated in synonyms in case when accepted name = basionym. Need to be blocked in the clearinghouse.

**Comment by yroskov** [comment]
- [ ] Sometime, incomplete Reference.
(I did not check Ref in the source file yet. The problem might be there.

_Example:_
Limonia (Dicranomyia) insignifica (Alexander, 1912)
Published in     Alexander, C.P. (1912).
https://data.catalogueoflife.org/dataset/2244/taxon/Limoniidae-Limoniinae-Limonia-Dicranomyia-insignifica-f52de6675

**Comment by yroskov** [comment]
- [ ] Taxa with * in the classification should be replaced with Not Assigned

*Diptera = Order Diptera - [Superfamily Not assigned] - Family Not assigned - [Subfamily Not assigned] - [Tribe Not assigned] - Genus Rhopaloscolex
*F = not assigned in a family (*FAcalyptratae)
*G = not assigned in a genus (!) (*GAcalyptratae commoror) - i.e. taxonomicly unresolved, has no sense in CoL.

![image](https://user-images.githubusercontent.com/28574252/102633439-0aba4e80-4116-11eb-8087-7e3a8253440f.png)


![image](https://user-images.githubusercontent.com/28574252/102632862-3e48a900-4115-11eb-9671-6afaa7e4d810.png)

**Comment by yroskov** [comment]
- [ ] Strange names:
_x0010__x0010_S_x0010_pungisomyia
_x0010__x0010_S_x0010_pungisomyia carinaolssonae Jaschhof & Jaschhof, 2020
_x0010__x0010_S_x0010_pungisomyia svemapro Jaschhof & Jaschhof, 2020

![image](https://user-images.githubusercontent.com/28574252/102653474-9c38b900-4134-11eb-82e4-891657909115.png)

It caused by parasitic characters in genus name Spungisomyia (tribe *TPorricondylinae)

![image](https://user-images.githubusercontent.com/28574252/102654353-043bcf00-4136-11eb-97b0-c63d7cc9604b.png)

**Comment by yroskov** [comment]
- [ ] Parasitic characters in authorstrings. Visible in Issues- Unparsable Authorship
https://data.catalogueoflife.org/catalogue/3/dataset/2244/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&issue=unparsable%20authorship&limit=100&offset=0

González     - 48 sci names filtered in master file

Example:
Agelanius burgeri González, 2006
![image](https://user-images.githubusercontent.com/28574252/102658770-d8244c00-413d-11eb-985c-f522009632e1.png)

- [ ] Some authors de-capitalized:
becker, 1913 (Formosina flavipleuris becker, 1913)
smith, 1969 (Hemerodromia gogi smith, 1969)
meigen, 1804 (Exechia fusca meigen, 1804)

**Comment by yroskov** [comment]
- [ ] Subgenera need to be deleted:
Syn:
Anthrax (molitor var.) vacans Coquillett, 1887
Anthrax (nigerrimus ssp.) ocellatus Bezzi, 1924
etc. etc.

Acc:
Archiborborus (*GArchiborborus) femoralis (Blanchard, 1852)
Cephalops (*SGCephalops) excellens (Kertész, 1912)
etc. etc.

These names are visible in Issues - Partially Parsable Names
https://data.catalogueoflife.org/catalogue/3/dataset/2244/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&issue=partially%20parsable%20name&limit=100&offset=0&status=accepted

**Comment by yroskov** [comment]
- [ ] Family 1 in the classification.
![image](https://user-images.githubusercontent.com/28574252/102667402-e038b780-414e-11eb-8c6c-41fcda6be858.png)

NameID in the master file: **153660**

Supposed to be: acc Systenus pallipes (Roser, 1840), syn Rhaphium pallipes Roser, 1840, Rhaphium adpropinquans Loew, 1857; fam Dolichopodidae

What's gone wrong?

**Comment by yroskov** [comment]
**2020-12-21 test of the CLASSIFICATION** diptera-flat-dev https://data.catalogueoflife.org/dataset/2244/classification

- [ ] 115 more Diptera families in new than in ac18.
I am not able to select and copy&paste expanded families in the tree in a new portal. It make comparison very difficult.

- [x] Taxa outside Diptera in the tree (included as "families", status=99 means non-Diptera (24 names have status 99 in the SPECIES file)); will be excluded from import: 
ACARI
Homoptera: Aphididae
HOMOPTERA: Tettigarctidae 
MECOPTERA
ORTHOPTERA
Trichoptera & TRICHOPTERA

- [ ] 562 names have empty Valid_Species field in SPECIES file. Majority of these names have statuses 55 (nomen nudum) or 61 (Established for Hybrid). These names should be filtered out of CoL.

**Comment by yroskov** [comment]
- [ ] Misspelled families:
Xylo0myidae
Xylomyidae
Xylomyiidae

**Comment by yroskov** [comment]
**TESTS OF ver 2.10, 2021-01-12**
Imported on 2021-01-14 https://data.catalogueoflife.org/dataset/2244/classification

**Comment by yroskov** [comment]
- [ ] Remaining issues in the family list:
family Brachystomatidae
family Brachystomatidae?
![image](https://user-images.githubusercontent.com/28574252/104645535-c79bbe80-5674-11eb-88eb-171cfdfb98f1.png)

**Comment by yroskov** [comment]
- [ ] Seems there is no indication of "fossil" species in SD.
There is a field Species_Fossil in SPECIES table, but it is empty.

**Comment by yroskov** [comment]
**Neil's comments to the ISSUES in ver V2.8 2020-11-13**

General remarks

Subspecies – we do not have a subspecies data field so this has been put into the “Valid species” field with the string as “[species] ssp. [subspecies]”. All of these have been searched for and made consistent. If it is allowed, this will clear out a number of records from “Unusual name Characters”, “Multi-word epithet”, and other issue categories.

Name match none –  there are a number of nomina nuda without a valid name to attach it to so the valid name is left blank.

Name match none / missing genus – unplaced names are dealt with by using an asterisk and then a one- or two-letter prefix to denote category; thus, *FNematocera means unplaced to family within Nematocera. This is a call for Thomas and I to make if we want to change all of these to instead read as “(Unplaced in …[taxon])” for all those cases where an asterisk is used in the Present Genus field. I have deleted all cases of this in the Present Subgenus field since leaving the field blank says the same thing [i.e., it is placed to genus, but there should be no indication of what subgenus until it is determined; so no need to say so with the “*SG-“ prefix (= redundant for that field)]. If we do this for the genus field, the resulting string would be, e.g., “(Unplaced in Lestremiinae) globulifera Keilbach”. For the family field, no parentheses would be needed as it displays as indicated. Thoughts?

Uninterpreted – the status field (a number) is what indicates the status of a record. The “Status” table (cheat-sheet of status definitions) should be referred to in order to help interpret any records that cannot be determined and may save a lot of time actually. A script was written in FM that imports the status definition into the “Status Line” field, which displays in the FM database and the web display but may be lost in the dataset you have. Thus, a Status field with “20” will have “(Available, Invalid) Junior Synonym” on the status line.

 

Specific remarks

Uppercase epithet: col:ID SP153660, SP100471 – both records look fine in SD but look like they may have had an export problem as in your dataset, the fields for these records have data from other fields

Doubtful name: col:ID F234  (Muscinae ariciaeformes) This is verbatim how the name appears. It seems to be the only multi-name epithet for family-group names

Unmatched reference brackets: col:ID 27074 – this looks fine. There is a beginning and end bracket and within in beginning and end parentheses

Unparsable authorship: col:ID SP186861 – looks OK. There are odd diacritics, but these are correct. There are records (SP187151, SP117359) with Vietnamese authors that got tagged as well and these have been checked and are fine.

Unparsable authorship: many records – there are a number of records with the following string “Gonz_x0005_ález” (which equals González”). Not sure what happened there as other authors with diacritics come out fine but just poor González got this added stuff. Also SP10872 has authorship as “_x0010_Chillcott & Teskey”. Clues as to what went on there?

Name ID invalid: these all seem to be nomina nuda with no valid name to attach to it

Accepted name missing; accepted ID invalid: col:ID SP73180; SP23744 – both look fine in SD; cannot see what is wrong; maybe another export glitch?

Name match variant: col:ID SP134850; SP145990 – both look OK, what is wrong?

Name match variant: col:ID SPO175218 – gender ending change is all I can see. Anything else I’m missing?

**Comment by yroskov** [comment]
- [ ] In a case of duplicated names ACC-SYN sp (same acc; diff auth): authorstring of accepted name has no year, whereas identical name in synonyms has it. 
For example: Anthrax trifasciatus Meigen (acc) and Anthrax trifasciata  Meigen, 1804 (syn)

Logic for crawler
**If:**
Original Genus = Present Genus
&
Species	= Valid Species	
&
Author = Valid Sp Author		
**=>**
Year should be taken in accepted species authorstring

**Comment by yroskov** [comment]
**NEW VERSION diptera-dev: Diptera Flat Dev of 2021-04-15**
at https://data.dev.catalogueoflife.org/dataset/2131/classification

Imported **169385 spp**

Classification: ranks present in order Diptera - families - subfamilies (optional) - tribes (optional) - genera - subgenera (optional) - species. None of the uninomials have an authorstring.

**Comment by yroskov** [comment]
- [ ] Year is missing in all species authorstrings (see column CN "Year" in **species** file of 2021-03-21)

![image](https://user-images.githubusercontent.com/28574252/115070289-61644900-9eba-11eb-88b7-43b937da681d.png)

![image](https://user-images.githubusercontent.com/28574252/115070350-73de8280-9eba-11eb-8e46-45941c218872.png)

**Comment by yroskov** [comment]
Good example from Geoff: https://data.dev.catalogueoflife.org/dataset/2131/taxon/Culicidae-Culicinae-Aedini-Aedes-Stegomyia-aegypti-4f837e18c

**Aedes (Stegomyia) aegypti**, its original combination = Culex aegypti Linnaeus, 1762 (acceptable), lot of synonyms (year present in authorstrings)

![image](https://user-images.githubusercontent.com/28574252/115073670-48f62d80-9ebe-11eb-8bfe-fda23a592600.png)

**Comment by yroskov** [comment]
>Year is missing in all accepted species authorstrings

**FIXED**

Dataset of April 20th 2021 at https://data.dev.catalogueoflife.org/dataset/2131/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&sortBy=taxonomic

Few sample names:
Dolichophaonia anoctiluca (Carvalho, 1983)
Dolichophaonia cacheuta (Snyder, 1957)
Dolichopus angulicornis (Grichanov, 2004)
Molophilus genitalis (Brunetti, 1912)
Platypalpus ostiorum (Becker, 1902)
Suillia aspinosa (Lamb, 1917)
Trupanea wheeleri (Curran, 1932)

**Comment by yroskov** [comment]
Assembly in the Tree at Dev:

![image](https://user-images.githubusercontent.com/28574252/116104988-84d78280-a676-11eb-968e-49ce7580ea1f.png)

9 families failed to be established as a sector:
Blephariceridae
Curtonotidae
Cypselosomatidae
Eomyiidae
Hennigmatidae
Pachyneuridae
Phaeomyiidae
Scatopsidae
and also:
![image](https://user-images.githubusercontent.com/28574252/116105284-c8ca8780-a676-11eb-9b3c-3ef3f46d9711.png)

Plus broken sectors in CoL:

![image](https://user-images.githubusercontent.com/28574252/116105778-41c9df00-a677-11eb-9e91-b6566db71a01.png)

Sector mapping changes with each browser refresh.

**Comment by yroskov** [comment]
Assembly in the Tree at Dev (experiment 2):

1. Renamed order Diptera as Dipteraold
2. Drag&Dropped order Diptera from diptera-dev (2131) as a child of class Isecta

Results: order Diptera with all children families established as a single sector successfully.

![image](https://user-images.githubusercontent.com/28574252/116107780-ef89bd80-a678-11eb-8cb6-58321fade6f0.png)

**Comment by yroskov** [comment]
Imported: 169386 spp.

**ISSUES** (selected)

- [ ] **Multi Word Epithet**, 1 - Only 1 "name", not important
![image](https://user-images.githubusercontent.com/28574252/116136029-6df55800-a697-11eb-8a6d-ae42deb4737c.png)

https://data.dev.catalogueoflife.org/catalogue/3/dataset/2131/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=multi%20word%20epithet&limit=100&offset=0

- [ ] **Unparsable Authorship**, 90. @gdower, one case should be fixed: name  **Gonz_x0005_ález** appears like that in many species names.
https://data.dev.catalogueoflife.org/catalogue/3/dataset/2131/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=unparsable%20authorship&limit=100&offset=0

- [x] **Missing Genus**, 3520 - expected.
![image](https://user-images.githubusercontent.com/28574252/116136784-67b3ab80-a698-11eb-8461-12c999eb44c5.png)

- [ ] **Unusual Name Characters**, 3787 & **Partially Parsable Name** - ask SD, what to do with such names:
https://data.dev.catalogueoflife.org/catalogue/3/dataset/2131/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=unusual%20name%20characters&limit=100&offset=0
![image](https://user-images.githubusercontent.com/28574252/116136983-a3e70c00-a698-11eb-9727-dd56b3e10820.png)

- [ ] **Id Not Unique**, 20420 - @gdower, how serious it might be?

**Comment by yroskov** [comment]
**TASKS** 2021-04-26

![image](https://user-images.githubusercontent.com/28574252/116137472-34bde780-a699-11eb-8344-6aa4bf303dfd.png)

- [x] ACC-ACC sp (diff auth) - all names with missing genus = to be blocked all
https://data.dev.catalogueoflife.org/catalogue/3/dataset/2131/duplicates?authorshipDifferent=true&category=binomial&limit=50&minSize=2&mode=STRICT&offset=0&status=accepted&withDecision=false

- [ ]  **Identical genus**. Split genera. Set of species attached to the next parent (unplaced)

- [ ] **Any uninomial** @yroskov, See the case of split Tribe:  Acemyini
![image](https://user-images.githubusercontent.com/28574252/116138502-8450e300-a69a-11eb-8707-f311746734df.png)

**Comment by yroskov** [comment]
POSSIBLE FAILURE:

Was name **Domomyza sp. 1959** present in any Issue reports? (seen in the Tree)
![image](https://user-images.githubusercontent.com/28574252/116139169-57510000-a69b-11eb-9484-0442204ef1b7.png)

- [ ] Search for "sp." in the workbench: 188 cases  (rank species) - to be blocked
https://data.dev.catalogueoflife.org/catalogue/3/dataset/2131/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=100&offset=0&q=sp.
![image](https://user-images.githubusercontent.com/28574252/116139676-e52ceb00-a69b-11eb-81ca-2e4182011cba.png)

**Comment by yroskov** [comment]
2021-04-29. Geof's import of 2021-04-28.

Most challenging Task is **Identical Genus**:

![image](https://user-images.githubusercontent.com/28574252/116622679-b2d4f500-a90a-11eb-8bc8-e8ef34884411.png)

**Comment by yroskov** [comment]
**diptera-dev2, id 2131**
https://data.dev.catalogueoflife.org/dataset/2134/issues
