### ISSUE TITLE
WoRMS Thermosbaenacea (id 1093): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#60]
**WoRMS Thermosbaenacea**, id 1093 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1093

- [x] _Sector:_ order Thermosbaenacea established
- [ ] _Metadata:_ Not updated
- [x] _Imports:_  40 spp vs 38 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-19
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-19

No issues.

![image](https://user-images.githubusercontent.com/28574252/111839211-74d6c100-88c8-11eb-979d-c667a00c3f5c.png)

**Comment by yroskov** [comment]
Synced 2021-03-19. **Sync need to be repeated after metadata fixes**
