### ISSUE TITLE
WoRMS Foraminifera (id 1157): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#61]
**WoRMS Foraminifera**, id 1157 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1157

- [x] _Sector:_ phylum Foraminifera
- [ ] _Metadata:_ Not updated
- [x] _Imports:_  49609 spp vs 9076 in ac19. (39381 extinct spp).

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-22
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-22

![image](https://user-images.githubusercontent.com/28574252/112007274-869bac80-8af2-11eb-8b0f-55dc01c8514a.png)

- [x] ACC-ACC species (same authors), 491 names with empty fields. - @bart-v, @gdower, is it OK?
Blocked in CoL for now.

https://data.catalogueoflife.org/catalogue/3/dataset/1157/duplicates?authorshipDifferent=false&category=binomial&limit=500&minSize=2&mode=STRICT&offset=0&status=accepted&withDecision=false

![image](https://user-images.githubusercontent.com/28574252/112010932-c2844100-8af5-11eb-88d2-8d2832957306.png)

- [ ] ACC-ACC infraspecies and infraspecies marker (same authors)   Duplicated entries, is it mistake in data entry?
https://data.catalogueoflife.org/catalogue/3/dataset/1157/duplicates?authorshipDifferent=false&category=trinomial&limit=500&minSize=2&mode=STRICT&offset=0&status=accepted&withDecision=false
![image](https://user-images.githubusercontent.com/28574252/112011615-6d94fa80-8af6-11eb-9069-b3e0ba3885bc.png)

Resolved 2021-03-22:

![image](https://user-images.githubusercontent.com/28574252/112013630-2dcf1280-8af8-11eb-9f76-c44138add6dc.png)

**Comment by yroskov** [comment]
Synced 2021-03-19. **Sync need to be repeated after metadata fixes**

**Comment by bart-v** [comment]
We are not sending these names/taxa as accepted...
i.e. first example _Globorotalia acostaensis_ Blow, 1959 
https://data.catalogueoflife.org/dataset/1157/taxon/x3XH
http://www.marinespecies.org/aphia.php?p=taxdetails&id=894416

This is something CoL makes up...instead of using the existing name from WoRMS
https://data.catalogueoflife.org/dataset/1157/name/x3XG
`placeholder`
I find this a worrying evolution...

It's caused by an accepted subspecies under an unaccepted species (in this case _Globorotalia acostaensis subsp. trochoidea_ Bizon & Bizon, 1965)

I know CoL does not like this, but still dangerous to just create entries...

**Comment by yroskov** [comment]
Woops! Indeed, these are species names created by the clearinghouse. OK, they should be blocked in CoL.

**Comment by mdoering** [comment]
I am not sure if I fully understand the problem.

There is an accepted subspecies `Globorotalia acostaensis subsp. trochoidea Bizon & Bizon, 1965 †` under the species synonym `Globorotalia acostaensis Blow, 1959 † ` which has an accepted species `Neogloboquadrina acostaensis (Blow, 1959) †`.

This indeed is an unsupported tree and against the ColDP or DwC format. Nevertheless ChecklistBank should be able to handle those cases and flag them. I would expect the accepted subspecies to be moved under the accepted species _Neogloboquadrina acostaensis_.

The record for species _acostaensis_ has "origin":"denormed classification".
That indicates there was `species=acostaensi` given with that name in the Taxon ColDP file? Checking the Taxon file I can see the species column indeed holds only the species epithet, when it should be the full binomial:

> The species binomial the taxon is classified in. If parentID is given this field is ignored.

I would recommend not to mix the flat classification with the parentID terms. Chose one or the other - unless you need the mix to complement missing higher ranks, e.g. you have no kingdom record in your database. If you can provide parentID to build up a parent child relation this is the recommended way in ColDP. This is safer and results in quicker imports too.

**Comment by mdoering** [comment]
As the flat ranks should be ignored if parentID is given you normally do not notice the problem.
But the Foraminifera dataset has [7478 invalid parentIDs](https://data.catalogueoflife.org/dataset/1157/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&issue=parent%20id%20invalid&limit=50&offset=0&sortBy=taxonomic), in which case the system switches to the flat classification for those records.

**Comment by mdoering** [comment]
There are 2259 usages created because of the flat classification, i.e. `origin=denormed classification`:
```
"usagesByOriginCount":{
  "source":73164,
  "denormed classification":2259
}
```
https://api.catalogueoflife.org/dataset/1157/import

We apparently miss a search filter/facet for origin - we will add that so they become searchable easily.

**Comment by bart-v** [comment]
(1) The invalid parentIDs are they are, this is not something we can easily fix.
Plus, Aphia does allow/support this.
We will report this to our editors, but it will need time to get fixed.

(2) Regarding parentIDs vs. flat classification
We prefer to have keep both, as that allows quick and easy inspection and comparison of records.

**Comment by mdoering** [comment]
@bart-v in case there is an invalid parentID, how do you extract any classification yourself? [Aphia seems to follow a parent child model with a parent column](http://www.marinespecies.org/structure/tables/tu.html). Should those records that have no parent not be entirely orphaned names?

Example accepted genus `Asymetria Georgescu, 2012` with an invalid parentID:
 - [CLB](https://data.catalogueoflife.org/dataset/1157/taxon/urn%3Alsid%3Amarinespecies.org%3Ataxname%3A1322331) with verbatim parentID=urn:lsid:marinespecies.org:taxname:520751
 - [WoRMS](http://www.marinespecies.org/foraminifera/aphia.php?p=taxdetails&id=1322331) with the classification:

> Biota Chromista (Kingdom) Harosa (Subkingdom) Rhizaria (Infrakingdom) Foraminifera (Phylum) Foraminifera incertae sedis (Class) Asymetria † (Genus)

[520751](http://www.marinespecies.org/foraminifera/aphia.php?p=taxdetails&id=520751) seems to exist in WoRMS, so why is it not part of the ColDP archive?

It is given as a Name record:
https://data.catalogueoflife.org/dataset/1157/verbatim?q=520751&type=col%3AName

But not as a Taxon/Usage record. There are just many records that have it as its parent:
https://data.catalogueoflife.org/dataset/1157/verbatim?offset=0&q=520751&type=col%3ATaxon

Is it maybe because it is considered a temporary name? We should probably assign all temporary names some status and not just leave a remark. Can that be done? Right now the best match seems "nom. inval.", but we might want to add another status for temporary/informal/placeholder names so we can clearly identify them

**Comment by bart-v** [comment]
In Aphia, a parentID can perfectly be invalid, we just follow the parents until Biota, accepted or not.

AphiaID 520751 is not in Taxon.txt, because of this it's not ac accepted name, while you require it:
https://github.com/CatalogueOfLife/coldp#taxon
{quote}
Taxon
**An accepted name** with a taxonomic classification(...)
{quote}

This is not only about temporary names.
There is many parents that are unaccepted...

**Comment by mdoering** [comment]
What is their status then? You use the name in the classification, so they should be considered a name usage, which is either a Taxon or Synonym in ColDP. Alternatively you could use the [NameUsage table](https://github.com/CatalogueOfLife/coldp/blob/master/README.md#nameusage) which does not differ between the two "subclasses". A Taxon record is not necessarily a fully accepted name. It can also be provisionally accepted. Maybe there is also the need to have a new Taxon status to represent your cases? Simply dropping the record is the worst solution I would think.

**Comment by bart-v** [comment]
There is no separate status for this: they can be any.
Notice that we don't have the formal taxon concept in Aphia...

I don't think we can easily fix this right now, so I propose we drop them for now.
If we inform our editors well, we can slowly tackle these issues...

**Comment by mdoering** [comment]
Excluding them entirely would be fine. But could we then also remove the name record and relink the parentID of the children to the ID of the next higher parent which is considered fine? That would produce a valid parent child tree structure again.

**Comment by bart-v** [comment]
I think this is not what we want, in theory you could end up with parent of a Genus as Biota or so. 
It would also involve some work at our side...

Let's just exclude them for now, and focus on getting at least some up-to-date data into CoL

**Comment by mdoering** [comment]
Not sure if I understand what you mean with _exclude_. Do you mean we should exclude them on our side? If so what should be excluded exactly?

**Comment by bart-v** [comment]
Just what Yuri did now: exclude or ignore on the CoL side

**Comment by bart-v** [comment]
The "invalid parent issue" has been fixed now.
These will be added as provisional=1
Also the metadata is now fixed

Available in next export on 2021-06-01

**Comment by yroskov** [comment]
TASKS 2021-07-08

![image](https://user-images.githubusercontent.com/28574252/124959337-b8bd1580-dfe0-11eb-93df-c2ff13c7dad6.png)

- [x] Broken decisions: 708; re-matched all: 724. Deleted all.

- [x] Duplicated uninomials are already marked as acc vs prov.acc
![image](https://user-images.githubusercontent.com/28574252/124959789-34b75d80-dfe1-11eb-9349-35c68363bb66.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/124959879-544e8600-dfe1-11eb-9a6c-e371422d805c.png)

**Comment by yroskov** [comment]
**ver 2021-11-01**

TASKS - there are changes
![image](https://user-images.githubusercontent.com/28574252/140382537-64e5c450-a72d-4c96-a57c-f45c6e9ac328.png)

- [x] Broken decisions, 15; RematchAll = 6 remains; deleted all

- Identical superfamily, family, genus = all cases marked as acc - prov acc by the provider. No decisions needed, except one case.

Resolved 2021-11-04
![image](https://user-images.githubusercontent.com/28574252/140383850-a911ddf7-7aa2-4ec7-94ff-247a51922188.png)

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/182680800-613135d8-2989-4129-93ec-764eff0baa3a.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/182681500-b81b3c62-c589-43a1-8d47-13fba6f4e9ba.png)

Re-synced 2022-08-03

**Comment by yroskov** [comment]
**ver 2023-06-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/0606f83d-cda0-471f-a337-0506eb3de721)

- Broken decisions, 130: all deleted

Resolved 2023-06-05:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/3d70c8db-cb65-47d7-bf1e-50cadb6317f1)

**Re-synced 2023-06-05**

**Comment by yroskov** [comment]
**ver 2024-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/ca37ac87-a977-436e-9165-664fe06a0bde)

Resolved 2024-05-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/43f6403e-62bc-4040-9846-e8cf302227e8)

**Re-synced 2024-05-07**

**Comment by yroskov** [comment]
**ver 2024-06-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/8d893af0-642d-489e-a6a5-0c3e10618b07)

- Broken decisions, 496 = all deleted 
- Outdated decisions, 1 = no actions (ref: the problem of decisions between GSDs)

Resolved 2024-06-03:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/bdb30381-6d4a-4378-a66d-c11cca0972aa)

**Synced 2024-06-03**

**Comment by yroskov** [comment]
2024-09-23: ranks "subvariety" & "subform" excluded from accepted taxa in the sector.
15 names affected
**Re-synced 2024-09-23**

**Comment by yroskov** [comment]
**ver 2025-01-01**

@bart-v, Ari (https://github.com/CatalogueOfLife/data/issues/904) reported comma at the end of scientific name Parafusulina alpinensis, Yang & Yancey, 2000

https://www.marinespecies.org/aphia.php?p=taxdetails&id=1310991

**Comment by yroskov** [comment]
**ver 2025-01-01** = TASKS resolved & re-synced 2025-01-16:

![Image](https://github.com/user-attachments/assets/1d539aa3-534b-4214-9169-42cc8ca74780)

**Comment by bart-v** [comment]
comma = fixed

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 4 names with portion _incertae sedis_ = 4 prov acc IGNORED

ISSUES assessed 2025-05-20

![Image](https://github.com/user-attachments/assets/9164a172-45ad-4b5a-994e-d15cc7ee861b)

TASKS

![Image](https://github.com/user-attachments/assets/c35a62f8-2dfa-4871-9baa-e5bc4a84b5f3)

- Broken decisions, 329 = deleted
- Outdated decisions, 1 = no action

Resolved 2025-05-20:

![Image](https://github.com/user-attachments/assets/b738d17d-99c4-4a33-9fe1-ee3defe33836)

**Synced 2025-05-20**

**Comment by yroskov** [comment]
**ver. 2025-09-01** 

TASKS

<img width="1359" height="908" alt="Image" src="https://github.com/user-attachments/assets/63b355e1-9d85-4972-9f0a-879edc85c8cd" />

Resolved 2025-09-11:

<img width="1378" height="964" alt="Image" src="https://github.com/user-attachments/assets/c32d6e65-c98b-45b4-8340-fdf383b85828" />

**Re-synced 2025-09-11**

**Comment by yroskov** [comment]
- [x] fam Rhizamminidae 3 times, see https://github.com/CatalogueOfLife/data/issues/1592 = blocked in CoL & reported
