### ISSUE TITLE
WoRMS Gastrotricha (id 1122): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#62]
**WoRMS Gastrotricha**, id 1122 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1122

- [x] _Sector:_ phylum Gastrotricha
- [ ] _Metadata:_ Not updated
- [x] _Imports:_  862 spp vs 852 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-22
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-22

![image](https://user-images.githubusercontent.com/28574252/112048527-831d1b00-8b1c-11eb-9328-8f2803d30ab5.png)

Resolved: 

![image](https://user-images.githubusercontent.com/28574252/112048631-9d56f900-8b1c-11eb-89ad-01ae9c37121f.png)

**Comment by yroskov** [comment]
Synced 2021-03-22. **Sync need to be repeated after metadata fixes**
