### ISSUE TITLE
WoRMS Holothuroidea (id 1125): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#63]
**WoRMS Holothuroidea**, id 1125 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1125

- [x] _Sector:_ phylum Gnathostomulida
- [ ] _Metadata:_ Not updated
- [x] _Imports:_  spp vs in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-22
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-22

No issues.

![image](https://user-images.githubusercontent.com/28574252/112052205-db561c00-8b20-11eb-8559-c56728385fa6.png)
