### ISSUE TITLE
WoRMS Hydrozoa: test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#64]
**WoRMS Hydrozoa**, id 1112 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1112

- [x] _Sector:_ class Hydrozoa, pre-existed
- [ ] _Metadata:_ Not updated
- [x] _Imports:_ 3843 spp vs 3762 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-22

![image](https://user-images.githubusercontent.com/28574252/112053263-21f84600-8b22-11eb-8d4c-28624dc42d80.png)

Resolved:

![image](https://user-images.githubusercontent.com/28574252/112053415-53711180-8b22-11eb-9e30-3d5cc7132db8.png)

**Comment by yroskov** [comment]
Synced 2021-03-22. **Sync need to be repeated after metadata fixes**

**Comment by yroskov** [comment]
Checks at preview (of 2021-04-05)

Spp 3843 - 3762 = + 81

All ranks are present correctly.

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/182872297-64716c3f-8724-407f-9bb9-8ac7ddffa53f.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/182872720-5068f54e-df7c-47d5-9013-1b0833d1a7c3.png)

Re-synced 2022-08-04

**Comment by yroskov** [comment]
**ver 2023-06-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/cfbedd3a-16c9-4439-b113-bfe02d25f9df)

- Broken decisions, 5: all deleted

Resolved 2023-06-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/bfc37db0-f9d8-49f9-b882-6c388cdfe518)

**Re-synced 2023-06-07**

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 7 names with portion _incertae sedis_ = 5 prov acc IGNORED; 1 syn BLOCKED

ISSUES assessed 2025-05-21

![Image](https://github.com/user-attachments/assets/aa92a59d-d50a-4699-ae4d-7432b1377553)

TASKS

![Image](https://github.com/user-attachments/assets/adca307c-1ec9-4a1a-b50d-dbe3f100c08b)

- Broken decisions, 13 = deleted

Resolved 2025-05-21:

![Image](https://github.com/user-attachments/assets/adbd771e-1c41-47f8-bb65-322c287d9f01)

**Synced 2025-05-21**
