### ISSUE TITLE
WoRMS Isopoda (id 1094): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#65]
**WoRMS Isopoda**, id 1094 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1094

- [x] _Sector:_ order Isopoda established
- [ ] _Metadata:_ Not updated
- [x] _Imports:_ 10685 spp vs 10411 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-22
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-22

![image](https://user-images.githubusercontent.com/28574252/112054956-3d645080-8b24-11eb-835c-82afc166c453.png)

Resolved:

![image](https://user-images.githubusercontent.com/28574252/112055277-a3e96e80-8b24-11eb-95c1-8e385c3cbe95.png)

**Comment by yroskov** [comment]
Synced 2021-03-22. **Sync need to be repeated after metadata fixes**

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/182873561-9316a401-8193-420e-a32a-c49d96407e66.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/182873906-5ed8e34f-1de5-439b-849f-f9eff860ac33.png)

Re-synced 2022-08-04

**Comment by yroskov** [comment]
**ver 2023-05-01**

TASKS

![image](https://user-images.githubusercontent.com/28574252/236889853-0882da13-8f0b-4988-8d94-9b4109a566ec.png)

- Broken decisions, 3: all deleted

Resolved 2023-05-08

![image](https://user-images.githubusercontent.com/28574252/236890552-46d5a149-e9f8-49ea-b9ad-2984e62938a7.png)

**Re-synced 2023-05-08**

**Comment by yroskov** [comment]
**ver 2023-06-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/d3f4a0ed-a54d-4aa9-805b-67433821b7d5)

- Broken decisions, 8: all deleted

Resolved 2023-06-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/c24cd40a-40a1-468a-88da-d18f99b27fca)

**Re-synced 2023-06-07**

**Comment by yroskov** [comment]
**ver 2024-05-01**

TASKS resolved 2024-05-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/d5d689ff-ae8e-4912-9b1b-97d40f82f238)

**Re-synced 2024-05-01**

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 46 names with portion _incertae sedis_ = 26 acc & 18 prov acc IGNORED

ISSUES assessed 2025-05-20

![Image](https://github.com/user-attachments/assets/853a5af2-d79f-4694-8141-c05db1a8d3ce)

TASKS

![Image](https://github.com/user-attachments/assets/d67be574-e993-46b1-9d75-f40040c60468)

- Broken decisions, 41 = deleted
- Outdated decisions, 2 = no action

Resolved 2025-05-20:

![Image](https://github.com/user-attachments/assets/dfb23394-c2f1-41db-a6dd-1b661a1453e6)

**Synced 2025-05-20**

**Comment by yroskov** [comment]
**ver 2025-12-12**

TASKS

<img width="1617" height="1047" alt="Image" src="https://github.com/user-attachments/assets/60a69c60-97d2-4f1f-971e-95063cd93f77" />

Resolved 2025-12-12:

<img width="1617" height="1047" alt="Image" src="https://github.com/user-attachments/assets/36213214-db87-413c-be29-de45ef2ca67f" />

**Re-synced 2025-12-12**
