### ISSUE TITLE
WoRMS Kinorhyncha (id 1153): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#66]
**WoRMS Kinorhyncha**, id 1153 on prod
https://data.catalogueoflife.org/dataset/1153

- [x] _Sector:_ phylum Kinorhyncha established. Was class Kinorhyncha in phylum Cephalorhyncha
- [ ] _Metadata:_ Not updated
- [ ] _Imports:_  308 spp vs 188 in ac19 (?)

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-23

![image](https://user-images.githubusercontent.com/28574252/112213254-df9b3b80-8beb-11eb-8715-2e03986c23ce.png)

Resolved: 

![image](https://user-images.githubusercontent.com/28574252/112213348-fb064680-8beb-11eb-96df-71d62f88a116.png)

**Comment by yroskov** [comment]
Synced 2021-03-23. **Sync need to be repeated after metadata fixes**
