### ISSUE TITLE
WoRMS Leptostraca (id 1105): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#71]
**WoRMS Leptostraca**, id 1105 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1105

- [x] _Sector:_ order Leptostraca re-established
- [ ] _Metadata:_ Not updated
- [x] _Imports:_  63 spp vs 60 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-30
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-30

**Comment by yroskov** [comment]
**Not synced.**
