### ISSUE TITLE
WoRMS Loricifera (id ): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#72]
**WoRMS Loricifera**, id 1182 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1182

- [x] _Sector:_ established as phylum Loricifera (was a class Loricifera)
- [ ] _Metadata:_ Not updated
- [x] _Imports:_  29 spp vs 27 in ac19

**Comment by yroskov** [comment]
**ISSUES** (selected only) 2021-03-30
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-03-30

No issues.

![image](https://user-images.githubusercontent.com/28574252/113055104-d2dc9180-916f-11eb-8fdb-b0160ee72305.png)

**Comment by yroskov** [comment]
Synced 2021-03-30. **Sync need to be repeated after metadata fixes**
