### ISSUE TITLE
SF Embioptera on DEV

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#90]
SF Embioptera, id 1089

https://data.dev.catalogueoflife.org/dataset/1089/classification

- [x] Growth of species: imported 419 spp vs 415 in ac19 (+4 spp)

- [x] Classification: all ranks interpreted correctly. 16 families match ac19. No "empty" taxa.

**Comment by yroskov** [comment]
**ISSUES**

- [ ] **Inconsistent name**, 6 - misinterpreted rank "superspecies". Clearinghouse software turned superspecies in trinomials with species epithet as "supersp" and misinterpreted species epithet as infraspecificEpithet.  

https://data.dev.catalogueoflife.org/catalogue/3/dataset/1089/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=inconsistent%20name&limit=100&offset=0
![image](https://user-images.githubusercontent.com/28574252/114770775-6e096580-9d31-11eb-9acf-6d66d5554a6d.png)

**Comment by yroskov** [comment]
**TASKS**

![image](https://user-images.githubusercontent.com/28574252/114773522-c726c880-9d34-11eb-889e-3be414d312fe.png)
