### ISSUE TITLE
WoRMS Mystacocarida (id 1088): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#97]
WoRMS Mystacocarida, id 1088 on prod
https://data.catalogueoflife.org/dataset/1088/meta 

- [ ] _Sector:_ subclass Mystacocarida established
- [ ] _Metadata:_ Not updated yet
- [x] _Imported:_  13 spp vs 13 in ac19

**ISSUES** (selected only) 2021-04-19
- [x] assessed

**TASKS** 2021-04-19
No issues.

![image](https://user-images.githubusercontent.com/28574252/115300990-4138c200-a126-11eb-9d86-e4cf82e2a49e.png)

**Comment by yroskov** [comment]
**Synced 2021-04-19**

**Comment by yroskov** [comment]
@DaveNicolson, 2021-05-13 pointed duplicated Mystacocarida branch in NotAssigned subclass:

![image](https://user-images.githubusercontent.com/28574252/118155878-524fb880-b3de-11eb-81e1-92f7a394ac84.png)

FIXED 2021-05-13
