### ISSUE TITLE
WoRMS Myxozoa (id 1129): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#98]
WoRMS Myxozoa, id 1129 on prod

- [x] _Sector:_ class Myxozoa in phylum Cnidaria re-established (was phylum Myxozoa)
- [ ] _Metadata:_ not updated yet
- [ ] _Imported:_  742 spp vs 194 in ac19 (+ 548?)

**ISSUES** (selected only) 2021-04-
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-04-19

![image](https://user-images.githubusercontent.com/28574252/115302387-00da4380-a128-11eb-9825-67f3f3bd2244.png)

Resolved:

![image](https://user-images.githubusercontent.com/28574252/115302682-4eef4700-a128-11eb-9b9d-af46a5feb0db.png)

**Comment by yroskov** [comment]
Synced 2021-04-19

**Comment by yroskov** [comment]
**ver 2022-08-01**

TASKS
![image](https://user-images.githubusercontent.com/28574252/182900210-7b8bf59e-363a-422c-9039-d921d436de51.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/182901154-c03ddae7-12da-4791-a91d-b4d83ebe328a.png)

Re-synced 2022-08-04

**Comment by yroskov** [comment]
**ver 2023-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/97b743bf-e9d1-4a36-9b96-3a8bd8eeec98)

- Broken decisions, 1: all deleted

Resolved 2023-05-10

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/316841ef-3318-419a-8454-60da6682ac12)

**Re-synced 2023-05-10**

**Comment by yroskov** [comment]
**ver 2023-06-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/e45785e8-255a-4ba1-b2fb-eb490ebc14af)

- Broken decisions, 1: all deleted

Resolved 2023-06-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/cce05254-9bdf-4161-98d7-77c0de379e80)

**Re-synced 2023-06-07**

**Comment by yroskov** [comment]
**ver 2023-11-01**

- Number of species in WoRMS Myxozoa increased from **761** in Oct to **1494** in Nov. I did not spot any bugs or overlaps inside GSD (checked on species level) or between GSDs (checked on genus level https://www.checklistbank.org/catalogue/3/duplicates?catalogueKey=3&limit=500&rank=genus&status=accepted&status=provisionally%20accepted)
Double check: dear @bart-v, could you please confirm that double growth of Myxozoa species is expected behavior?

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/9ec3dff3-4d01-4333-8161-7cd4ae027043)

**Comment by bart-v** [comment]
Yes, it's correct, Bert Hoeksema added a lot of them in the last month:

https://www.marinespecies.org/aphia.php?p=taxlist&rComp=%3E%3D&tRank=220&pid=146271&action_id=1&session_year=2023&session_month=10&session_day=1&session_year_end=2023&session_month_end=11&session_day_end=1&action=search&adv=1

**Comment by yroskov** [comment]
**ver 2024-05-01**

TASKS

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/70dc677c-a2cd-4fc4-97c7-b425a4f0b248)

Resolved 2024-05-07:

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/6b27a17a-2ec0-4301-9c99-a38d80455624)

**Re-synced 2024-05-07**

**Comment by yroskov** [comment]
- [x] https://github.com/CatalogueOfLife/data/issues/679

Hmm... Exactly as in WoRMS https://www.marinespecies.org/aphia.php?p=taxdetails&id=120238:

![image](https://github.com/CatalogueOfLife/data/assets/28574252/29352ff7-2064-4626-a90c-d969ad874381)

= Sector **class Myxozoa** deleted. Two **classes Malacosporea & Myxosporea** established as new sectors. Re-synced 2024-06-25.

**Comment by yroskov** [comment]
**ver. 2024-07-01**

- [x] class Myxozoa is re-established 2024-07-03 as a single sector: 
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/9f6734b6-6fed-4217-b0c8-956b3debe040)

**Synced 2024-07-03**

**Comment by yroskov** [comment]
**ver 2025-01-01**

Continue with **Either the opening or closing bracket is missing in the authorship**...
https://www.checklistbank.org/dataset/307413/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&issue=unmatched%20name%20brackets&limit=50&offset=0

@bart-v, missing bracket in Unicauda fontinalis var. notropis Fantham, Porter & Richardson, 1939) https://www.marinespecies.org/aphia.php?p=taxdetails&id=1714673

**Comment by bart-v** [comment]
Yawn...fixed

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 2 names with portion _incertae sedis_ = 1 prov acc IGNORED

@bart-v, FYI:

- Two entries for Chloromyxum africanum
https://www.marinespecies.org/aphia.php?p=taxdetails&id=1786325 - with no authorstring
https://www.marinespecies.org/aphia.php?p=taxdetails&id=1786326 

ISSUES assessed 2025-05-21

![Image](https://github.com/user-attachments/assets/748a80d5-4fba-4bf5-9718-1f16db5af536)

TASKS

![Image](https://github.com/user-attachments/assets/687ee1fe-6cd8-4a21-b232-00df8d8c0de7)

- Broken decisions, 109 = deleted
- Outdated decisions, 2 = no action

Resolved 2025-05-21:

![Image](https://github.com/user-attachments/assets/c429c456-ebec-4c5a-b670-72420776ccd6)

**Synced 2025-05-21**

**Comment by bart-v** [comment]
Duplicate fixed

**Comment by yroskov** [comment]
**ver. 2025-09-01**

TASKS

<img width="1329" height="934" alt="Image" src="https://github.com/user-attachments/assets/ee1f16a4-fa07-4844-a003-e5ac4a30e1ca" />

Resolved 2025-09-11:

<img width="1338" height="964" alt="Image" src="https://github.com/user-attachments/assets/077bd6c2-9326-4cdc-8174-59afd469eeba" />

**Re-synced 2025-09-11**
