### ISSUE TITLE
WoRMS Nemertea (id 1085): test report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/testing#99]
WoRMS Nemertea, id 1085 on prod
https://data.catalogueoflife.org/catalogue/3/dataset/1085/classification

- [x] _Sector:_ phylum Nemertea (wasn't broken)
- [ ] _Metadata:_ Not updated yet
- [x] _Imported:_  1356 spp vs 1373 in ac19

**ISSUES** (selected only) 2021-04-19
- [x] assessed

**Comment by yroskov** [comment]
**TASKS** 2021-04-19

![image](https://user-images.githubusercontent.com/28574252/115304250-5a437200-a12a-11eb-9424-ddbe37160e51.png)

Resolved:
![image](https://user-images.githubusercontent.com/28574252/115307396-c031f880-a12e-11eb-81a9-cb947f70956c.png)

**Comment by yroskov** [comment]
Synced 2021-04-19

**Comment by yroskov** [comment]
**ver. 2025-05-01 for AC25**

- [x] 2 names with portion _incertae sedis_ = 2 prov acc IGNORED

ISSUES assessed 2025-05-20

![Image](https://github.com/user-attachments/assets/b11412d2-3131-49a1-9e37-4be9fdc7faaf)

TASKS

![Image](https://github.com/user-attachments/assets/c7e0fd42-5b2d-465b-8251-fbbac85bcadb)

- Broken decisions, 17 = deleted
- Outdated decisions, 1 = no action

Resolved 2025-05-20:

![Image](https://github.com/user-attachments/assets/19161e24-a5b7-4b72-a4d9-329a95399117)

**Synced 2025-05-20**
